import type { Firestore } from "firebase-admin/firestore"; import { ApiError } from "../../errors/api-error.ts"; import { getFirebaseAdminServices } from "../../services/firebase/admin.ts"; import type { ChangeRequestRecord, MilestoneRecord, ProjectFileRecord, ProjectMessageRecord, ProjectRecord, ProjectWorkspace } from "./project.types.ts";
export interface EligiblePayment {eventId:string;customerId:string;contractId:string;invoiceId?:string;projectReference?:string}
export interface ProjectRepository {
  adminLifecycle?(projectId: string): Promise<{milestones: MilestoneRecord[]; changeRequests: ChangeRequestRecord[]}>;
  updateMilestone?(projectId: string, milestoneId: string, input: {status: MilestoneRecord["status"]; progressPercent: number}, actorId: string): Promise<void>;
  decideChange?(projectId: string, changeId: string, status: "approved" | "declined" | "completed", actorId: string): Promise<void>;
}
export interface ProjectRepository { findByContract(contractId:string):Promise<ProjectRecord|null>; getOwned(id:string,customerId:string):Promise<ProjectRecord|null>; listOwned(customerId:string):Promise<ProjectRecord[]>; listAll?():Promise<ProjectRecord[]>; createFromPaidContract(payment:EligiblePayment,hash:string):Promise<ProjectRecord|null>; markEmail(id:string,status:"sent"|"failed"):Promise<void>; unlock(id:string,customerId:string):Promise<void>; workspace(id:string,customerId:string):Promise<ProjectWorkspace|null>; addMessage(id:string,customerId:string,body:string):Promise<string>; addChangeRequest(id:string,customerId:string,input:{title:string;description:string;category:string;priority:"low"|"normal"|"high";origin?:"customer"|"completion_feedback"}):Promise<string>; submitSatisfaction(id:string,customerId:string,input:{satisfaction:"satisfied"|"not_satisfied";comment?:string;category?:string;severity?:"low"|"normal"|"high";desiredResolution?:string}):Promise<void>; regenerate(id:string,hash:string):Promise<ProjectRecord|null>; updateAdmin(id:string,input:Record<string,unknown>):Promise<void>; addMilestone(id:string,input:Omit<MilestoneRecord,"id"|"projectId">):Promise<string>; findFileByUploadKey?(idempotencyKey:string):Promise<ProjectFileRecord|null>; getFile?(id:string):Promise<ProjectFileRecord|null>; createFile?(input:Omit<ProjectFileRecord,"uploadedAt"|"firstDownloadedAt"|"latestDownloadedAt"|"downloadCount">,idempotencyKey:string):Promise<{file:ProjectFileRecord;created:boolean}>; recordDownload?(fileId:string,customerId:string):Promise<void> }
const safe=(project:ProjectRecord)=>{const rest={...project} as Partial<ProjectRecord>;delete rest.customerId;delete rest.customerEmail;delete rest.accessPasswordHash;return rest as Omit<ProjectRecord,"customerId"|"customerEmail"|"accessPasswordHash">;};
export const customerVisibleFiles=(files:Array<Record<string,unknown>&{id:string}>)=>files.filter(file=>file.customerVisible===true).map(file=>{const item={...file};delete item.storagePath;delete item.customerId;delete item.uploadedBy;return item;});
export class FirebaseProjectRepository implements ProjectRepository { private readonly db:Firestore; constructor(db:Firestore=getFirebaseAdminServices().firestore){this.db=db;} private now(){return getFirebaseAdminServices().serverTimestamp();} private map(doc:FirebaseFirestore.DocumentSnapshot){return {id:doc.id,...doc.data()} as ProjectRecord;} async findByContract(contractId:string){const s=await this.db.collection("projects").where("contractId","==",contractId).limit(1).get();return s.empty?null:this.map(s.docs[0]);} async getOwned(id:string,customerId:string){const d=await this.db.collection("projects").doc(id).get();return d.exists&&d.data()?.customerId===customerId?this.map(d):null;} async listOwned(customerId:string){const s=await this.db.collection("projects").where("customerId","==",customerId).get();return s.docs.map(d=>this.map(d));} async listAll(){const s=await this.db.collection("projects").get();return s.docs.map(d=>this.map(d));}
async createFromPaidContract(p:EligiblePayment,hash:string) {
  const contractRef = this.db.collection("contracts").doc(p.contractId);
  // The contract row is the serialization point for both event orders and concurrent retries.
  return this.db.runTransaction(async tx => {
    const contract = await tx.get(contractRef); const data = contract.data();
    if (!data || data.customerId !== p.customerId) throw new ApiError(404,"NOT_FOUND","Contract was not found.");
    if (data.status !== "signed" || data.signedBy !== p.customerId || !data.signedAt || !data.typedSignature || data.workspaceAccess !== true) return null;
    const invoices = await tx.get(this.db.collection("invoices").where("contractId","==",p.contractId));
    const deposit = invoices.docs.find(doc => {
      const invoice = doc.data();
      return (!p.invoiceId || doc.id === p.invoiceId) && invoice.customerId === p.customerId && invoice.isDeposit === true
        && invoice.status === "paid" && Number.isInteger(data.depositAmountCents) && data.depositAmountCents >= 100
        && invoice.amountCents === data.depositAmountCents && invoice.currency === data.currency;
    });
    if (!deposit) return null;
    const existing = await tx.get(this.db.collection("projects").where("contractId","==",p.contractId).limit(1));
    if (data.projectId || !existing.empty) return null;
    const ref = this.db.collection("projects").doc(); const now = this.now();
    const projectReference = String(data.projectReference ?? p.contractId);
    const project = {customerId:p.customerId,customerEmail:data.customerEmail,contractId:p.contractId,invoiceId:deposit.id,title:data.title,summary:data.scope,status:"active",progressPercent:0,accessEnabled:true,accessPasswordHash:hash,accessPasswordVersion:1,accessEmailStatus:"pending",projectReference,createdAt:now,updatedAt:now};
    tx.create(ref,project);
    tx.update(contractRef,{projectId:ref.id,updatedAt:now});
    tx.set(this.db.collection("notifications").doc(),{customerId:p.customerId,title:"Project access ready",body:`Project ${projectReference} is ready. Check your email for the access password.`,status:"unread",createdAt:now,updatedAt:now});
    tx.set(this.db.collection("auditLogs").doc(),{actorId:"system",action:"PROJECT_ACCESS_PASSWORD_GENERATED",targetCollection:"projects",targetId:ref.id,detail:"Signed contract and paid deposit verified.",createdAt:now});
    return {id:ref.id,...project} as ProjectRecord;
  });
}
async markEmail(id:string,status:"sent"|"failed"){await this.db.collection("projects").doc(id).update({accessEmailStatus:status,updatedAt:this.now()});await this.db.collection("auditLogs").add({actorId:"system",action:status==="sent"?"PROJECT_ACCESS_EMAIL_SENT":"PROJECT_ACCESS_EMAIL_FAILED",targetCollection:"projects",targetId:id,createdAt:this.now()});} async unlock(id:string,customerId:string){await this.db.collection("projects").doc(id).update({unlockedAt:this.now(),updatedAt:this.now()});await this.db.collection("auditLogs").add({actorId:customerId,action:"PROJECT_UNLOCKED",targetCollection:"projects",targetId:id,createdAt:this.now()});}
async workspace(id:string,customerId:string){const project=await this.getOwned(id,customerId);if(!project||project.accessEnabled!==true||!project.unlockedAt)return null;const get=async(name:string,value=id,field="projectId")=>(await this.db.collection(name).where(field,"==",value).get()).docs.map(d=>({id:d.id,...d.data()} as Record<string,unknown>&{id:string}));const [milestones,messages,changeRequests,files,invoices,payments,contract]=await Promise.all([get("projectMilestones"),get("messages"),get("changeRequests"),get("projectFiles"),get("invoices",project.contractId,"contractId"),get("payments",project.contractId,"contractId"),this.db.collection("contracts").doc(project.contractId).get()]);const safeFiles=customerVisibleFiles(files);return {project:safe(project),milestones:milestones as unknown as MilestoneRecord[],messages:messages as unknown as ProjectMessageRecord[],changeRequests:changeRequests as unknown as ChangeRequestRecord[],files:safeFiles as unknown as ProjectWorkspace["files"],invoices,payments,contract:contract.exists?{id:contract.id,...contract.data()}:null};}
async addMessage(id:string,customerId:string,body:string){const p=await this.getOwned(id,customerId);if(!p||p.accessEnabled!==true||!p.unlockedAt)throw new ApiError(403,"PROJECT_ACCESS_REQUIRED","Unlock this project before sending a message.");const d=await this.db.collection("messages").add({projectId:id,customerId,body,senderRole:"customer",status:"open",createdAt:this.now(),updatedAt:this.now()});return d.id;} async addChangeRequest(id:string,customerId:string,input:{title:string;description:string;category:string;priority:"low"|"normal"|"high";origin?:"customer"|"completion_feedback"}){const p=await this.getOwned(id,customerId);if(!p||p.accessEnabled!==true||!p.unlockedAt)throw new ApiError(403,"PROJECT_ACCESS_REQUIRED","Unlock this project before submitting a change request.");const d=await this.db.collection("changeRequests").add({...input,origin:input.origin??"customer",projectId:id,customerId,status:"submitted",createdAt:this.now(),updatedAt:this.now()});return d.id;}
async submitSatisfaction(id:string,customerId:string,input:{satisfaction:"satisfied"|"not_satisfied";comment?:string;category?:string;severity?:"low"|"normal"|"high";desiredResolution?:string}){const ref=this.db.collection("projects").doc(id);await this.db.runTransaction(async tx=>{const d=await tx.get(ref);const p=d.data();if(!p||p.customerId!==customerId||p.accessEnabled!==true||!p.unlockedAt||!p.completedAt||p.satisfaction)throw new ApiError(409,"FEEDBACK_NOT_ALLOWED","Completion feedback is unavailable.");const now=this.now();tx.update(ref,{satisfaction:input.satisfaction,satisfactionComment:input.comment??"",satisfactionAt:now,...(input.satisfaction==="satisfied"?{acceptedAt:now}:{}),updatedAt:now});if(input.satisfaction==="not_satisfied")tx.set(this.db.collection("changeRequests").doc(),{projectId:id,customerId,title:"Completion feedback follow-up",description:input.comment??input.desiredResolution??"Follow-up requested",category:input.category??"completion",priority:input.severity??"normal",status:"submitted",origin:"completion_feedback",createdAt:now,updatedAt:now});tx.set(this.db.collection("notifications").doc(),{customerId,title:input.satisfaction==="satisfied"?"Feedback received":"Follow-up request created",body:"Your completion feedback was recorded.",status:"unread",createdAt:now,updatedAt:now});});}
async regenerate(id:string,hash:string){const ref=this.db.collection("projects").doc(id);const d=await ref.get();if(!d.exists)return null;await ref.update({accessPasswordHash:hash,accessPasswordVersion:Number(d.data()?.accessPasswordVersion??1)+1,accessEmailStatus:null,unlockedAt:null,updatedAt:this.now()});return this.map(await ref.get());} async updateAdmin(id:string,input:Record<string,unknown>){const update={...input,updatedAt:this.now()} as Record<string,unknown>;if(input.status==="completed"){const d=await this.db.collection("projects").doc(id).get();if(!d.data()?.completedAt){const start=new Date();const end=new Date(start);end.setUTCMonth(end.getUTCMonth()+1);Object.assign(update,{completedAt:start.toISOString(),maintenanceStartAt:start.toISOString(),maintenanceEndAt:end.toISOString()});}}await this.db.collection("projects").doc(id).update(update);} async addMilestone(id:string,input:Omit<MilestoneRecord,"id"|"projectId">){const d=await this.db.collection("projectMilestones").add({...input,projectId:id,createdAt:this.now(),updatedAt:this.now()});return d.id;}
async updateMilestone(projectId:string,milestoneId:string,input:{status:MilestoneRecord["status"];progressPercent:number},actorId:string) {
  await this.db.runTransaction(async tx => {
    const project = await tx.get(this.db.collection("projects").doc(projectId));
    const ref = this.db.collection("projectMilestones").doc(milestoneId); const milestone = (await tx.get(ref)).data();
    if (!project.exists || !milestone || milestone.projectId !== projectId) throw new ApiError(404,"NOT_FOUND","Project milestone was not found.");
    const now = this.now();
    tx.update(ref,{...input,completedAt:input.status==="completed"?(milestone.completedAt??now):null,updatedBy:actorId,updatedAt:now});
    tx.set(this.db.collection("auditLogs").doc(),{actorId,action:"milestone_updated",projectId,targetCollection:"projectMilestones",targetId:milestoneId,createdAt:now});
  });
}
async adminLifecycle(projectId:string) {
  const project = (await this.db.collection("projects").doc(projectId).get()).data();
  if (!project) throw new ApiError(404,"NOT_FOUND","Project was not found.");
  const milestones = await this.db.collection("projectMilestones").where("projectId","==",projectId).get();
  const changes = await this.db.collection("changeRequests").where("projectId","==",projectId).get();
  return {milestones:milestones.docs.map(doc=>({id:doc.id,...doc.data()}) as MilestoneRecord),changeRequests:changes.docs.filter(doc=>doc.data().customerId===project.customerId).map(doc=>({id:doc.id,...doc.data()}) as ChangeRequestRecord)};
}
async decideChange(projectId:string,changeId:string,status:"approved"|"declined"|"completed",actorId:string) {
  await this.db.runTransaction(async tx => {
    const project = (await tx.get(this.db.collection("projects").doc(projectId))).data();
    const ref = this.db.collection("changeRequests").doc(changeId); const change = (await tx.get(ref)).data();
    if (!project || !change || change.projectId !== projectId || change.customerId !== project.customerId) throw new ApiError(404,"NOT_FOUND","Project change request was not found.");
    if (change.status === status) return;
    const allowed = status === "completed" ? ["approved","in_progress"] : ["submitted","reviewing"];
    if (!allowed.includes(change.status)) throw new ApiError(409,"CHANGE_STATE_INVALID","This decision is not allowed from the current state.");
    const now = this.now();
    tx.update(ref,{status,decidedBy:actorId,decidedAt:now,updatedAt:now,...(status==="completed"?{completedAt:now}:{})});
    tx.set(this.db.collection("notifications").doc(),{customerId:project.customerId,projectId,title:"Change request updated",body:`${change.title}: ${status}`,status:"unread",createdAt:now,updatedAt:now});
    tx.set(this.db.collection("auditLogs").doc(),{actorId,action:"change_request_decided",projectId,targetCollection:"changeRequests",targetId:changeId,status,createdAt:now});
  });
}
 async getFile(id:string){const d=await this.db.collection("projectFiles").doc(id).get();return d.exists?{id:d.id,...d.data()} as ProjectFileRecord:null;} async createFile(input:Omit<ProjectFileRecord,"uploadedAt"|"firstDownloadedAt"|"latestDownloadedAt"|"downloadCount">,idempotencyKey:string){const idem=this.db.collection("projectFileUploads").doc(idempotencyKey);const ref=this.db.collection("projectFiles").doc(input.id);let created=false;await this.db.runTransaction(async tx=>{const found=await tx.get(idem);if(found.exists)return;const now=this.now();tx.create(ref,{...input,downloadCount:0,uploadedAt:now,updatedAt:now});tx.create(idem,{projectId:input.projectId,fileId:input.id,createdAt:now});tx.set(this.db.collection("auditLogs").doc(),{actorId:input.uploadedBy,action:"PROJECT_FILE_UPLOADED",targetCollection:"projectFiles",targetId:input.id,projectId:input.projectId,createdAt:now});if(input.customerVisible)tx.set(this.db.collection("notifications").doc(),{customerId:input.customerId,projectId:input.projectId,title:"New project file available",body:`${input.name} is now available in your project workspace.`,status:"unread",createdAt:now,updatedAt:now});created=true;});const file=await this.getFile(created?input.id:String((await idem.get()).data()?.fileId??input.id));if(!file)throw new ApiError(500,"PROJECT_FILE_PERSISTENCE_FAILED","The project file metadata could not be verified.");return{file,created};} async recordDownload(fileId:string,customerId:string){const ref=this.db.collection("projectFiles").doc(fileId);await this.db.runTransaction(async tx=>{const d=await tx.get(ref);const data=d.data();if(!data||data.customerId!==customerId)throw new ApiError(404,"PROJECT_FILE_NOT_FOUND","The project file was not found.");const now=this.now();tx.update(ref,{downloadCount:Number(data.downloadCount??0)+1,firstDownloadedAt:data.firstDownloadedAt??now,latestDownloadedAt:now});tx.set(this.db.collection("auditLogs").doc(),{actorId:customerId,action:"PROJECT_FILE_DOWNLOADED",targetCollection:"projectFiles",targetId:fileId,projectId:data.projectId,createdAt:now});});}}
