export type ProjectStatus = "pending" | "active" | "completed" | "accepted" | "cancelled";
export type MilestoneStatus = "pending" | "in_progress" | "completed" | "blocked";
export interface ProjectRecord { id:string; customerId:string; customerEmail:string; contractId:string; projectReference:string; title:string; summary:string; status:ProjectStatus; progressPercent:number; accessEnabled:boolean; accessPasswordHash?:string; accessPasswordVersion?:number; accessEmailStatus?:"sent"|"failed"; startDate?:string; targetDate?:string; completedAt?:string; acceptedAt?:string; maintenanceStartAt?:string; maintenanceEndAt?:string; satisfaction?:"satisfied"|"not_satisfied"; satisfactionComment?:string; satisfactionAt?:string; unlockedAt?:string; createdAt?:unknown; updatedAt?:unknown }
export interface MilestoneRecord { id:string; projectId:string; title:string; description:string; status:MilestoneStatus; order:number; targetDate?:string; completedAt?:string; createdAt?:unknown; updatedAt?:unknown }
export interface ProjectMessageRecord { id:string; projectId:string; customerId:string; body:string; senderRole:"customer"|"admin"; createdAt?:unknown }
export interface ChangeRequestRecord { id:string; projectId:string; customerId:string; title:string; description:string; category:string; priority:"low"|"normal"|"high"; status:"submitted"|"reviewing"|"approved"|"declined"|"in_progress"|"completed"; origin:"customer"|"completion_feedback"; createdAt?:unknown; updatedAt?:unknown }
export type ProjectFileCategory = "deliverable" | "document" | "design" | "report" | "other";
export interface ProjectFileRecord { id:string; projectId:string; customerId:string; name:string; category:ProjectFileCategory; mimeType:string; sizeBytes:number; description?:string; version:number; customerVisible:boolean; deliveryStatus:"working"|"deliverable"|"final"; storagePath:string; uploadedBy:string; uploadedAt?:unknown; firstDownloadedAt?:unknown; latestDownloadedAt?:unknown; downloadCount:number }
export type CustomerProjectFile = Omit<ProjectFileRecord,"customerId"|"storagePath"|"uploadedBy">;
export interface ProjectWorkspace { project:Omit<ProjectRecord,"customerId"|"customerEmail"|"accessPasswordHash">; milestones:MilestoneRecord[]; messages:ProjectMessageRecord[]; changeRequests:ChangeRequestRecord[]; files:CustomerProjectFile[]; invoices:Array<Record<string,unknown>>; payments:Array<Record<string,unknown>>; contract:Record<string,unknown>|null }
