import type { WorkspaceTaskPriority, WorkspaceTaskStatus } from "@averon/shared-types";
import { ApiError } from "../../errors/api-error.ts";
const statuses = ["TODO", "IN_PROGRESS", "AWAITING_APPROVAL", "BLOCKED", "COMPLETED", "CANCELLED"] as const;
const priorities = ["LOW", "NORMAL", "HIGH", "URGENT"] as const;
const record = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === "object" && !Array.isArray(value);
const text = (value: unknown, field: string, maximum: number) => { if (typeof value !== "string" || !value.trim() || value.length > maximum) throw new ApiError(400, "TASK_INPUT_INVALID", `${field} is invalid.`); return value.trim(); };
const optionalDate = (value: unknown) => { if (value === undefined || value === null || value === "") return undefined; if (typeof value !== "string" || Number.isNaN(Date.parse(value))) throw new ApiError(400, "TASK_INPUT_INVALID", "dueAt must be a valid date."); return value; };
const agents = (value: unknown) => { if (value === undefined) return []; if (!Array.isArray(value) || value.length > 15 || value.some((item) => typeof item !== "string")) throw new ApiError(400, "TASK_AGENT_INVALID", "assignedAgentIds must contain valid specialist IDs."); return [...new Set(value as string[])]; };
export function parseTaskCreate(value: unknown) { if (!record(value) || Object.keys(value).some((key) => !["title", "description", "priority", "assignedAgentIds", "dueAt"].includes(key))) throw new ApiError(400, "TASK_INPUT_INVALID", "The Task request is invalid."); const priority = (value.priority ?? "NORMAL") as WorkspaceTaskPriority; if (!priorities.includes(priority)) throw new ApiError(400, "TASK_PRIORITY_INVALID", "The Task priority is invalid."); return { title: text(value.title, "title", 160), description: text(value.description, "description", 5000), priority, assignedAgentIds: agents(value.assignedAgentIds), dueAt: optionalDate(value.dueAt) }; }
export function parseTaskUpdate(value: unknown) { if (!record(value) || typeof value.expectedVersion !== "number" || !Number.isInteger(value.expectedVersion) || value.expectedVersion < 1 || Object.keys(value).some((key) => !["expectedVersion", "title", "description", "status", "priority", "assignedAgentIds", "dueAt"].includes(key))) throw new ApiError(400, "TASK_INPUT_INVALID", "A valid expectedVersion and Task patch are required."); const patch: Record<string, unknown> = {}; if (value.title !== undefined) patch.title = text(value.title, "title", 160); if (value.description !== undefined) patch.description = text(value.description, "description", 5000); if (value.status !== undefined) { if (!statuses.includes(value.status as WorkspaceTaskStatus)) throw new ApiError(400, "TASK_STATUS_INVALID", "The Task status is invalid."); patch.status = value.status; } if (value.priority !== undefined) { if (!priorities.includes(value.priority as WorkspaceTaskPriority)) throw new ApiError(400, "TASK_PRIORITY_INVALID", "The Task priority is invalid."); patch.priority = value.priority; } if (value.assignedAgentIds !== undefined) patch.assignedAgentIds = agents(value.assignedAgentIds); if (value.dueAt !== undefined) patch.dueAt = optionalDate(value.dueAt); if (!Object.keys(patch).length) throw new ApiError(400, "TASK_INPUT_INVALID", "At least one Task field must change."); return { expectedVersion: value.expectedVersion, patch }; }
