import { createHash, randomUUID } from "node:crypto";
import type { EmmyActionMetadata, WorkspaceTask, WorkspaceTaskExecutionResult, WorkspaceTaskStatus } from "@averon/shared-types";
import { DefaultAgentRegistry } from "../../ai/agents/registry.ts";
import { agentDisplayIdentities } from "../../ai/agents/catalog.ts";
import { ApiError } from "../../errors/api-error.ts";
import type { AuthContext } from "../../services/auth/authentication.ts";
import type { WorkspaceAuthorizationService } from "../workspaces/workspace.service.ts";
import { parseTaskCreate, parseTaskUpdate } from "./workspace-task.schemas.ts";
import type { WorkspaceTaskFilters, WorkspaceTaskRepository } from "./workspace-task.types.ts";
import type { PrivateEmmyService } from "../../ai/emmy/private-emmy.ts";
import type { DiagnosticsStore } from "../../ai/diagnostics/diagnostics.store.ts";
const transitions: Record<WorkspaceTaskStatus, WorkspaceTaskStatus[]> = { TODO: ["IN_PROGRESS", "AWAITING_APPROVAL", "CANCELLED"], IN_PROGRESS: ["AWAITING_APPROVAL", "BLOCKED", "COMPLETED", "CANCELLED"], AWAITING_APPROVAL: ["IN_PROGRESS", "BLOCKED", "CANCELLED"], BLOCKED: ["IN_PROGRESS", "CANCELLED"], COMPLETED: [], CANCELLED: [] };
export class WorkspaceTaskService {
  private readonly agents = new DefaultAgentRegistry(); private readonly repository: WorkspaceTaskRepository; private readonly workspaces: WorkspaceAuthorizationService; private readonly emmy?: PrivateEmmyService; private readonly diagnostics?: DiagnosticsStore;
  constructor(repository: WorkspaceTaskRepository, workspaces: WorkspaceAuthorizationService, emmy?: PrivateEmmyService, diagnostics?: DiagnosticsStore) { this.repository = repository; this.workspaces = workspaces; this.emmy = emmy; this.diagnostics = diagnostics; }
  private validAgents(ids: string[]) { for (const id of ids) if (!this.agents.get(id as never)) throw new ApiError(400, "TASK_AGENT_INVALID", `The assigned specialist ID ${id} is not registered.`); return ids; }
  private async reconcileAction(task: WorkspaceTask) { const actionId = task.linkedActionIds.at(-1); if (!actionId || !this.diagnostics?.getOperation || !["AWAITING_APPROVAL", "IN_PROGRESS"].includes(task.status)) return task; const operation = await this.diagnostics.getOperation(actionId, new Set([task.workspaceId])); const status = operation?.operationStatus; if (status === "applying" || status === "verifying") return this.repository.reconcileActionExecution(task.workspaceId, task.id, actionId, "IN_PROGRESS", "The authorized action is applying or verifying."); if (status === "completed" || status === "no_change_required") return this.repository.reconcileActionExecution(task.workspaceId, task.id, actionId, "COMPLETED", "The authorized action completed and passed verification."); if (status === "failed" || status === "rejected" || status === "rolled_back") return this.repository.reconcileActionExecution(task.workspaceId, task.id, actionId, "BLOCKED", "The authorized action did not complete; inspect the linked Run."); return task; }
  async list(auth: AuthContext, workspaceId: string, filters: WorkspaceTaskFilters = {}) { const context = await this.workspaces.requirePermission(auth, workspaceId, "workspace:read"); const listed = await this.repository.list(workspaceId, filters); const items = await Promise.all(listed.map((item) => this.reconcileAction(item))); return { workspace: { id: context.workspace.id, name: context.workspace.name }, canManage: context.permissions.includes("workspace:manage"), items, agentIdentities: Object.fromEntries(this.agents.list().map((agent) => [agent.id, agentDisplayIdentities[agent.id]])) }; }
  async detail(auth: AuthContext, workspaceId: string, taskId: string) { await this.workspaces.requirePermission(auth, workspaceId, "workspace:read"); const found = await this.repository.get(workspaceId, taskId); if (!found) throw new ApiError(404, "TASK_NOT_FOUND", "The Task was not found."); const item = await this.reconcileAction(found); return { ...item, history: await this.repository.history(workspaceId, taskId) }; }
  private async createValidated(auth: AuthContext, workspaceId: string, body: unknown, id: string) { await this.workspaces.requirePermission(auth, workspaceId, "workspace:manage"); const input = parseTaskCreate(body); this.validAgents(input.assignedAgentIds); const existing = await this.repository.get(workspaceId, id); if (existing) return existing; return this.repository.create({ id, workspaceId, title: input.title, description: input.description, status: "TODO", priority: input.priority, assignedAgentIds: input.assignedAgentIds, linkedRunIds: [], linkedActionIds: [], createdBy: auth.user.userId, updatedBy: auth.user.userId, ...(input.dueAt ? { dueAt: input.dueAt } : {}) }); }
  async create(auth: AuthContext, workspaceId: string, body: unknown) { return this.createValidated(auth, workspaceId, body, randomUUID()); }
  async createFromAutomation(auth: AuthContext, workspaceId: string, automationId: string, scheduledFor: string, body: unknown) { const id = `automation-${createHash("sha256").update(`${workspaceId}:${automationId}:${scheduledFor}`).digest("hex").slice(0, 32)}`; return this.createValidated(auth, workspaceId, body, id); }
  async createFromGuardian(auth: AuthContext, workspaceId: string, findingId: string, body: unknown) { const id = `guardian-${createHash("sha256").update(`${workspaceId}:${findingId}`).digest("hex").slice(0, 32)}`; try { return await this.createValidated(auth, workspaceId, body, id); } catch (caught) { const existing = await this.repository.get(workspaceId, id); if (existing) return existing; throw caught; } }
  async update(auth: AuthContext, workspaceId: string, taskId: string, body: unknown) { await this.workspaces.requirePermission(auth, workspaceId, "workspace:manage"); const { expectedVersion, patch } = parseTaskUpdate(body); if (patch.assignedAgentIds) this.validAgents(patch.assignedAgentIds as string[]); const current = await this.repository.get(workspaceId, taskId); if (!current) throw new ApiError(404, "TASK_NOT_FOUND", "The Task was not found."); if (patch.status && !transitions[current.status].includes(patch.status as WorkspaceTaskStatus)) throw new ApiError(409, "TASK_TRANSITION_INVALID", `Task status cannot transition from ${current.status} to ${patch.status}.`); return this.repository.update(workspaceId, taskId, expectedVersion, patch as Partial<WorkspaceTask>, auth.user.userId); }
  private actionAwaitsApproval(action?: EmmyActionMetadata) { return Boolean(action && (action.status === "approval_required" || action.status === "proposed" || ("approvalStatus" in action && action.approvalStatus === "pending" && action.status !== "failed"))); }
  private actionVerified(action?: EmmyActionMetadata) { return !action || (action.status === "completed" && action.verificationStatus === "passed"); }
  async execute(auth: AuthContext, workspaceId: string, taskId: string, body: unknown): Promise<WorkspaceTaskExecutionResult> {
    await this.workspaces.requirePermission(auth, workspaceId, "workspace:manage");
    if (!body || typeof body !== "object" || Array.isArray(body) || typeof (body as { idempotencyKey?: unknown }).idempotencyKey !== "string" || !/^[A-Za-z0-9._:-]{8,128}$/.test((body as { idempotencyKey: string }).idempotencyKey)) throw new ApiError(400, "TASK_EXECUTION_IDEMPOTENCY_REQUIRED", "A valid execution idempotency key is required.");
    if (!this.emmy) throw new ApiError(503, "TASK_EXECUTION_UNAVAILABLE", "Controlled Task execution is unavailable.");
    const task = await this.repository.get(workspaceId, taskId); if (!task) throw new ApiError(404, "TASK_NOT_FOUND", "The Task was not found.");
    this.validAgents(task.assignedAgentIds); for (const id of task.assignedAgentIds) { const agent = this.agents.get(id as never)!; if (!agent.enabled || agent.experimental || agent.certification.certificationStatus !== "passed") throw new ApiError(409, "TASK_SPECIALIST_NOT_READY", "An assigned specialist is not ready for controlled execution."); }
    const idempotencyKey = (body as { idempotencyKey: string }).idempotencyKey; const runId = `task-run-${createHash("sha256").update(`${workspaceId}:${taskId}:${idempotencyKey}`).digest("hex").slice(0, 32)}`;
    const begun = await this.repository.beginExecution(workspaceId, taskId, runId, auth.user.userId);
    if (!begun.started) return { taskId, runId, status: begun.task.status as WorkspaceTaskExecutionResult["status"], idempotentReplay: true, actionId: begun.task.linkedActionIds.at(-1), summary: begun.task.status === "COMPLETED" ? "The controlled execution already completed." : "The controlled execution request already exists." };
    const assignment = task.assignedAgentIds.length ? `\nAssigned specialist constraints: ${task.assignedAgentIds.join(", ")}. Use the existing planner and mandatory dependency rules; do not bypass readiness or safety.` : "";
    try {
      const result = await this.emmy.send(auth, workspaceId, { message: `${task.title}\n\n${task.description}${assignment}`, history: [] }, runId);
      await this.diagnostics?.linkTask?.(runId, taskId);
      const actionId = result.action?.actionId; const status: "AWAITING_APPROVAL" | "COMPLETED" | "BLOCKED" = this.actionAwaitsApproval(result.action) ? "AWAITING_APPROVAL" : result.finalStatus === "completed" && this.actionVerified(result.action) ? "COMPLETED" : "BLOCKED";
      const summary = status === "AWAITING_APPROVAL" ? "An authorized action is awaiting approval." : status === "COMPLETED" ? (result.action ? "The authorized action completed and passed verification." : "The validated advisory execution completed.") : "The controlled execution was blocked; inspect the linked Run.";
      await this.repository.finishExecution(workspaceId, taskId, runId, status, actionId, summary, auth.user.userId);
      return { taskId, runId, status, idempotentReplay: false, ...(actionId ? { actionId } : {}), summary };
    } catch (caught) { await this.repository.finishExecution(workspaceId, taskId, runId, "BLOCKED", undefined, "The controlled execution failed; inspect the linked Run.", auth.user.userId); throw caught; }
  }
}
