import type { Firestore } from "firebase-admin/firestore";
import type { WorkspaceTask, WorkspaceTaskHistoryItem } from "@averon/shared-types";
import { ApiError } from "../../errors/api-error.ts";
import { getFirebaseAdminServices } from "../../services/firebase/admin.ts";
import type { WorkspaceTaskFilters, WorkspaceTaskRepository } from "./workspace-task.types.ts";
const taskKey = (workspaceId: string, taskId: string) => `${workspaceId}__${taskId}`;
const changed = (current: WorkspaceTask, patch: Record<string, unknown>) => Object.keys(patch).filter((key) => JSON.stringify(current[key as keyof WorkspaceTask]) !== JSON.stringify(patch[key]));
function applyLifecycleFields(current: WorkspaceTask, patch: Partial<WorkspaceTask>) {
  const item: WorkspaceTask = { ...current, ...patch };
  if (patch.status === "COMPLETED") item.completedAt = new Date().toISOString();
  else if (patch.status) delete item.completedAt;
  return item;
}
export class FirebaseWorkspaceTaskRepository implements WorkspaceTaskRepository {
  private readonly db: Firestore; constructor(db: Firestore = getFirebaseAdminServices().firestore) { this.db = db; }
  private tasks() { return this.db.collection("workspaceTasks"); }
  private ref(workspaceId: string, taskId: string) { return this.tasks().doc(taskKey(workspaceId, taskId)); }
  async list(workspaceId: string, filters: WorkspaceTaskFilters = {}) { const found = await this.tasks().where("workspaceId", "==", workspaceId).limit(100).get(); return found.docs.map((item) => item.data() as WorkspaceTask).filter((item) => (!filters.status || item.status === filters.status) && (!filters.priority || item.priority === filters.priority) && (!filters.assignedAgentId || item.assignedAgentIds.includes(filters.assignedAgentId))).sort((a, b) => String(b.updatedAt ?? "").localeCompare(String(a.updatedAt ?? ""))); }
  async get(workspaceId: string, taskId: string) { const found = await this.ref(workspaceId, taskId).get(); if (!found.exists) return null; const item = found.data() as WorkspaceTask; return item.workspaceId === workspaceId ? item : null; }
  async create(input: Omit<WorkspaceTask, "version" | "createdAt" | "updatedAt">) { const ref = this.ref(input.workspaceId, input.id); const now = getFirebaseAdminServices().serverTimestamp(); const item = { ...input, version: 1 }; const history = ref.collection("history").doc(); const batch = this.db.batch(); batch.create(ref, { ...item, createdAt: now, updatedAt: now }); batch.create(history, { id: history.id, workspaceId: input.workspaceId, taskId: input.id, eventType: "task.created", actorId: input.createdBy, changedFields: ["title", "description", "priority", "assignedAgentIds"], version: 1, occurredAt: now }); await batch.commit(); return item; }
  async update(workspaceId: string, taskId: string, expectedVersion: number, patch: Partial<WorkspaceTask>, actorId: string) { const ref = this.ref(workspaceId, taskId); return this.db.runTransaction(async (tx) => { const found = await tx.get(ref); if (!found.exists) throw new ApiError(404, "TASK_NOT_FOUND", "The Task was not found."); const current = found.data() as WorkspaceTask; if (current.workspaceId !== workspaceId) throw new ApiError(404, "TASK_NOT_FOUND", "The Task was not found."); if (current.version !== expectedVersion) throw new ApiError(409, "TASK_VERSION_CONFLICT", "The Task changed since it was loaded."); const fields = changed(current, patch); if (!fields.length) return current; const version = current.version + 1; const item = { ...applyLifecycleFields(current, patch), updatedBy: actorId, version }; const now = getFirebaseAdminServices().serverTimestamp(); const eventType = fields.includes("status") ? "task.status_changed" : fields.includes("assignedAgentIds") ? "task.assignment_changed" : "task.updated"; const history = ref.collection("history").doc(); tx.update(ref, { ...patch, ...(patch.status ? { completedAt: item.completedAt ?? null } : {}), updatedBy: actorId, version, updatedAt: now }); tx.create(history, { id: history.id, workspaceId, taskId, eventType, actorId, changedFields: fields, ...(fields.includes("status") ? { fromStatus: current.status, toStatus: patch.status } : {}), version, occurredAt: now }); return item; }); }
  async history(workspaceId: string, taskId: string) { const found = await this.ref(workspaceId, taskId).collection("history").orderBy("version", "desc").limit(100).get(); return found.docs.map((item) => item.data() as WorkspaceTaskHistoryItem).filter((item) => item.workspaceId === workspaceId && item.taskId === taskId); }
  async beginExecution(workspaceId: string, taskId: string, runId: string, actorId: string) { const ref = this.ref(workspaceId, taskId); return this.db.runTransaction(async (tx) => { const found = await tx.get(ref); if (!found.exists || found.data()?.workspaceId !== workspaceId) throw new ApiError(404, "TASK_NOT_FOUND", "The Task was not found."); const current = found.data() as WorkspaceTask; if (current.linkedRunIds.includes(runId)) return { task: current, started: false }; if (current.lastExecutionStatus === "RUNNING") throw new ApiError(409, "TASK_EXECUTION_ALREADY_ACTIVE", "The Task already has an active execution."); if (current.status === "COMPLETED" || current.status === "CANCELLED") throw new ApiError(409, "TASK_EXECUTION_NOT_ALLOWED", "This Task cannot be executed in its current state."); const version = current.version + 1; const task = { ...current, status: "IN_PROGRESS" as const, linkedRunIds: [...current.linkedRunIds, runId], lastRunId: runId, lastExecutionStatus: "RUNNING" as const, updatedBy: actorId, version }; const now = getFirebaseAdminServices().serverTimestamp(); const history = ref.collection("history").doc(); tx.update(ref, { status: task.status, linkedRunIds: task.linkedRunIds, lastRunId: runId, lastExecutionStatus: task.lastExecutionStatus, completedAt: null, updatedBy: actorId, version, updatedAt: now }); tx.create(history, { id: history.id, workspaceId, taskId, eventType: "task.execution_started", actorId, changedFields: ["status", "linkedRunIds", "lastRunId", "lastExecutionStatus"], fromStatus: current.status, toStatus: task.status, runId, version, occurredAt: now }); return { task, started: true }; }); }
  async finishExecution(workspaceId: string, taskId: string, runId: string, status: "AWAITING_APPROVAL" | "COMPLETED" | "BLOCKED", actionId: string | undefined, summary: string, actorId: string) { const ref = this.ref(workspaceId, taskId); return this.db.runTransaction(async (tx): Promise<WorkspaceTask> => { const found = await tx.get(ref); if (!found.exists || found.data()?.workspaceId !== workspaceId) throw new ApiError(404, "TASK_NOT_FOUND", "The Task was not found."); const current = found.data() as WorkspaceTask; if (current.lastRunId !== runId) throw new ApiError(409, "TASK_EXECUTION_STALE", "The execution is no longer current for this Task."); const lastExecutionStatus: WorkspaceTask["lastExecutionStatus"] = status; const linkedActionIds = actionId ? [...new Set([...current.linkedActionIds, actionId])] : current.linkedActionIds; const version = current.version + 1; const task: WorkspaceTask = { ...current, status, linkedActionIds, lastExecutionStatus, lastExecutionSummary: summary, updatedBy: actorId, version }; if (status === "COMPLETED") task.completedAt = new Date().toISOString(); else delete task.completedAt; const now = getFirebaseAdminServices().serverTimestamp(); const history = ref.collection("history").doc(); tx.update(ref, { status, linkedActionIds, lastExecutionStatus, lastExecutionSummary: summary, ...(status === "COMPLETED" ? { completedAt: task.completedAt } : { completedAt: null }), updatedBy: actorId, version, updatedAt: now }); tx.create(history, { id: history.id, workspaceId, taskId, eventType: "task.execution_finished", actorId, changedFields: ["status", "lastExecutionStatus", "lastExecutionSummary", ...(actionId ? ["linkedActionIds"] : [])], fromStatus: current.status, toStatus: status, runId, ...(actionId ? { actionId } : {}), version, occurredAt: now }); return task; }); }
  async reconcileActionExecution(workspaceId: string, taskId: string, actionId: string, status: "IN_PROGRESS" | "COMPLETED" | "BLOCKED", summary: string) { const ref = this.ref(workspaceId, taskId); return this.db.runTransaction(async (tx): Promise<WorkspaceTask> => { const found = await tx.get(ref); if (!found.exists || found.data()?.workspaceId !== workspaceId) throw new ApiError(404, "TASK_NOT_FOUND", "The Task was not found."); const current = found.data() as WorkspaceTask; if (!current.linkedActionIds.includes(actionId)) throw new ApiError(409, "TASK_ACTION_LINK_INVALID", "The action is not linked to this Task."); const executionStatus: WorkspaceTask["lastExecutionStatus"] = status === "IN_PROGRESS" ? "RUNNING" : status; if (current.status === status && current.lastExecutionStatus === executionStatus && current.lastExecutionSummary === summary) return current; const version = current.version + 1; const task: WorkspaceTask = { ...current, status, lastExecutionStatus: executionStatus, lastExecutionSummary: summary, updatedBy: "system:action-reconciliation", version }; if (status === "COMPLETED") task.completedAt = new Date().toISOString(); else delete task.completedAt; const now = getFirebaseAdminServices().serverTimestamp(); const history = ref.collection("history").doc(); tx.update(ref, { status, lastExecutionStatus: executionStatus, lastExecutionSummary: summary, ...(status === "COMPLETED" ? { completedAt: task.completedAt } : { completedAt: null }), updatedBy: task.updatedBy, version, updatedAt: now }); tx.create(history, { id: history.id, workspaceId, taskId, eventType: status === "IN_PROGRESS" ? "task.status_changed" : "task.execution_finished", actorId: task.updatedBy, changedFields: ["status", "lastExecutionStatus", "lastExecutionSummary"], fromStatus: current.status, toStatus: status, runId: current.lastRunId, actionId, version, occurredAt: now }); return task; }); }
}
export class MemoryWorkspaceTaskRepository implements WorkspaceTaskRepository {
  tasks = new Map<string, WorkspaceTask>(); events: WorkspaceTaskHistoryItem[] = [];
  async list(workspaceId: string, filters: WorkspaceTaskFilters = {}) { return [...this.tasks.values()].filter((item) => item.workspaceId === workspaceId && (!filters.status || item.status === filters.status) && (!filters.priority || item.priority === filters.priority) && (!filters.assignedAgentId || item.assignedAgentIds.includes(filters.assignedAgentId))); }
  async get(workspaceId: string, taskId: string) { return this.tasks.get(taskKey(workspaceId, taskId)) ?? null; }
  async create(input: Omit<WorkspaceTask, "version" | "createdAt" | "updatedAt">) { const item = { ...input, version: 1 }; this.tasks.set(taskKey(input.workspaceId, input.id), item); this.events.push({ id: `event-${this.events.length + 1}`, workspaceId: input.workspaceId, taskId: input.id, eventType: "task.created", actorId: input.createdBy, changedFields: ["title", "description", "priority", "assignedAgentIds"], version: 1 }); return item; }
  async update(workspaceId: string, taskId: string, expectedVersion: number, patch: Partial<WorkspaceTask>, actorId: string) { const current = await this.get(workspaceId, taskId); if (!current) throw new ApiError(404, "TASK_NOT_FOUND", "The Task was not found."); if (current.version !== expectedVersion) throw new ApiError(409, "TASK_VERSION_CONFLICT", "The Task changed since it was loaded."); const fields = changed(current, patch); if (!fields.length) return current; const item = { ...applyLifecycleFields(current, patch), updatedBy: actorId, version: current.version + 1 }; this.tasks.set(taskKey(workspaceId, taskId), item); this.events.push({ id: `event-${this.events.length + 1}`, workspaceId, taskId, eventType: fields.includes("status") ? "task.status_changed" : fields.includes("assignedAgentIds") ? "task.assignment_changed" : "task.updated", actorId, changedFields: fields, ...(fields.includes("status") ? { fromStatus: current.status, toStatus: patch.status } : {}), version: item.version }); return item; }
  async history(workspaceId: string, taskId: string) { return this.events.filter((item) => item.workspaceId === workspaceId && item.taskId === taskId).reverse(); }
  async beginExecution(workspaceId: string, taskId: string, runId: string, actorId: string) { const current = await this.get(workspaceId, taskId); if (!current) throw new ApiError(404, "TASK_NOT_FOUND", "The Task was not found."); if (current.linkedRunIds.includes(runId)) return { task: current, started: false }; if (current.lastExecutionStatus === "RUNNING") throw new ApiError(409, "TASK_EXECUTION_ALREADY_ACTIVE", "The Task already has an active execution."); if (current.status === "COMPLETED" || current.status === "CANCELLED") throw new ApiError(409, "TASK_EXECUTION_NOT_ALLOWED", "This Task cannot be executed in its current state."); const task = { ...current, status: "IN_PROGRESS" as const, linkedRunIds: [...current.linkedRunIds, runId], lastRunId: runId, lastExecutionStatus: "RUNNING" as const, updatedBy: actorId, version: current.version + 1 }; delete task.completedAt; this.tasks.set(taskKey(workspaceId, taskId), task); this.events.push({ id: `event-${this.events.length + 1}`, workspaceId, taskId, eventType: "task.execution_started", actorId, changedFields: ["status", "linkedRunIds", "lastRunId", "lastExecutionStatus"], fromStatus: current.status, toStatus: task.status, runId, version: task.version }); return { task, started: true }; }
  async finishExecution(workspaceId: string, taskId: string, runId: string, status: "AWAITING_APPROVAL" | "COMPLETED" | "BLOCKED", actionId: string | undefined, summary: string, actorId: string) { const current = await this.get(workspaceId, taskId); if (!current) throw new ApiError(404, "TASK_NOT_FOUND", "The Task was not found."); if (current.lastRunId !== runId) throw new ApiError(409, "TASK_EXECUTION_STALE", "The execution is no longer current for this Task."); const task: WorkspaceTask = { ...current, status, linkedActionIds: actionId ? [...new Set([...current.linkedActionIds, actionId])] : current.linkedActionIds, lastExecutionStatus: status === "AWAITING_APPROVAL" ? "AWAITING_APPROVAL" : status, lastExecutionSummary: summary, updatedBy: actorId, version: current.version + 1 }; if (status === "COMPLETED") task.completedAt = new Date().toISOString(); else delete task.completedAt; this.tasks.set(taskKey(workspaceId, taskId), task); this.events.push({ id: `event-${this.events.length + 1}`, workspaceId, taskId, eventType: "task.execution_finished", actorId, changedFields: ["status", "lastExecutionStatus", "lastExecutionSummary", ...(actionId ? ["linkedActionIds"] : [])], fromStatus: current.status, toStatus: status, runId, ...(actionId ? { actionId } : {}), version: task.version }); return task; }
  async reconcileActionExecution(workspaceId: string, taskId: string, actionId: string, status: "IN_PROGRESS" | "COMPLETED" | "BLOCKED", summary: string) { const current = await this.get(workspaceId, taskId); if (!current) throw new ApiError(404, "TASK_NOT_FOUND", "The Task was not found."); if (!current.linkedActionIds.includes(actionId)) throw new ApiError(409, "TASK_ACTION_LINK_INVALID", "The action is not linked to this Task."); const executionStatus: WorkspaceTask["lastExecutionStatus"] = status === "IN_PROGRESS" ? "RUNNING" : status; if (current.status === status && current.lastExecutionStatus === executionStatus && current.lastExecutionSummary === summary) return current; const task: WorkspaceTask = { ...current, status, lastExecutionStatus: executionStatus, lastExecutionSummary: summary, updatedBy: "system:action-reconciliation", version: current.version + 1 }; if (status === "COMPLETED") task.completedAt = new Date().toISOString(); else delete task.completedAt; this.tasks.set(taskKey(workspaceId, taskId), task); this.events.push({ id: `event-${this.events.length + 1}`, workspaceId, taskId, eventType: status === "IN_PROGRESS" ? "task.status_changed" : "task.execution_finished", actorId: task.updatedBy, changedFields: ["status", "lastExecutionStatus", "lastExecutionSummary"], fromStatus: current.status, toStatus: status, runId: current.lastRunId, actionId, version: task.version }); return task; }
}
