import { createHash } from "node:crypto";
import { isIP } from "node:net";
import { lookup } from "node:dns/promises";
import type { AiDiagnostic, GuardianCheckKind, GuardianCheckResult, GuardianFinding, GuardianHealthReport, GuardianHealthStatus, GuardianSeverity, GuardianWebsite } from "@averon/shared-types";
import type { AuthContext } from "../../services/auth/authentication.ts";
import type { WorkspaceAuthorizationService } from "../workspaces/workspace.service.ts";
import type { DiagnosticsStore } from "../../ai/diagnostics/diagnostics.store.ts";
import { ApiError } from "../../errors/api-error.ts";
import type { GuardianRepository } from "./guardian.repository.ts";
import type { WorkspaceTaskService } from "../workspace-tasks/workspace-task.service.ts";
import type { GuardianRepairService } from "./guardian-repair.service.ts";

export const guardianCheckCapabilities: Record<GuardianCheckKind, "SUPPORTED" | "PARTIALLY_SUPPORTED" | "NOT_SUPPORTED"> = { AVAILABILITY: "SUPPORTED", ROUTES: "SUPPORTED", ASSETS: "SUPPORTED", LINKS: "SUPPORTED", UI_SMOKE: "SUPPORTED", RUNTIME: "SUPPORTED", FORMS: "SUPPORTED", API_HEALTH: "SUPPORTED", RESPONSIVE: "SUPPORTED" };
export function guardianSeverity(kind: GuardianCheckKind, signature = ""): GuardianSeverity { if (/outage|data.loss|severe.security/i.test(signature)) return "CRITICAL"; if (/auth|database|widespread/i.test(signature)) return "MAJOR"; if (["ROUTES", "FORMS", "API_HEALTH"].includes(kind)) return "MODERATE"; return "MINOR"; }
export function guardianStatus(checks: GuardianCheckResult[]): GuardianHealthStatus { if (!checks.length || checks.every((item) => item.status === "NOT_CHECKED")) return "CONFIGURATION_REQUIRED"; const severities = checks.filter((item) => item.status === "FAIL").map((item) => guardianSeverity(item.kind, item.evidence?.signature)); return severities.includes("CRITICAL") ? "CRITICAL" : severities.includes("MAJOR") ? "UNHEALTHY" : severities.length ? "DEGRADED" : "HEALTHY"; }
export function guardianFingerprint(websiteId: string, check: GuardianCheckResult) { return createHash("sha256").update([websiteId, check.kind, check.target ?? "", check.evidence?.signature ?? check.summary].join("|")).digest("hex").slice(0, 32); }

export interface GuardianInspector { inspect(website: GuardianWebsite): Promise<GuardianCheckResult[]> }
type AddressResolver = (hostname: string) => Promise<string[]>;
const defaultResolver: AddressResolver = async (hostname) => (await lookup(hostname, { all: true, verbatim: true })).map((item) => item.address);
function privateIpv4(address: string) { const parts = address.split(".").map(Number); return parts.length === 4 && (parts[0] === 0 || parts[0] === 10 || parts[0] === 127 || parts[0]! >= 224 || (parts[0] === 100 && parts[1]! >= 64 && parts[1]! <= 127) || (parts[0] === 169 && parts[1] === 254) || (parts[0] === 172 && parts[1]! >= 16 && parts[1]! <= 31) || (parts[0] === 192 && (parts[1] === 0 || parts[1] === 168)) || (parts[0] === 198 && (parts[1] === 18 || parts[1] === 19 || parts[1] === 51)) || (parts[0] === 203 && parts[1] === 0 && parts[2] === 113)); }
function privateIpv6(address: string) { const normalized = address.toLowerCase().split("%")[0]!; if (normalized === "::" || normalized === "::1" || normalized.startsWith("fc") || normalized.startsWith("fd") || /^fe[89ab]/.test(normalized) || normalized.startsWith("ff")) return true; const mapped = /^::ffff:(\d+\.\d+\.\d+\.\d+)$/.exec(normalized)?.[1]; if (mapped) return privateIpv4(mapped); const hexadecimalMapped = /^::ffff:([0-9a-f]{1,4}):([0-9a-f]{1,4})$/.exec(normalized); if (!hexadecimalMapped) return false; const high = Number.parseInt(hexadecimalMapped[1]!, 16); const low = Number.parseInt(hexadecimalMapped[2]!, 16); return privateIpv4(`${high >> 8}.${high & 255}.${low >> 8}.${low & 255}`); }
export async function validateGuardianTarget(value: string, allowedOrigin: string, resolve: AddressResolver = defaultResolver) {
  let url: URL; try { url = new URL(value); } catch { throw new ApiError(400, "GUARDIAN_TARGET_DENIED", "The registered Guardian target is not permitted."); }
  if (!["http:", "https:"].includes(url.protocol) || url.username || url.password || url.origin !== allowedOrigin || !url.hostname || url.hostname.toLowerCase() === "localhost") throw new ApiError(400, "GUARDIAN_TARGET_DENIED", "The registered Guardian target is not permitted.");
  let addresses: string[]; try { addresses = isIP(url.hostname) ? [url.hostname] : await resolve(url.hostname); } catch { throw new ApiError(400, "GUARDIAN_TARGET_DENIED", "The registered Guardian target is not permitted."); }
  if (!addresses.length || addresses.some((address) => isIP(address) === 4 ? privateIpv4(address) : isIP(address) === 6 ? privateIpv6(address) : true)) throw new ApiError(400, "GUARDIAN_TARGET_DENIED", "The registered Guardian target is not permitted.");
  return url;
}
export class RegisteredWebsiteHttpInspector implements GuardianInspector {
  private readonly request: typeof fetch; private readonly resolve: AddressResolver; private readonly maximumRedirects: number;
  constructor(request: typeof fetch = fetch, resolve: AddressResolver = defaultResolver, maximumRedirects = 5) { this.request = request; this.resolve = resolve; this.maximumRedirects = maximumRedirects; }
  private async fetchTerminal(value: string, origin: string) { let current = value; const visited = new Set<string>(); for (let redirects = 0; redirects <= this.maximumRedirects; redirects += 1) { const url = await validateGuardianTarget(current, origin, this.resolve); if (visited.has(url.toString())) throw new ApiError(400, "GUARDIAN_REDIRECT_LOOP", "The registered endpoint redirect could not be completed safely."); visited.add(url.toString()); const response = await this.request(url, { method: "GET", redirect: "manual", signal: AbortSignal.timeout(8_000) }); if (response.status < 300 || response.status >= 400) return response; const location = response.headers.get("location"); if (!location || redirects === this.maximumRedirects) throw new ApiError(400, "GUARDIAN_REDIRECT_INVALID", "The registered endpoint redirect could not be completed safely."); try { current = new URL(location, url).toString(); } catch { throw new ApiError(400, "GUARDIAN_REDIRECT_INVALID", "The registered endpoint redirect could not be completed safely."); } } throw new ApiError(400, "GUARDIAN_REDIRECT_INVALID", "The registered endpoint redirect could not be completed safely."); }
  async inspect(website: GuardianWebsite) {
    if (!website.baseUrl) return website.checks.map((kind) => ({ kind, status: "NOT_CHECKED" as const, summary: "Website URL is not configured.", reason: "CONFIGURATION_REQUIRED" }));
    let base: URL; try { base = new URL(website.baseUrl); } catch { return website.checks.map((kind) => ({ kind, status: kind === "AVAILABILITY" ? "FAIL" as const : "NOT_CHECKED" as const, summary: kind === "AVAILABILITY" ? "Registered website configuration is invalid." : "Check was not attempted because website configuration is invalid.", reason: "GUARDIAN_TARGET_DENIED", ...(kind === "AVAILABILITY" ? { evidence: { signature: "GUARDIAN_TARGET_DENIED" } } : {}) })); }
    const origin = base.origin; const targets = [{ kind: "AVAILABILITY" as const, value: website.baseUrl }, ...website.importantRoutes.map((route) => { try { return { kind: "ROUTES" as const, value: new URL(route, website.baseUrl).toString() }; } catch { return { kind: "ROUTES" as const, value: String(route) }; } }), ...(website.healthEndpoint ? [{ kind: "API_HEALTH" as const, value: (() => { try { return new URL(website.healthEndpoint!, website.baseUrl).toString(); } catch { return website.healthEndpoint!; } })() }] : [])];
    const results: GuardianCheckResult[] = [];
    for (const target of targets) { let path = "registered-target"; try { path = new URL(target.value).pathname; const response = await this.fetchTerminal(target.value, origin); const passed = response.status >= 200 && response.status < 300; results.push({ kind: target.kind, status: passed ? "PASS" : "FAIL", target: path, summary: passed ? "Registered endpoint responded successfully." : "Registered endpoint returned an unhealthy status.", evidence: { statusCode: response.status, signature: `http-${response.status}` } }); } catch (caught) { const code = caught instanceof ApiError ? caught.code : caught instanceof Error && caught.name === "TimeoutError" ? "GUARDIAN_TIMEOUT" : "GUARDIAN_NETWORK_FAILURE"; results.push({ kind: target.kind, status: "FAIL", target: path, summary: "Registered endpoint check failed.", reason: code, evidence: { signature: code } }); } }
    for (const kind of website.checks) if (!results.some((item) => item.kind === kind)) results.push(kind === "API_HEALTH" && !website.healthEndpoint ? { kind, status: "NOT_CHECKED", summary: "No authoritative health endpoint is configured.", reason: "HEALTH_ENDPOINT_NOT_CONFIGURED" } : { kind, status: "NOT_CHECKED", summary: "This check is not available in the configured inspection infrastructure.", reason: `CAPABILITY_${guardianCheckCapabilities[kind]}` });
    return results;
  }
}

export class GuardianService {
  private readonly repository: GuardianRepository; private readonly workspaces: WorkspaceAuthorizationService; private readonly inspector: GuardianInspector; private readonly diagnostics?: DiagnosticsStore; private readonly configured: GuardianWebsite[]; private tasks?: WorkspaceTaskService;
  private repairs?: GuardianRepairService;
  constructor(repository: GuardianRepository, workspaces: WorkspaceAuthorizationService, inspector: GuardianInspector, diagnostics?: DiagnosticsStore, configured: GuardianWebsite[] = []) { this.repository = repository; this.workspaces = workspaces; this.inspector = inspector; this.diagnostics = diagnostics; this.configured = configured; }
  setTaskService(tasks: WorkspaceTaskService) { this.tasks = tasks; }
  setRepairService(repairs: GuardianRepairService) { this.repairs = repairs; }
  repairService() { if (!this.repairs) throw new ApiError(503, "GUARDIAN_REPAIR_UNAVAILABLE", "Guardian supervised repair is unavailable."); return this.repairs; }
  async listWebsites(auth: AuthContext, workspaceId: string) { await this.workspaces.requirePermission(auth, workspaceId, "workspace:read"); const durable = await this.repository.listWebsites(workspaceId); return [...durable, ...this.configured.filter((item) => item.workspaceId === workspaceId && !durable.some((saved) => saved.id === item.id))]; }
  async getReport(auth: AuthContext, workspaceId: string, reportId: string) { await this.workspaces.requirePermission(auth, workspaceId, "workspace:read"); const report = await this.repository.getReport(workspaceId, reportId); if (!report) throw new ApiError(404, "GUARDIAN_REPORT_NOT_FOUND", "The Guardian report was not found."); return report; }
  async listFindings(auth: AuthContext, workspaceId: string, websiteId: string) { await this.workspaces.requirePermission(auth, workspaceId, "workspace:read"); const website = await this.repository.getWebsite(workspaceId, websiteId); if (!website) throw new ApiError(404, "GUARDIAN_WEBSITE_NOT_FOUND", "The registered website is unavailable."); return this.repository.listFindings(workspaceId, websiteId); }
  async inspect(auth: AuthContext, workspaceId: string, websiteId: string, runId: string): Promise<GuardianHealthReport> {
    const context = await this.workspaces.requirePermission(auth, workspaceId, "workspace:manage"); const website = await this.repository.getWebsite(workspaceId, websiteId) ?? this.configured.find((item) => item.workspaceId === workspaceId && item.id === websiteId) ?? null; if (!website || !website.enabled) throw new ApiError(404, "GUARDIAN_WEBSITE_NOT_FOUND", "The registered website is unavailable.");
    const checkedAt = new Date().toISOString(); const checks = await this.inspector.inspect(website); const failures = [...new Map(checks.filter((item) => item.status === "FAIL").map((item) => [guardianFingerprint(website.id, item), item])).values()]; const findings: GuardianFinding[] = [];
    for (const check of failures) { const severity = guardianSeverity(check.kind, check.evidence?.signature); const fingerprint = guardianFingerprint(website.id, check); let finding = await this.repository.upsertFinding({ findingId: `guardian-${fingerprint}`, fingerprint, workspaceId, websiteId, runId, linkedRunIds: [runId], detectedAt: checkedAt, lastSeenAt: checkedAt, occurrenceCount: 1, category: check.kind, severity, title: `${check.kind.replaceAll("_", " ")} check failed`, description: check.summary, evidence: [check.evidence?.signature ?? "check-failed"], ...(check.target && website.baseUrl ? { affectedUrl: new URL(check.target, website.baseUrl).toString() } : {}), status: "OPEN", recommendedAction: "Create a human-controlled maintenance Task for investigation.", repairComplexity: severity === "MINOR" ? "LOW" : severity === "MODERATE" ? "MEDIUM" : "HIGH", recommendedSpecialists: check.kind === "RUNTIME" || check.kind === "API_HEALTH" ? ["backend", "testing"] : check.kind === "ASSETS" || check.kind === "UI_SMOKE" || check.kind === "RESPONSIVE" ? ["frontend", "testing"] : check.kind === "LINKS" || check.kind === "FORMS" ? ["testing", "frontend"] : ["testing"], observedInLatestRun: true }); if (this.tasks && !finding.maintenanceTaskId) { const task = await this.tasks.createFromGuardian(auth, workspaceId, finding.findingId, { title: `Guardian: ${finding.title}`, description: `Investigate Guardian finding ${finding.findingId} for registered website ${website.id}. No repair is authorized by this Task.`, priority: severity === "CRITICAL" || severity === "MAJOR" ? "HIGH" : severity === "MODERATE" ? "NORMAL" : "LOW", assignedAgentIds: finding.recommendedSpecialists }); finding = await this.repository.linkTask(workspaceId, finding.findingId, finding.fingerprint, task.id); } findings.push(finding); }
    await this.repository.markNotObserved(workspaceId, websiteId, new Set(findings.map((item) => item.fingerprint)));
    const report: GuardianHealthReport = { reportId: `guardian-report-${runId}`, workspaceId, websiteId, runId, checkedAt, status: guardianStatus(checks), checks, findingIds: findings.map((item) => item.findingId), recommendedActions: findings.map((item) => item.recommendedAction), sourceChangesPerformed: false }; await this.repository.saveReport(report); await this.repository.saveWebsite({ ...website, lastCheckedAt: checkedAt, updatedAt: checkedAt });
    if (this.diagnostics) { const errorCodes = [...new Set(checks.filter((item) => item.status !== "PASS").map((item) => item.reason ?? `GUARDIAN_${item.kind}_${item.status}`))]; const diagnostic: AiDiagnostic = { requestId: runId, workspaceId, businessId: context.business.id, startedAt: checkedAt, durationMs: 0, finalStatus: report.status === "HEALTHY" ? "completed" : "partial", plan: { taskCount: 1, agentIds: ["guardian"] }, tasks: [{ taskId: `${runId}:guardian`, agentId: "guardian", status: "completed", durationMs: 0, providerCalls: 0, tokenUsage: { inputTokens: 0, outputTokens: 0, totalTokens: 0 }, validationStatus: "valid" }], citations: [], requestedSkills: ["website.health_check", "website.health_report"], selectedAgentIds: ["guardian"], selectedTeamSize: 1, tasksCompleted: 1, tasksFailed: 0, safeSynthesis: true, errorCodes, providerCalls: 0, tokenUsage: { inputTokens: 0, outputTokens: 0, totalTokens: 0 }, guardianExecution: { websiteId, reportId: report.reportId, findingIds: report.findingIds, checks: checks.map((item) => ({ kind: item.kind, status: item.status, ...(item.target ? { target: item.target } : {}), ...(item.reason ? { errorCode: item.reason } : {}) })) } }; await this.diagnostics.add(diagnostic); }
    return report;
  }
}

export function initialGuardianWebsites(env: NodeJS.ProcessEnv, now = new Date().toISOString()): GuardianWebsite[] { return [["averon", "Averon Technologies", env.AVERON_WEBSITE_URL, env.AVERON_HEALTH_ENDPOINT], ["movento", "Movento", env.MOVENTO_WEBSITE_URL, env.MOVENTO_HEALTH_ENDPOINT], ["lumora", "Lumora", env.LUMORA_WEBSITE_URL, env.LUMORA_HEALTH_ENDPOINT]].map(([workspaceId, name, baseUrl, healthEndpoint]) => ({ id: `${workspaceId}-website`, workspaceId: workspaceId!, name: name!, ...(baseUrl ? { baseUrl } : {}), enabled: true, environment: "production", ...(healthEndpoint ? { healthEndpoint } : {}), importantRoutes: ["/"], checks: ["AVAILABILITY", "ROUTES", "ASSETS", "LINKS", "UI_SMOKE", "RUNTIME", "FORMS", "API_HEALTH", "RESPONSIVE"], createdAt: now, updatedAt: now })); }
