import type { BusinessOsSectionType, BusinessOsVisibility, WorkspaceContext } from "@averon/shared-types";
import { ApiError } from "../../errors/api-error.ts";
import type { AuthContext } from "../../services/auth/authentication.ts";
import type { WorkspaceAuthorizationService } from "../workspaces/workspace.service.ts";
import { businessOsPermissions } from "../workspaces/workspace.types.ts";
import { parseDecisionCreate, parseDecisionUpdate, parseSectionCreate, parseSectionUpdate } from "./business-os.schemas.ts";
import type { BusinessContextRequest, BusinessContextResult, BusinessOsRepository } from "./business-os.types.ts";

export class BusinessOsService {
  private readonly repository: BusinessOsRepository; private readonly workspaces: WorkspaceAuthorizationService;
  constructor(repository: BusinessOsRepository, workspaces: WorkspaceAuthorizationService) { this.repository = repository; this.workspaces = workspaces; }
  private allowed(context: WorkspaceContext, visibility: BusinessOsVisibility) { if (visibility === "public") return true; if (visibility === "internal") return context.role !== "viewer"; return context.role === "owner" || context.role === "admin"; }
  private async readContext(auth: AuthContext, workspaceId: string) { return this.workspaces.requireBusinessOsPermission(auth, workspaceId, "business-os:read"); }
  private async manageContext(auth: AuthContext, workspaceId: string) { return this.workspaces.requireBusinessOsPermission(auth, workspaceId, "business-os:manage"); }
  async metadata(auth: AuthContext, workspaceId: string) { const context = await this.readContext(auth, workspaceId); const item = await this.repository.get(workspaceId); return { businessOs: item, workspace: context.workspace, business: context.business, access: { canManage: businessOsPermissions[context.role].includes("business-os:manage") } }; }
  async initialize(auth: AuthContext, workspaceId: string) { const context = await this.manageContext(auth, workspaceId); return this.repository.initialize(workspaceId, context.business.id, auth.user.userId); }
  async sections(auth: AuthContext, workspaceId: string, types?: BusinessOsSectionType[], maximumRecords = 25) { const context = await this.readContext(auth, workspaceId); const items = await this.repository.listSections(workspaceId, types, maximumRecords); return { items: items.filter((item) => item.status === "active" && this.allowed(context, item.visibility)) }; }
  async section(auth: AuthContext, workspaceId: string, sectionId: string) { const context = await this.readContext(auth, workspaceId); const item = await this.repository.getSection(workspaceId, sectionId); if (!item || !this.allowed(context, item.visibility)) throw new ApiError(404, "BUSINESS_OS_SECTION_NOT_FOUND", "The Business OS section was not found."); return item; }
  async createSection(auth: AuthContext, workspaceId: string, body: unknown) { const context = await this.manageContext(auth, workspaceId); const root = await this.repository.get(workspaceId); if (!root) throw new ApiError(409, "BUSINESS_OS_NOT_INITIALIZED", "Initialize Business OS before adding sections."); const input = parseSectionCreate(body); return this.repository.createSection({ ...input, workspaceId, businessId: context.business.id, updatedBy: auth.user.userId, actorId: auth.user.userId }); }
  async updateSection(auth: AuthContext, workspaceId: string, sectionId: string, body: unknown) { await this.manageContext(auth, workspaceId); return this.repository.updateSection(workspaceId, sectionId, parseSectionUpdate(body), auth.user.userId); }
  async decisions(auth: AuthContext, workspaceId: string) { await this.readContext(auth, workspaceId); return { items: await this.repository.listDecisions(workspaceId) }; }
  async createDecision(auth: AuthContext, workspaceId: string, body: unknown) { const context = await this.manageContext(auth, workspaceId); const root = await this.repository.get(workspaceId); if (!root) throw new ApiError(409, "BUSINESS_OS_NOT_INITIALIZED", "Initialize Business OS before adding decisions."); return this.repository.createDecision({ ...parseDecisionCreate(body), workspaceId, businessId: context.business.id, actorId: auth.user.userId }); }
  async updateDecision(auth: AuthContext, workspaceId: string, decisionId: string, body: unknown) { await this.manageContext(auth, workspaceId); return this.repository.updateDecision(workspaceId, decisionId, parseDecisionUpdate(body), auth.user.userId); }
  async history(auth: AuthContext, workspaceId: string, maximumRecords = 50) { await this.readContext(auth, workspaceId); return { items: await this.repository.listHistory?.(workspaceId, Math.max(1, Math.min(maximumRecords, 100))) ?? [] }; }
  async getBusinessContext(auth: AuthContext, request: BusinessContextRequest): Promise<BusinessContextResult> { const context = await this.readContext(auth, request.workspaceId); const root = await this.repository.get(request.workspaceId); if (!root) throw new ApiError(404, "BUSINESS_OS_NOT_FOUND", "Business OS has not been initialized."); const maximum = Math.max(1, Math.min(request.maximumRecords ?? 12, 25)); const items = await this.repository.listSections(request.workspaceId, request.requestedSections, maximum); return { businessOs: root, sections: items.filter((item) => item.status === "active" && this.allowed(context, item.visibility) && (request.includeRestricted || item.visibility !== "restricted")).slice(0, maximum) }; }
}
