import type { BusinessDecisionStatus, BusinessOsContent, BusinessOsSectionType, BusinessOsStatus, BusinessOsVisibility } from "@averon/shared-types";
import { ApiError } from "../../errors/api-error.ts";
import { sectionTypes, visibilities } from "./business-os.types.ts";

function object(value: unknown) { if (!value || typeof value !== "object" || Array.isArray(value)) throw new ApiError(400, "BUSINESS_OS_INVALID_REQUEST", "The request must be an object."); return value as Record<string, unknown>; }
function keys(input: Record<string, unknown>, allowed: string[]) { if (Object.keys(input).some((key) => !allowed.includes(key))) throw new ApiError(400, "BUSINESS_OS_UNKNOWN_FIELDS", "The request contains unsupported fields."); }
function text(value: unknown, label: string, minimum: number, maximum: number) { if (typeof value !== "string" || value.trim().length < minimum || value.trim().length > maximum) throw new ApiError(400, "BUSINESS_OS_INVALID_REQUEST", `${label} is invalid.`); return value.trim(); }
function optionalText(value: unknown, label: string, maximum: number) { return value === undefined ? undefined : text(value, label, 1, maximum); }
function validValue(value: unknown, depth = 0): boolean { if (depth > 2) return false; if (value === null || ["string", "number", "boolean"].includes(typeof value)) return typeof value !== "string" || value.length <= 10_000; if (Array.isArray(value)) return value.length <= 100 && value.every((item) => item === null || ["string", "number", "boolean"].includes(typeof item)); if (typeof value === "object") return Object.keys(value as object).length <= 50 && Object.values(value as object).every((item) => validValue(item, depth + 1)); return false; }
function content(value: unknown): BusinessOsContent { const input = object(value); keys(input, ["summary", "fields"]); const fields = object(input.fields); if (Object.keys(fields).length > 50 || !Object.values(fields).every((item) => validValue(item))) throw new ApiError(400, "BUSINESS_OS_INVALID_CONTENT", "Section content is invalid or too large."); return { ...(input.summary === undefined ? {} : { summary: text(input.summary, "summary", 1, 2000) }), fields } as BusinessOsContent; }

export function parseSectionCreate(value: unknown) { const input = object(value); keys(input, ["id", "type", "title", "content", "visibility", "status"]); if (!sectionTypes.includes(input.type as BusinessOsSectionType)) throw new ApiError(400, "BUSINESS_OS_INVALID_SECTION_TYPE", "The section type is invalid."); if (!visibilities.includes(input.visibility as BusinessOsVisibility)) throw new ApiError(400, "BUSINESS_OS_INVALID_VISIBILITY", "The section visibility is invalid."); const status = input.status ?? "active"; if (!(["active", "archived"] as unknown[]).includes(status)) throw new ApiError(400, "BUSINESS_OS_INVALID_STATUS", "The section status is invalid."); return { id: text(input.id, "id", 2, 128), type: input.type as BusinessOsSectionType, title: text(input.title, "title", 2, 160), content: content(input.content), visibility: input.visibility as BusinessOsVisibility, status: status as BusinessOsStatus }; }
export function parseSectionUpdate(value: unknown) { const input = object(value); keys(input, ["title", "content", "visibility", "status"]); if (!Object.keys(input).length) throw new ApiError(400, "BUSINESS_OS_INVALID_REQUEST", "At least one update is required."); if (input.visibility !== undefined && !visibilities.includes(input.visibility as BusinessOsVisibility)) throw new ApiError(400, "BUSINESS_OS_INVALID_VISIBILITY", "The section visibility is invalid."); if (input.status !== undefined && !["active", "archived"].includes(String(input.status))) throw new ApiError(400, "BUSINESS_OS_INVALID_STATUS", "The section status is invalid."); return { ...(input.title === undefined ? {} : { title: text(input.title, "title", 2, 160) }), ...(input.content === undefined ? {} : { content: content(input.content) }), ...(input.visibility === undefined ? {} : { visibility: input.visibility as BusinessOsVisibility }), ...(input.status === undefined ? {} : { status: input.status as BusinessOsStatus }) }; }
export function parseDecisionCreate(value: unknown) { const input = object(value); keys(input, ["id", "title", "summary", "rationale", "status", "effectiveDate", "supersedes"]); const status = input.status ?? "proposed"; if (!["proposed", "active", "superseded", "archived"].includes(String(status))) throw new ApiError(400, "BUSINESS_DECISION_INVALID_STATUS", "The decision status is invalid."); return { id: text(input.id, "id", 2, 128), title: text(input.title, "title", 2, 160), summary: text(input.summary, "summary", 2, 4000), rationale: optionalText(input.rationale, "rationale", 4000), status: status as BusinessDecisionStatus, effectiveDate: optionalText(input.effectiveDate, "effectiveDate", 40), supersedes: optionalText(input.supersedes, "supersedes", 128) }; }
export function parseDecisionUpdate(value: unknown) { const input = object(value); keys(input, ["title", "summary", "rationale", "status", "effectiveDate", "supersedes", "supersededBy"]); if (!Object.keys(input).length) throw new ApiError(400, "BUSINESS_OS_INVALID_REQUEST", "At least one update is required."); if (input.status !== undefined && !["proposed", "active", "superseded", "archived"].includes(String(input.status))) throw new ApiError(400, "BUSINESS_DECISION_INVALID_STATUS", "The decision status is invalid."); return { ...(input.title === undefined ? {} : { title: text(input.title, "title", 2, 160) }), ...(input.summary === undefined ? {} : { summary: text(input.summary, "summary", 2, 4000) }), ...(input.rationale === undefined ? {} : { rationale: optionalText(input.rationale, "rationale", 4000) }), ...(input.status === undefined ? {} : { status: input.status as BusinessDecisionStatus }), ...(input.effectiveDate === undefined ? {} : { effectiveDate: optionalText(input.effectiveDate, "effectiveDate", 40) }), ...(input.supersedes === undefined ? {} : { supersedes: optionalText(input.supersedes, "supersedes", 128) }), ...(input.supersededBy === undefined ? {} : { supersededBy: optionalText(input.supersededBy, "supersededBy", 128) }) }; }
