import type { DocumentData, Firestore } from "firebase-admin/firestore";
import type { BusinessDecision, BusinessOs, BusinessOsHistoryItem, BusinessOsSection } from "@averon/shared-types";
import { ApiError } from "../../errors/api-error.ts";
import { getFirebaseAdminServices } from "../../services/firebase/admin.ts";
import type { BusinessOsRepository } from "./business-os.types.ts";

function data<T>(snapshot: { id: string; data(): DocumentData | undefined }): T { return { id: snapshot.id, ...snapshot.data() } as T; }
export class FirebaseBusinessOsRepository implements BusinessOsRepository {
  private readonly db: Firestore; constructor(db: Firestore = getFirebaseAdminServices().firestore) { this.db = db; }
  private root(id: string) { return this.db.collection("businessOs").doc(id); }
  async get(workspaceId: string) { const found = await this.root(workspaceId).get(); return found.exists ? found.data() as BusinessOs : null; }
  async initialize(workspaceId: string, businessId: string, actorId: string) { const ref = this.root(workspaceId); const result = await this.db.runTransaction(async (tx) => { const found = await tx.get(ref); if (found.exists) return { item: found.data() as BusinessOs, created: false }; const item: BusinessOs = { workspaceId, businessId, status: "active", schemaVersion: 1 }; const now = getFirebaseAdminServices().serverTimestamp(); tx.create(ref, { ...item, createdAt: now, updatedAt: now, updatedBy: actorId }); return { item, created: true }; }); return result; }
  async listSections(workspaceId: string, types?: BusinessOsSection["type"][], limit = 25) { const found = await this.root(workspaceId).collection("sections").orderBy("type").limit(Math.min(limit, 50)).get(); return found.docs.map((doc) => data<BusinessOsSection>(doc)).filter((item) => !types?.length || types.includes(item.type)); }
  async getSection(workspaceId: string, sectionId: string) { const found = await this.root(workspaceId).collection("sections").doc(sectionId).get(); return found.exists ? data<BusinessOsSection>(found) : null; }
  async createSection(input: Omit<BusinessOsSection, "version"> & { actorId: string }) { const ref = this.root(input.workspaceId).collection("sections").doc(input.id); if ((await ref.get()).exists) throw new ApiError(409, "BUSINESS_OS_SECTION_EXISTS", "The Business OS section already exists."); const { actorId, ...section } = input; const item = { ...section, version: 1, updatedBy: actorId }; const now = getFirebaseAdminServices().serverTimestamp(); const batch = this.db.batch(); batch.create(ref, { ...item, createdAt: now, updatedAt: now }); batch.set(this.db.collection("auditLogs").doc(), { actorId, action: "BUSINESS_OS_SECTION_CREATED", targetCollection: "businessOs.sections", targetId: input.id, workspaceId: input.workspaceId, businessId: input.businessId, sectionType: input.type, createdAt: now }); await batch.commit(); return item; }
  async updateSection(workspaceId: string, sectionId: string, patch: Partial<Pick<BusinessOsSection, "title" | "content" | "visibility" | "status">>, actorId: string) { const ref = this.root(workspaceId).collection("sections").doc(sectionId); return this.db.runTransaction(async (tx) => { const found = await tx.get(ref); if (!found.exists) throw new ApiError(404, "BUSINESS_OS_SECTION_NOT_FOUND", "The Business OS section was not found."); const current = data<BusinessOsSection>(found); const item = { ...current, ...patch, version: current.version + 1, updatedBy: actorId }; const now = getFirebaseAdminServices().serverTimestamp(); tx.update(ref, { ...patch, version: item.version, updatedBy: actorId, updatedAt: now }); tx.set(this.db.collection("auditLogs").doc(), { actorId, action: "BUSINESS_OS_SECTION_UPDATED", targetCollection: "businessOs.sections", targetId: sectionId, workspaceId, businessId: current.businessId, sectionType: current.type, version: item.version, createdAt: now }); return item; }); }
  async listDecisions(workspaceId: string) { const found = await this.root(workspaceId).collection("decisions").orderBy("updatedAt", "desc").limit(50).get(); return found.docs.map((doc) => data<BusinessDecision>(doc)); }
  async createDecision(input: Omit<BusinessDecision, "version" | "createdBy" | "updatedBy"> & { actorId: string }) { const ref = this.root(input.workspaceId).collection("decisions").doc(input.id); if ((await ref.get()).exists) throw new ApiError(409, "BUSINESS_DECISION_EXISTS", "The business decision already exists."); const { actorId, ...decision } = input; const item = { ...decision, version: 1, createdBy: actorId, updatedBy: actorId }; const now = getFirebaseAdminServices().serverTimestamp(); const batch = this.db.batch(); batch.create(ref, { ...item, createdAt: now, updatedAt: now }); batch.set(this.db.collection("auditLogs").doc(), { actorId, action: "BUSINESS_DECISION_CREATED", targetCollection: "businessOs.decisions", targetId: input.id, workspaceId: input.workspaceId, businessId: input.businessId, createdAt: now }); await batch.commit(); return item; }
  async updateDecision(workspaceId: string, decisionId: string, patch: Partial<Pick<BusinessDecision, "title" | "summary" | "rationale" | "status" | "effectiveDate" | "supersedes" | "supersededBy">>, actorId: string) { const ref = this.root(workspaceId).collection("decisions").doc(decisionId); return this.db.runTransaction(async (tx) => { const found = await tx.get(ref); if (!found.exists) throw new ApiError(404, "BUSINESS_DECISION_NOT_FOUND", "The business decision was not found."); const current = data<BusinessDecision>(found); const item = { ...current, ...patch, version: current.version + 1, updatedBy: actorId }; const now = getFirebaseAdminServices().serverTimestamp(); tx.update(ref, { ...patch, version: item.version, updatedBy: actorId, updatedAt: now }); tx.set(this.db.collection("auditLogs").doc(), { actorId, action: "BUSINESS_DECISION_UPDATED", targetCollection: "businessOs.decisions", targetId: decisionId, workspaceId, businessId: current.businessId, version: item.version, createdAt: now }); return item; }); }
  async listHistory(workspaceId: string, limit = 50) { const found = await this.db.collection("auditLogs").where("workspaceId", "==", workspaceId).limit(Math.min(limit, 100)).get(); const allowed = new Set(["BUSINESS_OS_SECTION_CREATED", "BUSINESS_OS_SECTION_UPDATED", "BUSINESS_DECISION_CREATED", "BUSINESS_DECISION_UPDATED"]); return found.docs.map((doc): BusinessOsHistoryItem | null => { const item = doc.data(); if (!allowed.has(String(item.action))) return null; return { id: doc.id, workspaceId, eventType: item.action, targetType: String(item.targetCollection).endsWith("sections") ? "section" : "decision", targetId: String(item.targetId), ...(typeof item.version === "number" ? { version: item.version } : {}), ...(typeof item.actorId === "string" ? { actorId: item.actorId } : {}), ...(item.createdAt ? { occurredAt: item.createdAt } : {}) } as BusinessOsHistoryItem; }).filter((item): item is BusinessOsHistoryItem => Boolean(item)).sort((a, b) => { const seconds = (value: unknown) => value && typeof value === "object" && "_seconds" in value ? Number((value as { _seconds: unknown })._seconds) : typeof value === "string" ? Date.parse(value) / 1000 : 0; return seconds(b.occurredAt) - seconds(a.occurredAt); }); }
}
