import { afterEach, describe, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import type { WorkspaceAutomation, WorkspaceAutomationsResponse, WorkspaceSummary } from "@averon/shared-types";
vi.mock("../src/firebase", () => ({ firebaseAuth: { currentUser: null }, googleAuthProvider: {} }));
import { averonApi } from "../src/api";
import { AutomationsControlCenter } from "../src/automations-control-center";

afterEach(() => { cleanup(); vi.restoreAllMocks(); });
const workspace = (id = "averon", canManage = true): WorkspaceSummary => ({ workspace: { id, businessId: id, name: id === "averon" ? "Averon Technologies" : "Lumora", slug: id, status: "active" }, business: { id, name: id, slug: id, status: "active" }, role: canManage ? "owner" : "member", permissions: canManage ? ["workspace:read", "workspace:manage"] : ["workspace:read"] });
const automation: WorkspaceAutomation = { id: "automation-1", workspaceId: "averon", title: "Weekly SEO Review", description: "Create a review Task.", enabled: true, trigger: { type: "WEEKLY", weekday: 1, time: "09:00", timezone: "Europe/Rome" }, operation: { type: "CREATE_TASK", taskTemplate: { title: "Review SEO", description: "Review metadata.", priority: "NORMAL", assignedAgentIds: ["seo"] } }, createdBy: "user-1", updatedBy: "user-1", version: 1, nextRunAt: "2030-09-02T07:00:00.000Z", linkedTaskIds: [] };
const response = (id: string, canManage = true): WorkspaceAutomationsResponse => ({ workspace: { id, name: id === "averon" ? "Averon Technologies" : "Lumora" }, canManage, items: [{ ...automation, id: `${id}-automation`, workspaceId: id, title: id === "averon" ? automation.title : "Lumora Review" }], agentIdentities: { seo: { displayName: "Mantis", displayRole: "SEO Agent" } } });
function mocks() {
  vi.spyOn(averonApi.automations, "list").mockImplementation(async (id) => ({ success: true, data: response(id, id === "averon"), requestId: "list" }));
  vi.spyOn(averonApi.automations, "get").mockImplementation(async (id, automationId) => ({ success: true, data: { ...response(id).items[0]!, id: automationId, history: [{ id: "event-1", workspaceId: id, automationId, eventType: "automation.created", actorId: "user-1", version: 1 }] }, requestId: "get" }));
}

describe("Automations Control Center", () => {
  it("renders schedule, canonical agent identity, detail and durable history", async () => { mocks(); render(<AutomationsControlCenter workspace={workspace()}/>); fireEvent.click(await screen.findByRole("button", { name: /Weekly SEO Review/ })); expect(await screen.findByText("Schedule")).toBeTruthy(); expect(screen.getByText("Every Monday · 09:00")).toBeTruthy(); expect(screen.getByText("created")).toBeTruthy(); });
  it("creates disabled by default and updates with expectedVersion", async () => { mocks(); const create = vi.spyOn(averonApi.automations, "create").mockResolvedValue({ success: true, data: automation, requestId: "create" }); const update = vi.spyOn(averonApi.automations, "update").mockResolvedValue({ success: true, data: { ...automation, enabled: false, version: 2 }, requestId: "update" }); render(<AutomationsControlCenter workspace={workspace()}/>); await screen.findByText("Weekly SEO Review"); fireEvent.click(screen.getByRole("button", { name: "New Automation" })); expect((screen.getByRole("checkbox", { name: "Enabled immediately" }) as HTMLInputElement).checked).toBe(false); fireEvent.change(screen.getByLabelText("Automation title"), { target: { value: "Daily review" } }); fireEvent.change(screen.getByLabelText("Automation description"), { target: { value: "Create a Task" } }); fireEvent.change(screen.getByLabelText("Task title"), { target: { value: "Review site" } }); fireEvent.change(screen.getByLabelText("Task description"), { target: { value: "Review canonical records" } }); fireEvent.click(screen.getByRole("button", { name: "Create Automation" })); await waitFor(() => expect(create).toHaveBeenCalledWith("averon", expect.objectContaining({ enabled: false, operation: expect.objectContaining({ type: "CREATE_TASK" }) }))); fireEvent.click(screen.getByRole("button", { name: /Weekly SEO Review/ })); await screen.findByText("Schedule"); fireEvent.click(screen.getByRole("button", { name: "Pause" })); await waitFor(() => expect(update).toHaveBeenCalledWith("averon", "averon-automation", { expectedVersion: 1, enabled: false })); expect("run" in averonApi.automations).toBe(false); });
  it("clears list, detail and drafts across workspaces and hides mutations for read-only users", async () => { mocks(); const view = render(<AutomationsControlCenter workspace={workspace()}/>); await screen.findByText("Weekly SEO Review"); fireEvent.click(screen.getByRole("button", { name: "New Automation" })); fireEvent.change(screen.getByLabelText("Automation title"), { target: { value: "Private draft" } }); view.rerender(<AutomationsControlCenter workspace={workspace("lumora", false)}/>); expect(await screen.findByText("Lumora Review")).toBeTruthy(); expect(screen.queryByText("Weekly SEO Review")).toBeNull(); expect(screen.queryByDisplayValue("Private draft")).toBeNull(); expect(screen.queryByRole("button", { name: "New Automation" })).toBeNull(); });
});
