import { afterEach, describe, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { createMemoryRouter, MemoryRouter, Route, RouterProvider, Routes } from "react-router";
import type { BusinessOsSection } from "@averon/shared-types";
vi.mock("../src/firebase", () => ({ firebaseAuth: { currentUser: null }, googleAuthProvider: {} }));
import { BusinessOsControlCenter } from "../src/business-os-control-center";
import { averonApi } from "../src/api";
afterEach(() => { cleanup(); vi.restoreAllMocks(); });
const section: BusinessOsSection = { id: "brand", workspaceId: "averon", businessId: "averon", type: "brand", title: "Brand foundation", content: { summary: "Authoritative brand guidance", fields: { voice: "Clear and calm" } }, visibility: "internal", status: "active", version: 2, updatedBy: "user-1", updatedAt: "2026-09-01T08:00:00.000Z" };
function mocks(canManage = true) { vi.spyOn(averonApi.businessOs, "get").mockResolvedValue({ success: true, data: { businessOs: { workspaceId: "averon", businessId: "averon", status: "active", schemaVersion: 1 }, workspace: { id: "averon", businessId: "averon", name: "Averon Technologies", slug: "averon", status: "active" }, business: { id: "averon", name: "Averon Technologies", slug: "averon", status: "active" }, access: { canManage } }, requestId: "root" }); vi.spyOn(averonApi.businessOs, "listSections").mockResolvedValue({ success: true, data: { items: [section] }, requestId: "sections" }); vi.spyOn(averonApi.businessOs, "listDecisions").mockResolvedValue({ success: true, data: { items: [{ id: "decision-1", workspaceId: "averon", businessId: "averon", title: "Keep APIs private", summary: "Server-owned integrations remain private.", status: "active", version: 1, createdBy: "user-1", updatedBy: "user-1" }] }, requestId: "decisions" }); vi.spyOn(averonApi.businessOs, "history").mockResolvedValue({ success: true, data: { items: [{ id: "history-1", workspaceId: "averon", eventType: "BUSINESS_OS_SECTION_UPDATED", targetType: "section", targetId: "brand", version: 2 }] }, requestId: "history" }); }
const mounted = () => render(<MemoryRouter initialEntries={["/workspaces/averon/business-os"]}><Routes><Route path="/workspaces/:workspaceId/business-os" element={<BusinessOsControlCenter/>}/></Routes></MemoryRouter>);
describe("Business OS Control Center", () => {
  it("renders authoritative overview, accessible knowledge, decisions, history and deterministic search", async () => { mocks(); mounted(); expect(await screen.findByText("Operational knowledge")).toBeTruthy(); expect(screen.getAllByText("1", { selector: "strong" })).toHaveLength(2); fireEvent.click(screen.getByRole("button", { name: "knowledge" })); expect(screen.getByText("Brand foundation")).toBeTruthy(); fireEvent.change(screen.getByPlaceholderText("Search Business OS"), { target: { value: "missing" } }); expect(screen.queryByText("Brand foundation")).toBeNull(); fireEvent.click(screen.getByRole("button", { name: "decisions" })); fireEvent.change(screen.getByPlaceholderText("Search Business OS"), { target: { value: "private" } }); expect(screen.getByText("Keep APIs private")).toBeTruthy(); fireEvent.change(screen.getByPlaceholderText("Search Business OS"), { target: { value: "" } }); fireEvent.click(screen.getByRole("button", { name: "history" })); expect(screen.getByText("BUSINESS OS SECTION UPDATED")).toBeTruthy(); });
  it("uses the existing human update endpoint only for authorized managers", async () => { mocks(); const update = vi.spyOn(averonApi.businessOs, "updateSection").mockResolvedValue({ success: true, data: { ...section, title: "Updated brand", version: 3 }, requestId: "update" }); mounted(); await screen.findByText("Operational knowledge"); fireEvent.click(screen.getByRole("button", { name: "knowledge" })); fireEvent.click(screen.getByRole("button", { name: /Brand foundation/ })); fireEvent.click(screen.getByRole("button", { name: "Edit" })); expect(screen.queryByText("Unsaved changes")).toBeNull(); expect((screen.getByRole("button", { name: "Save" }) as HTMLButtonElement).disabled).toBe(true); fireEvent.change(screen.getByLabelText("Title"), { target: { value: "Updated brand" } }); expect(screen.getByText("Unsaved changes")).toBeTruthy(); fireEvent.click(screen.getByRole("button", { name: "Save" })); await waitFor(() => expect(update).toHaveBeenCalledWith("averon", "brand", expect.objectContaining({ title: "Updated brand" }))); expect(await screen.findByText("Version 3")).toBeTruthy(); });
  it("keeps read-only users out of the edit path and makes zero provider calls", async () => { mocks(false); mounted(); await screen.findByText("Operational knowledge"); fireEvent.click(screen.getByRole("button", { name: "knowledge" })); fireEvent.click(screen.getByRole("button", { name: /Brand foundation/ })); expect(screen.queryByRole("button", { name: "Edit" })).toBeNull(); expect("generate" in averonApi.businessOs).toBe(false); });
  it("uses the existing authorized decision create and update endpoints", async () => {
    mocks();
    const created = { id: "decision-2", workspaceId: "averon", businessId: "averon", title: "Document releases", summary: "Record release decisions.", status: "proposed" as const, version: 1, createdBy: "user-1", updatedBy: "user-1" };
    const create = vi.spyOn(averonApi.businessOs, "createDecision").mockResolvedValue({ success: true, data: created, requestId: "create" });
    const update = vi.spyOn(averonApi.businessOs, "updateDecision").mockResolvedValue({ success: true, data: { ...created, title: "Document every release", version: 2 }, requestId: "update" });
    mounted(); await screen.findByText("Operational knowledge"); fireEvent.click(screen.getByRole("button", { name: "decisions" }));
    fireEvent.click(screen.getByRole("button", { name: "New decision" })); fireEvent.change(screen.getByLabelText("Decision ID"), { target: { value: "decision-2" } }); fireEvent.change(screen.getByLabelText("Title"), { target: { value: "Document releases" } }); fireEvent.change(screen.getByLabelText("Summary"), { target: { value: "Record release decisions." } }); fireEvent.click(screen.getByRole("button", { name: "Save decision" }));
    await waitFor(() => expect(create).toHaveBeenCalledWith("averon", expect.objectContaining({ id: "decision-2", title: "Document releases" })));
    fireEvent.click(screen.getAllByRole("button", { name: "Edit decision" }).at(-1)!); fireEvent.change(screen.getByLabelText("Title"), { target: { value: "Document every release" } }); fireEvent.click(screen.getByRole("button", { name: "Save decision" }));
    await waitFor(() => expect(update).toHaveBeenCalledWith("averon", "decision-2", expect.objectContaining({ title: "Document every release" }))); expect(await screen.findByText("Document every release")).toBeTruthy();
  });
  it("clears authorized records when the mounted route changes workspace", async () => {
    mocks();
    vi.mocked(averonApi.businessOs.get).mockImplementation(async (workspaceId) => ({ success: true, data: { businessOs: { workspaceId, businessId: workspaceId, status: "active", schemaVersion: 1 }, workspace: { id: workspaceId, businessId: workspaceId, name: workspaceId === "averon" ? "Averon Technologies" : "Lumora", slug: workspaceId, status: "active" }, business: { id: workspaceId, name: workspaceId, slug: workspaceId, status: "active" }, access: { canManage: workspaceId === "averon" } }, requestId: "root" }));
    vi.mocked(averonApi.businessOs.listSections).mockImplementation(async (workspaceId) => ({ success: true, data: { items: workspaceId === "averon" ? [section] : [{ ...section, id: "lumora-brand", workspaceId, businessId: workspaceId, title: "Lumora identity" }] }, requestId: "sections" }));
    const router = createMemoryRouter([{ path: "/workspaces/:workspaceId/business-os", element: <BusinessOsControlCenter/> }], { initialEntries: ["/workspaces/averon/business-os"] });
    render(<RouterProvider router={router}/>);
    await screen.findByText("Business OS — Averon Technologies"); fireEvent.click(screen.getByRole("button", { name: "decisions" })); fireEvent.click(screen.getByRole("button", { name: "New decision" })); fireEvent.change(screen.getByLabelText("Title"), { target: { value: "Averon private draft" } }); expect(screen.getByDisplayValue("Averon private draft")).toBeTruthy();
    await router.navigate("/workspaces/lumora/business-os");
    expect(await screen.findByText("Business OS — Lumora")).toBeTruthy();
    fireEvent.click(screen.getByRole("button", { name: "knowledge" }));
    expect(await screen.findByText("Lumora identity")).toBeTruthy();
    expect(screen.queryByText("Brand foundation")).toBeNull();
    expect(screen.queryByDisplayValue("Averon private draft")).toBeNull();
    fireEvent.click(screen.getByRole("button", { name: "decisions" })); expect(screen.queryByRole("button", { name: "New decision" })).toBeNull();
  });
});
