import { afterEach, describe, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { MemoryRouter } from "react-router";
import type { WorkspaceRunDetail, WorkspaceRunsResponse } from "@averon/shared-types";
vi.mock("../src/firebase", () => ({ firebaseAuth: { currentUser: null }, googleAuthProvider: {} }));
import { RunDetail, RunsCatalog, RunsView } from "../src/App";
import { averonApi } from "../src/api";
afterEach(() => { cleanup(); vi.restoreAllMocks(); });
const summary = { operationId: "proposal-1", requestId: "request-1", title: "SEO Metadata Update", workspace: { id: "averon", name: "Averon Technologies" }, status: "completed" as const, startedAt: "2026-08-31T10:00:00.000Z", updatedAt: "2026-08-31T10:00:14.000Z", durationMs: 14200, specialistIds: ["seo"], specialists: [{ id: "seo", displayName: "Mantis", displayRole: "SEO Agent" }], actionType: "seo.metadata.update", errorCodes: [] };
const data: WorkspaceRunsResponse = { workspace: summary.workspace, items: [summary] };
const detail: WorkspaceRunDetail = { ...summary, requestIds: ["request-1"], requestedSkills: ["seo.metadata"], skillCoverage: { "seo.metadata": "seo" }, specialistDetails: [{ id: "seo", displayName: "Mantis", displayRole: "SEO Agent", status: "completed", skills: ["seo.metadata"], providerCalls: 1, validationStatus: "valid", durationMs: 12000 }], providerCalls: 1, validationStatus: "valid", criticInvoked: false, tokenUsage: { inputTokens: 100, outputTokens: 50, totalTokens: 150 }, grounding: { citationCount: 1, groundedClaimCount: 1, unsupportedClaimCount: 0 }, actionTransitions: [{ status: "awaiting_approval", occurredAt: "2026-08-31T10:00:01.000Z", requestId: "request-1" }, { status: "completed", occurredAt: "2026-08-31T10:00:14.000Z", requestId: "request-1" }], trace: [{ kind: "request", label: "Request received" }, { kind: "planner", label: "Planner selected specialist team" }, { kind: "specialist", label: "Mantis · SEO Agent", status: "completed" }, { kind: "skill", label: "seo.metadata" }, { kind: "action", label: "seo.metadata.update" }, { kind: "lifecycle", label: "Awaiting Approval", status: "awaiting_approval" }, { kind: "lifecycle", label: "Completed", status: "completed" }] };

describe("workspace Runs surfaces", () => {
  it("renders a workspace-scoped run list with deterministic filters and identity", () => { const open = vi.fn(); render(<MemoryRouter><RunsCatalog data={data} onOpen={open}/></MemoryRouter>); expect(screen.getByRole("heading", { name: "Runs" })).toBeTruthy(); expect(screen.getByText("Mantis · SEO Agent")).toBeTruthy(); expect(screen.getByText("14.2s")).toBeTruthy(); fireEvent.click(screen.getByRole("button", { name: /SEO Metadata Update/ })); expect(open).toHaveBeenCalledWith(summary); fireEvent.click(screen.getByRole("button", { name: "Failed" })); expect(screen.getByText("No matching runs")).toBeTruthy(); });
  it("renders only authoritative trace, specialist and lifecycle detail", () => { render(<MemoryRouter><RunDetail run={detail} onBack={vi.fn()}/></MemoryRouter>); expect(screen.getByText("Request received")).toBeTruthy(); expect(screen.getAllByText("Mantis · SEO Agent").length).toBeGreaterThan(0); expect(screen.getAllByText("seo.metadata").length).toBeGreaterThan(0); expect(screen.getAllByText("Awaiting Approval").length).toBeGreaterThan(0); expect(screen.getByText("View agent catalog").getAttribute("href")).toBe("/agents"); expect(screen.queryByText(/prompt/i)).toBeNull(); });
  it("opens an explicitly linked Task Run directly from its safe operation ID", async () => { vi.spyOn(averonApi.runs, "list").mockResolvedValue({ success: true, data, requestId: "list" }); const get = vi.spyOn(averonApi.runs, "get").mockResolvedValue({ success: true, data: { ...detail, taskId: "task-1" }, requestId: "detail" }); const workspace = { workspace: { id: "averon", businessId: "averon", name: "Averon Technologies", slug: "averon", status: "active" as const }, business: { id: "averon", name: "Averon", slug: "averon", status: "active" as const }, role: "owner" as const, permissions: ["workspace:read"] }; render(<MemoryRouter initialEntries={["/runs?run=proposal-1"]}><RunsView workspace={workspace}/></MemoryRouter>); expect(await screen.findByText("Task")).toBeTruthy(); expect(screen.getByText("task-1")).toBeTruthy(); expect(get).toHaveBeenCalledWith("averon", "proposal-1"); });
  it("switches workspace catalogs without rendering cached records from the prior workspace", async () => { const list = vi.spyOn(averonApi.runs, "list").mockImplementation(async (workspaceId) => ({ success: true, data: workspaceId === "averon" ? data : { workspace: { id: "lumora", name: "Lumora" }, items: [{ ...summary, operationId: "lumora-run", requestId: "lumora-request", title: "Lumora Specialist Run", workspace: { id: "lumora", name: "Lumora" } }] }, requestId: workspaceId })); const workspace = (id: string, name: string) => ({ workspace: { id, businessId: id, name, slug: id, status: "active" as const }, business: { id, name, slug: id, status: "active" as const }, role: "owner" as const, permissions: ["workspace:read"] }); const { rerender } = render(<MemoryRouter><RunsView workspace={workspace("averon", "Averon Technologies")}/></MemoryRouter>); expect(await screen.findByText("SEO Metadata Update")).toBeTruthy(); rerender(<MemoryRouter><RunsView workspace={workspace("lumora", "Lumora")}/></MemoryRouter>); await waitFor(() => expect(screen.queryByText("SEO Metadata Update")).toBeNull()); expect(await screen.findByText("Lumora Specialist Run")).toBeTruthy(); expect(list).toHaveBeenCalledWith("averon"); expect(list).toHaveBeenCalledWith("lumora"); });
});
