import { afterEach, describe, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import type { WorkspaceSummary, WorkspaceTask, WorkspaceTasksResponse } from "@averon/shared-types";
vi.mock("../src/firebase", () => ({ firebaseAuth: { currentUser: null }, googleAuthProvider: {} }));
import { averonApi } from "../src/api";
import { TasksControlCenter } from "../src/tasks-control-center";
afterEach(() => { cleanup(); vi.restoreAllMocks(); });
const workspace = (id = "averon", role: WorkspaceSummary["role"] = "owner"): WorkspaceSummary => ({ workspace: { id, businessId: id, name: id === "averon" ? "Averon Technologies" : "Lumora", slug: id, status: "active" }, business: { id, name: id, slug: id, status: "active" }, role, permissions: role === "owner" ? ["workspace:read", "workspace:manage"] : ["workspace:read"] });
const task: WorkspaceTask = { id: "task-1", workspaceId: "averon", title: "Improve website SEO", description: "Review metadata", status: "IN_PROGRESS", priority: "HIGH", assignedAgentIds: ["seo", "research"], linkedRunIds: [], linkedActionIds: [], createdBy: "user-1", updatedBy: "user-1", version: 2 };
const response = (workspaceId = "averon", canManage = true): WorkspaceTasksResponse => ({ workspace: { id: workspaceId, name: workspaceId === "averon" ? "Averon Technologies" : "Lumora" }, canManage, items: workspaceId === "averon" ? [task] : [{ ...task, id: "lumora-task", workspaceId, title: "Lumora launch" }], agentIdentities: { seo: { displayName: "Mantis", displayRole: "SEO Agent" }, research: { displayName: "Atlas", displayRole: "Research Agent" } } });
function mocks() { vi.spyOn(averonApi.tasks, "list").mockImplementation(async (id) => ({ success: true, data: response(id, id === "averon"), requestId: "list" })); vi.spyOn(averonApi.tasks, "get").mockResolvedValue({ success: true, data: { ...task, history: [{ id: "event-1", workspaceId: "averon", taskId: task.id, eventType: "task.created", actorId: "user-1", changedFields: ["title"], version: 1 }] }, requestId: "get" }); }
describe("Tasks Control Center", () => {
  it("renders canonical identities, filters and durable Task detail", async () => { mocks(); render(<TasksControlCenter workspace={workspace()}/>); expect(await screen.findByText("Improve website SEO")).toBeTruthy(); expect(screen.getAllByText(/Mantis · SEO Agent/).length).toBeGreaterThan(0); fireEvent.click(screen.getByRole("button", { name: "Completed" })); expect(screen.queryByText("Improve website SEO")).toBeNull(); fireEvent.click(screen.getByRole("button", { name: "All" })); fireEvent.click(screen.getByRole("button", { name: /Improve website SEO/ })); expect(await screen.findByText("Organization")).toBeTruthy(); expect(screen.getByText("Task Created")).toBeTruthy(); expect(screen.getByRole("button", { name: /All Tasks/ }).classList.contains("task-detail-back")).toBe(true); expect(screen.getByRole("button", { name: "Edit Task" }).classList.contains("task-detail-action-secondary")).toBe(true); expect(screen.getByRole("button", { name: "Start Execution" }).classList.contains("task-detail-action-primary")).toBe(true); });
  it("edits Task content through the versioned human update endpoint", async () => { mocks(); const updated = { ...task, title: "Improve canonical SEO", description: "Review canonical metadata", version: 3 }; const update = vi.spyOn(averonApi.tasks, "update").mockResolvedValue({ success: true, data: updated, requestId: "update" }); vi.mocked(averonApi.tasks.get).mockResolvedValueOnce({ success: true, data: { ...task, history: [] }, requestId: "get" }).mockResolvedValueOnce({ success: true, data: { ...updated, history: [] }, requestId: "get-updated" }); render(<TasksControlCenter workspace={workspace()}/>); fireEvent.click(await screen.findByRole("button", { name: /Improve website SEO/ })); await screen.findByText("Organization"); fireEvent.click(screen.getByRole("button", { name: "Edit Task" })); fireEvent.change(screen.getByLabelText("Edit title"), { target: { value: "Improve canonical SEO" } }); fireEvent.change(screen.getByLabelText("Edit description"), { target: { value: "Review canonical metadata" } }); fireEvent.click(screen.getByRole("button", { name: "Save Task" })); await waitFor(() => expect(update).toHaveBeenCalledWith("averon", "task-1", expect.objectContaining({ expectedVersion: 2, title: "Improve canonical SEO", description: "Review canonical metadata" }))); expect(await screen.findByText("Improve canonical SEO")).toBeTruthy(); });
  it("creates through the human Task endpoint without any execution API", async () => { mocks(); const create = vi.spyOn(averonApi.tasks, "create").mockResolvedValue({ success: true, data: { ...task, id: "task-2", title: "Renew domain", assignedAgentIds: [], status: "TODO", priority: "NORMAL", version: 1 }, requestId: "create" }); render(<TasksControlCenter workspace={workspace()}/>); await screen.findByText("Improve website SEO"); fireEvent.click(screen.getByRole("button", { name: "New Task" })); fireEvent.change(screen.getByLabelText("Title"), { target: { value: "Renew domain" } }); fireEvent.change(screen.getByLabelText("Description"), { target: { value: "Renew registration" } }); fireEvent.click(screen.getByRole("button", { name: "Create Task" })); await waitFor(() => expect(create).toHaveBeenCalledWith("averon", expect.objectContaining({ title: "Renew domain", assignedAgentIds: [] }))); expect("run" in averonApi.tasks).toBe(false); });
  it("starts execution only from the explicit control and renders the linked Run result", async () => { mocks(); const execute = vi.spyOn(averonApi.tasks, "execute").mockResolvedValue({ success: true, data: { taskId: "task-1", runId: "task-run-1", status: "COMPLETED", idempotentReplay: false, summary: "The validated advisory execution completed." }, requestId: "execute" }); vi.mocked(averonApi.tasks.get).mockResolvedValueOnce({ success: true, data: { ...task, history: [] }, requestId: "get" }).mockResolvedValueOnce({ success: true, data: { ...task, status: "COMPLETED", lastRunId: "task-run-1", lastExecutionStatus: "COMPLETED", lastExecutionSummary: "The validated advisory execution completed.", linkedRunIds: ["task-run-1"], history: [] }, requestId: "completed" }); render(<TasksControlCenter workspace={workspace()}/>); fireEvent.click(await screen.findByRole("button", { name: /Improve website SEO/ })); await screen.findByText("Organization"); expect(execute).not.toHaveBeenCalled(); fireEvent.click(screen.getByRole("button", { name: "Start Execution" })); await waitFor(() => expect(execute).toHaveBeenCalledTimes(1)); expect(await screen.findByText("The validated advisory execution completed.")).toBeTruthy(); expect(screen.getByText(/task-run-1/)).toBeTruthy(); expect(screen.getByRole("link", { name: "View Run" }).getAttribute("href")).toBe("/runs?run=task-run-1"); });
  it("clears list detail and unsaved drafts on workspace switch and keeps read-only UI immutable", async () => { mocks(); const view = render(<TasksControlCenter workspace={workspace()}/>); await screen.findByText("Improve website SEO"); fireEvent.click(screen.getByRole("button", { name: "New Task" })); fireEvent.change(screen.getByLabelText("Title"), { target: { value: "Averon private draft" } }); view.rerender(<TasksControlCenter workspace={workspace("lumora", "member")}/>); expect(await screen.findByText("Lumora launch")).toBeTruthy(); expect(screen.queryByText("Improve website SEO")).toBeNull(); expect(screen.queryByDisplayValue("Averon private draft")).toBeNull(); expect(screen.queryByRole("button", { name: "New Task" })).toBeNull(); });
});
