import { createHash } from "node:crypto";
import { readFile, realpath, writeFile } from "node:fs/promises";
import { isAbsolute, relative, resolve, sep } from "node:path";
import type { AiMessage } from "../../ai/providers/ai-provider.ts";
import { ApiError } from "../../errors/api-error.ts";
import { log } from "../../logger.ts";
import type { AuthContext } from "../../services/auth/authentication.ts";
import type { WorkspaceAuthorizationService } from "../workspaces/workspace.service.ts";
import { MemoryBackendSourceProposalRepository, type BackendSourceProposalRepository } from "./backend-source.repository.ts";
import type { GuardianVerificationAssertion } from "@averon/shared-types";

export type BackendRisk = "low" | "medium" | "high";
export type BackendValidationResult = { name: "typecheck" | "lint" | "test" | "build" | "runtime"; passed: boolean };
export interface BackendValidationRunner { run(files: string[], proposal: BackendSourceProposal): Promise<BackendValidationResult[]> }
export type BackendSourceEdit = { path: string; symbol: string; find: string; replace: string; requestedField?: never; requestedValue?: never } | { path: string; symbol: string; requestedField: "service" | "runtime"; requestedValue: string; find?: never; replace?: never };
export type BackendSourceProposal = { actionId: string; workspaceId: string; status: "proposed" | "applying" | "verifying" | "completed" | "failed" | "rejected"; approvalStatus: "pending" | "approved" | "rejected"; risk: BackendRisk; noOp?: boolean; requestedMutations?: Array<{ field: string; value: string }>; files: Array<{ path: string; symbol: string; originalHash: string; proposedHash: string; original: string; proposed: string; insertions: number; deletions: number }>; diff: string; verification?: BackendValidationResult[]; rollbackStatus?: "not_required" | "completed" | "failed" };
const digest = (value: string) => createHash("sha256").update(value).digest("hex");
const denied = /(^|\/)(?:\.|node_modules|dist|build|migrations?|scripts?|generated)(?:\/|$)|(?:firebase|firestore|stripe|payment|auth|permission|secret|credential|webhook)|(?:\.env|\.sh$|\.json$)/i;
function diff(path: string, before: string, after: string) { const a = before.split("\n"), b = after.split("\n"); let start = 0; while (a[start] === b[start] && start < a.length) start++; let ae = a.length - 1, be = b.length - 1; while (ae >= start && be >= start && a[ae] === b[be]) { ae--; be--; } const removed = a.slice(start, ae + 1), added = b.slice(start, be + 1); return { text: [`--- a/${path}`, `+++ b/${path}`, `@@ -${start + 1},${removed.length} +${start + 1},${added.length} @@`, ...removed.map(v => `-${v}`), ...added.map(v => `+${v}`)].join("\n"), insertions: added.length, deletions: removed.length }; }
export async function resolveBackendSourcePath(path: string, root: string) { const allowed = resolve(root, "apps/averon-api/src"); if (!path || isAbsolute(path) || path.includes("..") || !path.endsWith(".ts") || denied.test(path)) throw new ApiError(400, "SOURCE_PATH_NOT_ALLOWED", "The backend source path is not allowed in v5."); const target = resolve(root, path); if (!target.startsWith(`${allowed}${sep}`)) throw new ApiError(400, "SOURCE_PATH_NOT_ALLOWED", "Only the approved API source root is allowed."); let canonical: string, canonicalRoot: string; try { [canonical, canonicalRoot] = await Promise.all([realpath(target), realpath(allowed)]); } catch { throw new ApiError(404, "SOURCE_TARGET_NOT_FOUND", "The backend source target was not found."); } if (!canonical.startsWith(`${canonicalRoot}${sep}`)) throw new ApiError(400, "SOURCE_PATH_NOT_ALLOWED", "The backend target escapes its root."); return { absolute: canonical, relative: relative(await realpath(root), canonical) }; }
export function classifyBackendRisk(edit: BackendSourceEdit): BackendRisk { if (denied.test(`${edit.path} ${edit.symbol} ${"find" in edit ? edit.find : edit.requestedField}`)) return "high"; if (/repository|orchestrat|provider|route|contract/i.test(`${edit.path} ${edit.symbol}`)) return "medium"; return "low"; }
export function boundedBackendEdits(message: string): BackendSourceEdit[] { if (/\bhealth\b/i.test(message) && /\b(?:field|response|status)\b/i.test(message)) { const requested = /\b(service|runtime)\s*:\s*["“]([^"”]+)["”]/i.exec(message); if (!requested) throw new ApiError(400, "SOURCE_PROPOSAL_INVALID", "The health field and static string value must be explicit."); const field = requested[1]!.toLowerCase() as "service" | "runtime"; const value = requested[2]!; const allowed = field === "service" ? value === "averon-api" : value === "local"; if (!allowed) throw new ApiError(403, "BACKEND_RISK_NOT_ALLOWED", "That health field/value is not allowlisted."); return [{ path: "apps/averon-api/src/app.ts", symbol: "GET /health", requestedField: field, requestedValue: value }]; } throw new ApiError(404, "SOURCE_TARGET_NOT_FOUND", "The backend target is outside the initial deterministic allowlist."); }
function matchingBlockEnd(source: string, openingBrace: number) {
  let depth = 0; let quote = ""; let escaped = false; let lineComment = false; let blockComment = false;
  for (let index = openingBrace; index < source.length; index++) {
    const char = source[index]!; const next = source[index + 1];
    if (lineComment) { if (char === "\n") lineComment = false; continue; }
    if (blockComment) { if (char === "*" && next === "/") { blockComment = false; index++; } continue; }
    if (quote) { if (escaped) escaped = false; else if (char === "\\") escaped = true; else if (char === quote) quote = ""; continue; }
    if (char === "/" && next === "/") { lineComment = true; index++; continue; }
    if (char === "/" && next === "*") { blockComment = true; index++; continue; }
    if (char === '"' || char === "'" || char === "`") { quote = char; continue; }
    if (char === "{") depth++;
    if (char === "}" && --depth === 0) return index + 1;
  }
  return -1;
}
function uniqueHealthHandler(source: string) {
  const route = /if\s*\(\s*req\.method\s*===\s*["']GET["']\s*&&\s*url\.pathname\s*===\s*["']\/health["']\s*\)\s*\{/g;
  const matches = [...source.matchAll(route)];
  if (matches.length !== 1 || matches[0]!.index === undefined) throw new ApiError(409, "SOURCE_CONFLICT", "The GET /health handler is missing or ambiguous.");
  const start = matches[0]!.index; const openingBrace = start + matches[0]![0].lastIndexOf("{"); const end = matchingBlockEnd(source, openingBrace);
  if (end < 0) throw new ApiError(409, "SOURCE_CONFLICT", "The GET /health handler boundary could not be resolved.");
  return source.slice(start, end);
}
export function backendSourceIntent(message: string, history: readonly AiMessage[] = []) { const pattern = /\b[A-Za-z0-9][A-Za-z0-9._-]{0,127}:backend\.source\.propose\b/g; const ids = [...new Set(message.match(pattern) ?? [])]; const contextualIds = history.filter(x => x.role === "assistant").flatMap(x => [...x.content.matchAll(/\bProposal(?: ID)?\s*:\s*([A-Za-z0-9:._-]+:backend\.source\.propose)\b/gi)].map(m => m[1]!)); const backendContext = /\bbackend\b/i.test(message) || ids.length > 0 || contextualIds.length > 0; const reject = backendContext && /\b(?:reject|decline|cancel)\b/i.test(message) && /\b(?:backend|source|proposal|proposed|change|it|that)\b/i.test(message); if (reject) return { action: "reject" as const, explicit: true, proposalId: ids[0], historyProposalIds: ids.length ? [] : contextualIds, proposalResolutionError: ids.length > 1 ? "SOURCE_PROPOSAL_AMBIGUOUS" : undefined }; const apply = backendContext && /\bapply\b/i.test(message) && /\b(?:backend|source|proposal|proposed|change|it|that)\b/i.test(message); if (apply) { const explicitRef = /\bapply\s+(?:(?:backend\s+)?source\s+)?proposal\s+(\S+)/i.test(message); const proposalResolutionError = ids.length > 1 ? "SOURCE_PROPOSAL_AMBIGUOUS" : explicitRef && ids.length === 0 ? "SOURCE_PROPOSAL_INVALID" : undefined; const historyProposalIds = ids.length || proposalResolutionError ? [] : contextualIds; return { action: "apply" as const, explicit: true, proposalId: ids[0], historyProposalIds, proposalResolutionError }; } const mutation = /\b(?:add|fix|change|improve|update|adjust|replace)\b/i.test(message); const backend = /\b(?:backend|api|server|endpoint|route|health)\b/i.test(message); return mutation && backend ? { action: "propose" as const, explicit: true } : { action: "none" as const, explicit: false }; }
export class BackendSourceActionService {
  private cache = new Map<string, BackendSourceProposal>();
  private readonly workspaces: WorkspaceAuthorizationService; private readonly validator: BackendValidationRunner; private readonly root: string; private readonly repository: BackendSourceProposalRepository;
  constructor(workspaces: WorkspaceAuthorizationService, validator: BackendValidationRunner, root: string, repository: BackendSourceProposalRepository = new MemoryBackendSourceProposalRepository()) { this.workspaces = workspaces; this.validator = validator; this.root = root; this.repository = repository; }
  async read(auth: AuthContext, workspaceId: string, path: string) { await this.workspaces.requirePermission(auth, workspaceId, "source:read"); const target = await resolveBackendSourcePath(path, this.root); return { path: target.relative, content: await readFile(target.absolute, "utf8") }; }
  async propose(auth: AuthContext, actionId: string, workspaceId: string, edits: BackendSourceEdit[]) { await this.workspaces.requirePermission(auth, workspaceId, "source:propose"); const prior = this.cache.get(actionId) ?? await this.repository.get(actionId); if (prior) return structuredClone(prior); if (!edits.length || edits.length > 3) throw new ApiError(400, "SOURCE_PROPOSAL_INVALID", "One to three backend edits are required."); const files: BackendSourceProposal["files"] = [], diffs: string[] = [], requestedMutations: NonNullable<BackendSourceProposal["requestedMutations"]> = []; let risk: BackendRisk = "low"; for (const edit of edits) { const editRisk = classifyBackendRisk(edit); if (editRisk === "high") throw new ApiError(403, "BACKEND_RISK_NOT_ALLOWED", "Sensitive backend surfaces are not writable in v5."); if (editRisk === "medium") risk = "medium"; const target = await resolveBackendSourcePath(edit.path, this.root); const original = await readFile(target.absolute, "utf8"); let find: string; let replace: string; if ("requestedField" in edit) { const requestedField = edit.requestedField!; const requestedValue = edit.requestedValue!; requestedMutations.push({ field: requestedField, value: requestedValue }); const handler = uniqueHealthHandler(original); const matches = [...handler.matchAll(/sendJson\(res,\s*200,\s*success\(\{[^}\n]*\},\s*requestId\)\);\s*return;/g)]; if (matches.length !== 1) throw new ApiError(409, "SOURCE_CONFLICT", "The health response boundary is missing or ambiguous."); const response = matches[0]![0]; const fieldPattern = new RegExp(`\\b${requestedField}\\s*:\\s*"([^"]*)"(?:\\s+as const)?`); const existing = fieldPattern.exec(response); let updatedResponse: string; if (existing?.[1] === requestedValue) { updatedResponse = response; } else if (existing) { updatedResponse = response.replace(existing[0], `${requestedField}: "${requestedValue}"`); } else { updatedResponse = response.replace(/\s*},\s*requestId/, `, ${requestedField}: "${requestedValue}" }, requestId`); } const introducedFields = [...updatedResponse.matchAll(/\b([A-Za-z_$][\w$]*)\s*:/g)].map(match => match[1]).filter(field => !response.match(new RegExp(`\\b${field}\\s*:`))); if (introducedFields.some(field => field !== requestedField)) throw new ApiError(400, "SOURCE_PROPOSAL_INVALID", "The proposal introduced an unrequested response field."); find = handler; replace = handler.replace(response, updatedResponse); } else { find = edit.find; replace = edit.replace; }
      if (!find || original.indexOf(find) < 0 || original.indexOf(find) !== original.lastIndexOf(find)) throw new ApiError(409, "SOURCE_CONFLICT", "The backend symbol boundary is missing or ambiguous."); const proposed = find === replace ? original : original.replace(find, replace); const change = proposed === original ? { text: "", insertions: 0, deletions: 0 } : diff(target.relative, original, proposed); if (Math.max(change.insertions, change.deletions) > 80) throw new ApiError(400, "SOURCE_PROPOSAL_INVALID", "The backend patch exceeds 80 changed lines per file."); files.push({ path: target.relative, symbol: edit.symbol, originalHash: digest(original), proposedHash: digest(proposed), original, proposed, insertions: change.insertions, deletions: change.deletions }); if (change.text) diffs.push(change.text); }
    const noOp = files.every(file => file.originalHash === file.proposedHash); const proposal: BackendSourceProposal = { actionId, workspaceId, status: noOp ? "completed" : "proposed", approvalStatus: noOp ? "approved" : "pending", risk, noOp, requestedMutations, files, diff: diffs.join("\n"), ...(noOp ? { verification: [{ name: "runtime", passed: true }], rollbackStatus: "not_required" as const } : {}) }; this.cache.set(actionId, proposal); await this.repository.save(proposal); this.event(noOp ? "source.already_satisfied" : "source.proposed", proposal); return structuredClone(proposal); }
  async approve(auth: AuthContext, workspaceId: string, id: string) { await this.workspaces.requirePermission(auth, workspaceId, "source:manage"); const item = await this.required(id, workspaceId); item.approvalStatus = "approved"; await this.repository.save(item); return structuredClone(item); }
  async reject(auth: AuthContext, workspaceId: string, id: string) { await this.workspaces.requirePermission(auth, workspaceId, "source:manage"); const item = await this.required(id, workspaceId); if (item.status !== "proposed") throw new ApiError(409, "SOURCE_PROPOSAL_NOT_PENDING", "Only a pending backend proposal can be rejected."); item.status = "rejected"; item.approvalStatus = "rejected"; await this.repository.save(item); this.event("source.rejected", item); return structuredClone(item); }
  async apply(auth: AuthContext, workspaceId: string, id: string, onState: (proposal: BackendSourceProposal) => void | Promise<void> = () => undefined) { await this.workspaces.requirePermission(auth, workspaceId, "source:manage"); const item = await this.required(id, workspaceId); if (item.status === "completed") return structuredClone(item); if (item.approvalStatus !== "approved") throw new ApiError(409, "SOURCE_APPROVAL_REQUIRED", "Explicit backend source approval is required."); for (const file of item.files) { const target = await resolveBackendSourcePath(file.path, this.root); if (digest(await readFile(target.absolute, "utf8")) !== file.originalHash) throw new ApiError(409, "SOURCE_STALE_BASE", "The backend source changed after proposal."); } item.status = "applying"; await this.repository.save(item); await onState(structuredClone(item)); this.event("source.applying", item); try { for (const file of item.files) await writeFile((await resolveBackendSourcePath(file.path, this.root)).absolute, file.proposed, "utf8"); item.status = "verifying"; await this.repository.save(item); await onState(structuredClone(item)); this.event("source.verifying", item); item.verification = await this.validator.run(item.files.map(f => f.path), item); if (item.verification.some(v => !v.passed)) throw new ApiError(500, "SOURCE_VERIFICATION_FAILED", "Backend verification failed."); for (const file of item.files) if (digest(await readFile((await resolveBackendSourcePath(file.path, this.root)).absolute, "utf8")) !== file.proposedHash) throw new ApiError(500, "SOURCE_VERIFICATION_FAILED", "Backend read-back failed."); item.status = "completed"; item.rollbackStatus = "not_required"; await this.repository.save(item); this.event("source.completed", item); return structuredClone(item); } catch (cause) { try { for (const file of item.files) { const path = (await resolveBackendSourcePath(file.path, this.root)).absolute; await writeFile(path, file.original, "utf8"); if (digest(await readFile(path, "utf8")) !== file.originalHash) throw new Error("rollback mismatch", { cause }); } item.rollbackStatus = "completed"; } catch (rollback) { item.status = "failed"; item.rollbackStatus = "failed"; await this.repository.save(item); await onState(structuredClone(item)); throw new ApiError(500, "SOURCE_ROLLBACK_FAILED", "Backend rollback failed.", { cause: new AggregateError([cause, rollback], "Backend apply and rollback failed") }); } item.status = "failed"; await this.repository.save(item); await onState(structuredClone(item)); throw cause; } }
  async get(id: string) { const item = this.cache.get(id) ?? await this.repository.get(id); return item ? structuredClone(item) : undefined; }
  async resolveExplicit(auth: AuthContext, workspaceId: string, id: string) { await this.workspaces.requirePermission(auth, workspaceId, "source:manage"); const item = await this.get(id); if (!item || item.workspaceId !== workspaceId || item.status === "failed" || item.status === "rejected") throw new ApiError(404, "SOURCE_PROPOSAL_NOT_FOUND", "Backend proposal not found."); return item; }
  async resolveForGuardianRepair(auth: AuthContext, workspaceId: string, id: string) { const item = await this.resolveExplicit(auth, workspaceId, id); if (item.status !== "proposed") throw new ApiError(409, "SOURCE_PROPOSAL_NOT_PENDING", "The backend proposal is not pending approval."); for (const file of item.files) { const target = await resolveBackendSourcePath(file.path, this.root); if (digest(await readFile(target.absolute, "utf8")) !== file.originalHash) throw new ApiError(409, "SOURCE_STALE_BASE", "The backend source changed after the proposal was prepared."); } return item; }
  async verifyForGuardianRepair(auth: AuthContext, workspaceId: string, id: string, assertions: GuardianVerificationAssertion[]) { await this.workspaces.requirePermission(auth, workspaceId, "source:manage"); const item = await this.required(id, workspaceId); const evidence = item.verification?.filter((entry) => entry.passed).map((entry) => entry.name) ?? []; if (item.status !== "completed" || !item.verification?.length || item.verification.some((entry) => !entry.passed)) return { passed: false, evidence: [], assertionResults: [] }; const assertionResults = []; for (const assertion of assertions) { const file = item.files.find((entry) => entry.path === assertion.resource); if (!file) continue; const target = await resolveBackendSourcePath(file.path, this.root); const observedState = `sha256:${digest(await readFile(target.absolute, "utf8"))}`; assertionResults.push({ assertionId: assertion.assertionId, resource: assertion.resource, observedState, verdict: observedState === assertion.expectedState ? "PASS" as const : "FAIL" as const, evidenceReference: `canonical-readback:${file.path}`, verificationMethod: "source_readback" as const }); } return { passed: assertionResults.length === assertions.length && assertionResults.every((entry) => entry.verdict === "PASS"), evidence: [...evidence, "canonical-source-read-back"], assertionResults }; }
  async rollback(auth: AuthContext, workspaceId: string, id: string) { await this.workspaces.requirePermission(auth, workspaceId, "source:manage"); const item = await this.required(id, workspaceId); if (item.status !== "completed" || item.rollbackStatus !== "not_required") throw new ApiError(409, "SOURCE_ROLLBACK_UNSUPPORTED", "A bounded rollback is unavailable for this backend proposal."); for (const file of item.files) { const target = await resolveBackendSourcePath(file.path, this.root); if (digest(await readFile(target.absolute, "utf8")) !== file.proposedHash) throw new ApiError(409, "SOURCE_STALE_BASE", "The backend source changed after the repair was applied."); } try { for (const file of item.files) await writeFile((await resolveBackendSourcePath(file.path, this.root)).absolute, file.original, "utf8"); const verification = await this.validator.run(item.files.map((file) => file.path), item); if (verification.some((entry) => !entry.passed)) throw new ApiError(500, "SOURCE_ROLLBACK_VERIFICATION_FAILED", "The bounded backend rollback validation failed."); for (const file of item.files) if (digest(await readFile((await resolveBackendSourcePath(file.path, this.root)).absolute, "utf8")) !== file.originalHash) throw new ApiError(500, "SOURCE_ROLLBACK_VERIFICATION_FAILED", "The bounded backend rollback read-back failed."); item.status = "failed"; item.rollbackStatus = "completed"; item.verification = verification; await this.repository.save(item); return structuredClone(item); } catch (caught) { item.rollbackStatus = "failed"; await this.repository.save(item); throw caught; } }
  async readOperationalState(auth: AuthContext, workspaceId: string, id: string) { await this.workspaces.requirePermission(auth, workspaceId, "source:manage"); const item = await this.get(id); if (!item || item.workspaceId !== workspaceId) throw new ApiError(404, "SOURCE_PROPOSAL_NOT_FOUND", "Backend proposal not found."); return item; }
  async resolvePending(auth: AuthContext, workspaceId: string, ids: readonly string[]) { await this.workspaces.requirePermission(auth, workspaceId, "source:manage"); const items = (await Promise.all([...new Set(ids)].map(id => this.get(id)))).filter((x): x is BackendSourceProposal => Boolean(x && x.workspaceId === workspaceId && x.status === "proposed")); if (!items.length) throw new ApiError(404, "SOURCE_PROPOSAL_NOT_FOUND", "No pending backend proposal was found."); if (items.length !== 1) throw new ApiError(409, "SOURCE_PROPOSAL_AMBIGUOUS", "Multiple backend proposals match."); return items[0]!; }
  private async required(id: string, workspaceId: string) { const item = this.cache.get(id) ?? await this.repository.get(id); if (!item || item.workspaceId !== workspaceId) throw new ApiError(404, "SOURCE_PROPOSAL_NOT_FOUND", "Backend proposal not found."); this.cache.set(id, item); return item; }
  private event(event: string, item: BackendSourceProposal) { log(event === "source.completed" ? "info" : "warn", "backend_source_action", { event, actionId: item.actionId, workspaceId: item.workspaceId, targetFiles: item.files.map(f => f.path), symbols: item.files.map(f => f.symbol), risk: item.risk, approvalStatus: item.approvalStatus, changedLines: item.files.reduce((n, f) => n + f.insertions + f.deletions, 0), verification: item.verification, rollbackStatus: item.rollbackStatus }); }
}
