import type { WorkspaceAutomationTaskTemplate, WorkspaceAutomationTrigger, WorkspaceTaskPriority } from "@averon/shared-types";
import { ApiError } from "../../errors/api-error.ts";
import { validateTrigger } from "./workspace-automation.schedule.ts";
const record = (value: unknown): value is Record<string, unknown> => Boolean(value && typeof value === "object" && !Array.isArray(value));
const text = (value: unknown, field: string, max: number) => { if (typeof value !== "string" || !value.trim() || value.trim().length > max) throw new ApiError(400, "AUTOMATION_INPUT_INVALID", `${field} is invalid.`); return value.trim(); };
const priorities: WorkspaceTaskPriority[] = ["LOW", "NORMAL", "HIGH", "URGENT"];
function agents(value: unknown) { if (!Array.isArray(value) || value.some((item) => typeof item !== "string") || new Set(value).size !== value.length) throw new ApiError(400, "AUTOMATION_INPUT_INVALID", "assignedAgentIds must be unique strings."); return value as string[]; }
function trigger(value: unknown): WorkspaceAutomationTrigger { if (!record(value) || typeof value.type !== "string" || typeof value.timezone !== "string") throw new ApiError(400, "AUTOMATION_TRIGGER_INVALID", "The schedule is invalid."); let result: WorkspaceAutomationTrigger; if (value.type === "ONCE") result = { type: "ONCE", runAt: text(value.runAt, "runAt", 64), timezone: value.timezone }; else if (value.type === "DAILY") result = { type: "DAILY", time: text(value.time, "time", 5), timezone: value.timezone }; else if (value.type === "WEEKLY") result = { type: "WEEKLY", weekday: Number(value.weekday) as 1, time: text(value.time, "time", 5), timezone: value.timezone }; else throw new ApiError(400, "AUTOMATION_TRIGGER_INVALID", "Only ONCE, DAILY, and WEEKLY schedules are supported."); validateTrigger(result); return result; }
function template(value: unknown): WorkspaceAutomationTaskTemplate { if (!record(value)) throw new ApiError(400, "AUTOMATION_OPERATION_INVALID", "A Task template is required."); const priority = (value.priority ?? "NORMAL") as WorkspaceTaskPriority; if (!priorities.includes(priority)) throw new ApiError(400, "TASK_PRIORITY_INVALID", "The Task priority is invalid."); return { title: text(value.title, "task title", 160), description: text(value.description, "task description", 5000), priority, assignedAgentIds: agents(value.assignedAgentIds ?? []) }; }
export function parseAutomationCreate(value: unknown) { if (!record(value) || !record(value.operation) || value.operation.type !== "CREATE_TASK") throw new ApiError(400, "AUTOMATION_OPERATION_INVALID", "Only CREATE_TASK is supported."); return { title: text(value.title, "title", 160), description: text(value.description, "description", 5000), enabled: value.enabled === true, trigger: trigger(value.trigger), operation: { type: "CREATE_TASK" as const, taskTemplate: template(value.operation.taskTemplate) } }; }
export function parseAutomationUpdate(value: unknown) { if (!record(value) || !Number.isInteger(value.expectedVersion) || Number(value.expectedVersion) < 1) throw new ApiError(400, "AUTOMATION_INPUT_INVALID", "A valid expectedVersion is required."); const patch: Record<string, unknown> = {}; if (value.title !== undefined) patch.title = text(value.title, "title", 160); if (value.description !== undefined) patch.description = text(value.description, "description", 5000); if (value.enabled !== undefined) { if (typeof value.enabled !== "boolean") throw new ApiError(400, "AUTOMATION_INPUT_INVALID", "enabled must be boolean."); patch.enabled = value.enabled; } if (value.trigger !== undefined) patch.trigger = trigger(value.trigger); if (value.operation !== undefined) { if (!record(value.operation) || value.operation.type !== "CREATE_TASK") throw new ApiError(400, "AUTOMATION_OPERATION_INVALID", "Only CREATE_TASK is supported."); patch.operation = { type: "CREATE_TASK", taskTemplate: template(value.operation.taskTemplate) }; } if (!Object.keys(patch).length) throw new ApiError(400, "AUTOMATION_INPUT_INVALID", "At least one field must change."); return { expectedVersion: Number(value.expectedVersion), patch }; }
