import type { AuthContext } from "../../services/auth/authentication.ts";
import type { WorkspaceTaskService } from "../workspace-tasks/workspace-task.service.ts";
import { nextOccurrence } from "./workspace-automation.schedule.ts";
import type { WorkspaceAutomationRepository } from "./workspace-automation.types.ts";
export class WorkspaceAutomationRunner {
  private readonly repository: WorkspaceAutomationRepository; private readonly tasks: WorkspaceTaskService; private readonly owner: string; private readonly now: () => Date;
  constructor(repository: WorkspaceAutomationRepository, tasks: WorkspaceTaskService, owner: string, now: () => Date = () => new Date()) { this.repository = repository; this.tasks = tasks; this.owner = owner; this.now = now; }
  async tick() { const now = this.now(); const due = await this.repository.due(now.toISOString()); const results: Array<{ automationId: string; status: "TASK_CREATED" | "FAILED" | "SKIPPED"; taskId?: string }> = []; for (const automation of due) { const scheduledFor = automation.nextRunAt!; const leaseUntil = new Date(now.getTime() + 5 * 60_000).toISOString(); if (!await this.repository.acquireOccurrence(automation, scheduledFor, this.owner, leaseUntil)) { results.push({ automationId: automation.id, status: "SKIPPED" }); continue; } const next = automation.trigger.type === "ONCE" ? undefined : nextOccurrence(automation.trigger, new Date(scheduledFor)); const auth: AuthContext = { user: { userId: automation.createdBy, emailVerified: true, role: "user", isAdmin: false, permissions: [] } }; try { const task = await this.tasks.createFromAutomation(auth, automation.workspaceId, automation.id, scheduledFor, automation.operation.taskTemplate); await this.repository.finishOccurrence(automation, scheduledFor, { status: "TASK_CREATED", taskId: task.id }, next); results.push({ automationId: automation.id, status: "TASK_CREATED", taskId: task.id }); } catch (caught) { const safeErrorCode = typeof caught === "object" && caught && "code" in caught ? String(caught.code) : "AUTOMATION_TASK_CREATION_FAILED"; await this.repository.finishOccurrence(automation, scheduledFor, { status: "FAILED", safeErrorCode }, next); results.push({ automationId: automation.id, status: "FAILED" }); } } return results; }
}
