import type { Firestore } from "firebase-admin/firestore";
import type { WorkspaceAutomation, WorkspaceAutomationHistoryItem } from "@averon/shared-types";
import { ApiError } from "../../errors/api-error.ts";
import { getFirebaseAdminServices } from "../../services/firebase/admin.ts";
import type { AutomationOccurrence, WorkspaceAutomationRepository } from "./workspace-automation.types.ts";
const key = (workspaceId: string, id: string) => `${workspaceId}__${id}`;
const occurrenceKey = (automationId: string, scheduledFor: string) => `${automationId}__${scheduledFor}`;
const fieldsChanged = (current: WorkspaceAutomation, patch: Partial<WorkspaceAutomation>) => Object.keys(patch).filter((field) => JSON.stringify(current[field as keyof WorkspaceAutomation]) !== JSON.stringify(patch[field as keyof WorkspaceAutomation]));
export class FirebaseWorkspaceAutomationRepository implements WorkspaceAutomationRepository {
  private readonly db: Firestore; constructor(db: Firestore = getFirebaseAdminServices().firestore) { this.db = db; }
  private automations() { return this.db.collection("workspaceAutomations"); } private occurrences() { return this.db.collection("workspaceAutomationOccurrences"); }
  private ref(workspaceId: string, id: string) { return this.automations().doc(key(workspaceId, id)); }
  async list(workspaceId: string) { const found = await this.automations().where("workspaceId", "==", workspaceId).limit(100).get(); return found.docs.map((item) => item.data() as WorkspaceAutomation).sort((a, b) => String(b.updatedAt ?? "").localeCompare(String(a.updatedAt ?? ""))); }
  async get(workspaceId: string, id: string) { const found = await this.ref(workspaceId, id).get(); if (!found.exists) return null; const item = found.data() as WorkspaceAutomation; return item.workspaceId === workspaceId ? item : null; }
  async create(input: Omit<WorkspaceAutomation, "version" | "createdAt" | "updatedAt">) { const ref = this.ref(input.workspaceId, input.id); const history = ref.collection("history").doc(); const now = getFirebaseAdminServices().serverTimestamp(); const item = { ...input, version: 1 }; const batch = this.db.batch(); batch.create(ref, { ...item, createdAt: now, updatedAt: now }); batch.create(history, { id: history.id, workspaceId: input.workspaceId, automationId: input.id, eventType: "automation.created", actorId: input.createdBy, version: 1, occurredAt: now }); await batch.commit(); return item; }
  async update(workspaceId: string, id: string, expectedVersion: number, patch: Partial<WorkspaceAutomation>, actorId: string, eventType: WorkspaceAutomationHistoryItem["eventType"] = "automation.updated") { const ref = this.ref(workspaceId, id); return this.db.runTransaction(async (tx) => { const found = await tx.get(ref); if (!found.exists) throw new ApiError(404, "AUTOMATION_NOT_FOUND", "The Automation was not found."); const current = found.data() as WorkspaceAutomation; if (current.workspaceId !== workspaceId) throw new ApiError(404, "AUTOMATION_NOT_FOUND", "The Automation was not found."); if (current.version !== expectedVersion) throw new ApiError(409, "AUTOMATION_VERSION_CONFLICT", "The Automation changed since it was loaded."); if (!fieldsChanged(current, patch).length) return current; const item = { ...current, ...patch, updatedBy: actorId, version: current.version + 1 }; const now = getFirebaseAdminServices().serverTimestamp(); const history = ref.collection("history").doc(); tx.update(ref, { ...patch, updatedBy: actorId, version: item.version, updatedAt: now }); tx.create(history, { id: history.id, workspaceId, automationId: id, eventType, actorId, version: item.version, occurredAt: now }); return item; }); }
  async history(workspaceId: string, id: string) { const found = await this.ref(workspaceId, id).collection("history").orderBy("occurredAt", "desc").limit(100).get(); return found.docs.map((item) => item.data() as WorkspaceAutomationHistoryItem).filter((item) => item.workspaceId === workspaceId && item.automationId === id); }
  async due(now: string) { const found = await this.automations().where("enabled", "==", true).limit(100).get(); return found.docs.map((item) => item.data() as WorkspaceAutomation).filter((item) => item.nextRunAt && item.nextRunAt <= now); }
  async acquireOccurrence(automation: WorkspaceAutomation, scheduledFor: string, owner: string, leaseUntil: string) { const occurrence = this.occurrences().doc(occurrenceKey(automation.id, scheduledFor)); const automationRef = this.ref(automation.workspaceId, automation.id); return this.db.runTransaction(async (tx) => { const found = await tx.get(occurrence); const existing = found.exists ? found.data() as AutomationOccurrence : undefined; if (existing && (existing.status !== "LEASED" || existing.leaseUntil > new Date().toISOString())) return false; const value: AutomationOccurrence = { id: occurrence.id, workspaceId: automation.workspaceId, automationId: automation.id, scheduledFor, status: "LEASED", leaseOwner: owner, leaseUntil }; if (found.exists) tx.update(occurrence, value); else { tx.create(occurrence, value); const history = automationRef.collection("history").doc(); tx.create(history, { id: history.id, workspaceId: automation.workspaceId, automationId: automation.id, eventType: "automation.triggered", actorId: "automation-runner", version: automation.version, scheduledFor, occurredAt: getFirebaseAdminServices().serverTimestamp() }); } return true; }); }
  async finishOccurrence(automation: WorkspaceAutomation, scheduledFor: string, result: { status: "TASK_CREATED"; taskId: string } | { status: "FAILED"; safeErrorCode: string }, nextRunAt?: string) { const occurrence = this.occurrences().doc(occurrenceKey(automation.id, scheduledFor)); const ref = this.ref(automation.workspaceId, automation.id); await this.db.runTransaction(async (tx) => { const found = await tx.get(ref); if (!found.exists) throw new ApiError(404, "AUTOMATION_NOT_FOUND", "The Automation was not found."); const current = found.data() as WorkspaceAutomation; const now = getFirebaseAdminServices().serverTimestamp(); const linkedTaskIds = result.status === "TASK_CREATED" ? [...new Set([...current.linkedTaskIds, result.taskId])] : current.linkedTaskIds; tx.update(occurrence, result.status === "TASK_CREATED" ? { status: result.status, createdTaskId: result.taskId } : { status: result.status, safeErrorCode: result.safeErrorCode }); tx.update(ref, { lastTriggeredAt: new Date().toISOString(), lastResult: result.status, linkedTaskIds, enabled: current.trigger.type === "ONCE" ? false : current.enabled, nextRunAt: nextRunAt ?? null, updatedAt: now }); const history = ref.collection("history").doc(); tx.create(history, { id: history.id, workspaceId: current.workspaceId, automationId: current.id, eventType: result.status === "TASK_CREATED" ? "automation.task_created" : "automation.failed", actorId: "automation-runner", version: current.version, scheduledFor, ...(result.status === "TASK_CREATED" ? { createdTaskId: result.taskId } : { safeErrorCode: result.safeErrorCode }), occurredAt: now }); }); }
}
export class MemoryWorkspaceAutomationRepository implements WorkspaceAutomationRepository {
  automations = new Map<string, WorkspaceAutomation>(); events: WorkspaceAutomationHistoryItem[] = []; occurrences = new Map<string, AutomationOccurrence>();
  async list(workspaceId: string) { return [...this.automations.values()].filter((item) => item.workspaceId === workspaceId); } async get(workspaceId: string, id: string) { return this.automations.get(key(workspaceId, id)) ?? null; }
  async create(input: Omit<WorkspaceAutomation, "version" | "createdAt" | "updatedAt">) { const item = { ...input, version: 1 }; this.automations.set(key(input.workspaceId, input.id), item); this.events.push({ id: `history-${this.events.length + 1}`, workspaceId: input.workspaceId, automationId: input.id, eventType: "automation.created", actorId: input.createdBy, version: 1 }); return item; }
  async update(workspaceId: string, id: string, expectedVersion: number, patch: Partial<WorkspaceAutomation>, actorId: string, eventType: WorkspaceAutomationHistoryItem["eventType"] = "automation.updated") { const current = await this.get(workspaceId, id); if (!current) throw new ApiError(404, "AUTOMATION_NOT_FOUND", "The Automation was not found."); if (current.version !== expectedVersion) throw new ApiError(409, "AUTOMATION_VERSION_CONFLICT", "The Automation changed since it was loaded."); if (!fieldsChanged(current, patch).length) return current; const item = { ...current, ...patch, updatedBy: actorId, version: current.version + 1 }; this.automations.set(key(workspaceId, id), item); this.events.push({ id: `history-${this.events.length + 1}`, workspaceId, automationId: id, eventType, actorId, version: item.version }); return item; }
  async history(workspaceId: string, id: string) { return this.events.filter((item) => item.workspaceId === workspaceId && item.automationId === id).reverse(); }
  async due(now: string) { return [...this.automations.values()].filter((item) => item.enabled && item.nextRunAt && item.nextRunAt <= now); }
  async acquireOccurrence(automation: WorkspaceAutomation, scheduledFor: string, owner: string, leaseUntil: string) { const id = occurrenceKey(automation.id, scheduledFor); const existing = this.occurrences.get(id); if (existing && (existing.status !== "LEASED" || existing.leaseUntil > new Date().toISOString())) return false; this.occurrences.set(id, { id, workspaceId: automation.workspaceId, automationId: automation.id, scheduledFor, status: "LEASED", leaseOwner: owner, leaseUntil }); if (!existing) this.events.push({ id: `history-${this.events.length + 1}`, workspaceId: automation.workspaceId, automationId: automation.id, eventType: "automation.triggered", actorId: "automation-runner", version: automation.version, scheduledFor }); return true; }
  async finishOccurrence(automation: WorkspaceAutomation, scheduledFor: string, result: { status: "TASK_CREATED"; taskId: string } | { status: "FAILED"; safeErrorCode: string }, nextRunAt?: string) { const id = occurrenceKey(automation.id, scheduledFor); const occurrence = this.occurrences.get(id)!; this.occurrences.set(id, { ...occurrence, ...result, ...(result.status === "TASK_CREATED" ? { createdTaskId: result.taskId } : { safeErrorCode: result.safeErrorCode }) }); const current = (await this.get(automation.workspaceId, automation.id))!; const linkedTaskIds = result.status === "TASK_CREATED" ? [...new Set([...current.linkedTaskIds, result.taskId])] : current.linkedTaskIds; this.automations.set(key(current.workspaceId, current.id), { ...current, linkedTaskIds, lastTriggeredAt: new Date().toISOString(), lastResult: result.status, enabled: current.trigger.type === "ONCE" ? false : current.enabled, nextRunAt: nextRunAt ?? null }); this.events.push({ id: `history-${this.events.length + 1}`, workspaceId: current.workspaceId, automationId: current.id, eventType: result.status === "TASK_CREATED" ? "automation.task_created" : "automation.failed", actorId: "automation-runner", version: current.version, scheduledFor, ...(result.status === "TASK_CREATED" ? { createdTaskId: result.taskId } : { safeErrorCode: result.safeErrorCode }) }); }
}
