import type { PageMetadata, PageMetadataId, SeoMetadataActionMetadata, SeoMetadataPatch, StaticPageId } from "@averon/shared-types";
import { staticPageIdForPath } from "@averon/shared-types";
import { ApiError } from "../../errors/api-error.ts";
import { log } from "../../logger.ts";
import type { AuthContext } from "../../services/auth/authentication.ts";
import type { WorkspaceAuthorizationService } from "../workspaces/workspace.service.ts";
import type { PageMetadataRepository } from "./page-metadata.types.ts";

const fields = ["title", "metaDescription", "ogTitle", "ogDescription"] as const;
const dangerous = /<\/?[a-z][^>]*>|javascript\s*:|on(?:error|load|click)\s*=/i;
const limits = { title: 120, metaDescription: 180, ogTitle: 120, ogDescription: 200 } as const;
export function parseSeoMetadataPatch(value: unknown): SeoMetadataPatch { if (!value || typeof value !== "object" || Array.isArray(value)) throw new ApiError(400, "ACTION_VALIDATION_FAILED", "A metadata patch is required."); const input = value as Record<string, unknown>; if (Object.keys(input).some((key) => !fields.includes(key as typeof fields[number])) || !Object.keys(input).length) throw new ApiError(400, "ACTION_VALIDATION_FAILED", "Only supported metadata fields may be changed."); const output: SeoMetadataPatch = {}; for (const field of fields) if (field in input) { const item = input[field]; if (typeof item !== "string" || !item.trim() || item.length > limits[field] || dangerous.test(item)) throw new ApiError(400, "ACTION_VALIDATION_FAILED", `${field} is invalid.`); output[field] = item.trim(); } return output; }

function pageFrom(text: string): StaticPageId | undefined { const route = /(?:^|\s)(\/(?:services|products|technology|blog)?)(?=\s|[,.?!]|$)/i.exec(text)?.[1]?.toLowerCase(); if (route !== undefined) return staticPageIdForPath(route) ?? undefined; const named = /\b(home(?:page)?|services|products|technology|blog)(?:\s+page)?\b/i.exec(text)?.[1]?.toLowerCase(); return named === "home" || named === "homepage" ? "home" : named as StaticPageId | undefined; }
export function seoMetadataIntent(message: string, history: readonly { role: "user" | "assistant"; content: string }[] = []) { const metadata = /\b(?:seo\s+title|meta\s+description|metadata|open\s+graph|og\s+title|og\s+description)\b/i.test(message); const advisory = /\b(?:how\s+(?:could|can|should)|review|recommend|suggest|summari[sz]e|what\s+is|show\s+me)\b/i.test(message); const mutation = /\b(?:update|change|set|rewrite|edit|improve)\b/i.test(message) && (metadata || /\btitle\b/i.test(message)) && (!advisory || /\b(?:save|apply|update|change|set)\b/i.test(message)); const currentTarget = pageFrom(message); if (mutation) return { action: "update" as const, explicit: true, pageId: currentTarget ?? [...history].reverse().map((item) => pageFrom(item.content)).find(Boolean) }; if (metadata || /\bSEO\b/i.test(message)) return { action: "read" as const, explicit: false, pageId: currentTarget }; return { action: "none" as const, explicit: false };
}

function quotedAfter(pattern: RegExp, message: string) { return pattern.exec(message)?.[1]?.trim(); }
export function buildSeoMetadataPatch(message: string, seo: Record<string, unknown>): SeoMetadataPatch { const patch: SeoMetadataPatch = {}; const meta = /meta\s+description/i.test(message); const ogTitle = /(?:open\s+graph|og)\s+title/i.test(message); const ogDescription = /(?:open\s+graph|og)\s+description/i.test(message); const plainTitle = /\b(?:seo\s+)?title\b/i.test(message) && !ogTitle; const quotes = quotedAfter(/[“"]([^”"]+)[”"]/, message); if (meta) patch.metaDescription = quotes ?? (seo.metaDescriptionSuggestions as string[] | undefined)?.[0]; if (ogDescription) patch.ogDescription = quotes ?? (seo.metaDescriptionSuggestions as string[] | undefined)?.[0]; if (ogTitle) patch.ogTitle = quotes ?? (seo.titleSuggestions as string[] | undefined)?.[0]; if (plainTitle) patch.title = quotes ?? (seo.titleSuggestions as string[] | undefined)?.[0]; return parseSeoMetadataPatch(patch); }

export class SeoMetadataActionService {
  private readonly repository: PageMetadataRepository; private readonly workspaces: WorkspaceAuthorizationService;
  constructor(repository: PageMetadataRepository, workspaces: WorkspaceAuthorizationService) { this.repository = repository; this.workspaces = workspaces; }
  async read(auth: AuthContext, workspaceId: string, pageId: PageMetadataId) { await this.workspaces.requirePermission(auth, workspaceId, "content:read"); const item = await this.repository.get(workspaceId, pageId); if (!item) throw new ApiError(404, "PAGE_METADATA_NOT_FOUND", "Page metadata was not found."); return item; }
  async update(auth: AuthContext, actionId: string, workspaceId: string, pageId: PageMetadataId, value: unknown): Promise<{ result: PageMetadata; metadata: SeoMetadataActionMetadata }> { const patch = parseSeoMetadataPatch(value); const changedFields = Object.keys(patch) as Array<keyof SeoMetadataPatch>; const safe = (event: string, status: string, verificationStatus: string, errorCode?: string) => log(event === "action.completed" ? "info" : "warn", "seo_metadata_action", { event, actionId, workspaceId, pageId, actionType: "seo.metadata.update", changedFields, status, verificationStatus, ...(errorCode ? { errorCode } : {}) }); safe("action.requested", "requested", "pending"); try { await this.workspaces.requirePermission(auth, workspaceId, "content:manage"); safe("action.authorized", "authorized", "pending"); const before = await this.repository.get(workspaceId, pageId); if (!before) throw new ApiError(404, "PAGE_METADATA_NOT_FOUND", "Page metadata was not found."); safe("action.started", "executing", "pending"); const written = await this.repository.update(actionId, workspaceId, pageId, patch, auth.user.userId); const readBack = await this.repository.get(workspaceId, pageId); const unchanged = Object.keys(before).filter((key) => !changedFields.includes(key as keyof SeoMetadataPatch) && !["version", "updatedAt", "updatedBy"].includes(key)).every((key) => JSON.stringify(before[key as keyof PageMetadata]) === JSON.stringify(readBack?.[key as keyof PageMetadata])); const verified = Boolean(readBack && readBack.workspaceId === workspaceId && readBack.pageId === pageId && readBack.route === before.route && changedFields.every((field) => readBack[field] === patch[field]) && unchanged); if (!verified || !readBack) throw new ApiError(500, "ACTION_VERIFICATION_FAILED", "The metadata update could not be verified."); safe("action.completed", "completed", "passed"); return { result: readBack, metadata: { actionId, actionType: "seo.metadata.update", status: "completed", verificationStatus: "passed", pageId, route: readBack.route, changedFields, specialists: [], warnings: written.duplicate ? ["Idempotent replay returned the existing metadata."] : [] } }; } catch (caught) { const error = caught instanceof ApiError ? caught : new ApiError(500, "ACTION_EXECUTION_FAILED", "The metadata update failed."); safe("action.failed", "failed", "failed", error.code); throw error; } }
}
