import { createHash } from "node:crypto";
import { readFile, realpath, writeFile } from "node:fs/promises";
import { dirname, extname, isAbsolute, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import type { FrontendSourceActionMetadata, GuardianVerificationAssertion } from "@averon/shared-types";
import { ApiError } from "../../errors/api-error.ts";
import { log } from "../../logger.ts";
import type { AuthContext } from "../../services/auth/authentication.ts";
import type { AiMessage } from "../../ai/providers/ai-provider.ts";
import type { WorkspaceAuthorizationService } from "../workspaces/workspace.service.ts";
import { MemoryFrontendSourceProposalRepository, type FrontendSourceProposalRepository } from "./frontend-source.repository.ts";

export type SourceValidationResult = { name: "typecheck" | "test" | "lint" | "build"; passed: boolean };
export interface SourceValidationRunner { run(files: string[]): Promise<SourceValidationResult[]> }
export interface SourceProposalFile { path: string; originalHash: string; proposedHash: string; original: string; proposed: string; insertions: number; deletions: number }
export interface SourceProposalTarget { resource: string; targetType: "selector" | "source_range"; targetIdentifier: string; requestedState?: string; expectedState: string }
export interface SourceProposal { actionId: string; workspaceId: string; status: "proposed" | "applying" | "verifying" | "completed" | "failed" | "rejected"; approvalStatus: "not_required" | "pending" | "approved" | "rejected"; highRisk: boolean; files: SourceProposalFile[]; targets: SourceProposalTarget[]; diff: string; verification?: SourceValidationResult[]; rollbackStatus?: "not_required" | "completed" | "failed" }
export type SourceEdit = { path: string; find: string; replace: string } | { path: string; cssSelector: string; cssProperty: string; cssValue: string };
const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../../../../..");
const hash = (value: string) => createHash("sha256").update(value).digest("hex");
const allowedExtension = new Set([".ts", ".tsx", ".css"]);
function sourceDiff(path: string, original: string, proposed: string) { const before = original.split("\n"); const after = proposed.split("\n"); let start = 0; while (start < before.length && before[start] === after[start]) start += 1; let beforeEnd = before.length - 1; let afterEnd = after.length - 1; while (beforeEnd >= start && afterEnd >= start && before[beforeEnd] === after[afterEnd]) { beforeEnd -= 1; afterEnd -= 1; } const removed = before.slice(start, beforeEnd + 1); const added = after.slice(start, afterEnd + 1); return { diff: [`--- a/${path}`, `+++ b/${path}`, `@@ -${start + 1},${removed.length} +${start + 1},${added.length} @@`, ...removed.map((line) => `-${line}`), ...added.map((line) => `+${line}`)].join("\n"), insertions: added.length, deletions: removed.length }; }
const escapePattern = (value: string) => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
function materializeEdit(original: string, edit: SourceEdit) { if ("find" in edit) return edit; const selectorPattern = new RegExp(`(^|\\n)([ \\t]*${escapePattern(edit.cssSelector)}[ \\t]*\\{[\\s\\S]*?\\n[ \\t]*\\})`, "g"); const blocks = [...original.matchAll(selectorPattern)].map((match) => match[2]!); if (blocks.length !== 1) throw new ApiError(409, "SOURCE_CONFLICT", "The requested CSS selector is missing or ambiguous."); const block = blocks[0]!; const declarationPattern = new RegExp(`(^|\\n)([ \\t]*)${escapePattern(edit.cssProperty)}[ \\t]*:[ \\t]*([^;\\n]+);`, "g"); const declarations = [...block.matchAll(declarationPattern)]; if (declarations.length !== 1) throw new ApiError(409, "SOURCE_CONFLICT", "The requested CSS property is missing or ambiguous."); const declaration = declarations[0]![0]; const linePrefix = declarations[0]![1] ?? ""; const indentation = declarations[0]![2] ?? ""; const replacement = `${linePrefix}${indentation}${edit.cssProperty}: ${edit.cssValue};`; return { path: edit.path, find: block, replace: block.replace(declaration, replacement) }; }
export async function resolveFrontendSourcePath(path: string, root = repositoryRoot) { const allowedRoot = resolve(root, "src"); if (!path || isAbsolute(path) || path.includes("..") || path.split(/[\\/]/).some((part) => part.startsWith("."))) throw new ApiError(400, "SOURCE_PATH_NOT_ALLOWED", "The source path is not allowed."); const absolute = resolve(root, path); if (!(absolute === allowedRoot || absolute.startsWith(`${allowedRoot}${sep}`)) || !allowedExtension.has(extname(absolute))) throw new ApiError(400, "SOURCE_PATH_NOT_ALLOWED", "Only approved frontend source files are allowed."); let canonical: string; let canonicalRoot: string; try { [canonical, canonicalRoot] = await Promise.all([realpath(absolute), realpath(allowedRoot)]); } catch { throw new ApiError(404, "SOURCE_TARGET_NOT_FOUND", "The frontend source target was not found."); } if (!(canonical === canonicalRoot || canonical.startsWith(`${canonicalRoot}${sep}`))) throw new ApiError(400, "SOURCE_PATH_NOT_ALLOWED", "The source target escapes the frontend root."); return { absolute: canonical, relative: relative(await realpath(root), canonical) }; }
export class FrontendSourceActionService {
  private readonly proposals = new Map<string, SourceProposal>();
  private readonly workspaces: WorkspaceAuthorizationService; private readonly validator: SourceValidationRunner; private readonly root: string; private readonly repository: FrontendSourceProposalRepository;
  constructor(workspaces: WorkspaceAuthorizationService, validator: SourceValidationRunner, root = repositoryRoot, repository: FrontendSourceProposalRepository = new MemoryFrontendSourceProposalRepository()) { this.workspaces = workspaces; this.validator = validator; this.root = root; this.repository = repository; }
  async read(auth: AuthContext, workspaceId: string, path: string) { await this.workspaces.requirePermission(auth, workspaceId, "source:read"); const target = await resolveFrontendSourcePath(path, this.root); return { path: target.relative, content: await readFile(target.absolute, "utf8") }; }
  async propose(auth: AuthContext, actionId: string, workspaceId: string, edits: SourceEdit[], highRisk = false) {
    await this.workspaces.requirePermission(auth, workspaceId, "source:propose"); const prior = this.proposals.get(actionId) ?? await this.repository.get(actionId); if (prior) { if (prior.workspaceId !== workspaceId) throw new ApiError(409, "SOURCE_CONFLICT", "The source action ID belongs to another workspace."); this.proposals.set(actionId, prior); return structuredClone(prior); } if (!edits.length || edits.length > 4) throw new ApiError(400, "SOURCE_PROPOSAL_INVALID", "A bounded frontend proposal is required.");
    const files: SourceProposalFile[] = []; const targets: SourceProposalTarget[] = []; const diffs: string[] = [];
    for (const requestedEdit of edits) { const target = await resolveFrontendSourcePath(requestedEdit.path, this.root); const original = await readFile(target.absolute, "utf8"); const edit = materializeEdit(original, requestedEdit); if (!edit.find || edit.find === edit.replace || !original.includes(edit.find) || original.indexOf(edit.find) !== original.lastIndexOf(edit.find)) throw new ApiError(409, "SOURCE_CONFLICT", "The requested source block is missing or ambiguous."); const proposed = original.replace(edit.find, edit.replace); const change = sourceDiff(target.relative, original, proposed); if (change.insertions + change.deletions > 120) throw new ApiError(400, "SOURCE_PROPOSAL_INVALID", "The proposed patch is too large."); const proposedHash = hash(proposed); files.push({ path: target.relative, originalHash: hash(original), proposedHash, original, proposed, insertions: change.insertions, deletions: change.deletions }); targets.push({ resource: target.relative, targetType: "cssSelector" in requestedEdit ? "selector" : "source_range", targetIdentifier: "cssSelector" in requestedEdit ? requestedEdit.cssSelector : target.relative, ...("cssSelector" in requestedEdit ? { requestedState: `${requestedEdit.cssProperty}=${requestedEdit.cssValue}` } : {}), expectedState: `sha256:${proposedHash}` }); diffs.push(change.diff); }
    const proposal: SourceProposal = { actionId, workspaceId, status: "proposed", approvalStatus: highRisk ? "pending" : "not_required", highRisk, files, targets, diff: diffs.join("\n") }; this.proposals.set(actionId, proposal); await this.repository.save(proposal); this.event("source.proposed", proposal); return structuredClone(proposal);
  }
  async approve(auth: AuthContext, workspaceId: string, actionId: string) { await this.workspaces.requirePermission(auth, workspaceId, "source:manage"); const proposal = await this.required(actionId, workspaceId); proposal.approvalStatus = "approved"; await this.repository.save(proposal); this.event("source.approved", proposal); return structuredClone(proposal); }
  async reject(auth: AuthContext, workspaceId: string, actionId: string) { await this.workspaces.requirePermission(auth, workspaceId, "source:manage"); const proposal = await this.required(actionId, workspaceId); if (proposal.status !== "proposed") throw new ApiError(409, "SOURCE_PROPOSAL_NOT_PENDING", "Only a pending source proposal can be rejected."); proposal.status = "rejected"; proposal.approvalStatus = "rejected"; await this.repository.save(proposal); this.event("source.rejected", proposal); return structuredClone(proposal); }
  async apply(auth: AuthContext, workspaceId: string, actionId: string, onState: (proposal: SourceProposal) => void | Promise<void> = () => undefined) {
    await this.workspaces.requirePermission(auth, workspaceId, "source:manage"); const proposal = await this.required(actionId, workspaceId); if (proposal.status === "completed") return structuredClone(proposal); if (proposal.highRisk && proposal.approvalStatus !== "approved") throw new ApiError(409, "SOURCE_APPROVAL_REQUIRED", "Approval is required before applying this source proposal.");
    for (const file of proposal.files) { const target = await resolveFrontendSourcePath(file.path, this.root); if (hash(await readFile(target.absolute, "utf8")) !== file.originalHash) throw new ApiError(409, "SOURCE_STALE_BASE", "The source file changed after proposal."); }
    proposal.status = "applying"; await this.repository.save(proposal); await onState(structuredClone(proposal)); this.event("source.applying", proposal);
    try { for (const file of proposal.files) { const target = await resolveFrontendSourcePath(file.path, this.root); await writeFile(target.absolute, file.proposed, "utf8"); } proposal.status = "verifying"; await this.repository.save(proposal); await onState(structuredClone(proposal)); this.event("source.verifying", proposal); const verification = await this.validator.run(proposal.files.map((file) => file.path)); proposal.verification = verification; if (verification.some((item) => !item.passed)) throw new ApiError(500, "SOURCE_VERIFICATION_FAILED", "Frontend source verification failed."); proposal.status = "completed"; proposal.rollbackStatus = "not_required"; await this.repository.save(proposal); this.event("source.completed", proposal); return structuredClone(proposal); }
    catch (caught) { try { for (const file of proposal.files) { const target = await resolveFrontendSourcePath(file.path, this.root); await writeFile(target.absolute, file.original, "utf8"); if (hash(await readFile(target.absolute, "utf8")) !== file.originalHash) throw new Error("rollback mismatch", { cause: caught }); } proposal.rollbackStatus = "completed"; } catch (rollbackError) { proposal.rollbackStatus = "failed"; proposal.status = "failed"; await this.repository.save(proposal); await onState(structuredClone(proposal)); this.event("source.rollback_failed", proposal, "SOURCE_ROLLBACK_FAILED"); throw new ApiError(500, "SOURCE_ROLLBACK_FAILED", "The source rollback failed.", { cause: rollbackError }); } proposal.status = "failed"; await this.repository.save(proposal); await onState(structuredClone(proposal)); this.event("source.rolled_back", proposal, caught instanceof ApiError ? caught.code : "SOURCE_APPLY_FAILED"); throw caught instanceof ApiError ? caught : new ApiError(500, "SOURCE_APPLY_FAILED", "The source patch could not be applied.", { cause: caught }); }
  }
  async get(actionId: string) { const found = this.proposals.get(actionId) ?? await this.repository.get(actionId); return found ? structuredClone(found) : undefined; }
  async resolveExplicit(auth: AuthContext, workspaceId: string, actionId: string) { await this.workspaces.requirePermission(auth, workspaceId, "source:manage"); const proposal = await this.get(actionId); if (!proposal || proposal.workspaceId !== workspaceId || proposal.status === "failed" || proposal.status === "rejected") throw new ApiError(404, "SOURCE_PROPOSAL_NOT_FOUND", "The explicit source proposal was not found in this workspace."); return proposal; }
  async resolveForGuardianRepair(auth: AuthContext, workspaceId: string, actionId: string) { const proposal = await this.resolveExplicit(auth, workspaceId, actionId); if (proposal.status !== "proposed") throw new ApiError(409, "SOURCE_PROPOSAL_NOT_PENDING", "The source proposal is not pending approval."); for (const file of proposal.files) { const target = await resolveFrontendSourcePath(file.path, this.root); if (hash(await readFile(target.absolute, "utf8")) !== file.originalHash) throw new ApiError(409, "SOURCE_STALE_BASE", "The source changed after the proposal was prepared."); } return proposal; }
  async verifyForGuardianRepair(auth: AuthContext, workspaceId: string, actionId: string, assertions: GuardianVerificationAssertion[]) { await this.workspaces.requirePermission(auth, workspaceId, "source:manage"); const proposal = await this.required(actionId, workspaceId); const evidence = proposal.verification?.filter((item) => item.passed).map((item) => item.name) ?? []; if (proposal.status !== "completed" || !proposal.verification?.length || proposal.verification.some((item) => !item.passed)) return { passed: false, evidence: [], assertionResults: [] }; const assertionResults = []; for (const assertion of assertions) { const file = proposal.files.find((item) => item.path === assertion.resource); if (!file) continue; const target = await resolveFrontendSourcePath(file.path, this.root); const observedState = `sha256:${hash(await readFile(target.absolute, "utf8"))}`; assertionResults.push({ assertionId: assertion.assertionId, resource: assertion.resource, observedState, verdict: observedState === assertion.expectedState ? "PASS" as const : "FAIL" as const, evidenceReference: `canonical-readback:${file.path}`, verificationMethod: "source_readback" as const }); } return { passed: assertionResults.length === assertions.length && assertionResults.every((item) => item.verdict === "PASS"), evidence: [...evidence, "canonical-source-read-back"], assertionResults }; }
  async rollback(auth: AuthContext, workspaceId: string, actionId: string) { await this.workspaces.requirePermission(auth, workspaceId, "source:manage"); const proposal = await this.required(actionId, workspaceId); if (proposal.status !== "completed" || proposal.rollbackStatus !== "not_required") throw new ApiError(409, "SOURCE_ROLLBACK_UNSUPPORTED", "A bounded rollback is unavailable for this source proposal."); for (const file of proposal.files) { const target = await resolveFrontendSourcePath(file.path, this.root); if (hash(await readFile(target.absolute, "utf8")) !== file.proposedHash) throw new ApiError(409, "SOURCE_STALE_BASE", "The source changed after the repair was applied."); } try { for (const file of proposal.files) await writeFile((await resolveFrontendSourcePath(file.path, this.root)).absolute, file.original, "utf8"); const verification = await this.validator.run(proposal.files.map((file) => file.path)); if (verification.some((item) => !item.passed)) throw new ApiError(500, "SOURCE_ROLLBACK_VERIFICATION_FAILED", "The bounded rollback validation failed."); for (const file of proposal.files) if (hash(await readFile((await resolveFrontendSourcePath(file.path, this.root)).absolute, "utf8")) !== file.originalHash) throw new ApiError(500, "SOURCE_ROLLBACK_VERIFICATION_FAILED", "The bounded rollback read-back failed."); proposal.status = "failed"; proposal.rollbackStatus = "completed"; proposal.verification = verification; await this.repository.save(proposal); return structuredClone(proposal); } catch (caught) { proposal.rollbackStatus = "failed"; await this.repository.save(proposal); throw caught; } }
  async readOperationalState(auth: AuthContext, workspaceId: string, actionId: string) { await this.workspaces.requirePermission(auth, workspaceId, "source:manage"); const proposal = await this.get(actionId); if (!proposal || proposal.workspaceId !== workspaceId) throw new ApiError(404, "SOURCE_PROPOSAL_NOT_FOUND", "The source proposal was not found in this workspace."); return proposal; }
  async resolvePending(auth: AuthContext, workspaceId: string, actionIds: readonly string[]) { await this.workspaces.requirePermission(auth, workspaceId, "source:manage"); const uniqueIds = [...new Set(actionIds)]; const found = (await Promise.all(uniqueIds.map((actionId) => this.get(actionId)))).filter((proposal): proposal is SourceProposal => Boolean(proposal && proposal.workspaceId === workspaceId && proposal.status === "proposed")); if (!found.length) throw new ApiError(404, "SOURCE_PROPOSAL_NOT_FOUND", "No pending source proposal was found in this conversation."); if (found.length !== 1) throw new ApiError(409, "SOURCE_PROPOSAL_AMBIGUOUS", "More than one pending source proposal matches this conversation."); return found[0]!; }
  private async required(actionId: string, workspaceId: string) { const found = this.proposals.get(actionId) ?? await this.repository.get(actionId); if (!found || found.workspaceId !== workspaceId) throw new ApiError(404, "SOURCE_TARGET_NOT_FOUND", "The source proposal was not found."); this.proposals.set(actionId, found); return found; }
  private event(event: string, proposal: SourceProposal, errorCode?: string) { log(event === "source.completed" ? "info" : "warn", "frontend_source_action", { event, actionId: proposal.actionId, workspaceId: proposal.workspaceId, actionType: "frontend.source.apply", targetFiles: proposal.files.map((file) => file.path), changedLines: proposal.files.reduce((sum, file) => sum + file.insertions + file.deletions, 0), proposalStatus: proposal.status, approvalStatus: proposal.approvalStatus, verification: proposal.verification, rollbackStatus: proposal.rollbackStatus, ...(errorCode ? { errorCode } : {}) }); }
}
export function sourceActionMetadata(proposal: SourceProposal): FrontendSourceActionMetadata { return { actionId: proposal.actionId, actionType: proposal.status === "proposed" || proposal.status === "rejected" ? "frontend.source.propose" : "frontend.source.apply", status: proposal.status === "proposed" ? proposal.highRisk ? "approval_required" : "proposed" : proposal.status, approvalStatus: proposal.approvalStatus, verificationStatus: proposal.status === "completed" ? "passed" : proposal.status === "failed" ? "failed" : "pending", ...(proposal.rollbackStatus ? { rollbackStatus: proposal.rollbackStatus } : {}), deploymentStatus: "not_performed", targetFiles: proposal.files.map((file) => file.path), changedLines: proposal.files.reduce((sum, file) => sum + file.insertions + file.deletions, 0), insertions: proposal.files.reduce((sum, file) => sum + file.insertions, 0), deletions: proposal.files.reduce((sum, file) => sum + file.deletions, 0), summary: proposal.files.length ? `Bounded source change for ${proposal.files.map((file) => file.path).join(", ")}` : "No source change required", ...(proposal.diff ? { diff: proposal.diff } : {}), warnings: [] }; }
export function frontendSourceIntent(message: string, history: readonly AiMessage[] = []) {
  const explicitReject = /\b(?:reject|decline|cancel)\b/i.test(message) && /\b(?:proposal|proposed|change|it|that)\b/i.test(message);
  if (explicitReject) { const durableIdPattern = /\b[A-Za-z0-9][A-Za-z0-9._-]{0,127}:frontend\.source\.propose\b/g; const explicitProposalIds = [...new Set(message.match(durableIdPattern) ?? [])]; const historyProposalIds = explicitProposalIds.length ? [] : history.filter((item) => item.role === "assistant").flatMap((item) => [...item.content.matchAll(/\bProposal(?: ID)?\s*:\s*([A-Za-z0-9:._-]{8,180})/gi)].map((match) => match[1]!)); return { action: "reject" as const, explicit: true, proposalId: explicitProposalIds[0], historyProposalIds, proposalResolutionError: explicitProposalIds.length > 1 ? "SOURCE_PROPOSAL_AMBIGUOUS" : undefined }; }
  const explicitApply = /\bapply\b/i.test(message) && /\b(?:proposal|proposed|change|it|that)\b/i.test(message);
  if (explicitApply) {
    const durableIdPattern = /\b[A-Za-z0-9][A-Za-z0-9._-]{0,127}:frontend\.source\.propose\b/g;
    const explicitProposalIds = [...new Set(message.match(durableIdPattern) ?? [])];
    const explicitProposalReference = /\bapply\s+(?:(?:frontend\s+)?source\s+)?proposal\s+(\S+)/i.test(message);
    const proposalResolutionError = explicitProposalIds.length > 1
      ? "SOURCE_PROPOSAL_AMBIGUOUS"
      : explicitProposalReference && explicitProposalIds.length === 0
        ? "SOURCE_PROPOSAL_INVALID"
        : undefined;
    const historyProposalIds = explicitProposalIds.length === 0 && !proposalResolutionError
      ? history.filter((item) => item.role === "assistant").flatMap((item) => [...item.content.matchAll(/\bProposal(?: ID)?\s*:\s*([A-Za-z0-9:._-]{8,180})/gi)].map((match) => match[1]!))
      : [];
    return { action: "apply" as const, explicit: true, proposalId: explicitProposalIds[0], historyProposalIds, proposalResolutionError };
  }
  const explicitlyReadOnly = /\b(?:do\s+not|don't|without)\s+(?:modify|edit|change|update|write|alter|replace)\s+(?:any\s+)?(?:files?|source|code|content|repository)\b/i.test(message) || /\b(?:recommendations?|analysis|advice)\s+only\b/i.test(message);
  const mutation = /\b(?:make|fix|change|increase|decrease|adjust|update|replace|refactor)\b/i.test(message); const sourceScope = /\b(?:frontend|component|tsx|css|style|layout|spacing|gap|responsive|mobile|desktop|navigation|button)\b/i.test(message); return !explicitlyReadOnly && mutation && sourceScope ? { action: "propose" as const, explicit: true } : { action: "none" as const, explicit: false };
}
export function boundedFrontendEdits(message: string): SourceEdit[] {
  if (/\bhero\b/i.test(message) && /\b(?:buttons?|actions?)\b/i.test(message) && /\b(?:gap|spacing)\b/i.test(message)) {
    const pixelValues = [...message.matchAll(/\b(\d{1,3})\s*px\b/gi)].map((match) => Number(match[1]));
    const requestedGap = pixelValues.at(-1) ?? 20;
    if (!Number.isInteger(requestedGap) || requestedGap < 0 || requestedGap > 64) throw new ApiError(400, "SOURCE_PROPOSAL_INVALID", "The requested spacing value is outside the bounded allowlist.");
    return [{ path: "src/styles/globals.css", cssSelector: ".hero-actions", cssProperty: "gap", cssValue: `${requestedGap}px` }];
  }
  throw new ApiError(400, "SOURCE_TARGET_NOT_FOUND", "The requested frontend source target is not in the initial allowlist.");
}
