import assert from "node:assert/strict";
import { mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { runInNewContext } from "node:vm";
import test from "node:test";
import type { AiProvider } from "../src/ai/providers/ai-provider.ts";
import { BackendSourceActionService, backendSourceIntent, boundedBackendEdits, resolveBackendSourcePath, type BackendValidationResult } from "../src/domains/backend-source/backend-source.actions.ts";
import { WorkspaceAuthorizationService } from "../src/domains/workspaces/workspace.service.ts";
import { ApiError } from "../src/errors/api-error.ts";
import { MemoryBusinessOsRepository, MemoryConversationRepository, MemoryWorkspaceRepository, request } from "./http-harness.ts";
import { AiDiagnosticsStore } from "../src/ai/diagnostics/diagnostics.store.ts";
import type { EmmyActionMetadata } from "@averon/shared-types";

const auth = { user: { userId: "user-1", emailVerified: true, role: "owner" as const, isAdmin: true, permissions: [] } };
const workspaces = () => new MemoryWorkspaceRepository({ businesses: [{ id: "averon", name: "Averon", slug: "averon", status: "active" }], workspaces: [{ id: "averon", businessId: "averon", name: "Averon", slug: "averon", status: "active" }], memberships: [{ id: "m1", userId: "user-1", workspaceId: "averon", businessId: "averon", role: "owner", status: "active" }] });
const business = () => { const value = new MemoryBusinessOsRepository(); value.roots.set("averon", { workspaceId: "averon", businessId: "averon", status: "active", schemaVersion: 1 }); return value; };
const originalLine = 'sendJson(res, 200, success({ status: "ok" as const, service: "averon-api" }, requestId)); return;';
const fixtureSource = (line = originalLine) => `export function handler(req: Request, url: URL) {\n  if (req.method === "GET" && url.pathname === "/health") {\n    ${line}\n  }\n}\n`;
async function fixture(line = originalLine) { const root = await mkdtemp(join(tmpdir(), "backend-v5-")); const dir = join(root, "apps/averon-api/src"); await mkdir(dir, { recursive: true }); await writeFile(join(dir, "app.ts"), fixtureSource(line), "utf8"); return root; }
async function productionShapedFixture(line = originalLine) { const root = await mkdtemp(join(tmpdir(), "backend-v5-production-")); const dir = join(root, "apps/averon-api/src"); await mkdir(dir, { recursive: true }); await writeFile(join(dir, "app.ts"), `export function handler(req: Request, url: URL) {\n  if (req.method === "GET" && url.pathname === "/ready") {\n    sendJson(res, 200, success({ ready: true }, requestId)); return;\n  }\n  if (req.method === "GET" && url.pathname === "/health") {\n    ${line}\n  }\n  if (req.method === "GET" && url.pathname === "/api/v1/version") {\n    sendJson(res, 200, success({ service: "averon-api", version: "test" }, requestId)); return;\n  }\n}\n`, "utf8"); return root; }
const passed: BackendValidationResult[] = ["typecheck", "lint", "test", "build", "runtime"].map(name => ({ name: name as BackendValidationResult["name"], passed: true }));
const service = (root: string, results = passed) => new BackendSourceActionService(new WorkspaceAuthorizationService(workspaces()), { async run() { return results; } }, root);
class BackendProvider implements AiProvider { calls = 0; async generate() { this.calls++; return { text: JSON.stringify({ schemaVersion: "backend.v1", agentId: "backend", taskId: "task-1-backend", status: "completed", summary: "Reviewed the bounded health response change.", output: { findings: ["The health response is deterministic."], recommendations: ["Add the allowlisted static runtime field."], risks: [], assumptions: [], missingInformation: [] }, warnings: [], missingInformation: [] }) }; } }

test("backend read and advisory intent perform zero writes", async () => { const root = await fixture(), actions = service(root), path = "apps/averon-api/src/app.ts"; const before = await readFile(join(root, path), "utf8"); assert.equal((await actions.read(auth, "averon", path)).content, before); for (const message of ["Explain how the health endpoint works.", "Review the quote API.", "Why does this route return 500?"]) assert.equal(backendSourceIntent(message).action, "none"); assert.equal(await readFile(join(root, path), "utf8"), before); });
test("backend path and sensitive-surface boundaries fail closed", async () => { const root = await fixture(); for (const path of ["../app.ts", "/tmp/app.ts", ".env", "src/pages/Home.tsx", "apps/averon-api/src/auth/session.ts", "apps/averon-api/src/migrations/change.ts", "firestore.rules"]) await assert.rejects(resolveBackendSourcePath(path, root), (e: unknown) => e instanceof ApiError && e.code === "SOURCE_PATH_NOT_ALLOWED"); const actions = service(root); await assert.rejects(actions.propose(auth, "risk", "averon", [{ path: "apps/averon-api/src/app.ts", symbol: "authentication", find: originalLine, replace: `${originalLine} // auth` }]), (e: unknown) => e instanceof ApiError && e.code === "BACKEND_RISK_NOT_ALLOWED"); });
test("already-satisfied health field is a durable no-op and never invents a substitute", async () => { const root = await fixture(), path = join(root, "apps/averon-api/src/app.ts"), before = await readFile(path, "utf8"), actions = service(root); const proposal = await actions.propose(auth, "satisfied:backend.source.propose", "averon", boundedBackendEdits('Add static field service: "averon-api" to the GET /health response.')); assert.equal(proposal.noOp, true); assert.equal(proposal.status, "completed"); assert.equal(proposal.diff, ""); assert.equal(proposal.files[0]?.originalHash, proposal.files[0]?.proposedHash); assert.doesNotMatch(proposal.files[0]!.proposed, /runtime:/); assert.equal(await readFile(path, "utf8"), before); });
test("missing service and a different allowlisted field produce only the requested mutation", async () => { const withoutService = 'sendJson(res, 200, success({ status: "ok" as const, trace: "keep" }, requestId)); return;'; const root = await fixture(withoutService), path = join(root, "apps/averon-api/src/app.ts"), actions = service(root); const serviceProposal = await actions.propose(auth, "service:backend.source.propose", "averon", boundedBackendEdits('Add static field service: "averon-api" to the GET /health response.')); assert.match(serviceProposal.diff, /service: "averon-api"/); assert.doesNotMatch(serviceProposal.diff, /runtime:/); assert.match(serviceProposal.files[0]!.proposed, /trace: "keep"/); assert.equal(await readFile(path, "utf8"), fixtureSource(withoutService)); const runtimeProposal = await actions.propose(auth, "runtime:backend.source.propose", "averon", boundedBackendEdits('Add static field runtime: "local" to the GET /health response.')); assert.match(runtimeProposal.diff, /runtime: "local"/); assert.doesNotMatch(runtimeProposal.diff, /^\+.*service:/m); assert.match(runtimeProposal.files[0]!.proposed, /trace: "keep"/); });
test("production-shaped health target ignores unrelated responses and preserves a satisfied request as a no-op", async () => { const root = await productionShapedFixture(), path = join(root, "apps/averon-api/src/app.ts"), before = await readFile(path, "utf8"), actions = service(root); const proposal = await actions.propose(auth, "production-noop:backend.source.propose", "averon", boundedBackendEdits('Add a static field service: "averon-api" to the GET /health JSON response. Do not change any existing health fields or behavior. Prepare the backend source change for review only.')); assert.equal(proposal.noOp, true); assert.equal(proposal.status, "completed"); assert.equal(proposal.approvalStatus, "approved"); assert.equal(proposal.diff, ""); assert.equal(proposal.files[0]?.insertions, 0); assert.equal(proposal.files[0]?.deletions, 0); assert.equal(await readFile(path, "utf8"), before); });
test("production-shaped health target changes only its bounded response", async () => { const root = await productionShapedFixture(), path = join(root, "apps/averon-api/src/app.ts"), before = await readFile(path, "utf8"), actions = service(root); const proposal = await actions.propose(auth, "production-runtime:backend.source.propose", "averon", boundedBackendEdits('Add a static field runtime: "local" to the GET /health JSON response. Do not change any existing health fields or behavior. Prepare the backend source change for review only.')); assert.equal(proposal.noOp, false); assert.match(proposal.diff, /runtime: "local"/); assert.doesNotMatch(proposal.diff, /^[-+].*(?:ready: true|version: "test")/m); const proposed = proposal.files[0]!.proposed; assert.equal(proposed.match(/runtime: "local"/g)?.length, 1); assert.match(proposed, /pathname === "\/health"[\s\S]*status: "ok" as const, service: "averon-api", runtime: "local"/); assert.equal(await readFile(path, "utf8"), before); });
test("Private Emmy no-op ignores unrelated specialist enhancement", async () => { const root = await fixture(), path = join(root, "apps/averon-api/src/app.ts"), before = await readFile(path, "utf8"), provider = new BackendProvider(), actions = service(root); const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", requestId: "live-shape", body: { message: 'Add a static field service: "averon-api" to the GET /health JSON response. Do not change existing fields. Prepare for review only.' }, workspaceRepository: workspaces(), businessOsRepository: business(), aiProvider: provider, backendSourceActions: actions }); assert.equal(result.payload.data.finalStatus, "completed"); assert.match(String(result.payload.data.reply), /already present/i); assert.equal((result.payload.data.action as { changedLines: number }).changedLines, 0); assert.equal(await readFile(path, "utf8"), before); assert.doesNotMatch(before, /runtime:/); });
test("proposal is bounded, exact, approval-gated, and leaves canonical source untouched", async () => { const root = await fixture(), actions = service(root), path = "apps/averon-api/src/app.ts"; const before = await readFile(join(root, path), "utf8"); const proposal = await actions.propose(auth, "safe:backend.source.propose", "averon", boundedBackendEdits('Add static field runtime: "local" to the health response.')); assert.equal(proposal.files[0]?.symbol, "GET /health"); assert.equal(proposal.approvalStatus, "pending"); assert.match(proposal.diff, /runtime: "local"/); assert.equal(await readFile(join(root, path), "utf8"), before); await assert.rejects(actions.apply(auth, "averon", proposal.actionId), (e: unknown) => e instanceof ApiError && e.code === "SOURCE_APPROVAL_REQUIRED"); });
test("rejection is durable and can never apply", async () => { const root = await fixture(), actions = service(root), path = join(root, "apps/averon-api/src/app.ts"), before = await readFile(path, "utf8"); const proposal = await actions.propose(auth, "reject:backend.source.propose", "averon", boundedBackendEdits('Add runtime: "local" to the health response.')); const rejected = await actions.reject(auth, "averon", proposal.actionId); assert.equal(rejected.status, "rejected"); assert.equal(rejected.approvalStatus, "rejected"); await assert.rejects(actions.resolveExplicit(auth, "averon", proposal.actionId), (error: unknown) => error instanceof ApiError && error.code === "SOURCE_PROPOSAL_NOT_FOUND"); assert.equal(await readFile(path, "utf8"), before); });
test("ambiguous and stale exact boundaries fail closed", async () => { const root = await fixture(), path = join(root, "apps/averon-api/src/app.ts"); await writeFile(path, `${originalLine}\n${originalLine}\n`, "utf8"); await assert.rejects(service(root).propose(auth, "ambiguous", "averon", boundedBackendEdits('Add runtime: "local" to the health response.')), (e: unknown) => e instanceof ApiError && e.code === "SOURCE_CONFLICT"); const root2 = await fixture(), actions = service(root2); const proposal = await actions.propose(auth, "stale", "averon", boundedBackendEdits('Add runtime: "local" to the health response.')); await actions.approve(auth, "averon", proposal.actionId); await writeFile(join(root2, "apps/averon-api/src/app.ts"), "changed", "utf8"); await assert.rejects(actions.apply(auth, "averon", proposal.actionId), (e: unknown) => e instanceof ApiError && e.code === "SOURCE_STALE_BASE"); });
test("duplicate health routes and multiple responses inside health fail closed", async () => { const duplicateRoot = await fixture(); const duplicatePath = join(duplicateRoot, "apps/averon-api/src/app.ts"); await writeFile(duplicatePath, `${fixtureSource()}\n${fixtureSource()}`, "utf8"); await assert.rejects(service(duplicateRoot).propose(auth, "duplicate-route", "averon", boundedBackendEdits('Add runtime: "local" to the health response.')), (e: unknown) => e instanceof ApiError && e.code === "SOURCE_CONFLICT"); const responsesRoot = await fixture(`${originalLine}\n    sendJson(res, 200, success({ duplicate: true }, requestId)); return;`); await assert.rejects(service(responsesRoot).propose(auth, "multiple-responses", "averon", boundedBackendEdits('Add runtime: "local" to the health response.')), (e: unknown) => e instanceof ApiError && e.code === "SOURCE_CONFLICT"); });
test("failed fixed verification restores exact original bytes", async () => { const root = await fixture(), path = join(root, "apps/averon-api/src/app.ts"), before = await readFile(path, "utf8"), actions = service(root, [{ name: "typecheck", passed: false }]); const proposal = await actions.propose(auth, "rollback", "averon", boundedBackendEdits('Add runtime: "local" to the health response.')); await actions.approve(auth, "averon", proposal.actionId); await assert.rejects(actions.apply(auth, "averon", proposal.actionId), (e: unknown) => e instanceof ApiError && e.code === "SOURCE_VERIFICATION_FAILED"); assert.equal(await readFile(path, "utf8"), before); assert.equal((await actions.get(proposal.actionId))?.rollbackStatus, "completed"); });
test("Private Emmy production path proposes then explicitly applies and runtime-verifies exactly once", async () => { const root = await fixture(); let validations = 0; const path = join(root, "apps/averon-api/src/app.ts"); const actions = new BackendSourceActionService(new WorkspaceAuthorizationService(workspaces()), { async run(_files, proposal) { validations++; assert.match(proposal.files[0]!.proposed, /runtime: "local"/); const source = await readFile(path, "utf8"); const statement = source.split("\n").find(line => line.includes("sendJson(res, 200")); assert.ok(statement); let runtime: unknown; runInNewContext(statement.replaceAll(" as const", "").replace(/\s+return;$/, ""), { res: {}, requestId: "runtime", success: (data: unknown) => data, sendJson: (_res: unknown, status: number, body: unknown) => { assert.equal(status, 200); runtime = body; } }); assert.equal(JSON.stringify(runtime), JSON.stringify({ status: "ok", service: "averon-api", runtime: "local" })); return passed; } }, root); const provider = new BackendProvider(); const base = { method: "POST", authorization: "Bearer valid", workspaceRepository: workspaces(), businessOsRepository: business(), aiProvider: provider, backendSourceActions: actions }; const before = await readFile(path, "utf8"); const proposed = await request("/api/v1/workspaces/averon/emmy/messages", { ...base, requestId: "backend-safe", body: { message: 'Add static field runtime: "local" to the health endpoint response and prepare it for review.' } }); assert.equal(proposed.payload.data.finalStatus, "completed", JSON.stringify(proposed.payload.data)); assert.equal(provider.calls, 1); assert.equal(await readFile(path, "utf8"), before); const id = (proposed.payload.data.action as { actionId: string }).actionId; assert.equal(id, "backend-safe:backend.source.propose"); const applied = await request("/api/v1/workspaces/averon/emmy/messages", { ...base, requestId: "apply", body: { message: `Apply backend source proposal ${id}.`, history: [{ role: "assistant", content: `Proposal ID: ${id}` }] } }); assert.equal(applied.payload.data.finalStatus, "completed", JSON.stringify(applied.payload.data)); assert.equal(provider.calls, 1); assert.equal(validations, 1); assert.match(await readFile(path, "utf8"), /runtime: "local"/); assert.equal((applied.payload.data.action as { verificationStatus: string }).verificationStatus, "passed"); await actions.apply(auth, "averon", id); assert.equal(validations, 1); });

test("conversation production stream publishes authoritative applying then verifying and persists one stable action message", async () => { const root = await fixture(), actions = service(root), proposal = await actions.propose(auth, "stream-phase:backend.source.propose", "averon", boundedBackendEdits('Add runtime: "local" to the health response.')); const conversations = new MemoryConversationRepository(); const conversation = await conversations.create("user-1", "averon"); await conversations.appendMessage(conversation.id, { role: "assistant", content: `Proposal ID: ${proposal.actionId}`, generationStatus: "completed" }); const result = await request(`/api/v1/emmy/conversations/${conversation.id}/messages/stream`, { method: "POST", authorization: "Bearer valid", requestId: "stream-phase", body: { message: `Apply backend source proposal ${proposal.actionId}.` }, workspaceRepository: workspaces(), businessOsRepository: business(), conversationRepository: conversations, backendSourceActions: actions }); const events = result.rawBody.trim().split("\n").map((line) => JSON.parse(line) as { type: string; action?: { status: string }; assistantMessage?: { id: string } }); const phases = events.filter((event) => event.type === "action_status"); assert.deepEqual(phases.map((event) => event.action?.status), ["applying", "verifying"]); assert.equal(phases[0]?.assistantMessage?.id, phases[1]?.assistantMessage?.id); assert.equal(events.at(-1)?.type, "completed"); const actionMessages = (await conversations.listMessages(conversation.id)).filter((message) => message.action?.actionId === proposal.actionId); assert.equal(actionMessages.length, 1); assert.equal(actionMessages[0]?.action?.status, "completed"); assert.equal(actionMessages[0]?.generationStatus, "completed"); });
test("production stream upserts Applying and Verifying into Diagnostics before terminal completion", async () => {
  const root = await fixture(); let releaseApplying!: () => void; let releaseVerifying!: () => void; let applyingSeen!: () => void; let verifyingSeen!: () => void;
  const applying = new Promise<void>((resolve) => { applyingSeen = resolve; }); const verifying = new Promise<void>((resolve) => { verifyingSeen = resolve; });
  class BlockingDiagnostics extends AiDiagnosticsStore { override async recordOperation(requestId: string, action: EmmyActionMetadata, context?: { workspaceId: string; businessId: string; startedAt?: string }) { await super.recordOperation(requestId, action, context); if (action.status === "applying") { applyingSeen(); await new Promise<void>((resolve) => { releaseApplying = resolve; }); } if (action.status === "verifying") { verifyingSeen(); await new Promise<void>((resolve) => { releaseVerifying = resolve; }); } } }
  const diagnostics = new BlockingDiagnostics(); const actions = service(root); const proposal = await actions.propose(auth, "diagnostic-phase:backend.source.propose", "averon", boundedBackendEdits('Add runtime: "local" to the health response.')); const conversations = new MemoryConversationRepository(); const conversation = await conversations.create("user-1", "averon"); await conversations.appendMessage(conversation.id, { role: "assistant", content: `Proposal ID: ${proposal.actionId}`, generationStatus: "completed" });
  const operation = request(`/api/v1/emmy/conversations/${conversation.id}/messages/stream`, { method: "POST", authorization: "Bearer valid", requestId: "diagnostic-phase", body: { message: `Apply backend source proposal ${proposal.actionId}.` }, workspaceRepository: workspaces(), businessOsRepository: business(), conversationRepository: conversations, backendSourceActions: actions, aiDiagnostics: diagnostics });
  await applying; assert.equal((await diagnostics.get("diagnostic-phase"))?.operationStatus, "applying"); assert.equal((await diagnostics.get("diagnostic-phase"))?.operationId, proposal.actionId); releaseApplying();
  await verifying; assert.equal((await diagnostics.get("diagnostic-phase"))?.operationStatus, "verifying"); assert.equal((await diagnostics.list()).length, 1); releaseVerifying();
  const result = await operation; assert.match(result.rawBody, /"type":"completed"/); const final = await diagnostics.get("diagnostic-phase"); assert.equal(final?.operationStatus, "completed"); assert.equal(final?.operationId, proposal.actionId); assert.equal((await diagnostics.list()).length, 1);
});
test("explicit IDs win while history fallback remains unambiguous", () => { const a = "a:backend.source.propose", b = "b:backend.source.propose", history = [{ role: "assistant" as const, content: `Proposal ID: ${a}\nProposal ID: ${b}` }]; assert.equal(backendSourceIntent(`Apply backend source proposal ${a}.`, history).proposalId, a); assert.deepEqual(backendSourceIntent(`Apply backend source proposal ${a}.`, history).historyProposalIds, []); assert.equal(backendSourceIntent("Apply that backend proposal.", history).historyProposalIds.length, 2); });
