import assert from "node:assert/strict";
import test from "node:test";
import type { WorkspaceRole } from "@averon/shared-types";
import { MemoryBusinessOsRepository, MemoryWorkspaceRepository, request } from "./http-harness.ts";

function workspaceRepository(role: WorkspaceRole = "owner", status: "active" | "disabled" = "active", workspaceStatus: "active" | "disabled" = "active") { return new MemoryWorkspaceRepository({ businesses: [{ id: "averon", name: "Averon Technologies", slug: "averon", status: workspaceStatus }], workspaces: [{ id: "averon", businessId: "averon", name: "Averon Technologies", slug: "averon", status: workspaceStatus }], memberships: [{ id: "averon__user-1", userId: "user-1", workspaceId: "averon", businessId: "averon", role, status }] }); }
async function initialize(repository: MemoryBusinessOsRepository, role: WorkspaceRole = "owner") { return request("/api/v1/workspaces/averon/business-os", { method: "POST", authorization: "Bearer valid", workspaceRepository: workspaceRepository(role), businessOsRepository: repository, body: {} }); }
const section = { id: "profile-main", type: "profile", title: "Company profile", content: { summary: "Authoritative profile", fields: { displayName: "Averon Technologies" } }, visibility: "internal", status: "active" };

test("Business OS access requires authentication", async () => { assert.equal((await request("/api/v1/workspaces/averon/business-os")).status, 401); });
test("initialization creates an empty workspace-scoped container idempotently", async () => { const repository = new MemoryBusinessOsRepository(); const first = await initialize(repository); const second = await initialize(repository); assert.equal(first.payload.data.created, true); assert.equal(second.payload.data.created, false); assert.equal(repository.sections.size, 0); });
test("empty Business OS returns metadata and no sections", async () => { const repository = new MemoryBusinessOsRepository(); await initialize(repository); const result = await request("/api/v1/workspaces/averon/business-os/sections", { authorization: "Bearer valid", workspaceRepository: workspaceRepository(), businessOsRepository: repository }); assert.deepEqual(result.payload.data.items, []); });
test("metadata projects existing Business OS management authority", async () => { const repository = new MemoryBusinessOsRepository(); await initialize(repository); const owner = await request("/api/v1/workspaces/averon/business-os", { authorization: "Bearer valid", workspaceRepository: workspaceRepository(), businessOsRepository: repository }); const member = await request("/api/v1/workspaces/averon/business-os", { authorization: "Bearer valid", workspaceRepository: workspaceRepository("member"), businessOsRepository: repository }); assert.equal(owner.payload.data.access.canManage, true); assert.equal(member.payload.data.access.canManage, false); });
test("owner creates and reads a structured section with server identity and audit", async () => { const repository = new MemoryBusinessOsRepository(); await initialize(repository); const created = await request("/api/v1/workspaces/averon/business-os/sections", { method: "POST", authorization: "Bearer valid", body: section, workspaceRepository: workspaceRepository(), businessOsRepository: repository }); assert.equal(created.status, 201); assert.equal(created.payload.data.businessId, "averon"); assert.equal(created.payload.data.version, 1); assert.deepEqual(repository.audits, ["BUSINESS_OS_SECTION_CREATED"]); const found = await request("/api/v1/workspaces/averon/business-os/sections/profile-main", { authorization: "Bearer valid", workspaceRepository: workspaceRepository(), businessOsRepository: repository }); assert.equal(found.status, 200); });
test("section update increments version and records audit without content in audit", async () => { const repository = new MemoryBusinessOsRepository(); await initialize(repository); await request("/api/v1/workspaces/averon/business-os/sections", { method: "POST", authorization: "Bearer valid", body: section, workspaceRepository: workspaceRepository(), businessOsRepository: repository }); const updated = await request("/api/v1/workspaces/averon/business-os/sections/profile-main", { method: "PATCH", authorization: "Bearer valid", body: { title: "Updated profile" }, workspaceRepository: workspaceRepository(), businessOsRepository: repository }); assert.equal(updated.payload.data.version, 2); assert.equal(repository.audits.at(-1), "BUSINESS_OS_SECTION_UPDATED"); });
test("invalid type, visibility, and privileged fields are rejected", async () => { const repository = new MemoryBusinessOsRepository(); await initialize(repository); for (const body of [{ ...section, type: "agent" }, { ...section, visibility: "secret" }, { ...section, businessId: "lumora" }]) { const result = await request("/api/v1/workspaces/averon/business-os/sections", { method: "POST", authorization: "Bearer valid", body, workspaceRepository: workspaceRepository(), businessOsRepository: repository }); assert.equal(result.status, 400); } });
test("Business OS must be initialized before section creation", async () => { const result = await request("/api/v1/workspaces/averon/business-os/sections", { method: "POST", authorization: "Bearer valid", body: section, workspaceRepository: workspaceRepository(), businessOsRepository: new MemoryBusinessOsRepository() }); assert.equal(result.status, 409); assert.equal(result.payload.error.code, "BUSINESS_OS_NOT_INITIALIZED"); });
test("viewer sees public sections only", async () => { const repository = new MemoryBusinessOsRepository(); await initialize(repository); repository.sections.set("averon/public", { ...section, id: "public", visibility: "public", version: 1, workspaceId: "averon", businessId: "averon", updatedBy: "user-1" }); repository.sections.set("averon/internal", { ...section, id: "internal", visibility: "internal", version: 1, workspaceId: "averon", businessId: "averon", updatedBy: "user-1" }); const result = await request("/api/v1/workspaces/averon/business-os/sections", { authorization: "Bearer valid", workspaceRepository: workspaceRepository("viewer"), businessOsRepository: repository }); assert.deepEqual((result.payload.data.items as Array<{ id: string }>).map((item) => item.id), ["public"]); });
test("member sees internal but not restricted content", async () => { const repository = new MemoryBusinessOsRepository(); await initialize(repository); for (const visibility of ["internal", "restricted"] as const) repository.sections.set(`averon/${visibility}`, { ...section, id: visibility, visibility, version: 1, workspaceId: "averon", businessId: "averon", updatedBy: "user-1" }); const result = await request("/api/v1/workspaces/averon/business-os/sections", { authorization: "Bearer valid", workspaceRepository: workspaceRepository("member"), businessOsRepository: repository }); assert.deepEqual((result.payload.data.items as Array<{ id: string }>).map((item) => item.id), ["internal"]); });
test("restricted section requires elevated workspace role", async () => { const repository = new MemoryBusinessOsRepository(); await initialize(repository); repository.sections.set("averon/restricted", { ...section, id: "restricted", visibility: "restricted", version: 1, workspaceId: "averon", businessId: "averon", updatedBy: "user-1" }); assert.equal((await request("/api/v1/workspaces/averon/business-os/sections/restricted", { authorization: "Bearer valid", workspaceRepository: workspaceRepository("member"), businessOsRepository: repository })).status, 404); assert.equal((await request("/api/v1/workspaces/averon/business-os/sections/restricted", { authorization: "Bearer valid", workspaceRepository: workspaceRepository("admin"), businessOsRepository: repository })).status, 200); });
test("cross-workspace and manipulated IDs cannot read Business OS", async () => { const repository = new MemoryBusinessOsRepository(); repository.roots.set("movento", { workspaceId: "movento", businessId: "movento", status: "active", schemaVersion: 1 }); const result = await request("/api/v1/workspaces/movento/business-os", { authorization: "Bearer valid", workspaceRepository: workspaceRepository(), businessOsRepository: repository }); assert.equal(result.status, 403); });
test("inactive membership and disabled workspace deny Business OS", async () => { for (const workspaces of [workspaceRepository("owner", "disabled"), workspaceRepository("owner", "active", "disabled")]) assert.equal((await request("/api/v1/workspaces/averon/business-os", { authorization: "Bearer valid", workspaceRepository: workspaces, businessOsRepository: new MemoryBusinessOsRepository() })).status, 403); });
test("member cannot mutate Business OS", async () => { const repository = new MemoryBusinessOsRepository(); await initialize(repository); const result = await request("/api/v1/workspaces/averon/business-os/sections", { method: "POST", authorization: "Bearer valid", body: section, workspaceRepository: workspaceRepository("member"), businessOsRepository: repository }); assert.equal(result.status, 403); });
test("decisions can be created and updated with versioned safe rationale", async () => { const repository = new MemoryBusinessOsRepository(); await initialize(repository); const created = await request("/api/v1/workspaces/averon/business-os/decisions", { method: "POST", authorization: "Bearer valid", body: { id: "decision-1", title: "Document the API boundary", summary: "Keep privileged integrations in averon-api.", rationale: "Central ownership reduces credential exposure.", status: "active" }, workspaceRepository: workspaceRepository(), businessOsRepository: repository }); assert.equal(created.status, 201); assert.equal(created.payload.data.version, 1); const updated = await request("/api/v1/workspaces/averon/business-os/decisions/decision-1", { method: "PATCH", authorization: "Bearer valid", body: { status: "superseded", supersededBy: "decision-2" }, workspaceRepository: workspaceRepository(), businessOsRepository: repository }); assert.equal(updated.payload.data.version, 2); assert.equal(repository.audits.at(-1), "BUSINESS_DECISION_UPDATED"); });
test("history projects the existing workspace audit evidence without record payloads", async () => { const repository = new MemoryBusinessOsRepository(); await initialize(repository); await request("/api/v1/workspaces/averon/business-os/sections", { method: "POST", authorization: "Bearer valid", body: section, workspaceRepository: workspaceRepository(), businessOsRepository: repository }); await request("/api/v1/workspaces/averon/business-os/sections/profile-main", { method: "PATCH", authorization: "Bearer valid", body: { title: "Updated profile" }, workspaceRepository: workspaceRepository(), businessOsRepository: repository }); const result = await request("/api/v1/workspaces/averon/business-os/history", { authorization: "Bearer valid", workspaceRepository: workspaceRepository(), businessOsRepository: repository }); assert.equal(result.status, 200); const items = result.payload.data.items as Array<Record<string, unknown>>; assert.deepEqual(items.map((item) => item.eventType), ["BUSINESS_OS_SECTION_UPDATED", "BUSINESS_OS_SECTION_CREATED"]); assert.equal(items.every((item) => item.workspaceId === "averon"), true); const serialized = JSON.stringify(items); assert.equal(serialized.includes("Authoritative profile"), false); assert.equal(serialized.includes("displayName"), false); });
test("invalid decision status and unauthorized decision mutation are rejected", async () => { const repository = new MemoryBusinessOsRepository(); await initialize(repository); const invalid = await request("/api/v1/workspaces/averon/business-os/decisions", { method: "POST", authorization: "Bearer valid", body: { id: "decision-1", title: "Decision", summary: "Decision summary", status: "hidden" }, workspaceRepository: workspaceRepository(), businessOsRepository: repository }); assert.equal(invalid.status, 400); const member = await request("/api/v1/workspaces/averon/business-os/decisions", { method: "POST", authorization: "Bearer valid", body: { id: "decision-2", title: "Decision", summary: "Decision summary" }, workspaceRepository: workspaceRepository("member"), businessOsRepository: repository }); assert.equal(member.status, 403); });
