import assert from "node:assert/strict"; import test from "node:test";
import type { AgentSpec, SkillDefinition } from "@averon/agent-contracts";
import { DefaultAgentRegistry, isValidAgentSpec, productionAgentSpecs } from "../src/ai/agents/registry.ts";
import { isValidSkillDefinition, SkillRegistry, productionSkills } from "../src/ai/agents/skills.ts";
import { AgentReadinessEngine, CapabilityResolver, SmallestTeamSelector } from "../src/ai/agents/readiness.ts";
import { TaskPlanner } from "../src/ai/agents/planner.ts";

const environment = { availableProviders: ["ai.text_generation"], availableTools: [] as string[], availableModelCapabilities: ["structured_output"] };
const spec = (id: string, skills: string[], overrides: Partial<AgentSpec> = {}): AgentSpec => ({ ...productionAgentSpecs[0], id, name: id, domain: "test", skills, outputSchema: `${id}.v1`, certification: { lastEvalStatus: "passed", certificationStatus: "passed", certifiedSchemaVersion: `${id}.v1` }, ...overrides });

test("production AgentSpecs and skills are complete, credential-free, and exactly sixteen",()=>{assert.equal(productionAgentSpecs.length,16);assert.equal(new Set(productionAgentSpecs.map(item=>item.id)).size,16);for(const agent of productionAgentSpecs){assert.ok(agent.skills.length);assert.ok(agent.maxProviderCalls<=2);assert.ok(agent.verificationRequirements.includes("validator_only"));assert.ok(agent.executionRights.every(right=>["read","analyze","draft","recommend"].includes(right)));assert.doesNotMatch(JSON.stringify(agent),/"(apiKey|secret|token|password)"\s*:/i);}assert.equal(productionSkills.length,19);assert.equal(new SkillRegistry().get("development.backend_analysis")?.domain,"development");});
test("AgentSpec and SkillDefinition validators reject incomplete definitions",()=>{assert.equal(isValidAgentSpec(productionAgentSpecs[0]),true);assert.equal(isValidAgentSpec({...productionAgentSpecs[0],outputSchema:""}),false);assert.equal(isValidSkillDefinition(productionSkills[0]),true);assert.equal(isValidSkillDefinition({...productionSkills[0],requiredPermissions:"emmy:use"}),false);});
test("skill registry supports ID, domain, requirements, and agent mapping",()=>{const skills=new SkillRegistry();assert.equal(skills.get("seo.metadata")?.domain,"seo");assert.equal(skills.listByDomain("seo").length,2);assert.equal(skills.isKnown("unknown"),false);assert.deepEqual(skills.supportedBy(productionAgentSpecs[1]).map(item=>item.id),["seo.content_strategy","seo.metadata"]);});
test("readiness reports ready, disabled, experimental, missing provider, missing skill, and failed certification",()=>{const skills=new SkillRegistry();const agents=new DefaultAgentRegistry([spec("ready",["seo.metadata"]),spec("disabled",["seo.metadata"],{enabled:false}),spec("experimental",["seo.metadata"],{experimental:true}),spec("missing-skill",["unknown"]),spec("failed-cert",["seo.metadata"],{certification:{lastEvalStatus:"failed",certificationStatus:"failed",certifiedSchemaVersion:"failed-cert.v1"}})]);const ready=new AgentReadinessEngine(agents,skills,environment);assert.equal(ready.evaluate(agents.get("ready")!).status,"READY");assert.equal(ready.evaluate(agents.get("disabled")!).status,"DISABLED");assert.equal(ready.evaluate(agents.get("experimental")!).status,"EXPERIMENTAL");assert.equal(ready.evaluate(agents.get("missing-skill")!).status,"NOT_READY");assert.equal(ready.evaluate(agents.get("failed-cert")!).status,"NOT_READY");const missingProvider=new AgentReadinessEngine(agents,skills,{...environment,availableProviders:[]});assert.match(missingProvider.evaluate(agents.get("ready")!).missingRequirements.join(),/provider/);});
test("skill readiness and resolver enforce workspace permission and risk",()=>{const skills=new SkillRegistry();const agents=new DefaultAgentRegistry();const ready=new AgentReadinessEngine(agents,skills,environment);assert.equal(ready.skill("seo.content_strategy",["emmy:use"]).executable,true);assert.equal(ready.skill("seo.content_strategy",[]).executable,false);assert.equal(ready.skill("unknown",["emmy:use"]).status,"NOT_READY");const resolver=new CapabilityResolver(agents,ready);assert.deepEqual(resolver.resolveCandidates({requiredSkills:["seo.content_strategy"],permissions:[],riskLevel:"moderate"}).candidates,[]);assert.deepEqual(resolver.resolveCandidates({requiredSkills:["seo.content_strategy"],permissions:["emmy:use"],riskLevel:"low"}).candidates.map(item=>item.id),["seo"]);});
test("planner expresses skills and selector chooses the smallest sufficient team",()=>{const planner=new TaskPlanner();const capabilityPlan=planner.capabilities("Write an SEO-friendly article");assert.deepEqual(capabilityPlan.requiredSkills,["seo.content_strategy","content.blog_drafting"]);const agents=new DefaultAgentRegistry();const readiness=new AgentReadinessEngine(agents,new SkillRegistry(),environment);const resolved=new CapabilityResolver(agents,readiness).resolveCandidates({requiredSkills:capabilityPlan.requiredSkills,permissions:["emmy:use"],riskLevel:"moderate"});const team=new SmallestTeamSelector().select(capabilityPlan.requiredSkills,resolved.candidates,{maxAgents:4,maxProviderCalls:4,maxRuntimeMs:20_000,costClassCeiling:"medium"});assert.deepEqual(team.selectedAgents,["blog","seo"]);assert.equal(team.unresolvedSkills.length,0);const plan=planner.materialize("Write an SEO-friendly article",capabilityPlan,team);assert.deepEqual(plan.tasks.map(item=>item.agentId),["seo","blog"]);assert.ok(plan.tasks.find(item=>item.agentId==="blog")?.dependencies.includes(plan.tasks.find(item=>item.agentId==="seo")!.taskId));assert.equal(planner.capabilities("What is our brand tone?").directAnswerPossible,true);});
test("selector reports unsupported skills and respects agent/call/runtime/cost budgets",()=>{const selected=new SmallestTeamSelector().select(["unknown"],productionAgentSpecs as AgentSpec[],{maxAgents:4,maxProviderCalls:4,maxRuntimeMs:20_000});assert.deepEqual(selected.selectedAgents,[]);assert.deepEqual(selected.unresolvedSkills,["unknown"]);const blocked=new SmallestTeamSelector().select(["seo.content_strategy"],productionAgentSpecs as AgentSpec[],{maxAgents:0,maxProviderCalls:0,maxRuntimeMs:1,costClassCeiling:"low"});assert.deepEqual(blocked.unresolvedSkills,["seo.content_strategy"]);});
test("test-only 100-agent registry stays indexed, bounded, and excludes disabled definitions",()=>{const skillDefinitions:SkillDefinition[]=Array.from({length:100},(_,index)=>({id:`test.skill.${index}`,name:`Skill ${index}`,domain:`domain-${index%10}`,description:"Test-only capacity skill.",riskLevel:"low",requiredPermissions:["emmy:use"]}));const agentDefinitions=skillDefinitions.map((skill,index)=>spec(`test-agent-${index}`,[skill.id],{enabled:index!==77}));const skills=new SkillRegistry(skillDefinitions);const agents=new DefaultAgentRegistry(agentDefinitions);assert.equal(agents.list().length,100);assert.equal(agents.listByDomain("test").length,100);assert.equal(agents.listBySkill("test.skill.42")[0].id,"test-agent-42");const readiness=new AgentReadinessEngine(agents,skills,environment);const resolver=new CapabilityResolver(agents,readiness);assert.equal(resolver.resolveCandidates({requiredSkills:["test.skill.77"],permissions:["emmy:use"],riskLevel:"low"}).candidates.length,0);const candidates=resolver.resolveCandidates({requiredSkills:["test.skill.1","test.skill.2"],permissions:["emmy:use"],riskLevel:"low"}).candidates;const team=new SmallestTeamSelector().select(["test.skill.1","test.skill.2"],candidates,{maxAgents:4,maxProviderCalls:5,maxRuntimeMs:20_000});assert.equal(team.selectedAgents.length,2);assert.equal(team.candidateCount,2);});
