import assert from "node:assert/strict";
import test from "node:test";
import { ApiError } from "../src/errors/api-error.ts";
import { InMemoryRateLimiter } from "../src/ai/emmy/rate-limiter.ts";
import { DeepSeekProvider } from "../src/ai/providers/deepseek/deepseek.provider.ts";
import type { AiProvider } from "../src/ai/providers/ai-provider.ts";
import { request } from "./http-harness.ts";

function response(status: number, body: unknown) { return new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json" } }); }

test("DeepSeek maps successful provider response and usage", async () => { const provider = new DeepSeekProvider(async () => response(200, { choices: [{ message: { content: "Hello from Emmy" } }], usage: { prompt_tokens: 3, completion_tokens: 4, total_tokens: 7 } }), { DEEPSEEK_API_KEY: "test-key" }); const result = await provider.generate({ systemPrompt: "system", messages: [] }); assert.equal(result.text, "Hello from Emmy"); assert.equal(result.usage?.totalTokens, 7); });
test("DeepSeek enables provider JSON mode only for explicitly structured requests", async () => { const bodies: Array<Record<string, unknown>> = []; const provider = new DeepSeekProvider(async (_url, init) => { bodies.push(JSON.parse(String(init?.body)) as Record<string, unknown>); return response(200, { choices: [{ message: { content: "{}" } }] }); }, { DEEPSEEK_API_KEY: "test-key" }); await provider.generate({ systemPrompt: "Return JSON", messages: [], responseFormat: "json_object" }); await provider.generate({ systemPrompt: "Plain response", messages: [] }); assert.deepEqual(bodies[0].response_format, { type: "json_object" }); assert.equal(bodies[1].response_format, undefined); });
test("DeepSeek timeout maps safely", async () => { const provider = new DeepSeekProvider((_url, init) => new Promise((_resolve, reject) => init?.signal?.addEventListener("abort", () => reject(Object.assign(new Error("aborted"), { name: "AbortError" })))), { DEEPSEEK_API_KEY: "test-key", DEEPSEEK_TIMEOUT_MS: "1" }); await assert.rejects(() => provider.generate({ systemPrompt: "system", messages: [] }), (error: ApiError) => error.code === "AI_PROVIDER_TIMEOUT"); });
test("DeepSeek HTTP failure is sanitized", async () => { const provider = new DeepSeekProvider(async () => response(500, { error: { message: "provider internal secret" } }), { DEEPSEEK_API_KEY: "test-key" }); await assert.rejects(() => provider.generate({ systemPrompt: "system", messages: [] }), (error: ApiError) => error.code === "AI_PROVIDER_ERROR" && !error.message.includes("secret")); });
test("malformed provider response is rejected", async () => { const provider = new DeepSeekProvider(async () => response(200, { choices: [] }), { DEEPSEEK_API_KEY: "test-key" }); await assert.rejects(() => provider.generate({ systemPrompt: "system", messages: [] }), (error: ApiError) => error.code === "EMMY_RESPONSE_FAILED"); });
test("missing provider configuration is safe", async () => { const provider = new DeepSeekProvider(async () => response(200, {}), {}); await assert.rejects(() => provider.generate({ systemPrompt: "system", messages: [] }), (error: ApiError) => error.code === "AI_PROVIDER_UNAVAILABLE" && !JSON.stringify(error).includes("API_KEY")); });
test("DeepSeek streaming preserves ordered Unicode chunks and usage", async () => {
  const encoder = new TextEncoder(); const payload = 'data: {"choices":[{"delta":{"content":"Hello "}}]}\n\ndata: {"choices":[{"delta":{"content":"🌍"}}]}\n\ndata: {"choices":[],"usage":{"prompt_tokens":2,"completion_tokens":3,"total_tokens":5}}\n\ndata: [DONE]\n\n'; const bytes = encoder.encode(payload);
  const body = new ReadableStream<Uint8Array>({ start(controller) { controller.enqueue(bytes.slice(0, 57)); controller.enqueue(bytes.slice(57, 83)); controller.enqueue(bytes.slice(83)); controller.close(); } });
  const provider = new DeepSeekProvider(async () => new Response(body, { status: 200, headers: { "Content-Type": "text/event-stream" } }), { DEEPSEEK_API_KEY: "test-key" }); const chunks: string[] = [];
  const result = await provider.generateStream({ systemPrompt: "system", messages: [] }, { onTextDelta(delta) { chunks.push(delta); } });
  assert.deepEqual(chunks, ["Hello ", "🌍"]); assert.equal(result.text, "Hello 🌍"); assert.equal(result.usage?.totalTokens, 5);
});
test("public Emmy accepts a valid message without authentication", async () => { const result = await request("/api/v1/emmy/messages", { method: "POST", body: { message: "What does Averon build?", history: [] } }); assert.equal(result.status, 200); assert.equal(result.payload.data.reply, "Test Emmy response"); });
test("empty and oversized messages are rejected", async () => { for (const message of ["", "x".repeat(2001)]) { const result = await request("/api/v1/emmy/messages", { method: "POST", body: { message } }); assert.equal(result.payload.error.code, "EMMY_INVALID_REQUEST"); } });
test("malformed body and excessive history are rejected", async () => { const malformed = await request("/api/v1/emmy/messages", { method: "POST", body: [] }); assert.equal(malformed.payload.error.code, "EMMY_INVALID_REQUEST"); const history = Array.from({ length: 9 }, () => ({ role: "user", content: "hello" })); const excessive = await request("/api/v1/emmy/messages", { method: "POST", body: { message: "hello", history } }); assert.equal(excessive.payload.error.code, "EMMY_INVALID_REQUEST"); });
test("provider failures retain stable envelopes and request IDs", async () => { const provider: AiProvider = { async generate() { throw new ApiError(502, "AI_PROVIDER_ERROR", "Emmy could not complete the request."); } }; const result = await request("/api/v1/emmy/messages", { method: "POST", requestId: "emmy-request", body: { message: "hello" }, aiProvider: provider }); assert.equal(result.status, 502); assert.equal(result.payload.requestId, "emmy-request"); assert.equal(result.payload.error.code, "AI_PROVIDER_ERROR"); });
test("public Emmy rate limiter rejects rapid abuse", async () => { const limiter = new InMemoryRateLimiter(1, 60_000); const first = await request("/api/v1/emmy/messages", { method: "POST", body: { message: "hello" }, emmyRateLimiter: limiter }); const second = await request("/api/v1/emmy/messages", { method: "POST", body: { message: "again" }, emmyRateLimiter: limiter }); assert.equal(first.status, 200); assert.equal(second.payload.error.code, "EMMY_RATE_LIMITED"); });
