import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import type { AiProvider } from "../src/ai/providers/ai-provider.ts";
import { FrontendSourceActionService, boundedFrontendEdits, frontendSourceIntent, resolveFrontendSourcePath, type SourceValidationResult } from "../src/domains/frontend-source/frontend-source.actions.ts";
import { WorkspaceAuthorizationService } from "../src/domains/workspaces/workspace.service.ts";
import { ApiError } from "../src/errors/api-error.ts";
import { MemoryFrontendSourceProposalRepository } from "../src/domains/frontend-source/frontend-source.repository.ts";
import { MemoryBusinessOsRepository, MemoryWorkspaceRepository, request } from "./http-harness.ts";

const auth = { user: { userId: "user-1", emailVerified: true, role: "owner" as const, isAdmin: true, permissions: [] } };
const workspaces = (role: "owner" | "member" = "owner") => new MemoryWorkspaceRepository({ businesses: [{ id: "averon", name: "Averon", slug: "averon", status: "active" }], workspaces: [{ id: "averon", businessId: "averon", name: "Averon", slug: "averon", status: "active" }], memberships: [{ id: "m1", userId: "user-1", workspaceId: "averon", businessId: "averon", role, status: "active" }] });
const business = () => { const repo = new MemoryBusinessOsRepository(); repo.roots.set("averon", { workspaceId: "averon", businessId: "averon", status: "active", schemaVersion: 1 }); return repo; };
async function fixture() { const root = await mkdtemp(join(tmpdir(), "averon-source-v4-")); await mkdir(join(root, "src", "styles"), { recursive: true }); await mkdir(join(root, "src", "components"), { recursive: true }); await writeFile(join(root, "src", "styles", "globals.css"), ".unrelated { color: red; }\n.hero-actions {\n  display: flex;\n  gap: 16px;\n}\n", "utf8"); await writeFile(join(root, "src", "components", "Card.tsx"), "export const Card = () => <div className=\"card\" />;\n", "utf8"); return root; }
const service = (root: string, results: SourceValidationResult[] = [{ name: "typecheck", passed: true }, { name: "lint", passed: true }, { name: "test", passed: true }, { name: "build", passed: true }], role: "owner" | "member" = "owner") => new FrontendSourceActionService(new WorkspaceAuthorizationService(workspaces(role)), { async run() { return results; } }, root);
const edit = { path: "src/styles/globals.css", find: "gap: 16px;", replace: "gap: 20px;" };

test("current-turn source mutation intent is explicit and advisory review remains read-only", () => { assert.equal(frontendSourceIntent("Increase the desktop gap between the homepage hero buttons slightly.").action, "propose"); for (const value of ["Show me how the homepage hero component works.", "Why is this button misaligned?", "Review the mobile navigation.", "Do something better with it."]) assert.equal(frontendSourceIntent(value).action, "none", value); });

test("explicit no-write polarity keeps production-shaped design reviews advisory", () => {
  const request = `Review Averon homepage design\n\nReview the Averon Technologies homepage and identify the most important improvements needed to make it look like a premium, established technology company.\n\nFocus on typography, spacing, visual hierarchy, layout composition, trust presentation, brand quality, and overall premium appearance.\n\nDo not modify any files or content.\nReturn recommendations only.`;
  assert.equal(frontendSourceIntent(request).action, "none");
  assert.equal(frontendSourceIntent("Increase the hero button spacing to 20px. Do not change mobile spacing.").action, "propose");
});

test("source read is authorized and performs zero writes", async () => { const root = await fixture(); const actions = service(root); const before = await readFile(join(root, edit.path), "utf8"); const result = await actions.read(auth, "averon", edit.path); assert.equal(result.content, before); assert.equal(await readFile(join(root, edit.path), "utf8"), before); });

test("path resolver rejects traversal absolute hidden backend and missing targets", async () => { const root = await fixture(); for (const value of ["../secret.ts", "/tmp/source.ts", ".env", "apps/averon-api/src/app.ts", "src/.secret/file.ts"]) await assert.rejects(resolveFrontendSourcePath(value, root), (error: unknown) => error instanceof ApiError && error.code === "SOURCE_PATH_NOT_ALLOWED"); await assert.rejects(resolveFrontendSourcePath("src/missing.tsx", root), (error: unknown) => error instanceof ApiError && error.code === "SOURCE_TARGET_NOT_FOUND"); });

test("bounded proposals target exact files, preserve unrelated edits, support multiple files, and do not mutate", async () => { const root = await fixture(); const actions = service(root); const originalCss = await readFile(join(root, edit.path), "utf8"); const cardPath = "src/components/Card.tsx"; const originalCard = await readFile(join(root, cardPath), "utf8"); const proposal = await actions.propose(auth, "proposal-multi", "averon", [edit, { path: cardPath, find: "className=\"card\"", replace: "className=\"card card--compact\"" }]); assert.deepEqual(proposal.files.map((file) => file.path), [edit.path, cardPath]); assert.match(proposal.diff, /gap: 16px/); assert.match(proposal.diff, /gap: 20px/); assert.equal(await readFile(join(root, edit.path), "utf8"), originalCss); assert.equal(await readFile(join(root, cardPath), "utf8"), originalCard); assert.match(proposal.files[0]!.proposed, /\.unrelated \{ color: red; \}/); });

test("exact live request scopes the proposal to the production-shaped hero-actions rule without mutating source", async () => { const productionRoot = await fixture(); const cssPath = join(productionRoot, "src", "styles", "globals.css"); const original = await readFile(cssPath, "utf8"); const actions = service(productionRoot); const message = "Increase the horizontal spacing between the homepage hero action buttons slightly on desktop. Do not change mobile spacing or any other part of the homepage. Prepare the change for review."; const proposal = await actions.propose(auth, "live-source-conflict-regression", "averon", boundedFrontendEdits(message)); const file = proposal.files[0]!; assert.equal(file.path, "src/styles/globals.css"); assert.equal((original.match(/\.hero-actions\s*\{/g) ?? []).length, 1); assert.match(proposal.diff, /^--- a\/src\/styles\/globals\.css/m); assert.match(proposal.diff, /-{1} {2}gap: 16px;/m); assert.match(proposal.diff, /\+{1} {2}gap: 20px;/m); assert.equal(file.insertions, 1); assert.equal(file.deletions, 1); assert.notEqual(file.originalHash, file.proposedHash); assert.equal(file.original, original); assert.equal(await readFile(cssPath, "utf8"), original); });

test("exact 20px to 22px live request derives current source and creates an approval-gated proposal without mutation", async () => {
  const root = await fixture(); const cssPath = join(root, "src", "styles", "globals.css");
  const mobile = "@media (max-width: 720px) {\n  .mobile-actions { gap: 8px; }\n}\n";
  const original = `.unrelated { color: red; }\n.hero-actions {\n  display: flex;\n  gap: 20px;\n}\n${mobile}`;
  await writeFile(cssPath, original, "utf8"); const actions = service(root); const provider = new FrontendProvider();
  const message = "Increase the horizontal spacing between the homepage hero action buttons from 20px to 22px on desktop only. Do not change mobile spacing or anything else on the homepage. Prepare the frontend source change for review only.";
  const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", requestId: "live-20-to-22", body: { message }, workspaceRepository: workspaces(), businessOsRepository: business(), aiProvider: provider, frontendSourceActions: actions });
  const action = result.payload.data.action as { actionId: string; status: string; approvalStatus: string; verificationStatus: string; changedLines: number; diff: string };
  assert.equal(result.payload.data.finalStatus, "completed"); assert.equal(provider.calls, 1); assert.equal(action.status, "approval_required"); assert.equal(action.approvalStatus, "pending"); assert.equal(action.verificationStatus, "pending"); assert.equal(action.changedLines, 2);
  assert.match(action.diff, /-{1} {2}gap: 20px;/); assert.match(action.diff, /\+{1} {2}gap: 22px;/); assert.equal(await readFile(cssPath, "utf8"), original); assert.match(original, new RegExp(mobile.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  const proposal = await actions.get(action.actionId); assert.equal(proposal?.files[0]?.original, original); assert.equal(proposal?.approvalStatus, "pending");
});

test("bounded hero spacing adapter derives arbitrary requested destination instead of an acceptance-test constant", async () => {
  const root = await fixture(); const cssPath = join(root, "src", "styles", "globals.css"); const original = ".hero-actions {\n  display: flex;\n  gap: 18px;\n}\n"; await writeFile(cssPath, original, "utf8");
  const proposal = await service(root).propose(auth, "generalized-gap", "averon", boundedFrontendEdits("Change the hero action button spacing from 18px to 24px on desktop."));
  assert.match(proposal.diff, /-{1} {2}gap: 18px;/); assert.match(proposal.diff, /\+{1} {2}gap: 24px;/); assert.equal(await readFile(cssPath, "utf8"), original);
});

test("unknown and conflicting targets fail closed", async () => { const root = await fixture(); const actions = service(root); await assert.rejects(actions.propose(auth, "unknown", "averon", [{ ...edit, find: "missing selector" }]), (error: unknown) => error instanceof ApiError && error.code === "SOURCE_CONFLICT"); await writeFile(join(root, edit.path), "gap: 16px;\ngap: 16px;\n", "utf8"); await assert.rejects(actions.propose(auth, "ambiguous", "averon", [edit]), (error: unknown) => error instanceof ApiError && error.code === "SOURCE_CONFLICT"); });

test("stale bases and high-risk proposals block apply until explicit approval", async () => { const root = await fixture(); const actions = service(root); await actions.propose(auth, "stale-action", "averon", [edit]); await writeFile(join(root, edit.path), "user changed this file\n", "utf8"); await assert.rejects(actions.apply(auth, "averon", "stale-action"), (error: unknown) => error instanceof ApiError && error.code === "SOURCE_STALE_BASE"); const root2 = await fixture(); const highRisk = service(root2); await highRisk.propose(auth, "high-risk-action", "averon", [edit], true); await assert.rejects(highRisk.apply(auth, "averon", "high-risk-action"), (error: unknown) => error instanceof ApiError && error.code === "SOURCE_APPROVAL_REQUIRED"); await highRisk.approve(auth, "averon", "high-risk-action"); assert.equal((await highRisk.apply(auth, "averon", "high-risk-action")).status, "completed"); });
test("rejected proposal is durable and cannot apply", async () => { const root = await fixture(), actions = service(root), path = join(root, edit.path), before = await readFile(path, "utf8"); const proposal = await actions.propose(auth, "reject-action:frontend.source.propose", "averon", [edit], true); const rejected = await actions.reject(auth, "averon", proposal.actionId); assert.equal(rejected.status, "rejected"); assert.equal(rejected.approvalStatus, "rejected"); await assert.rejects(actions.resolveExplicit(auth, "averon", proposal.actionId), (error: unknown) => error instanceof ApiError && error.code === "SOURCE_PROPOSAL_NOT_FOUND"); assert.equal(await readFile(path, "utf8"), before); });

test("apply validates, mutates exactly once, and idempotent replay returns the verified result", async () => { const root = await fixture(); let validationRuns = 0; const actions = new FrontendSourceActionService(new WorkspaceAuthorizationService(workspaces()), { async run() { validationRuns += 1; return [{ name: "typecheck", passed: true }, { name: "lint", passed: true }, { name: "test", passed: true }, { name: "build", passed: true }]; } }, root); await actions.propose(auth, "apply-once", "averon", [edit]); const first = await actions.apply(auth, "averon", "apply-once"); const second = await actions.apply(auth, "averon", "apply-once"); assert.equal(validationRuns, 1); assert.deepEqual(second, first); assert.match(await readFile(join(root, edit.path), "utf8"), /gap: 20px/); assert.match(await readFile(join(root, edit.path), "utf8"), /\.unrelated \{ color: red; \}/); });

test("frontend executor durably publishes applying before verifying", async () => { const root = await fixture(); const repository = new MemoryFrontendSourceProposalRepository(); const actions = new FrontendSourceActionService(new WorkspaceAuthorizationService(workspaces()), { async run() { assert.equal((await repository.get("phase-action"))?.status, "verifying"); return [{ name: "typecheck", passed: true }]; } }, root, repository); await actions.propose(auth, "phase-action", "averon", [edit]); const states: string[] = []; await actions.apply(auth, "averon", "phase-action", async (state) => { states.push(state.status); assert.equal((await repository.get(state.actionId))?.status, state.status); }); assert.deepEqual(states, ["applying", "verifying"]); assert.equal((await repository.get("phase-action"))?.status, "completed"); });

test("durable proposal state survives a service restart and completed replay does not mutate twice", async () => { const root = await fixture(); const repository = new MemoryFrontendSourceProposalRepository(); let validationRuns = 0; const validator = { async run() { validationRuns += 1; return [{ name: "typecheck" as const, passed: true }, { name: "lint" as const, passed: true }, { name: "test" as const, passed: true }, { name: "build" as const, passed: true }]; } }; const authorization = new WorkspaceAuthorizationService(workspaces()); const firstProcess = new FrontendSourceActionService(authorization, validator, root, repository); await firstProcess.propose(auth, "durable-action", "averon", [edit]); const secondProcess = new FrontendSourceActionService(authorization, validator, root, repository); await secondProcess.apply(auth, "averon", "durable-action"); const thirdProcess = new FrontendSourceActionService(authorization, validator, root, repository); assert.equal((await thirdProcess.apply(auth, "averon", "durable-action")).status, "completed"); assert.equal(validationRuns, 1); assert.match(await readFile(join(root, edit.path), "utf8"), /gap: 20px/); });

test("verification failure automatically restores exact original bytes", async () => { const root = await fixture(); const original = await readFile(join(root, edit.path), "utf8"); const actions = service(root, [{ name: "typecheck", passed: true }, { name: "build", passed: false }]); await actions.propose(auth, "rollback-action", "averon", [edit]); await assert.rejects(actions.apply(auth, "averon", "rollback-action"), (error: unknown) => error instanceof ApiError && error.code === "SOURCE_VERIFICATION_FAILED"); assert.equal(await readFile(join(root, edit.path), "utf8"), original); assert.equal((await actions.get("rollback-action"))?.rollbackStatus, "completed"); });

test("workspace authorization denies source mutation for members", async () => { const root = await fixture(); await assert.rejects(service(root, [], "member").propose(auth, "denied-action", "averon", [edit]), (error: unknown) => error instanceof ApiError && error.code === "WORKSPACE_PERMISSION_DENIED"); assert.match(await readFile(join(root, edit.path), "utf8"), /gap: 16px/); });

class FrontendProvider implements AiProvider { calls = 0; async generate() { this.calls += 1; return { text: JSON.stringify({ schemaVersion: "frontend.v1", agentId: "frontend", taskId: "task-1-frontend", status: "completed", summary: "Reviewed the bounded spacing change.", output: { findings: ["The hero action gap is 16px."], recommendations: ["Use 20px for the requested desktop spacing."], risks: [], assumptions: [], missingInformation: [] }, warnings: [], missingInformation: [] }) }; } }

test("production path proposes without writes then explicitly applies with zero synthesis fallback", async () => { const root = await fixture(); const actions = service(root); const provider = new FrontendProvider(); const base = { method: "POST", authorization: "Bearer valid", workspaceRepository: workspaces(), businessOsRepository: business(), aiProvider: provider, frontendSourceActions: actions }; const proposed = await request("/api/v1/workspaces/averon/emmy/messages", { ...base, requestId: "source-acceptance", body: { message: "Increase the desktop gap between the homepage hero buttons slightly." } }); assert.equal(proposed.payload.data.finalStatus, "completed"); assert.equal(provider.calls, 1); assert.match(await readFile(join(root, edit.path), "utf8"), /gap: 16px/); const action = proposed.payload.data.action as { actionId: string; status: string }; assert.equal(action.status, "approval_required"); const applied = await request("/api/v1/workspaces/averon/emmy/messages", { ...base, requestId: "source-apply", body: { message: `Apply source proposal ${action.actionId}` } }); assert.equal(applied.payload.data.finalStatus, "completed"); assert.equal(provider.calls, 1); assert.match(await readFile(join(root, edit.path), "utf8"), /gap: 20px/); assert.equal((applied.payload.data.action as { verificationStatus: string }).verificationStatus, "passed"); });

test("production follow-up resolves the pending conversation proposal and applies without another specialist or proposal", async () => { const root = await fixture(); let validationRuns = 0; const actions = new FrontendSourceActionService(new WorkspaceAuthorizationService(workspaces()), { async run() { validationRuns += 1; return [{ name: "typecheck", passed: true }, { name: "lint", passed: true }, { name: "test", passed: true }, { name: "build", passed: true }]; } }, root); const provider = new FrontendProvider(); const base = { method: "POST", authorization: "Bearer valid", workspaceRepository: workspaces(), businessOsRepository: business(), aiProvider: provider, frontendSourceActions: actions }; const prepareMessage = "Increase the horizontal spacing between the homepage hero action buttons slightly on desktop. Do not change mobile spacing or any other part of the homepage. Prepare the change for review."; const prepared = await request("/api/v1/workspaces/averon/emmy/messages", { ...base, requestId: "followup-proposal", body: { message: prepareMessage } }); const preparedAction = prepared.payload.data.action as { actionId: string }; const preparedReply = String(prepared.payload.data.reply); assert.equal(provider.calls, 1); assert.match(await readFile(join(root, edit.path), "utf8"), /gap: 16px/); const applied = await request("/api/v1/workspaces/averon/emmy/messages", { ...base, requestId: "followup-apply", body: { message: "Apply the proposed homepage hero button spacing change.", history: [{ role: "user", content: prepareMessage }, { role: "assistant", content: preparedReply }] } }); assert.equal(applied.payload.data.finalStatus, "completed"); assert.equal((applied.payload.data.action as { actionId: string }).actionId, preparedAction.actionId); assert.equal(provider.calls, 1); assert.equal(validationRuns, 1); assert.equal(await actions.get("followup-apply:frontend.source.propose"), undefined); assert.match(await readFile(join(root, edit.path), "utf8"), /gap: 20px/); });

test("natural apply variants resolve one pending proposal while missing and ambiguous history fail closed", async () => { for (const phrase of ["Apply that proposal", "Apply the proposed change"]) { const root = await fixture(); const actions = service(root); const proposal = await actions.propose(auth, `variant-${phrase.replaceAll(" ", "-")}`, "averon", [edit]); const provider = new FrontendProvider(); const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", requestId: `request-${proposal.actionId}`, body: { message: phrase, history: [{ role: "assistant", content: `Frontend source proposal prepared\nProposal ID: ${proposal.actionId}` }] }, workspaceRepository: workspaces(), businessOsRepository: business(), aiProvider: provider, frontendSourceActions: actions }); assert.equal(result.payload.data.finalStatus, "completed", phrase); assert.equal(provider.calls, 0, phrase); }
  const missingRoot = await fixture(); const missingProvider = new FrontendProvider(); const missing = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", body: { message: "Apply the proposed change", history: [] }, workspaceRepository: workspaces(), businessOsRepository: business(), aiProvider: missingProvider, frontendSourceActions: service(missingRoot) }); assert.equal(missing.payload.data.finalStatus, "failed"); assert.match(String(missing.payload.data.reply), /SOURCE_PROPOSAL_NOT_FOUND/); assert.equal(missingProvider.calls, 0); assert.match(await readFile(join(missingRoot, edit.path), "utf8"), /gap: 16px/);
  const ambiguousRoot = await fixture(); const ambiguousActions = service(ambiguousRoot); const first = await ambiguousActions.propose(auth, "ambiguous-first", "averon", [edit]); const second = await ambiguousActions.propose(auth, "ambiguous-second", "averon", [{ path: edit.path, find: "display: flex;", replace: "display: inline-flex;" }]); const ambiguousProvider = new FrontendProvider(); const ambiguous = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", body: { message: "Apply that proposal", history: [{ role: "assistant", content: `Proposal ID: ${first.actionId}` }, { role: "assistant", content: `Proposal ID: ${second.actionId}` }] }, workspaceRepository: workspaces(), businessOsRepository: business(), aiProvider: ambiguousProvider, frontendSourceActions: ambiguousActions }); assert.equal(ambiguous.payload.data.finalStatus, "failed"); assert.match(String(ambiguous.payload.data.reply), /SOURCE_PROPOSAL_AMBIGUOUS/); assert.equal(ambiguousProvider.calls, 0); assert.match(await readFile(join(ambiguousRoot, edit.path), "utf8"), /gap: 16px/); });

test("proposal mentions and prior proposal history cannot authorize apply without a current apply command", () => { const history = [{ role: "assistant" as const, content: "Proposal ID: prior-action:frontend.source.propose" }]; for (const message of ["What does that proposal change?", "Show me the proposed change", "Is the proposal ready?"]) assert.notEqual(frontendSourceIntent(message, history).action, "apply", message); });

test("explicit durable proposal ID takes precedence over multiple pending history proposals", async () => {
  for (const selected of ["5779dac3-bf7c-4517-adec-caaead0e6a41:frontend.source.propose", "b3b17f9b-653a-491f-94cd-ad3c74af19b4:frontend.source.propose"]) {
    const root = await fixture(); let validationRuns = 0;
    const actions = new FrontendSourceActionService(new WorkspaceAuthorizationService(workspaces()), { async run() { validationRuns += 1; return [{ name: "typecheck", passed: true }, { name: "lint", passed: true }, { name: "test", passed: true }, { name: "build", passed: true }]; } }, root);
    const firstId = "5779dac3-bf7c-4517-adec-caaead0e6a41:frontend.source.propose"; const secondId = "b3b17f9b-653a-491f-94cd-ad3c74af19b4:frontend.source.propose";
    await actions.propose(auth, firstId, "averon", [edit]);
    await actions.propose(auth, secondId, "averon", [{ path: edit.path, find: "display: flex;", replace: "display: inline-flex;" }]);
    const provider = new FrontendProvider();
    const intent = frontendSourceIntent(`Apply frontend source proposal ${selected}.`, [{ role: "assistant", content: `Proposal ID: ${firstId}\nProposal ID: ${secondId}` }]);
    assert.equal(intent.action, "apply"); assert.equal(intent.proposalId, selected); assert.deepEqual(intent.historyProposalIds, []);
    const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", body: { message: `Apply frontend source proposal ${selected}.`, history: [{ role: "assistant", content: `Proposal ID: ${firstId}\nProposal ID: ${secondId}` }] }, workspaceRepository: workspaces(), businessOsRepository: business(), aiProvider: provider, frontendSourceActions: actions });
    assert.equal(result.payload.data.finalStatus, "completed"); assert.equal((result.payload.data.action as { actionId: string }).actionId, selected); assert.equal(provider.calls, 0); assert.equal(validationRuns, 1);
    assert.equal((await actions.get(selected))?.status, "completed"); assert.equal((await actions.get(selected === firstId ? secondId : firstId))?.status, "proposed");
  }
});

test("explicit proposal IDs fail closed when malformed missing cross-workspace or multiple", async () => {
  const malformed = frontendSourceIntent("Apply frontend source proposal definitely-not-valid."); assert.equal(malformed.action, "apply"); assert.equal(malformed.proposalResolutionError, "SOURCE_PROPOSAL_INVALID");
  const multiple = frontendSourceIntent("Apply frontend source proposal first:frontend.source.propose and second:frontend.source.propose."); assert.equal(multiple.proposalResolutionError, "SOURCE_PROPOSAL_AMBIGUOUS");
  const root = await fixture(); const actions = service(root); const provider = new FrontendProvider(); const base = { method: "POST", authorization: "Bearer valid", workspaceRepository: workspaces(), businessOsRepository: business(), aiProvider: provider, frontendSourceActions: actions };
  const malformedResult = await request("/api/v1/workspaces/averon/emmy/messages", { ...base, body: { message: "Apply frontend source proposal definitely-not-valid." } }); assert.equal(malformedResult.payload.data.finalStatus, "failed"); assert.match(String(malformedResult.payload.data.reply), /SOURCE_PROPOSAL_INVALID/);
  const multipleResult = await request("/api/v1/workspaces/averon/emmy/messages", { ...base, body: { message: "Apply frontend source proposal first:frontend.source.propose and second:frontend.source.propose." } }); assert.equal(multipleResult.payload.data.finalStatus, "failed"); assert.match(String(multipleResult.payload.data.reply), /SOURCE_PROPOSAL_AMBIGUOUS/);
  const nonexistent = await request("/api/v1/workspaces/averon/emmy/messages", { ...base, body: { message: "Apply frontend source proposal missing:frontend.source.propose." } }); assert.equal(nonexistent.payload.data.finalStatus, "failed"); assert.match(String(nonexistent.payload.data.reply), /SOURCE_PROPOSAL_NOT_FOUND/);
  await actions.propose(auth, "foreign:frontend.source.propose", "other-workspace", [edit]).catch(() => undefined);
  const repository = new MemoryFrontendSourceProposalRepository(); const authorization = new WorkspaceAuthorizationService(workspaces()); const foreignActions = new FrontendSourceActionService(authorization, { async run() { return []; } }, root, repository); await repository.save({ actionId: "foreign:frontend.source.propose", workspaceId: "other-workspace", status: "proposed", approvalStatus: "not_required", highRisk: false, files: [], diff: "" });
  const crossWorkspace = await request("/api/v1/workspaces/averon/emmy/messages", { ...base, frontendSourceActions: foreignActions, body: { message: "Apply frontend source proposal foreign:frontend.source.propose." } }); assert.equal(crossWorkspace.payload.data.finalStatus, "failed"); assert.match(String(crossWorkspace.payload.data.reply), /SOURCE_PROPOSAL_NOT_FOUND/); assert.equal(provider.calls, 0);
});

test("specialist failure prevents proposal and ordinary synthesis fallback", async () => { const root = await fixture(); const provider: AiProvider = { async generate() { throw new Error("fixture provider failure"); } }; const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", requestId: "source-specialist-failure", body: { message: "Increase the desktop gap between the homepage hero buttons slightly." }, workspaceRepository: workspaces(), businessOsRepository: business(), aiProvider: provider, frontendSourceActions: service(root) }); assert.equal(result.payload.data.finalStatus, "failed"); assert.match(String(result.payload.data.reply), /ACTION_SPECIALIST_NOT_COMPLETED/); assert.match(await readFile(join(root, edit.path), "utf8"), /gap: 16px/); });
