import assert from "node:assert/strict";
import test from "node:test";
import type { AuthContext } from "../src/services/auth/authentication.ts";
import type { GuardianCheckResult, GuardianWebsite } from "@averon/shared-types";
import { DefaultAgentRegistry } from "../src/ai/agents/registry.ts";
import { SkillRegistry } from "../src/ai/agents/skills.ts";
import { AgentReadinessEngine } from "../src/ai/agents/readiness.ts";
import { TaskPlanner } from "../src/ai/agents/planner.ts";
import { AiDiagnosticsStore } from "../src/ai/diagnostics/diagnostics.store.ts";
import { MemoryWorkspaceRepository, request } from "./http-harness.ts";
import { WorkspaceAuthorizationService } from "../src/domains/workspaces/workspace.service.ts";
import { MemoryGuardianRepository } from "../src/domains/guardian/guardian.repository.ts";
import { GuardianService, RegisteredWebsiteHttpInspector, guardianCheckCapabilities, guardianSeverity, initialGuardianWebsites, validateGuardianTarget } from "../src/domains/guardian/guardian.service.ts";
import { handleGuardianRoute } from "../src/domains/guardian/guardian.routes.ts";
import { MemoryWorkspaceTaskRepository } from "../src/domains/workspace-tasks/workspace-task.repository.ts";
import { WorkspaceTaskService } from "../src/domains/workspace-tasks/workspace-task.service.ts";
import { GuardianBrowserInspector, guardianBrowserLimits, installGuardianFormSubmissionGuard, isExpectedDomLifecycleArtifact, isExpectedInspectionCancellation, isGuardianReadMethod, isReportableResourceFailure, type BrowserRouteObservation, type GuardianBrowserDriver } from "../src/domains/guardian/guardian.browser.ts";

const auth = { user: { userId: "user-1", role: "owner" } } as AuthContext;
function workspaces() { return new WorkspaceAuthorizationService(new MemoryWorkspaceRepository({ businesses: [{ id: "averon", name: "Averon", slug: "averon", status: "active" }, { id: "lumora", name: "Lumora", slug: "lumora", status: "active" }], workspaces: [{ id: "averon", businessId: "averon", name: "Averon", slug: "averon", status: "active" }, { id: "lumora", businessId: "lumora", name: "Lumora", slug: "lumora", status: "active" }], memberships: [{ id: "m1", userId: "user-1", workspaceId: "averon", businessId: "averon", role: "owner", status: "active" }] })); }
const website = (patch: Partial<GuardianWebsite> = {}): GuardianWebsite => ({ id: "averon-website", workspaceId: "averon", name: "Averon", baseUrl: "https://averon.example", enabled: true, environment: "test", importantRoutes: ["/", "/services"], checks: ["AVAILABILITY", "ROUTES", "ASSETS", "LINKS", "UI_SMOKE", "RUNTIME", "FORMS", "API_HEALTH", "RESPONSIVE"], createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z", ...patch });
function setup(results: GuardianCheckResult[]) { const repository = new MemoryGuardianRepository(); repository.saveWebsite(website()); const diagnostics = new AiDiagnosticsStore(); return { repository, diagnostics, service: new GuardianService(repository, workspaces(), { async inspect() { return structuredClone(results); } }, diagnostics) }; }

test("Guardian is the certified sixteenth read-only specialist with authoritative skills and Chat routing", () => {
  const agents = new DefaultAgentRegistry(); const guardian = agents.get("guardian")!; assert.equal(agents.list().length, 16); assert.deepEqual(guardian.executionRights, ["read", "analyze", "draft", "recommend"]); assert.deepEqual(guardian.skills, ["website.health_check", "website.health_report"]); assert.equal(guardian.certification.certificationStatus, "passed"); assert.equal(new AgentReadinessEngine(agents, new SkillRegistry(), { availableProviders: ["ai.text_generation"], availableTools: [], availableModelCapabilities: ["structured_output"] }).evaluate(guardian).status, "READY"); for (const prompt of ["Guardian, check Averon.", "Run a health review on Movento.", "Check Lumora for broken pages."]) { assert.deepEqual(new TaskPlanner().capabilities(prompt).requiredSkills, ["website.health_check"], prompt); assert.deepEqual(new TaskPlanner().plan(prompt).tasks.map((item) => item.agentId), ["guardian"]); }
});

test("initial registry never guesses URLs and advertises the bounded browser checks", () => { const sites = initialGuardianWebsites({ AVERON_WEBSITE_URL: "https://averon.example" }); assert.deepEqual(sites.map((item) => item.workspaceId), ["averon", "movento", "lumora"]); assert.equal(sites[0]?.baseUrl, "https://averon.example"); assert.equal(sites[1]?.baseUrl, undefined); assert.equal(sites[2]?.baseUrl, undefined); assert.equal(guardianCheckCapabilities.RUNTIME, "SUPPORTED"); assert.equal(guardianCheckCapabilities.RESPONSIVE, "SUPPORTED"); });

const publicResolver = async () => ["93.184.216.34"];
test("registered-origin inspector passes healthy routes and reports unsupported checks", async () => { const inspector = new RegisteredWebsiteHttpInspector(async () => new Response("ok", { status: 200 }), publicResolver); const results = await inspector.inspect(website({ importantRoutes: ["/services"], healthEndpoint: "/health" })); assert.equal(results.filter((item) => item.status === "PASS").length, 3); assert.equal(results.find((item) => item.kind === "RUNTIME")?.status, "NOT_CHECKED"); });

test("Guardian target validation denies local private malformed credentialed non-http and unregistered targets", async () => { const denied = ["http://localhost", "http://127.4.5.6", "http://10.1.2.3", "http://172.31.2.3", "http://192.168.2.3", "http://169.254.169.254", "http://[::1]", "http://[fd00::1]", "http://[fe80::1]", "file:///tmp/x", "https://user:secret@averon.example", "https://evil.example"]; for (const value of denied) await assert.rejects(() => validateGuardianTarget(value, "https://averon.example", async (host) => host === "averon.example" ? ["93.184.216.34"] : [host.replaceAll("[", "").replaceAll("]", "")]), (error: { code?: string }) => error.code === "GUARDIAN_TARGET_DENIED", value); await assert.rejects(() => validateGuardianTarget("not a url", "https://averon.example", publicResolver), (error: { code?: string }) => error.code === "GUARDIAN_TARGET_DENIED"); for (const resolved of ["10.0.0.8", "::ffff:127.0.0.1", "::ffff:7f00:1"]) await assert.rejects(() => validateGuardianTarget("https://averon.example", "https://averon.example", async () => [resolved]), (error: { code?: string }) => error.code === "GUARDIAN_TARGET_DENIED", resolved); });

test("redirect handling follows bounded same-origin redirects and fails every unsafe redirect shape", async () => { let calls = 0; const same = new RegisteredWebsiteHttpInspector(async () => ++calls === 1 ? new Response(null, { status: 302, headers: { location: "/ready" } }) : new Response("ok", { status: 200 }), publicResolver); const passed = await same.inspect(website({ importantRoutes: [], checks: ["AVAILABILITY"] })); assert.equal(passed[0]?.status, "PASS"); for (const location of ["https://evil.example", "http://127.0.0.1", "http://%", "::bad"] ) { const inspector = new RegisteredWebsiteHttpInspector(async () => new Response(null, { status: 302, headers: { location } }), publicResolver); assert.equal((await inspector.inspect(website({ importantRoutes: [], checks: ["AVAILABILITY"] })))[0]?.status, "FAIL", location); } const loop = new RegisteredWebsiteHttpInspector(async () => new Response(null, { status: 302, headers: { location: "/" } }), publicResolver); assert.equal((await loop.inspect(website({ importantRoutes: [], checks: ["AVAILABILITY"] })))[0]?.reason, "GUARDIAN_REDIRECT_LOOP"); let next = 0; const excessive = new RegisteredWebsiteHttpInspector(async () => new Response(null, { status: 302, headers: { location: `/r${++next}` } }), publicResolver, 2); assert.equal((await excessive.inspect(website({ importantRoutes: [], checks: ["AVAILABILITY"] })))[0]?.reason, "GUARDIAN_REDIRECT_INVALID"); });

test("HTTP outcome policy never turns timeout network 404 or 500 into PASS", async () => { const timeout = new RegisteredWebsiteHttpInspector(async () => { const error = new Error("timeout"); error.name = "TimeoutError"; throw error; }, publicResolver); assert.equal((await timeout.inspect(website({ importantRoutes: [], checks: ["AVAILABILITY"] })))[0]?.reason, "GUARDIAN_TIMEOUT"); const network = new RegisteredWebsiteHttpInspector(async () => { throw new Error("offline"); }, publicResolver); assert.equal((await network.inspect(website({ importantRoutes: [], checks: ["AVAILABILITY"] })))[0]?.status, "FAIL"); const statuses = [404, 500]; for (const status of statuses) { const inspector = new RegisteredWebsiteHttpInspector(async () => new Response(null, { status }), publicResolver); assert.equal((await inspector.inspect(website({ importantRoutes: status === 404 ? ["/missing"] : [], healthEndpoint: status === 500 ? "/health" : undefined, checks: status === 404 ? ["ROUTES"] : ["API_HEALTH"] }))).some((item) => item.status === "FAIL"), true); } });

test("healthy, unavailable, route, asset, and unsupported results produce durable reports and normal Diagnostics", async () => { const results: GuardianCheckResult[] = [{ kind: "AVAILABILITY", status: "PASS", summary: "Available" }, { kind: "ROUTES", status: "FAIL", target: "/contact", summary: "Route failed", evidence: { statusCode: 500, signature: "http-500" } }, { kind: "ASSETS", status: "FAIL", target: "/logo.png", summary: "Asset failed", evidence: { statusCode: 404, signature: "http-404" } }, { kind: "RUNTIME", status: "NOT_CHECKED", summary: "Unavailable", reason: "CAPABILITY_NOT_SUPPORTED" }]; const { repository, diagnostics, service } = setup(results); const report = await service.inspect(auth, "averon", "averon-website", "run-1"); assert.equal(report.status, "DEGRADED"); assert.equal(report.sourceChangesPerformed, false); assert.deepEqual(report.checks.map((item) => item.status), ["PASS", "FAIL", "FAIL", "NOT_CHECKED"]); assert.equal((await repository.getReport("averon", report.reportId))?.reportId, report.reportId); const diagnostic = await diagnostics.get("run-1"); assert.deepEqual(diagnostic?.selectedAgentIds, ["guardian"]); assert.equal(diagnostic?.providerCalls, 0); assert.equal((await repository.listFindings("averon", "averon-website")).length, 2); });

test("severity is deterministic across MINOR MODERATE MAJOR and CRITICAL", () => { assert.equal(guardianSeverity("ASSETS", "http-404"), "MINOR"); assert.equal(guardianSeverity("FORMS", "submit-failed"), "MODERATE"); assert.equal(guardianSeverity("RUNTIME", "authentication-widespread"), "MAJOR"); assert.equal(guardianSeverity("AVAILABILITY", "production-outage"), "CRITICAL"); });

test("repeated observations update one open finding and link Runs without mutation", async () => { const failed: GuardianCheckResult[] = [{ kind: "ROUTES", status: "FAIL", target: "/contact", summary: "Route failed", evidence: { signature: "http-500" } }]; const { repository, service } = setup(failed); await service.inspect(auth, "averon", "averon-website", "run-1"); await service.inspect(auth, "averon", "averon-website", "run-2"); const findings = await repository.listFindings("averon", "averon-website"); assert.equal(findings.length, 1); assert.equal(findings[0]?.occurrenceCount, 2); assert.deepEqual(findings[0]?.linkedRunIds, ["run-1", "run-2"]); assert.equal(findings[0]?.status, "OPEN"); });

test("findings create one canonical human-controlled Task and never auto-start it", async () => { const { repository, diagnostics, service } = setup([{ kind: "ROUTES", status: "FAIL", target: "/contact", summary: "Route failed", evidence: { signature: "http-500" } }]); const tasks = new MemoryWorkspaceTaskRepository(); service.setTaskService(new WorkspaceTaskService(tasks, workspaces(), undefined, diagnostics)); await service.inspect(auth, "averon", "averon-website", "run-task-1"); await service.inspect(auth, "averon", "averon-website", "run-task-2"); const [finding] = await repository.listFindings("averon", "averon-website"); const listed = await tasks.list("averon"); assert.equal(listed.length, 1); assert.equal(listed[0]?.id, finding?.maintenanceTaskId); assert.equal(listed[0]?.status, "TODO"); assert.equal(listed[0]?.linkedRunIds.length, 0); assert.equal(listed[0]?.linkedActionIds.length, 0); });

test("concurrent repeated findings converge on one deterministic Task identity", async () => { const { diagnostics, service } = setup([{ kind: "API_HEALTH", status: "FAIL", target: "/health", summary: "Health failed", evidence: { signature: "http-500" } }]); const tasks = new MemoryWorkspaceTaskRepository(); service.setTaskService(new WorkspaceTaskService(tasks, workspaces(), undefined, diagnostics)); await Promise.all([service.inspect(auth, "averon", "averon-website", "parallel-1"), service.inspect(auth, "averon", "averon-website", "parallel-2")]); const listed = await tasks.list("averon"); assert.equal(listed.length, 1); assert.equal(listed[0]?.status, "TODO"); });

test("a finding not seen in the next run remains open but is marked not observed", async () => { const repository = new MemoryGuardianRepository(); await repository.saveWebsite(website()); let results: GuardianCheckResult[] = [{ kind: "ROUTES", status: "FAIL", target: "/contact", summary: "Route failed", evidence: { signature: "http-500" } }]; const service = new GuardianService(repository, workspaces(), { async inspect() { return structuredClone(results); } }); await service.inspect(auth, "averon", "averon-website", "run-1"); results = [{ kind: "ROUTES", status: "PASS", target: "/contact", summary: "Route passed" }]; await service.inspect(auth, "averon", "averon-website", "run-2"); const [finding] = await repository.listFindings("averon", "averon-website"); assert.equal(finding?.status, "OPEN"); assert.equal(finding?.observedInLatestRun, false); });

test("authenticated Guardian routes expose only canonical workspace-scoped data", async () => { const { service } = setup([{ kind: "AVAILABILITY", status: "PASS", summary: "Available" }]); const created = await handleGuardianRoute({ method: "POST", path: "/api/v1/workspaces/averon/guardian/websites/averon-website/inspections", auth, requestId: "run-route", service }); assert.equal(created?.status, 201); const report = await handleGuardianRoute({ method: "GET", path: "/api/v1/workspaces/averon/guardian/reports/guardian-report-run-route", auth, requestId: "read", service }); assert.equal(report?.status, 200); const findings = await handleGuardianRoute({ method: "GET", path: "/api/v1/workspaces/averon/guardian/websites/averon-website/findings", auth, requestId: "read", service }); assert.deepEqual((findings?.data as { items: unknown[] }).items, []); await assert.rejects(() => handleGuardianRoute({ method: "GET", path: "/api/v1/workspaces/lumora/guardian/websites", auth, requestId: "cross", service }), (error: { code?: string }) => error.code === "WORKSPACE_ACCESS_DENIED"); });

test("configuration and target failures settle as durable report and Diagnostics with matching outcomes", async () => { for (const configured of [website({ baseUrl: undefined }), website({ baseUrl: "not-a-url" }), website({ baseUrl: "http://127.0.0.1" })]) { const repository = new MemoryGuardianRepository(); await repository.saveWebsite(configured); const diagnostics = new AiDiagnosticsStore(); const service = new GuardianService(repository, workspaces(), new RegisteredWebsiteHttpInspector(async () => new Response("unexpected"), publicResolver), diagnostics); const runId = `failure-${configured.baseUrl ?? "missing"}`; const report = await service.inspect(auth, "averon", configured.id, runId); const diagnostic = await diagnostics.get(runId); assert.equal(Boolean(report.checks.some((item) => item.status === "PASS")), false); assert.equal(diagnostic?.guardianExecution?.reportId, report.reportId); assert.equal(diagnostic?.guardianExecution?.websiteId, configured.id); assert.deepEqual(diagnostic?.guardianExecution?.checks.map((item) => item.status), report.checks.map((item) => item.status)); } });

test("Private Emmy routes unconfigured Guardian checks to durable configuration-required reports with zero provider calls", async () => { for (const [workspaceId, name, prompt] of [["averon", "Averon", "Guardian, check Averon."], ["movento", "Movento", "Run a health review on Movento."], ["lumora", "Lumora", "Check Lumora for broken pages."]] as const) { const repository = new MemoryGuardianRepository(); let providerCalls = 0; const result = await request(`/api/v1/workspaces/${workspaceId}/emmy/messages`, { method: "POST", authorization: "Bearer valid", requestId: `chat-${workspaceId}`, body: { message: prompt, history: [] }, aiProvider: { async generate() { providerCalls += 1; return { text: "should not run" }; } }, guardianRepository: repository, workspaceRepository: new MemoryWorkspaceRepository({ businesses: [{ id: workspaceId, name, slug: workspaceId, status: "active" }], workspaces: [{ id: workspaceId, businessId: workspaceId, name, slug: workspaceId, status: "active" }], memberships: [{ id: `m-${workspaceId}`, userId: "user-1", workspaceId, businessId: workspaceId, role: "owner", status: "active" }] }) }); assert.equal(result.status, 200); assert.match(String(result.payload.data.reply), /CONFIGURATION_REQUIRED/); assert.match(String(result.payload.data.reply), /No source changes were performed/); assert.equal(providerCalls, 0); assert.equal((await repository.getReport(workspaceId, `guardian-report-chat-${workspaceId}`))?.status, "CONFIGURATION_REQUIRED"); } });

test("website and report reads are workspace isolated", async () => { const { repository, service } = setup([{ kind: "AVAILABILITY", status: "PASS", summary: "Available" }]); await service.inspect(auth, "averon", "averon-website", "run-1"); await assert.rejects(() => service.inspect(auth, "lumora", "averon-website", "run-x"), (error: { code?: string }) => error.code === "WORKSPACE_ACCESS_DENIED"); assert.equal(await repository.getReport("lumora", "guardian-report-run-1"), null); });

test("Automations preserve CREATE_TASK-only and Guardian never gains repair authority", () => { const guardian = new DefaultAgentRegistry().get("guardian")!; assert.equal(guardian.executionRights.includes("prepare_action"), false); assert.equal(guardian.executionRights.includes("execute_reversible"), false); assert.equal(JSON.stringify(guardian).match(/deploy|publish|delete/i), null); });

function observation(route: string, viewport: "desktop" | "mobile", patch: Partial<BrowserRouteObservation> = {}): BrowserRouteObservation { return { route, viewport, rendered: true, hasMainContent: true, horizontalOverflow: false, internalLinks: [], failedResources: [], runtimeErrors: [], formCount: 0, formControls: 0, ...patch }; }

test("browser inspection is depth-one, same-origin, bounded, responsive, and never submits forms", async () => {
  const calls: Array<{ url: string; viewport: string }> = []; let closed = 0; const submissions = 0;
  const driver: GuardianBrowserDriver = { async inspect(url, _origin, viewport) { calls.push({ url: url.toString(), viewport }); if (url.pathname === "/") return observation("/", viewport, { internalLinks: Array.from({ length: 20 }, (_, index) => `/route-${index}`), formCount: 1, formControls: 3 }); return observation(url.pathname, viewport); }, async close() { closed += 1; } };
  const results = await new GuardianBrowserInspector(async () => driver, publicResolver).inspect(website({ importantRoutes: [], checks: ["ASSETS", "LINKS", "UI_SMOKE", "RUNTIME", "FORMS", "RESPONSIVE"] }));
  assert.equal(calls.length, guardianBrowserLimits.maximumRoutes * 2); assert.equal(new Set(calls.map((item) => new URL(item.url).origin)).size, 1); assert.deepEqual(new Set(calls.map((item) => item.viewport)), new Set(["desktop", "mobile"])); assert.equal(results.every((item) => item.status === "PASS"), true); assert.equal(submissions, 0); assert.equal(closed, 1);
});

test("browser inspection reports broken assets links runtime blank pages and overflow without mutation", async () => {
  const driver: GuardianBrowserDriver = { async inspect(url, _origin, viewport) { return observation(url.pathname, viewport, { rendered: url.pathname !== "/broken", hasMainContent: url.pathname !== "/blank", horizontalOverflow: viewport === "mobile", internalLinks: url.pathname === "/" ? ["/broken", "/blank"] : [], failedResources: url.pathname === "/" ? [{ url: "/missing.png", statusCode: 404 }] : [], runtimeErrors: url.pathname === "/" ? ["Uncaught application failure"] : [], formCount: 1, formControls: 2 }); }, async close() {} };
  const results = await new GuardianBrowserInspector(async () => driver, publicResolver).inspect(website({ importantRoutes: [], checks: ["ASSETS", "LINKS", "UI_SMOKE", "RUNTIME", "FORMS", "RESPONSIVE"] }));
  for (const kind of ["ASSETS", "LINKS", "UI_SMOKE", "RUNTIME", "RESPONSIVE"] as const) assert.equal(results.some((item) => item.kind === kind && item.status === "FAIL"), true, kind); assert.equal(results.find((item) => item.kind === "FORMS")?.status, "PASS"); assert.equal(results.some((item) => item.evidence?.viewport === "mobile"), true);
});

test("unavailable browser and denied targets remain truthful and do not attempt inspection", async () => {
  let calls = 0; const unavailable = await new GuardianBrowserInspector(async () => { throw new Error("missing"); }, publicResolver).inspect(website({ checks: ["UI_SMOKE", "RESPONSIVE"] })); assert.deepEqual(unavailable.map((item) => item.status), ["NOT_CHECKED", "NOT_CHECKED"]); assert.equal(unavailable.every((item) => item.reason === "GUARDIAN_BROWSER_UNAVAILABLE"), true);
  const denied = await new GuardianBrowserInspector(async () => ({ async inspect() { calls += 1; return observation("/", "desktop"); }, async close() {} }), async () => ["127.0.0.1"]).inspect(website({ checks: ["UI_SMOKE"] })); assert.equal(denied[0]?.status, "NOT_CHECKED"); assert.equal(denied[0]?.reason, "GUARDIAN_TARGET_DENIED"); assert.equal(calls, 0);
});

test("browser route failure settles through the canonical report and Diagnostics instead of escaping", async () => {
  const browser = new GuardianBrowserInspector(async () => ({ async inspect() { throw new Error("browser route failed"); }, async close() {} }), publicResolver); const { repository, diagnostics } = setup([]); const composite = new GuardianService(repository, workspaces(), browser, diagnostics); const report = await composite.inspect(auth, "averon", "averon-website", "browser-failure-run"); const diagnostic = await diagnostics.get("browser-failure-run"); assert.equal(report.status === "HEALTHY", false); assert.equal(report.checks.some((item) => item.status === "FAIL"), true); assert.equal(diagnostic?.guardianExecution?.reportId, report.reportId);
});

test("browser session has a hard deadline and settles truthfully", async () => {
  let closed = false; const browser = new GuardianBrowserInspector(async () => ({ async inspect() { return new Promise<BrowserRouteObservation>(() => undefined); }, async close() { closed = true; } }), publicResolver, 5); const started = Date.now(); const results = await browser.inspect(website({ importantRoutes: [], checks: ["UI_SMOKE", "RUNTIME"] })); assert.equal(Date.now() - started < 100, true); assert.equal(closed, true); assert.equal(results.every((item) => item.status === "NOT_CHECKED" && item.reason === "GUARDIAN_BROWSER_SESSION_TIMEOUT"), true);
});

test("browser ignores cancelled prefetches and Guardian deduplicates identical failures within one Run", async () => {
  assert.equal(isReportableResourceFailure("fetch", "net::ERR_ABORTED"), false); assert.equal(isReportableResourceFailure("image", "net::ERR_ABORTED"), false); assert.equal(isReportableResourceFailure("image", "net::ERR_FAILED"), true);
  const duplicate: GuardianCheckResult = { kind: "ASSETS", status: "FAIL", target: "/missing.png", summary: "Missing", evidence: { signature: "http-404", viewport: "desktop", route: "/" } }; const { repository, service } = setup([duplicate, duplicate]); const report = await service.inspect(auth, "averon", "averon-website", "dedupe-run"); assert.equal(report.findingIds.length, 1); assert.equal((await repository.listFindings("averon", "averon-website")).length, 1);
});

test("browser lifecycle cancellations are inspector artifacts while genuine driver and page errors remain failures", async () => {
  for (const caught of [Object.assign(new Error("page.goto: net::ERR_ABORTED; maybe frame was detached"), { name: "AbortError" }), new Error("Target page, context or browser has been closed"), new Error("Navigation interrupted by another one")]) assert.equal(isExpectedInspectionCancellation(caught), true);
  assert.equal(isExpectedInspectionCancellation(new Error("Uncaught application failure")), false);
  const cancelled = new GuardianBrowserInspector(async () => ({ async inspect() { throw new Error("Target page, context or browser has been closed"); }, async close() {} }), publicResolver);
  const cancelledResults = await cancelled.inspect(website({ importantRoutes: [], checks: ["UI_SMOKE", "RUNTIME"] }));
  assert.equal(cancelledResults.every((item) => item.status === "NOT_CHECKED" && item.reason === "GUARDIAN_INSPECTION_CANCELLED"), true);
  const failed = new GuardianBrowserInspector(async () => ({ async inspect() { throw new Error("genuine driver failure"); }, async close() {} }), publicResolver);
  assert.equal((await failed.inspect(website({ importantRoutes: [], checks: ["UI_SMOKE"] })))[0]?.status, "FAIL");
  const runtime = new GuardianBrowserInspector(async () => ({ async inspect() { return observation("/", "desktop", { runtimeErrors: ["Uncaught application failure"] }); }, async close() {} }), publicResolver);
  assert.equal((await runtime.inspect(website({ importantRoutes: [], checks: ["RUNTIME"] })))[0]?.status, "FAIL");
});

test("browser request policy permits only GET and HEAD and blocked mutations are not resource defects", () => {
  assert.equal(isGuardianReadMethod("GET"), true); assert.equal(isGuardianReadMethod("head"), true);
  for (const method of ["POST", "PUT", "PATCH", "DELETE", "OPTIONS", "CONNECT", "CUSTOM"]) assert.equal(isGuardianReadMethod(method), false, method);
  assert.equal(isReportableResourceFailure("fetch", "net::ERR_BLOCKED_BY_CLIENT"), false);
  assert.equal(isReportableResourceFailure("image", "net::ERR_FAILED"), true);
});

test("form submission guard prevents events and disables submit and requestSubmit", () => {
  const previousDocument = globalThis.document; const previousForm = globalThis.HTMLFormElement; let listener: ((event: { preventDefault(): void; stopImmediatePropagation(): void }) => void) | undefined;
  class FakeForm { submit() { throw new Error("submitted"); } requestSubmit() { throw new Error("submitted"); } }
  Object.assign(globalThis, { document: { addEventListener(type: string, callback: typeof listener, capture: boolean) { assert.equal(type, "submit"); assert.equal(capture, true); listener = callback; } }, HTMLFormElement: FakeForm });
  try { installGuardianFormSubmissionGuard(); let prevented = 0; let stopped = 0; listener?.({ preventDefault() { prevented += 1; }, stopImmediatePropagation() { stopped += 1; } }); assert.equal(prevented, 1); assert.equal(stopped, 1); new FakeForm().submit(); new FakeForm().requestSubmit(); }
  finally { Object.assign(globalThis, { document: previousDocument, HTMLFormElement: previousForm }); }
});

test("missing API health endpoint has a truthful NOT_CHECKED reason", async () => {
  const results = await new RegisteredWebsiteHttpInspector(async () => new Response("ok", { status: 200 }), publicResolver).inspect(website({ importantRoutes: [], healthEndpoint: undefined, checks: ["AVAILABILITY", "API_HEALTH"] }));
  const health = results.find((item) => item.kind === "API_HEALTH"); assert.equal(health?.status, "NOT_CHECKED"); assert.equal(health?.reason, "HEALTH_ENDPOINT_NOT_CONFIGURED");
});

test("inner DOM evaluation distinguishes Guardian cleanup from real DOM and page failures", () => {
  const closed = new Error("page.evaluate: Target page, context or browser has been closed");
  assert.equal(isExpectedDomLifecycleArtifact(closed, { pageClosed: true, browserConnected: true }), true);
  assert.equal(isExpectedDomLifecycleArtifact(closed, { pageClosed: false, browserConnected: false }), true);
  assert.equal(isExpectedDomLifecycleArtifact(closed, { pageClosed: false, browserConnected: true }), false);
  assert.equal(isExpectedDomLifecycleArtifact(new Error("DOM evaluation failed while page remained active"), { pageClosed: false, browserConnected: true }), false);
  assert.equal(isExpectedDomLifecycleArtifact(new Error("Page crashed"), { pageClosed: true, browserConnected: true }), false);
});

test("Guardian cleanup interruption produces no failed checks findings or Tasks", async () => {
  const browser = new GuardianBrowserInspector(async () => ({ async inspect() { throw new Error("Target page, context or browser has been closed"); }, async close() {} }), publicResolver);
  const repository = new MemoryGuardianRepository(); await repository.saveWebsite(website({ importantRoutes: [], checks: ["LINKS", "UI_SMOKE", "RUNTIME", "RESPONSIVE"] })); const tasks = new MemoryWorkspaceTaskRepository(); const diagnostics = new AiDiagnosticsStore(); const service = new GuardianService(repository, workspaces(), browser, diagnostics); service.setTaskService(new WorkspaceTaskService(tasks, workspaces(), undefined, diagnostics));
  const report = await service.inspect(auth, "averon", "averon-website", "cleanup-artifact-run");
  assert.equal(report.checks.every((item) => item.status === "NOT_CHECKED"), true); assert.deepEqual(report.findingIds, []); assert.deepEqual(await repository.listFindings("averon", "averon-website"), []); assert.deepEqual(await tasks.list("averon"), []);
});
