import assert from "node:assert/strict";
import test from "node:test";
import { AVERON_PUBLIC_PAGE_CONTENT } from "@averon/shared-types";
import type { AiProvider } from "../src/ai/providers/ai-provider.ts";
import { buildPageContentPatch, pageContentIntent, parsePageContentPatch } from "../src/domains/page-content/page-content.actions.ts";
import { MemoryBusinessOsRepository, MemoryPageContentRepository, MemoryWorkspaceRepository, request } from "./http-harness.ts";
const workspace = (role: "owner" | "member" = "owner") => new MemoryWorkspaceRepository({ businesses: [{ id: "averon", name: "Averon", slug: "averon", status: "active" }], workspaces: [{ id: "averon", businessId: "averon", name: "Averon", slug: "averon", status: "active" }], memberships: [{ id: "averon__user-1", userId: "user-1", workspaceId: "averon", businessId: "averon", role, status: "active" }] });
const business = () => { const repo = new MemoryBusinessOsRepository(); repo.roots.set("averon", { workspaceId: "averon", businessId: "averon", status: "active", schemaVersion: 1 }); return repo; };
class Provider implements AiProvider { requests: unknown[] = []; fail = false; async generate(input: unknown) { this.requests.push(input); if (this.fail) throw new Error("provider failed"); return { text: JSON.stringify({ schemaVersion: "marketing.v1", agentId: "marketing", taskId: "task-1-marketing", status: "completed", summary: "Reviewed copy", output: { findings: ["Existing copy reviewed"], recommendations: ["Clearer canonical copy"], risks: [], assumptions: [], missingInformation: [] }, warnings: [], missingInformation: [] }) }; } }
test("intent requires current-turn mutation and history only resolves an explicit target", () => { assert.equal(pageContentIntent("What does the homepage hero currently say?").explicit, false); assert.equal(pageContentIntent("Change it to “Clearer copy”", [{ role: "user", content: "Review the homepage hero" }]).pageId, "home"); assert.equal(pageContentIntent("summarize it", [{ role: "user", content: "Change the homepage hero" }]).explicit, false); });
test("payload adapter is partial and rejects unknown unsafe or oversized fields", () => { assert.deepEqual(parsePageContentPatch("hero", { heading: "Safe" }), { heading: "Safe" }); for (const value of [{ unknown: "x" }, { heading: "<script>x</script>" }, { heading: "x".repeat(501) }]) assert.throws(() => parsePageContentPatch("hero", value)); assert.deepEqual(buildPageContentPatch("Change the homepage hero heading to “New heading”", "hero", {}), { heading: "New heading" }); });
test("direct canonical read uses zero provider calls and mutations", async () => { const repository = new MemoryPageContentRepository(Object.values(AVERON_PUBLIC_PAGE_CONTENT)); const provider = new Provider(); const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", body: { message: "What does the homepage hero currently say?" }, workspaceRepository: workspace(), businessOsRepository: business(), pageContentRepository: repository, aiProvider: provider }); assert.equal(result.payload.data.finalStatus, "completed"); assert.equal(provider.requests.length, 0); assert.equal(repository.writes, 0); });
test("production update runs Marketing once, preserves unrelated content, verifies and is idempotent", async () => { const repository = new MemoryPageContentRepository(Object.values(AVERON_PUBLIC_PAGE_CONTENT)); const provider = new Provider(); const options = { method: "POST", authorization: "Bearer valid", requestId: "content-update", body: { message: "Change the homepage hero heading to “A smarter future starts here.”" }, workspaceRepository: workspace(), businessOsRepository: business(), pageContentRepository: repository, aiProvider: provider }; const before = await repository.get("averon", "home"); const first = await request("/api/v1/workspaces/averon/emmy/messages", options); const after = await repository.get("averon", "home"); assert.equal(first.payload.data.finalStatus, "completed"); assert.equal(repository.writes, 1); assert.equal(provider.requests.length, 1); assert.equal(after?.sections.find((item) => item.sectionId === "hero")?.fields.heading, "A smarter future starts here."); assert.equal(after?.sections.find((item) => item.sectionId === "hero")?.fields.subheading, before?.sections.find((item) => item.sectionId === "hero")?.fields.subheading); assert.deepEqual(after?.sections.find((item) => item.sectionId === "primaryCta"), before?.sections.find((item) => item.sectionId === "primaryCta")); await request("/api/v1/workspaces/averon/emmy/messages", options); assert.equal(repository.writes, 1); assert.equal((first.payload.data.action as { verificationStatus: string }).verificationStatus, "passed"); });
test("CTA and service-description targets resolve and update exact allowlisted fields", async () => { const repository = new MemoryPageContentRepository(Object.values(AVERON_PUBLIC_PAGE_CONTENT)); for (const [id, message, pageId, sectionId, field, value] of [["cta", "Replace the homepage CTA label with “See our work”", "home", "primaryCta", "label", "See our work"], ["service", "Update the AI Solutions service description on the services page to “Practical AI systems for growing teams.”", "services", "aiSolutions", "description", "Practical AI systems for growing teams."]] as const) { const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", requestId: id, body: { message }, workspaceRepository: workspace(), businessOsRepository: business(), pageContentRepository: repository, aiProvider: new Provider() }); assert.equal(result.payload.data.finalStatus, "completed"); assert.equal((await repository.get("averon", pageId))?.sections.find((item) => item.sectionId === sectionId)?.fields[field], value); } });
test("advisory ambiguous denied specialist and verification failures produce no verified success", async () => { for (const scenario of ["advisory", "ambiguous", "denied", "specialist", "verification"] as const) { const repository = new MemoryPageContentRepository(Object.values(AVERON_PUBLIC_PAGE_CONTENT)); if (scenario === "verification") repository.corruptReadBack = true; const provider = new Provider(); if (scenario === "specialist") provider.fail = true; const message = scenario === "advisory" ? "How could we improve the homepage hero?" : scenario === "ambiguous" ? "Change the heading to “New”" : "Change the homepage hero heading to “New”"; const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", requestId: scenario, body: { message }, workspaceRepository: workspace(scenario === "denied" ? "member" : "owner"), businessOsRepository: business(), pageContentRepository: repository, aiProvider: provider }); if (scenario === "advisory") assert.equal(repository.writes, 0); else { assert.equal(result.payload.data.finalStatus, "failed", scenario); assert.doesNotMatch(String(result.payload.data.reply), /updated successfully/i); } } });
test("multi-field hero update changes only requested fields in one mutation", async () => { const repository = new MemoryPageContentRepository(Object.values(AVERON_PUBLIC_PAGE_CONTENT)); const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", requestId: "multi", body: { message: "Change the homepage hero heading to “New heading” and subheading to “New supporting line”" }, workspaceRepository: workspace(), businessOsRepository: business(), pageContentRepository: repository, aiProvider: new Provider() }); const content = await repository.get("averon", "home"); assert.equal(result.payload.data.finalStatus, "completed"); assert.equal(repository.writes, 1); assert.deepEqual(content?.sections.find((item) => item.sectionId === "hero")?.fields, { heading: "New heading", subheading: "New supporting line" }); });
test("unknown pages sections fields and script payloads fail closed", () => { assert.deepEqual(pageContentIntent("Change the unknown page banner heading to “X”"), { action: "update", explicit: true, pageId: undefined, sectionId: undefined }); for (const [sectionId, patch] of [["missing", { heading: "x" }], ["hero", { title: "x" }], ["hero", { heading: "<img onerror=alert(1)>" }]] as const) assert.throws(() => parsePageContentPatch(sectionId, patch)); });
