import assert from "node:assert/strict";
import test from "node:test";
import { ApiError } from "../src/errors/api-error.ts";
import type { PaymentRepository } from "../src/domains/payments/payment.repository.ts";
import { PaymentService } from "../src/domains/payments/payment.service.ts";
import type { PaymentEvent, TrustedInvoice } from "../src/domains/payments/payment.types.ts";
import type { PaymentProvider } from "../src/providers/payments/stripe/stripe.adapter.ts";
import { emptyPaymentProvider, emptyPaymentRepository, request } from "./http-harness.ts";

const invoice: TrustedInvoice = { invoiceId: "invoice-1", contractId: "contract-1", customerId: "user-1", projectReference: "AVR-1", title: "Deposit", amountCents: 25000, currency: "eur", status: "issued" };
function repository(overrides: Partial<PaymentRepository> = {}): PaymentRepository { return { ...emptyPaymentRepository, async getInvoice() { return invoice; }, ...overrides }; }

test("valid unpaid invoice creates checkout from trusted values", async () => {
  let received: TrustedInvoice | undefined; const provider: PaymentProvider = { ...emptyPaymentProvider, async createCheckout(value) { received = value; return { id: "cs_1", url: "https://checkout.test/1" }; } };
  const result = await new PaymentService(repository(), provider, "https://averon.test").createCheckout("invoice-1", "user-1");
  assert.equal(received?.amountCents, 25000); assert.equal(result.checkoutReference, "cs_1");
});
test("checkout HTTP route rejects unauthenticated request", async () => { const response = await request("/api/v1/payments/checkout", { method: "POST", body: { invoiceId: "invoice-1" } }); assert.equal(response.status, 401); });
test("invoice ownership is enforced", async () => { await assert.rejects(() => new PaymentService(repository(), emptyPaymentProvider, "https://averon.test").createCheckout("invoice-1", "other"), (error: ApiError) => error.code === "PAYMENT_NOT_ALLOWED"); });
test("already-paid invoice is rejected", async () => { await assert.rejects(() => new PaymentService(repository({ async getInvoice() { return { ...invoice, status: "paid" }; } }), emptyPaymentProvider, "https://averon.test").createCheckout("invoice-1", "user-1"), (error: ApiError) => error.code === "INVOICE_ALREADY_PAID"); });
test("client amount injection is rejected", async () => { const response = await request("/api/v1/payments/checkout", { method: "POST", authorization: "Bearer valid", body: { invoiceId: "invoice-1", amountCents: 1 } }); assert.equal(response.payload.error.code, "UNKNOWN_FIELDS"); });
test("invalid invoice ID is rejected", async () => { const response = await request("/api/v1/payments/checkout", { method: "POST", authorization: "Bearer valid", body: { invoiceId: "bad id" } }); assert.equal(response.payload.error.code, "INVALID_ID"); });
test("provider failure remains a stable API error", async () => { const provider: PaymentProvider = { ...emptyPaymentProvider, async createCheckout() { throw new ApiError(502, "CHECKOUT_CREATION_FAILED", "Unable"); } }; await assert.rejects(() => new PaymentService(repository(), provider, "https://averon.test").createCheckout("invoice-1", "user-1"), (error: ApiError) => error.code === "CHECKOUT_CREATION_FAILED"); });
test("open checkout is reused", async () => { const provider: PaymentProvider = { ...emptyPaymentProvider, async getCheckout() { return { id: "cs_existing", url: "https://checkout.test/existing", reusable: true }; } }; const result = await new PaymentService(repository({ async getInvoice() { return { ...invoice, checkoutReference: "cs_existing" }; } }), provider, "https://averon.test").createCheckout("invoice-1", "user-1"); assert.equal(result.reused, true); });
test("webhook rejects missing signature", async () => { const response = await request("/api/v1/webhooks/stripe", { method: "POST", body: {} }); assert.equal(response.payload.error.code, "INVALID_WEBHOOK_SIGNATURE"); });
test("webhook rejects invalid signature", async () => { const provider: PaymentProvider = { ...emptyPaymentProvider, verifyWebhook() { throw new ApiError(400, "INVALID_WEBHOOK_SIGNATURE", "Invalid"); } }; const response = await request("/api/v1/webhooks/stripe", { method: "POST", body: {}, headers: { "stripe-signature": "bad" }, paymentProvider: provider }); assert.equal(response.payload.error.code, "INVALID_WEBHOOK_SIGNATURE"); });
test("verified webhook event reaches reconciliation", async () => { let event: PaymentEvent | undefined; const repo = repository({ async reconcile(value) { event = value; return "processed"; } }); const provider: PaymentProvider = { ...emptyPaymentProvider, verifyWebhook() { return { eventId: "evt_1", type: "paid", checkoutReference: "cs_1", invoiceId: "invoice-1", contractId: "contract-1", customerId: "user-1", amountCents: 25000, currency: "eur" }; } }; const response = await request("/api/v1/webhooks/stripe", { method: "POST", body: {}, headers: { "stripe-signature": "valid" }, paymentRepository: repo, paymentProvider: provider }); assert.equal(response.status, 200); assert.equal(event?.type, "paid"); });
test("unknown verified event is acknowledged", async () => { const response = await request("/api/v1/webhooks/stripe", { method: "POST", body: {}, headers: { "stripe-signature": "valid" } }); assert.equal(response.status, 200); assert.equal(response.payload.data.result, "ignored"); });
test("duplicate event result is acknowledged without repeated effects", async () => { const repo = repository({ async reconcile() { return "duplicate"; } }); const provider: PaymentProvider = { ...emptyPaymentProvider, verifyWebhook() { return { eventId: "evt_duplicate", type: "paid", checkoutReference: "cs_1", invoiceId: "invoice-1" }; } }; const response = await request("/api/v1/webhooks/stripe", { method: "POST", body: {}, headers: { "stripe-signature": "valid" }, paymentRepository: repo, paymentProvider: provider }); assert.equal(response.payload.data.result, "duplicate"); });
test("amount mismatch prevents successful reconciliation", async () => { const repo = repository({ async reconcile() { throw new ApiError(409, "PAYMENT_AMOUNT_MISMATCH", "Investigation required"); } }); const provider: PaymentProvider = { ...emptyPaymentProvider, verifyWebhook() { return { eventId: "evt_amount", type: "paid" }; } }; const response = await request("/api/v1/webhooks/stripe", { method: "POST", body: {}, headers: { "stripe-signature": "valid" }, paymentRepository: repo, paymentProvider: provider }); assert.equal(response.status, 409); assert.equal(response.payload.error.code, "PAYMENT_AMOUNT_MISMATCH"); });
test("currency mismatch prevents successful reconciliation", async () => { const repo = repository({ async reconcile() { throw new ApiError(409, "PAYMENT_AMOUNT_MISMATCH", "Investigation required"); } }); const provider: PaymentProvider = { ...emptyPaymentProvider, verifyWebhook() { return { eventId: "evt_currency", type: "paid" }; } }; const response = await request("/api/v1/webhooks/stripe", { method: "POST", body: {}, headers: { "stripe-signature": "valid" }, paymentRepository: repo, paymentProvider: provider }); assert.equal(response.payload.error.code, "PAYMENT_AMOUNT_MISMATCH"); });
test("failed and expired events are passed to provider-neutral reconciliation", async () => { const seen: string[] = []; const repo = repository({ async reconcile(event) { seen.push(event.type); return "processed"; } }); for (const type of ["failed", "expired"] as const) { const provider: PaymentProvider = { ...emptyPaymentProvider, verifyWebhook() { return { eventId: `evt_${type}`, type }; } }; await request("/api/v1/webhooks/stripe", { method: "POST", body: {}, headers: { "stripe-signature": "valid" }, paymentRepository: repo, paymentProvider: provider }); } assert.deepEqual(seen, ["failed", "expired"]); });
