import assert from "node:assert/strict";
import test from "node:test";
import type { AiProvider, AiProviderRequest } from "../src/ai/providers/ai-provider.ts";
import { assertExplicitActionResolved, parseStructuredEnvelope, selectBusinessOsSections } from "../src/ai/emmy/private-emmy.ts";
import { InMemoryRateLimitStore, RateLimiter } from "../src/ai/emmy/rate-limiter.ts";
import { MemoryBlogDraftRepository, MemoryBusinessOsRepository, MemoryWorkspaceRepository, request } from "./http-harness.ts";
import type { BlogDraft, WorkspaceRole } from "@averon/shared-types";
import { AiDiagnosticsStore } from "../src/ai/diagnostics/diagnostics.store.ts";
import { ApiError } from "../src/errors/api-error.ts";
import { ActionDiagnosticsStore, explicitBlogDraftIntent } from "../src/domains/blog-drafts/blog-draft.actions.ts";

function workspaces(role: WorkspaceRole = "member") { return new MemoryWorkspaceRepository({ businesses: [{ id: "averon", name: "Averon Technologies", slug: "averon", status: "active" }, { id: "other", name: "Other", slug: "other", status: "active" }], workspaces: [{ id: "averon", businessId: "averon", name: "Averon Technologies", slug: "averon", status: "active" }, { id: "other", businessId: "other", name: "Other", slug: "other", status: "active" }], memberships: [{ id: "m1", userId: "user-1", workspaceId: "averon", businessId: "averon", role, status: "active" }] }); }
function businessOs() { const repository = new MemoryBusinessOsRepository(); repository.roots.set("averon", { workspaceId: "averon", businessId: "averon", status: "active", schemaVersion: 1 }); for (const [id, visibility] of [["public", "public"], ["internal", "internal"], ["restricted", "restricted"]] as const) repository.sections.set(`averon/${id}`, { id, type: "pricing", title: id, content: { summary: `${id} fact`, fields: {} }, visibility, status: "active", version: 1, workspaceId: "averon", businessId: "averon", updatedBy: "user-1" }); return repository; }
class CaptureProvider implements AiProvider { requests: AiProviderRequest[] = []; async generate(input: AiProviderRequest) { this.requests.push(input); return { text: "Private answer" }; } }
class SequenceProvider implements AiProvider { requests: AiProviderRequest[] = []; constructor(values: string[]) { this.values = values; } private readonly values: string[]; async generate(input: AiProviderRequest) { this.requests.push(input); const text = this.values.shift(); if (text === "THROW") throw new Error("failure"); const agentId = input.observability?.agentId; if (agentId) { const taskId = (JSON.parse(input.messages[0].content) as { task?: { taskId?: string } }).task?.taskId ?? `task-${agentId}`; const outputs: Record<string, unknown> = { research: { findings: ["Finding"], knownFacts: ["Fact"], informationGaps: [], externalResearchRequired: false, recommendations: ["Recommendation"] }, seo: { targetIntent: "informational", suggestedKeywords: ["moving to Rome"], titleSuggestions: [], metaDescriptionSuggestions: [], contentOutline: [], limitations: [] }, blog: { title: "Article", summary: "Summary", body: "Draft", suggestedSlug: "article", callToAction: "Learn more", assumptions: [], missingInformation: [] }, documentation: { title: "SOP", purpose: "Purpose", sections: [{ heading: "Step", content: "Content" }], actionItems: [], unresolvedItems: [] }, marketing: { findings: ["Finding"], recommendations: ["Recommendation"], risks: [], assumptions: [], missingInformation: [] } }; return { text: JSON.stringify({ schemaVersion: `${agentId}.v1`, agentId, taskId, status: "completed", summary: "Ready", output: outputs[agentId], warnings: [], missingInformation: [] }) }; } return { text: text ?? "Final Emmy answer" }; } }
class UpdateProvider implements AiProvider {
  requests: AiProviderRequest[] = [];
  private readonly failAgent?: "seo" | "blog";
  constructor(failAgent?: "seo" | "blog") { this.failAgent = failAgent; }
  async generate(input: AiProviderRequest) {
    this.requests.push(input); const agentId = input.observability?.agentId;
    if (agentId === this.failAgent) throw new Error(`${agentId} failed`);
    const taskId = (JSON.parse(input.messages[0].content) as { task?: { taskId?: string } }).task?.taskId ?? `task-${agentId}`;
    const output = agentId === "seo"
      ? { targetIntent: "informational", suggestedKeywords: ["AI automation"], titleSuggestions: ["AI Automation for Small Businesses: A Practical Guide"], metaDescriptionSuggestions: ["A practical guide to using AI automation to improve small-business efficiency."], contentOutline: [], limitations: [] }
      : { title: "AI Automation for Small Businesses: A Practical Guide to Improving Efficiency", summary: "A practical efficiency guide.", body: "Updated guide with a stronger call to action: contact Averon to plan your automation roadmap.", suggestedSlug: "ai-automation-small-business-practical-guide", callToAction: "Contact Averon to plan your automation roadmap.", assumptions: [], missingInformation: [] };
    return { text: JSON.stringify({ schemaVersion: `${agentId}.v1`, agentId, taskId, status: "completed", summary: "Ready", output, warnings: [], missingInformation: [] }) };
  }
}
class MalformedBlogProvider extends UpdateProvider { override async generate(input: AiProviderRequest) { if (input.observability?.agentId === "blog") { this.requests.push(input); return { text: "{}" }; } return super.generate(input); } }
function seedDraft(repository: MemoryBlogDraftRepository, id = "PIelFZHRQ3lFtSBqAbDT") { const now = new Date(0).toISOString(); const draft: BlogDraft = { id, workspaceId: "averon", businessId: "averon", title: "Original", slug: "original", excerpt: "Original excerpt", body: "Original body", metaDescription: "Original metadata", status: "draft", published: false, createdBy: "user-1", updatedBy: "user-1", createdAt: now, updatedAt: now }; repository.drafts.set(id, draft); return draft; }

test("private Emmy requires authentication and workspace membership", async () => { assert.equal((await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", body: { message: "Hello" } })).status, 401); assert.equal((await request("/api/v1/workspaces/other/emmy/messages", { method: "POST", authorization: "Bearer valid", body: { message: "Hello" }, workspaceRepository: workspaces() })).status, 403); });
test("private contract rejects client workspace and permission fields", async () => { for (const extra of [{ workspaceId: "other" }, { permissions: ["admin"] }, { role: "owner" }]) { const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", body: { message: "Hello", ...extra }, workspaceRepository: workspaces(), businessOsRepository: businessOs() }); assert.equal(result.status, 400); } });
test("unsupported and unresolved mutations fail closed before providers and persist the canonical decision", async () => {
  for (const [requestId, message, code, kind] of [["unsupported", "Delete draft ABC12345.", "ACTION_NOT_SUPPORTED", "UNSUPPORTED"], ["unresolved", "Change it and make it better.", "TARGET_UNRESOLVED", "CLARIFICATION_REQUIRED"]] as const) {
    const provider = new CaptureProvider(); const diagnostics = new AiDiagnosticsStore();
    const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", requestId, body: { message }, workspaceRepository: workspaces(), businessOsRepository: businessOs(), aiProvider: provider, aiDiagnostics: diagnostics });
    const saved = await diagnostics.get(requestId);
    assert.equal(result.payload.data.finalStatus, "failed");
    assert.match(String(result.payload.data.reply), new RegExp(code));
    assert.equal(provider.requests.length, 0);
    assert.equal(saved?.requestDecision?.kind, kind);
    assert.deepEqual(saved?.errorCodes, [code]);
    assert.equal(saved?.providerCalls, 0);
  }
});
test("private Emmy uses bounded deterministic section selection", () => { const first = selectBusinessOsSections("pricing campaign SEO operations roadmap sales policy service"); assert.deepEqual(first, selectBusinessOsSections("pricing campaign SEO operations roadmap sales policy service")); assert.ok(first.length <= 6); assert.deepEqual(first.slice(0, 3), ["profile", "brand", "instructions"]); });
test("private Emmy extracts a valid embedded envelope without exposing surrounding provider text", () => {
  const envelope = parseStructuredEnvelope('Intro that must not be shown. {"reply":"Only this reply","claims":[]} trailing text');
  assert.deepEqual(envelope, { reply: "Only this reply", claims: [] });
});
test("explicit action branch invariant rejects ordinary synthesis bypass", () => { assert.throws(() => assertExplicitActionResolved({ explicit: true }), (caught: unknown) => caught instanceof ApiError && caught.code === "ACTION_PATH_BYPASSED"); assert.doesNotThrow(() => assertExplicitActionResolved({ explicit: false })); assert.doesNotThrow(() => assertExplicitActionResolved({ explicit: true }, "typed terminal action result")); });
test("synthesis extraction accepts harmless object representations and rejects non-objects", () => {
  const envelope = { reply: "Answer", claims: [] };
  assert.deepEqual(parseStructuredEnvelope(JSON.stringify(envelope)), envelope);
  assert.deepEqual(parseStructuredEnvelope(JSON.stringify(JSON.stringify(envelope))), envelope);
  assert.deepEqual(parseStructuredEnvelope(`\`\`\`json\n${JSON.stringify(envelope)}\n\`\`\``), envelope);
  for (const value of ["{", "plain text", "[]", "null"]) assert.equal(typeof parseStructuredEnvelope(value) === "object" && parseStructuredEnvelope(value) !== null && !Array.isArray(parseStructuredEnvelope(value)), false, value);
});
test("role visibility and the existing private Emmy permission are enforced", async () => { const viewerProvider = new CaptureProvider(); assert.equal((await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", body: { message: "What is our pricing?" }, workspaceRepository: workspaces("viewer"), businessOsRepository: businessOs(), aiProvider: viewerProvider })).status, 403); assert.equal(viewerProvider.requests.length, 0); for (const [role, visible, hidden] of [["member", ["public fact", "internal fact"], ["restricted fact"]], ["admin", ["public fact", "internal fact", "restricted fact"], []]] as const) { const provider = new CaptureProvider(); const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", body: { message: "What is our pricing?" }, workspaceRepository: workspaces(role), businessOsRepository: businessOs(), aiProvider: provider }); assert.equal(result.status, 200); for (const value of visible) assert.match(provider.requests[0].systemPrompt, new RegExp(value)); for (const value of hidden) assert.doesNotMatch(provider.requests[0].systemPrompt, new RegExp(value)); } });
test("private prompt is read-only, workspace-bound, and treats context as data", async () => { const provider = new CaptureProvider(); const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", body: { message: "What is our pricing?", history: [{ role: "assistant", content: "Earlier" }] }, workspaceRepository: workspaces(), businessOsRepository: businessOs(), aiProvider: provider }); assert.equal(result.payload.data.businessOsStatus, "ready"); assert.equal((result.payload.data.workspace as { id: string }).id, "averon"); assert.match(provider.requests[0].systemPrompt, /read-only/); assert.match(provider.requests[0].systemPrompt, /cannot call tools, agents, email, Altrex/); assert.equal(provider.requests[0].observability?.workspaceId, "averon"); assert.equal(provider.requests[0].messages.length, 2); });
test("uninitialized and empty Business OS are explicit safe states", async () => { for (const [repository, status] of [[new MemoryBusinessOsRepository(), "uninitialized"], [businessOs(), "empty"]] as const) { if (status === "empty") repository.sections.clear(); const provider = new CaptureProvider(); const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", body: { message: "What do we sell?" }, workspaceRepository: workspaces(), businessOsRepository: repository, aiProvider: provider }); assert.equal(result.status, 200); assert.equal(result.payload.data.businessOsStatus, status); assert.match(provider.requests[0].systemPrompt, /Never invent missing facts/); } });
test("private rate limiting is isolated by user and workspace", async () => { const limiter = new RateLimiter(new InMemoryRateLimitStore(), 1, 60_000, "PRIVATE_EMMY_RATE_LIMITED"); const options = { method: "POST", authorization: "Bearer valid", body: { message: "Hello" }, workspaceRepository: workspaces(), businessOsRepository: businessOs(), privateEmmyRateLimiter: limiter }; assert.equal((await request("/api/v1/workspaces/averon/emmy/messages", options)).status, 200); const rejected = await request("/api/v1/workspaces/averon/emmy/messages", options); assert.equal(rejected.status, 429); assert.equal(rejected.payload.error.code, "PRIVATE_EMMY_RATE_LIMITED"); });
test("public Emmy remains separate and rejects workspace injection", async () => { const provider = new CaptureProvider(); const result = await request("/api/v1/emmy/messages", { method: "POST", body: { message: "Hello", workspaceId: "averon" }, aiProvider: provider }); assert.equal(result.status, 400); assert.equal(provider.requests.length, 0); });
test("direct Business OS question uses only Emmy without a specialist", async () => { const provider = new SequenceProvider([JSON.stringify({ reply: "Direct answer", claims: [] })]); const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", body: { message: "What is our pricing?" }, workspaceRepository: workspaces(), businessOsRepository: businessOs(), aiProvider: provider }); assert.equal(result.status, 200); assert.equal(provider.requests.length, 1); assert.equal(provider.requests[0].observability?.operation, "direct"); });
test("private Emmy returns only the reply from a prose-wrapped structured response", async () => {
  const provider = new SequenceProvider(['Preface {"reply":"Visible answer","claims":[]} {not appended}']);
  const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", body: { message: "What is our pricing?" }, workspaceRepository: workspaces(), businessOsRepository: businessOs(), aiProvider: provider });
  assert.equal(result.payload.data.reply, "Emmy's structured response could not be validated. Please retry this request.");
  assert.doesNotMatch(String(result.payload.data.reply), /\{"reply"/);
});
test("private Emmy returns the reply from a valid embedded structured response", async () => {
  const provider = new SequenceProvider(['Preface {"reply":"Visible answer","claims":[]} trailing']);
  const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", body: { message: "What is our pricing?" }, workspaceRepository: workspaces(), businessOsRepository: businessOs(), aiProvider: provider });
  assert.equal(result.payload.data.reply, "Visible answer");
  assert.equal(result.payload.data.finalStatus, "completed");
});
test("invalid synthesis cannot be reported as a clean completed diagnostic", async () => {
  const diagnostics = new AiDiagnosticsStore(); const provider = new SequenceProvider(["Plain invalid synthesis", "Still invalid after repair"]);
  const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", requestId: "invalid-synthesis", body: { message: "What is our pricing?" }, workspaceRepository: workspaces(), businessOsRepository: businessOs(), aiProvider: provider, aiDiagnostics: diagnostics });
  const [diagnostic] = await diagnostics.list(); const objectRequired = { specialist: "emmy", stage: "synthesis" as const, path: "$", code: "SYNTHESIS_OBJECT_REQUIRED", repairable: true }; assert.equal(result.payload.data.finalStatus, "failed"); assert.equal(provider.requests.length, 2); assert.equal(diagnostic.finalStatus, "failed"); assert.equal(diagnostic.attributionValidation, "failed"); assert.deepEqual(diagnostic.errorCodes, ["SYNTHESIS_OBJECT_REQUIRED"]); assert.deepEqual(diagnostic.synthesisValidationIssues?.[0], objectRequired); assert.deepEqual(diagnostic.synthesisAttempts, [{ attempt: 1, validationStatus: "failed", validationIssues: [objectRequired] }, { attempt: 2, validationStatus: "failed", validationIssues: [objectRequired] }]);
});
test("zero-delta invalid specialist synthesis receives one strict validated retry", async () => {
  const diagnostics = new AiDiagnosticsStore(); const provider = new SequenceProvider(["worker-slot", "truncated synthesis", JSON.stringify({ reply: "Recovered valid reply", claims: [] })]);
  const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", requestId: "strict-synthesis-retry", body: { message: "Create a marketing strategy" }, workspaceRepository: workspaces(), businessOsRepository: businessOs(), aiProvider: provider, aiDiagnostics: diagnostics });
  const [diagnostic] = await diagnostics.list(); assert.equal(result.payload.data.reply, "Recovered valid reply"); assert.equal(result.payload.data.finalStatus, "completed"); assert.equal(provider.requests.length, 3); assert.equal(provider.requests[2].temperature, 0); assert.match(provider.requests[2].systemPrompt, /STRICT SYNTHESIS RETRY CONTRACT/); assert.equal(diagnostic.providerCalls, 3); assert.equal(diagnostic.attributionValidation, "valid"); assert.deepEqual(diagnostic.errorCodes, []); assert.deepEqual(diagnostic.synthesisAttempts, [{ attempt: 1, validationStatus: "failed", validationIssues: [{ specialist: "emmy", stage: "synthesis", path: "$", code: "SYNTHESIS_OBJECT_REQUIRED", repairable: true }] }, { attempt: 2, validationStatus: "valid", validationIssues: [] }]);
});
test("double-encoded valid synthesis is canonicalized without consuming repair", async () => {
  const envelope = JSON.stringify({ reply: "Recovered encoded reply", claims: [] }); const diagnostics = new AiDiagnosticsStore(); const provider = new SequenceProvider([JSON.stringify(envelope)]);
  const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", requestId: "encoded-synthesis", body: { message: "What is our pricing?" }, workspaceRepository: workspaces(), businessOsRepository: businessOs(), aiProvider: provider, aiDiagnostics: diagnostics });
  const [diagnostic] = await diagnostics.list(); assert.equal(result.payload.data.reply, "Recovered encoded reply"); assert.equal(provider.requests.length, 1); assert.deepEqual(diagnostic.synthesisAttempts, [{ attempt: 1, validationStatus: "valid", validationIssues: [] }]);
});
test("synthesis schema recovery is bounded and succeeds in five repeated direct runs", async () => { for (let run = 0; run < 5; run += 1) { const provider = new SequenceProvider(["truncated synthesis", JSON.stringify({ reply: `Recovered ${run + 1}`, claims: [] })]); const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", body: { message: "Summarize our supplied business profile" }, workspaceRepository: workspaces(), businessOsRepository: businessOs(), aiProvider: provider }); assert.equal(result.payload.data.reply, `Recovered ${run + 1}`); assert.equal(result.payload.data.finalStatus, "completed"); assert.equal(provider.requests.length, 2); assert.match(provider.requests[1].systemPrompt, /STRICT SYNTHESIS RETRY CONTRACT/); } });
test("Marketing and Research feed valid synthesis in five repeated deterministic runs", async () => { for (let run = 0; run < 5; run += 1) { const provider = new SequenceProvider(["research-slot", "marketing-slot", JSON.stringify({ reply: `GTM ${run + 1}`, claims: [] })]); const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", body: { message: "Research our internal positioning and create a marketing strategy" }, workspaceRepository: workspaces(), businessOsRepository: businessOs(), aiProvider: provider }); assert.equal(result.payload.data.finalStatus, "completed", `run ${run + 1}`); assert.equal(result.payload.data.reply, `GTM ${run + 1}`); assert.deepEqual(provider.requests.slice(0, 2).map((item) => item.observability?.agentId).sort(), ["marketing", "research"]); assert.equal(provider.requests[2].observability?.operation, "synthesis"); } });
test("SEO and documentation requests run an internal worker then one Emmy synthesis", async () => { for (const [message, agentId] of [["Recommend SEO keywords", "seo"], ["Create an internal SOP document", "documentation"]] as const) { const provider = new SequenceProvider(["worker-slot", JSON.stringify({ reply: "Final Emmy answer", claims: [] })]); const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", body: { message }, workspaceRepository: workspaces(), businessOsRepository: businessOs(), aiProvider: provider }); assert.equal(result.status, 200); assert.equal(provider.requests.length, 2); assert.equal(provider.requests[0].observability?.agentId, agentId); assert.equal(provider.requests[1].observability?.operation, "synthesis"); assert.match(provider.requests[1].systemPrompt, /Current-run validated specialist results/i); } });
test("combined advisory SEO blog request preserves dependency order and returns one visible reply", async () => { const provider = new SequenceProvider([JSON.stringify({ status: "completed", summary: "SEO ready", output: { keywords: ["moving to Rome"] } }), JSON.stringify({ status: "completed", summary: "Draft ready", output: { draft: "Article" } }), JSON.stringify({ reply: "One final draft", claims: [] })]); const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", body: { message: "What should an SEO-friendly blog article about moving to Rome include?" }, workspaceRepository: workspaces(), businessOsRepository: businessOs(), aiProvider: provider }); assert.equal(result.status, 200); assert.equal(result.payload.data.reply, "One final draft"); assert.deepEqual(provider.requests.slice(0, 2).map((item) => item.observability?.agentId), ["seo", "blog"]); assert.match(provider.requests[1].messages[0].content, /moving to Rome/); });
test("explicit validated blog request performs one verified unpublished action", async () => { const provider = new SequenceProvider(["worker-slot"]); const repository = new MemoryBlogDraftRepository(); const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", requestId: "emmy-create", body: { message: "Create an unpublished blog draft about safe automation" }, workspaceRepository: workspaces("owner"), businessOsRepository: businessOs(), blogDraftRepository: repository, aiProvider: provider }); assert.equal(result.status, 200); assert.equal(provider.requests.length, 1); assert.equal(repository.writes, 1); assert.match(String(result.payload.data.reply), /Draft created successfully/); assert.match(String(result.payload.data.reply), /Status: Unpublished/); assert.equal((result.payload.data.action as { verificationStatus: string }).verificationStatus, "passed"); assert.equal([...repository.drafts.values()][0].published, false); });
test("advisory blog request never writes and failed specialist output never writes", async () => { const advisoryRepository = new MemoryBlogDraftRepository(); const advisoryProvider = new SequenceProvider(["worker-slot", JSON.stringify({ reply: "Here are some ideas.", claims: [] })]); const advisory = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", body: { message: "What should we write about AI automation?" }, workspaceRepository: workspaces("owner"), businessOsRepository: businessOs(), blogDraftRepository: advisoryRepository, aiProvider: advisoryProvider }); assert.equal(advisory.status, 200); assert.equal(advisoryRepository.writes, 0); assert.ok(advisoryProvider.requests.length > 0); const failedRepository = new MemoryBlogDraftRepository(); const failedProvider = new SequenceProvider(["THROW", JSON.stringify({ reply: "The draft specialist failed.", claims: [] })]); const failed = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", body: { message: "Create an unpublished blog draft about AI automation" }, workspaceRepository: workspaces("owner"), businessOsRepository: businessOs(), blogDraftRepository: failedRepository, aiProvider: failedProvider }); assert.equal(failed.status, 200); assert.equal(failedRepository.writes, 0); assert.equal(failedProvider.requests.length, 1); });
test("required Critic failure prevents the blog action", async () => { const repository = new MemoryBlogDraftRepository(); const provider = new SequenceProvider(["blog", "critic-invalid", "critic-repair-invalid", JSON.stringify({ reply: "Verification did not pass.", claims: [] })]); const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", body: { message: "Create an unpublished blog draft about safe automation with independent verification" }, workspaceRepository: workspaces("owner"), businessOsRepository: businessOs(), blogDraftRepository: repository, aiProvider: provider }); assert.equal(result.status, 200); assert.equal(repository.writes, 0); });
test("production action bridge executes the live acceptance shape exactly once and returns verified metadata", async () => { const repository = new MemoryBlogDraftRepository(); const provider = new SequenceProvider(["seo", "blog"]); const message = "Create an unpublished blog draft for Averon Technologies about how AI automation can help small businesses improve efficiency. Optimize the title, structure, and metadata for SEO. Do not publish it."; const options = { method: "POST", authorization: "Bearer valid", requestId: "acceptance-action", body: { message }, workspaceRepository: workspaces("owner"), businessOsRepository: businessOs(), blogDraftRepository: repository, aiProvider: provider }; const first = await request("/api/v1/workspaces/averon/emmy/messages", options); assert.equal(provider.requests.length, 2); assert.equal(repository.writes, 1); assert.equal(repository.actions.size, 1); assert.equal(repository.drafts.size, 1); const draft = [...repository.drafts.values()][0]; assert.equal(draft.status, "draft"); assert.equal(draft.published, false); assert.match(String(first.payload.data.reply), new RegExp(draft.id)); assert.equal((first.payload.data.action as { actionId: string; status: string; verificationStatus: string; draftId: string }).actionId, "acceptance-action:blog.draft.create"); assert.equal((first.payload.data.action as { status: string }).status, "completed"); const second = await request("/api/v1/workspaces/averon/emmy/messages", options); assert.equal(second.status, 200); assert.equal(provider.requests.length, 4); assert.equal(repository.writes, 1); assert.equal(repository.actions.size, 1); assert.equal(repository.drafts.size, 1); });
test("artifact references and advisory language never become write intent", () => {
  for (const message of ["Give me a summary of what we accomplished with the blog draft today", "Summarize draft ABC12345", "Show me draft ABC12345", "What changed in draft ABC12345?", "How could we improve draft ABC12345?", "Explain the SEO changes", "Is the draft unpublished?", "What do you think about this article?", "Give me recommendations for this draft", "Do something better with it"]) assert.deepEqual(explicitBlogDraftIntent(message), { action: "none", explicit: false }, message);
  assert.deepEqual(explicitBlogDraftIntent("Create an unpublished draft about X"), { action: "create", explicit: true });
  assert.deepEqual(explicitBlogDraftIntent("Update draft ABC12345 and change its title"), { action: "update", explicit: true, draftId: "ABC12345" });
  assert.deepEqual(explicitBlogDraftIntent("Change the CTA", [{ role: "assistant", content: "Draft ID: PIelFZHRQ3lFtSBqAbDT" }]), { action: "update", explicit: true, draftId: "PIelFZHRQ3lFtSBqAbDT" });
});
test("production read-only turns create no actions writes drafts or write audits", async () => {
  const fixtures = [
    { message: "Give me a summary of what we accomplished with the blog draft today" },
    { message: "Summarize draft ABC12345" }, { message: "Show me draft ABC12345" }, { message: "What changed in draft ABC12345?" }, { message: "How could we improve draft ABC12345?" }, { message: "Do something better with it" },
    { message: "summarize it", history: [{ role: "user" as const, content: "Create an unpublished blog draft about X" }, { role: "assistant" as const, content: "Draft created successfully. Draft ID: PIelFZHRQ3lFtSBqAbDT" }] },
    { message: "what changed?", history: [{ role: "user" as const, content: "Update draft PIelFZHRQ3lFtSBqAbDT and change its title" }, { role: "assistant" as const, content: "Draft updated successfully" }] },
  ];
  for (const [index, fixture] of fixtures.entries()) {
    const repository = new MemoryBlogDraftRepository(); const diagnostics = new ActionDiagnosticsStore(); const provider = new SequenceProvider(Array(5).fill(JSON.stringify({ reply: "Read-only answer", claims: [] })));
    const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", requestId: `read-only-${index}`, body: fixture, workspaceRepository: workspaces("owner"), businessOsRepository: businessOs(), blogDraftRepository: repository, actionDiagnostics: diagnostics, aiProvider: provider });
    assert.equal(result.payload.data.action, undefined, fixture.message); assert.equal(repository.writes, 0, fixture.message); assert.equal(repository.actions.size, 0, fixture.message); assert.equal(repository.drafts.size, 0, fixture.message); assert.equal(diagnostics.list().length, 0, fixture.message);
    if (fixture.message === "summarize it") assert.equal(provider.requests[0]?.observability?.operation, "direct");
  }
});
test("production current-turn mutation remains explicit while history supplies only an update target", async () => {
  const createRepository = new MemoryBlogDraftRepository(); const create = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", requestId: "intent-create", body: { message: "Create an unpublished draft about X" }, workspaceRepository: workspaces("owner"), businessOsRepository: businessOs(), blogDraftRepository: createRepository, aiProvider: new SequenceProvider(["blog"]) }); assert.equal(create.payload.data.finalStatus, "completed"); assert.equal(createRepository.writes, 1); assert.equal(createRepository.drafts.size, 1);
  const updateRepository = new MemoryBlogDraftRepository(); seedDraft(updateRepository); const update = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", requestId: "intent-update", body: { message: "Update draft PIelFZHRQ3lFtSBqAbDT and change its title" }, workspaceRepository: workspaces("owner"), businessOsRepository: businessOs(), blogDraftRepository: updateRepository, aiProvider: new UpdateProvider() }); assert.equal(update.payload.data.finalStatus, "completed"); assert.equal(updateRepository.writes, 1); assert.equal(updateRepository.drafts.size, 1);
  const contextualRepository = new MemoryBlogDraftRepository(); seedDraft(contextualRepository); const contextual = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", requestId: "intent-context-update", body: { message: "Change the CTA", history: [{ role: "assistant", content: "The current unpublished draft has Draft ID: PIelFZHRQ3lFtSBqAbDT" }] }, workspaceRepository: workspaces("owner"), businessOsRepository: businessOs(), blogDraftRepository: contextualRepository, aiProvider: new UpdateProvider() }); assert.equal(contextual.payload.data.finalStatus, "completed"); assert.equal(contextualRepository.writes, 1); assert.equal(contextualRepository.drafts.size, 1); assert.match(contextualRepository.drafts.get("PIelFZHRQ3lFtSBqAbDT")?.body ?? "", /Contact Averon/);
});
test("explicit draft update injects mandatory Blog plus requested SEO and updates only its target", async () => {
  const repository = new MemoryBlogDraftRepository(); seedDraft(repository); const provider = new UpdateProvider();
  const message = "Update the unpublished draft PIelFZHRQ3lFtSBqAbDT. Change the title to “AI Automation for Small Businesses: A Practical Guide to Improving Efficiency”, strengthen the call to action, and improve the meta description for SEO. Keep it unpublished.";
  const options = { method: "POST", authorization: "Bearer valid", requestId: "update-action", body: { message }, workspaceRepository: workspaces("owner"), businessOsRepository: businessOs(), blogDraftRepository: repository, aiProvider: provider };
  const first = await request("/api/v1/workspaces/averon/emmy/messages", options); const updated = repository.drafts.get("PIelFZHRQ3lFtSBqAbDT")!;
  assert.deepEqual(provider.requests.map((item) => item.observability?.agentId), ["seo", "blog"]); assert.equal(provider.requests.filter((item) => item.observability?.operation === "synthesis").length, 0);
  assert.equal(first.payload.data.finalStatus, "completed"); assert.equal((first.payload.data.action as { draftId: string; verificationStatus: string }).draftId, "PIelFZHRQ3lFtSBqAbDT"); assert.equal((first.payload.data.action as { verificationStatus: string }).verificationStatus, "passed");
  assert.equal(repository.drafts.size, 1); assert.equal(repository.writes, 1); assert.equal(updated.id, "PIelFZHRQ3lFtSBqAbDT"); assert.equal(updated.title, "AI Automation for Small Businesses: A Practical Guide to Improving Efficiency"); assert.match(updated.body, /stronger call to action/i); assert.match(updated.metaDescription ?? "", /practical guide/i); assert.equal(updated.slug, "original"); assert.equal(updated.excerpt, "Original excerpt"); assert.equal(updated.workspaceId, "averon"); assert.equal(updated.businessId, "averon"); assert.equal(updated.createdAt, new Date(0).toISOString()); assert.equal(updated.createdBy, "user-1"); assert.equal(updated.status, "draft"); assert.equal(updated.published, false);
  const second = await request("/api/v1/workspaces/averon/emmy/messages", options); assert.equal(second.payload.data.finalStatus, "completed"); assert.equal(repository.drafts.size, 1); assert.equal(repository.writes, 1); assert.equal(repository.actions.size, 1);
});
test("explicit update failures remain typed and never write or synthesize", async () => {
  for (const [requestId, message, provider, warning] of [
    ["missing-target", "Update the unpublished draft and strengthen the CTA", new UpdateProvider(), "ACTION_TARGET_REQUIRED"],
    ["blog-failed", "Update draft PIelFZHRQ3lFtSBqAbDT and strengthen the CTA", new UpdateProvider("blog"), "ACTION_SPECIALIST_NOT_COMPLETED"],
    ["seo-failed", "Update draft PIelFZHRQ3lFtSBqAbDT and improve SEO metadata", new UpdateProvider("seo"), "ACTION_SPECIALIST_NOT_COMPLETED"],
  ] as const) {
    const repository = new MemoryBlogDraftRepository(); seedDraft(repository); const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", requestId, body: { message }, workspaceRepository: workspaces("owner"), businessOsRepository: businessOs(), blogDraftRepository: repository, aiProvider: provider });
    assert.equal(result.payload.data.finalStatus, "failed", requestId); assert.deepEqual((result.payload.data.action as { warnings: string[] }).warnings, [warning]); assert.equal(repository.writes, 0); assert.equal(repository.drafts.size, 1); assert.equal(provider.requests.filter((item) => item.observability?.operation === "synthesis").length, 0);
  }
});
test("production update failure paths never mutate or create a replacement draft", async () => {
  const message = "Update draft PIelFZHRQ3lFtSBqAbDT. Change the title, strengthen the CTA, and improve the meta description for SEO.";
  const cases: Array<{ name: string; repository: MemoryBlogDraftRepository; provider: AiProvider; role?: WorkspaceRole; expected: string; expectedWrites?: number }> = [];
  const malformed = new MemoryBlogDraftRepository(); seedDraft(malformed); cases.push({ name: "malformed specialist", repository: malformed, provider: new MalformedBlogProvider(), expected: "ACTION_SPECIALIST_NOT_COMPLETED" });
  const missing = new MemoryBlogDraftRepository(); cases.push({ name: "non-existent target", repository: missing, provider: new UpdateProvider(), expected: "BLOG_DRAFT_NOT_FOUND" });
  const wrongWorkspace = new MemoryBlogDraftRepository(); const wrong = seedDraft(wrongWorkspace); wrongWorkspace.drafts.set(wrong.id, { ...wrong, workspaceId: "other", businessId: "other" }); cases.push({ name: "wrong workspace", repository: wrongWorkspace, provider: new UpdateProvider(), expected: "BLOG_DRAFT_NOT_FOUND" });
  const published = new MemoryBlogDraftRepository(); const publishedDraft = seedDraft(published); published.drafts.set(publishedDraft.id, { ...publishedDraft, status: "draft", published: true }); cases.push({ name: "published target", repository: published, provider: new UpdateProvider(), expected: "ACTION_UNSUPPORTED" });
  const denied = new MemoryBlogDraftRepository(); seedDraft(denied); cases.push({ name: "authorization", repository: denied, provider: new UpdateProvider(), role: "member", expected: "ACTION_FORBIDDEN" });
  const mismatch = new MemoryBlogDraftRepository(); seedDraft(mismatch); mismatch.corruptReadBack = true; cases.push({ name: "verification mismatch", repository: mismatch, provider: new UpdateProvider(), expected: "ACTION_VERIFICATION_FAILED", expectedWrites: 1 });
  for (const fixture of cases) {
    const beforeSize = fixture.repository.drafts.size; const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", requestId: `failure-${fixture.name.replaceAll(" ", "-")}`, body: { message }, workspaceRepository: workspaces(fixture.role ?? "owner"), businessOsRepository: businessOs(), blogDraftRepository: fixture.repository, aiProvider: fixture.provider });
    assert.equal(result.payload.data.finalStatus, "failed", fixture.name); assert.deepEqual((result.payload.data.action as { warnings: string[] }).warnings, [fixture.expected], fixture.name); assert.equal(fixture.repository.writes, fixture.expectedWrites ?? 0, fixture.name); assert.equal(fixture.repository.drafts.size, beforeSize, fixture.name); assert.doesNotMatch(String(result.payload.data.reply), /updated successfully/i, fixture.name);
  }
});
test("advisory blog SEO guidance does not become an update action", async () => { const repository = new MemoryBlogDraftRepository(); seedDraft(repository); const provider = new SequenceProvider(["seo", "blog", JSON.stringify({ reply: "Advisory guidance", claims: [] })]); const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", requestId: "advisory-update", body: { message: "How could I improve this blog's SEO?" }, workspaceRepository: workspaces("owner"), businessOsRepository: businessOs(), blogDraftRepository: repository, aiProvider: provider }); assert.equal(result.payload.data.action, undefined); assert.equal(repository.writes, 0); });
test("explicit specialist success fails closed when the production action coordinator is unavailable", async () => { const provider = new SequenceProvider(["seo", "blog"]); const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", body: { message: "Create an unpublished SEO blog draft about automation. Do not publish it." }, workspaceRepository: workspaces("owner"), businessOsRepository: businessOs(), aiProvider: provider }); assert.equal(result.status, 200); assert.equal(provider.requests.length, 2); assert.equal(result.payload.data.finalStatus, "failed"); assert.match(String(result.payload.data.reply), /was not created or updated/); assert.doesNotMatch(String(result.payload.data.reply), /Draft created successfully/); assert.deepEqual((result.payload.data.action as { warnings: string[] }).warnings, ["ACTION_EXECUTOR_UNAVAILABLE"]); });
test("action authorization, execution, and verification failures never claim success", async () => { const message = "Create an unpublished blog draft about automation. Do not publish it."; const deniedRepository = new MemoryBlogDraftRepository(); const denied = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", body: { message }, workspaceRepository: workspaces("member"), businessOsRepository: businessOs(), blogDraftRepository: deniedRepository, aiProvider: new SequenceProvider(["blog"]) }); assert.equal(deniedRepository.writes, 0); assert.equal(denied.payload.data.finalStatus, "failed"); assert.doesNotMatch(String(denied.payload.data.reply), /created successfully/); class FailingRepository extends MemoryBlogDraftRepository { override async create(): Promise<never> { throw new ApiError(500, "ACTION_EXECUTION_FAILED", "failed"); } } const failedRepository = new FailingRepository(); const failed = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", body: { message }, workspaceRepository: workspaces("owner"), businessOsRepository: businessOs(), blogDraftRepository: failedRepository, aiProvider: new SequenceProvider(["blog"]) }); assert.equal(failedRepository.drafts.size, 0); assert.equal(failed.payload.data.finalStatus, "failed"); assert.doesNotMatch(String(failed.payload.data.reply), /created successfully/); const mismatchRepository = new MemoryBlogDraftRepository(); mismatchRepository.corruptReadBack = true; const mismatch = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", body: { message }, workspaceRepository: workspaces("owner"), businessOsRepository: businessOs(), blogDraftRepository: mismatchRepository, aiProvider: new SequenceProvider(["blog"]) }); assert.equal(mismatch.payload.data.finalStatus, "failed"); assert.match(String(mismatch.payload.data.reply), /ACTION_VERIFICATION_FAILED/); assert.doesNotMatch(String(mismatch.payload.data.reply), /created successfully/); });
test("analytics without data reports the gap through Emmy without fabricating a worker call", async () => { const repository = businessOs(); repository.sections.clear(); const provider = new SequenceProvider([JSON.stringify({ reply: "Please provide real metrics and a date range.", claims: [] })]); const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", body: { message: "Analyze our performance trends" }, workspaceRepository: workspaces(), businessOsRepository: repository, aiProvider: provider }); assert.equal(result.status, 200); assert.equal(provider.requests.length, 1); assert.equal(provider.requests[0].observability?.operation, "synthesis"); assert.match(provider.requests[0].systemPrompt, /needs_input/); });
test("worker failure still allows a safe partial Emmy synthesis", async () => { const provider = new SequenceProvider(["THROW", JSON.stringify({ reply: "The specialist analysis was unavailable, so here is a limited response.", claims: [] })]); const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", body: { message: "Recommend SEO keywords" }, workspaceRepository: workspaces(), businessOsRepository: businessOs(), aiProvider: provider }); assert.equal(result.status, 200); assert.match(String(result.payload.data.reply), /limited response/); assert.match(provider.requests[1].systemPrompt, /INTERNAL_ORCHESTRATION_ERROR/); });
test("public Emmy normal requests make one public direct provider call and never orchestrate", async () => { const provider = new SequenceProvider(["Public answer"]); const result = await request("/api/v1/emmy/messages", { method: "POST", body: { message: "What does Averon build?" }, aiProvider: provider }); assert.equal(result.status, 200); assert.equal(provider.requests.length, 1); assert.equal(provider.requests[0].observability?.channel, "public"); assert.equal(provider.requests[0].observability?.agentId, undefined); assert.doesNotMatch(provider.requests[0].systemPrompt, /Validated specialist results/); });
test("private Emmy rejects frontend agent, skill, and readiness injection", async () => { for (const injected of [{ agentId: "coding" }, { requiredSkills: ["seo.content_strategy"] }, { readiness: "READY" }, { enabled: true }]) { const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", body: { message: "Hello", ...injected }, workspaceRepository: workspaces(), businessOsRepository: businessOs() }); assert.equal(result.status, 400); assert.equal(result.payload.error.code, "EMMY_INVALID_REQUEST"); } });
test("private citations contain only claim-used authorized provenance", async () => { const repository = businessOs(); const groundedProvider: AiProvider = { async generate() { return { text: JSON.stringify({ reply: "Pricing fact [1]", claims: [{ text: "Pricing fact", sourceRefs: ["src_1"], grounding: "business_os" }] }) }; } }; const member = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", body: { message: "What is our pricing?" }, workspaceRepository: workspaces("member"), businessOsRepository: repository, aiProvider: groundedProvider }); const citations = member.payload.data.citations as Array<{ citationId: string; sectionType: string; label: string; version: number }>; assert.deepEqual(citations, [{ citationId: "c1", sectionType: "pricing", label: "Pricing", version: 1 }]); const denied = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", body: { message: "What is our pricing?", citations: [{ sectionType: "instructions" }] }, workspaceRepository: workspaces("member"), businessOsRepository: repository }); assert.equal(denied.status, 400); });
