import assert from "node:assert/strict";
import test from "node:test";
import { AVERON_PUBLIC_METADATA } from "@averon/shared-types";
import type { AiProvider, AiProviderRequest } from "../src/ai/providers/ai-provider.ts";
import { parseSeoMetadataPatch, seoMetadataIntent } from "../src/domains/page-metadata/page-metadata.actions.ts";
import { MemoryBusinessOsRepository, MemoryPageMetadataRepository, MemoryWorkspaceRepository, request } from "./http-harness.ts";

function workspaces(role: "owner" | "member" = "owner") { return new MemoryWorkspaceRepository({ businesses: [{ id: "averon", name: "Averon Technologies", slug: "averon", status: "active" }], workspaces: [{ id: "averon", businessId: "averon", name: "Averon Technologies", slug: "averon", status: "active" }], memberships: [{ id: "m1", userId: "user-1", workspaceId: "averon", businessId: "averon", role, status: "active" }] }); }
function businessOs() { const repository = new MemoryBusinessOsRepository(); repository.roots.set("averon", { workspaceId: "averon", businessId: "averon", status: "active", schemaVersion: 1 }); return repository; }
class SeoProvider implements AiProvider { requests: AiProviderRequest[] = []; fail = false; async generate(input: AiProviderRequest) { this.requests.push(input); if (this.fail) throw new Error("failed"); if (!input.observability?.agentId) return { text: JSON.stringify({ reply: "Read-only SEO guidance.", claims: [] }) }; const taskId = (JSON.parse(input.messages[0].content) as { task?: { taskId?: string } }).task?.taskId ?? "task-seo"; return { text: JSON.stringify({ schemaVersion: "seo.v1", agentId: "seo", taskId, status: "completed", summary: "Ready", output: { targetIntent: "informational", suggestedKeywords: [], titleSuggestions: ["Improved services title"], metaDescriptionSuggestions: ["Improved services metadata description."], contentOutline: [], limitations: [] }, warnings: [], missingInformation: [] }) }; } }

test("intent requires current-turn mutation and history supplies only the page target", () => { for (const message of ["Review the services page SEO", "How could we improve the homepage title?", "Summarize our SEO metadata"]) assert.equal(seoMetadataIntent(message).explicit, false); assert.deepEqual(seoMetadataIntent("Change the title", [{ role: "assistant", content: "We were discussing /services" }]), { action: "update", explicit: true, pageId: "services" }); assert.equal(seoMetadataIntent("Summarize it", [{ role: "user", content: "Update /services metadata" }]).explicit, false); });
test("payload validation allows only safe bounded partial fields", () => { assert.deepEqual(parseSeoMetadataPatch({ title: "Safe title" }), { title: "Safe title" }); for (const value of [{ robots: "noindex" }, { title: "<script>x</script>" }, { title: "" }]) assert.throws(() => parseSeoMetadataPatch(value)); });

test("simple canonical metadata read uses zero provider calls and zero mutations", async () => { const repository = new MemoryPageMetadataRepository(Object.values(AVERON_PUBLIC_METADATA)); const provider = new SeoProvider(); const result = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", requestId: "seo-read", body: { message: "What is the meta description for /services?" }, workspaceRepository: workspaces(), businessOsRepository: businessOs(), pageMetadataRepository: repository, aiProvider: provider }); assert.equal(result.payload.data.finalStatus, "completed"); assert.equal(provider.requests.length, 0); assert.equal(repository.writes, 0); assert.match(String(result.payload.data.reply), /Page: \/services/); });

test("production explicit update runs SEO once, mutates one canonical record, verifies, and never synthesizes", async () => { const repository = new MemoryPageMetadataRepository(Object.values(AVERON_PUBLIC_METADATA)); const provider = new SeoProvider(); const before = structuredClone(AVERON_PUBLIC_METADATA.services); const options = { method: "POST", authorization: "Bearer valid", requestId: "seo-update", body: { message: "Update the meta description for /services to “A clearer services metadata description.”" }, workspaceRepository: workspaces(), businessOsRepository: businessOs(), pageMetadataRepository: repository, aiProvider: provider }; const result = await request("/api/v1/workspaces/averon/emmy/messages", options); const updated = await repository.get("averon", "services"); assert.equal(result.payload.data.finalStatus, "completed"); assert.equal(provider.requests.length, 1); assert.equal(provider.requests[0].observability?.agentId, "seo"); assert.equal(repository.writes, 1); assert.equal(updated?.metaDescription, "A clearer services metadata description."); assert.equal(updated?.title, before.title); assert.equal(updated?.route, before.route); assert.equal(updated?.canonicalPath, before.canonicalPath); assert.equal(updated?.robots, before.robots); assert.equal((result.payload.data.action as { verificationStatus: string }).verificationStatus, "passed"); const publicRead = await request("/api/v1/public/workspaces/averon/page-metadata/services", { pageMetadataRepository: repository }); assert.equal(publicRead.payload.data.metaDescription, updated?.metaDescription); await request("/api/v1/workspaces/averon/emmy/messages", options); assert.equal(repository.writes, 1); });

test("advisory, missing target, authorization, specialist, and verification failures produce no success", async () => { const advisory = new MemoryPageMetadataRepository(Object.values(AVERON_PUBLIC_METADATA)); await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", body: { message: "How could we improve the homepage title?" }, workspaceRepository: workspaces(), businessOsRepository: businessOs(), pageMetadataRepository: advisory, aiProvider: new SeoProvider() }); assert.equal(advisory.writes, 0); const missing = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", requestId: "missing", body: { message: "Update the meta description to “Better metadata.”" }, workspaceRepository: workspaces(), businessOsRepository: businessOs(), pageMetadataRepository: advisory, aiProvider: new SeoProvider() }); assert.deepEqual((missing.payload.data.action as { warnings: string[] }).warnings, ["ACTION_TARGET_REQUIRED"]); const deniedRepo = new MemoryPageMetadataRepository(Object.values(AVERON_PUBLIC_METADATA)); const denied = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", requestId: "denied", body: { message: "Change the SEO title for /services to “New title”" }, workspaceRepository: workspaces("member"), businessOsRepository: businessOs(), pageMetadataRepository: deniedRepo, aiProvider: new SeoProvider() }); assert.equal(deniedRepo.writes, 0); assert.doesNotMatch(String(denied.payload.data.reply), /updated successfully/i); const failedRepo = new MemoryPageMetadataRepository(Object.values(AVERON_PUBLIC_METADATA)); const failedProvider = new SeoProvider(); failedProvider.fail = true; const failed = await request("/api/v1/workspaces/averon/emmy/messages", { method: "POST", authorization: "Bearer valid", requestId: "failed", body: { message: "Change the SEO title for /services to “New title”" }, workspaceRepository: workspaces(), businessOsRepository: businessOs(), pageMetadataRepository: failedRepo, aiProvider: failedProvider }); assert.equal(failedRepo.writes, 0); assert.doesNotMatch(String(failed.payload.data.reply), /updated successfully/i); });
