import assert from "node:assert/strict"; import test from "node:test";
import type { AgentTask } from "@averon/agent-contracts";
import { productionAgentSpecs, DefaultAgentRegistry } from "../src/ai/agents/registry.ts"; import { SkillRegistry } from "../src/ai/agents/skills.ts"; import { AgentReadinessEngine, CapabilityResolver, SmallestTeamSelector } from "../src/ai/agents/readiness.ts"; import { TaskPlanner } from "../src/ai/agents/planner.ts"; import { parseWorkerResult, workerSchemaVersions } from "../src/ai/agents/schemas.ts"; import { AgentResultValidator } from "../src/ai/agents/validator.ts"; import { assessOrchestrationSafety, detectStructuredContradictions, expectedCriticVerdict } from "../src/ai/agents/quality.ts";
const registry=new DefaultAgentRegistry();const readiness=new AgentReadinessEngine(registry,new SkillRegistry(),{availableProviders:["ai.text_generation"],availableTools:[],availableModelCapabilities:["structured_output"]});const resolver=new CapabilityResolver(registry,readiness);const selector=new SmallestTeamSelector();
function team(message:string){const planner=new TaskPlanner();const capabilities=planner.capabilities(message);const risk=capabilities.requiredSkills.some(skill=>skill.startsWith("security.")||skill.startsWith("verification."))?"high":"moderate";const resolved=resolver.resolveCandidates({requiredSkills:capabilities.requiredSkills,permissions:["emmy:use"],riskLevel:risk});return {capabilities,team:selector.select(capabilities.requiredSkills,resolved.candidates,{maxAgents:4,maxProviderCalls:4,maxRuntimeMs:20_000,costClassCeiling:"medium"}),plan:undefined as ReturnType<TaskPlanner["materialize"]>|undefined,planner};}
const cases:[string,string[]][]=[["Review the React frontend architecture",["frontend"]],["Review our backend API architecture",["backend"]],["Propose a database schema design",["database"]],["Create a test strategy and acceptance criteria",["testing"]],["Perform a security review",["security","critic"]],["Optimize our business operations workflow",["business-operations"]],["Create a marketing strategy",["marketing"]],["Create a sales strategy",["sales"]],["Analyze the customer operations support workflow",["customer-operations"]],["Independently verify the recommendation",["critic"]],["Review backend and database data model architecture",["backend","database"]],["Review a secure backend API",["backend","security","critic"]],["Review frontend development and propose tests",["frontend","testing"]],["Create marketing strategy and blog content",["blog","marketing"]],["Review business operations using analytics",["analytics","business-operations"]]];
test("representative requests select the smallest capability-based teams",()=>{for(const [message,expected] of cases){const result=team(message);assert.deepEqual([...result.team.selectedAgents].sort(),[...expected].sort(),message);assert.deepEqual(result.team.unresolvedSkills,[],message);assert.ok(result.team.selectedAgents.length<=4);}});
test("security-sensitive work makes critic a structured final dependency",()=>{const result=team("Review a secure backend API");const plan=result.planner.materialize("Review a secure backend API",result.capabilities,result.team);const critic=plan.tasks.find(item=>item.agentId==="critic")!;assert.deepEqual(critic.dependencies.sort(),plan.tasks.filter(item=>item.agentId!=="critic").map(item=>item.taskId).sort());assert.equal(plan.tasks.at(-1)?.agentId,"critic");});
test("all sixteen specs are ready and limited to non-execution rights",()=>{assert.equal(productionAgentSpecs.length,16);for(const spec of productionAgentSpecs){assert.equal(readiness.evaluate(spec).status,"READY");assert.ok(spec.executionRights.every(right=>["read","analyze","draft","recommend"].includes(right)));assert.deepEqual(spec.toolRequirements,[]);}});
function task(agentId:string,sections:unknown[]=[]):AgentTask{return{taskId:`task-${agentId}`,agentId,workspaceId:"averon",businessId:"averon",objective:"Verify",input:"Verify",constraints:["read-only"],approvalPolicy:"never",context:{workspace:{id:"averon",name:"Averon"},business:{id:"averon",name:"Averon"},sections,upstreamResults:[],userRequest:"Verify"},expectedOutput:"Structured output"};}
test("new role schemas accept bounded outputs and reject arbitrary shapes",()=>{for(const agentId of ["frontend","backend","database","testing","security","business-operations","marketing","sales","customer-operations"]){const value={schemaVersion:workerSchemaVersions[agentId as keyof typeof workerSchemaVersions],agentId,taskId:`task-${agentId}`,status:"completed",summary:"Review complete",output:{findings:[],recommendations:[],risks:[],assumptions:[],missingInformation:[]}};assert.equal(parseWorkerResult(task(agentId),value).ok,true);assert.equal(parseWorkerResult(task(agentId),{...value,output:{freeform:true}}).ok,false);}});
test("critic schema handles verdicts without hidden reasoning",()=>{const base={schemaVersion:"critic.v1",agentId:"critic",taskId:"task-critic",status:"completed",summary:"Verified",output:{verdict:"PASS",findings:[],contradictions:[],missingEvidence:[],requirementViolations:[],riskConcerns:[],recommendedRevisions:[]}};assert.equal(parseWorkerResult(task("critic"),base).ok,true);assert.equal(parseWorkerResult(task("critic"),{...base,output:{...base.output,chainOfThought:"hidden"}}).ok,false);assert.equal(parseWorkerResult(task("critic"),{...base,output:{...base.output,verdict:"NEEDS_INPUT"},status:"needs_input",missingInformation:["Evidence"]}).ok,true);});
test("critic represents unsupported claims, contradictions, and missing evidence as review outcomes",()=>{const base={schemaVersion:"critic.v1",agentId:"critic",taskId:"task-critic",status:"completed",summary:"Review",output:{verdict:"REVISE",findings:["Unsupported claim"],contradictions:["Statements conflict"],missingEvidence:["Authorized source"],requirementViolations:[],riskConcerns:[],recommendedRevisions:["Remove or source the claim"]}};const parsed=parseWorkerResult(task("critic"),base);assert.equal(parsed.ok,true);if(parsed.ok){const output=parsed.result.output as typeof base.output;assert.equal(output.verdict,"REVISE");assert.equal(output.contradictions.length,1);assert.equal(output.missingEvidence.length,1);}});
test("provenance, mutation claims, and task identity remain authoritative",()=>{const source={sourceRef:"src_1"};const value={schemaVersion:"critic.v1",agentId:"critic",taskId:"task-critic",status:"completed",summary:"Verified",output:{verdict:"PASS_WITH_WARNINGS",findings:[],contradictions:[],missingEvidence:["Evidence"],requirementViolations:[],riskConcerns:[],recommendedRevisions:[]},sourceRefs:["src_other"]};assert.equal(parseWorkerResult(task("critic",[source]),value).ok,false);const validator=new AgentResultValidator();assert.equal(validator.validate(task("frontend"),{taskId:"task-frontend",agentId:"frontend",status:"completed",summary:"I deployed the fix."}).error?.code,"PROHIBITED_ACTION_CLAIM");assert.equal(validator.validate(task("backend"),{taskId:"wrong",agentId:"backend",status:"completed",summary:"Done"}).error?.code,"AGENT_CONTEXT_MISMATCH");});
test("structured contradictions prefer evidence and otherwise require input",()=>{const grounded=detectStructuredContradictions([{resultId:"analytics",subject:"trend",value:"up",sourceRefs:["src_1"]},{resultId:"operations",subject:"trend",value:"down",sourceRefs:[]}]);assert.equal(grounded[0].resolution,"prefer_grounded");assert.equal(grounded[0].preferredResultId,"analytics");const unsupported=detectStructuredContradictions([{resultId:"a",subject:"trend",value:"up",sourceRefs:[]},{resultId:"b",subject:"trend",value:"down",sourceRefs:[]}]);assert.equal(unsupported[0].resolution,"needs_input");});
test("critic outcomes are evidence and safety based rather than majority votes",()=>{assert.equal(expectedCriticVerdict({}),"PASS");assert.equal(expectedCriticVerdict({findings:["minor"]}),"PASS_WITH_WARNINGS");assert.equal(expectedCriticVerdict({missingEvidence:["source"]}),"NEEDS_INPUT");assert.equal(expectedCriticVerdict({contradictions:["conflict"]}),"REVISE");assert.equal(expectedCriticVerdict({executionViolation:true}),"REJECT");});
test("partial failures distinguish optional, required, and verifier failures",()=>{const planned=(taskId:string,agentId:string,dependencyPolicy:"required"|"optional")=>({taskId,agentId,objective:"Review",dependencies:[],dependencyPolicy,requiredContextSections:[],expectedOutput:"Structured"} as const);const failed=(taskId:string,agentId:string)=>({taskId,agentId,status:"failed",summary:"Unavailable"} as const);assert.equal(assessOrchestrationSafety([planned("optional","backend","optional")],[failed("optional","backend")]).safeToSynthesize,true);assert.equal(assessOrchestrationSafety([planned("required","backend","required")],[failed("required","backend")]).safeToSynthesize,false);assert.equal(assessOrchestrationSafety([planned("critic","critic","required")],[failed("critic","critic")]).criticFailed,true);});
test("all current execution-claim forms are rejected",()=>{const validator=new AgentResultValidator();for(const summary of ["I deployed the application.","I changed the database.","I emailed the customer.","I updated the website.","I charged the invoice."])assert.equal(validator.validate(task("backend"),{taskId:"task-backend",agentId:"backend",status:"completed",summary}).error?.code,"PROHIBITED_ACTION_CLAIM");});
