import test from "node:test";
import assert from "node:assert/strict";
import type { AuthContext } from "../src/services/auth/authentication.ts";
import { WorkspaceAuthorizationService } from "../src/domains/workspaces/workspace.service.ts";
import { MemoryWorkspaceNotificationRepository } from "../src/domains/workspace-notifications/workspace-notification.repository.ts";
import { evaluateWorkspaceHealth, safeNotificationDestination, WorkspaceNotificationService, workspaceHealthSchedules } from "../src/domains/workspace-notifications/workspace-notification.service.ts";
import { AnalyticsWorkspaceHealthAnalyzer } from "../src/domains/workspace-notifications/analytics-health-review.ts";
import type { AiProvider } from "../src/ai/providers/ai-provider.ts";
import { MemoryWorkspaceRepository } from "./http-harness.ts";

const auth = { user: { userId: "user-1", role: "owner" } } as AuthContext;
function analyticsResult(observations = ["API health check failed."]) { return JSON.stringify({ schemaVersion: "analytics.v1", agentId: "analytics", taskId: "health-review-health-request", status: "completed", summary: "Authoritative health evidence reviewed.", output: { observations, metricsUsed: ["apiHealthy", "failedOperationCount"], trends: [], caveats: [], missingData: [], recommendations: ["Investigate API runtime stability."] }, warnings: [], missingInformation: [], sourceRefs: [] }); }
function setup(provider?: AiProvider) { const workspaceRepository = new MemoryWorkspaceRepository({ businesses: [{ id: "business-a", name: "A", slug: "a", status: "active" }, { id: "business-b", name: "B", slug: "b", status: "active" }], workspaces: [{ id: "averon", businessId: "business-a", name: "Averon Technologies", slug: "averon", status: "active" }, { id: "movento", businessId: "business-b", name: "Movento", slug: "movento", status: "active" }], memberships: [{ id: "member-a", userId: "user-1", workspaceId: "averon", businessId: "business-a", role: "owner", status: "active" }] }); const repository = new MemoryWorkspaceNotificationRepository(); const fallback: AiProvider = { async generate() { return { text: analyticsResult() }; } }; const evidence = { async collect() { return { apiHealthy: false, failedOperationCount: 2 }; } }; return { repository, service: new WorkspaceNotificationService(repository, new WorkspaceAuthorizationService(workspaceRepository), evidence, new AnalyticsWorkspaceHealthAnalyzer(provider ?? fallback)) }; }

test("workspace notification reads and status writes remain authorized and scoped", async () => { const { repository, service } = setup(); await repository.save({ notificationId: "a", workspaceId: "averon", category: "ACTION_RESULT", severity: "success", title: "Completed", message: "Verified.", source: "action", createdAt: "2026-08-31T00:00:00.000Z", status: "unread", authoritativeStatus: "completed" }); await repository.save({ notificationId: "b", workspaceId: "movento", category: "BOOKING", severity: "info", title: "Booking", message: "Received.", source: "booking.created", createdAt: "2026-08-31T00:00:01.000Z", status: "unread", authoritativeStatus: "observed" }); const listed = await service.list(auth); assert.deepEqual(listed.items.map((item) => item.notificationId), ["a"]); await assert.rejects(() => service.list(auth, { workspaceId: "movento" }), (error: { code?: string }) => error.code === "WORKSPACE_ACCESS_DENIED"); await assert.rejects(() => service.setStatus(auth, "b", "read")); assert.equal((await service.setStatus(auth, "a", "read")).status, "read"); assert.equal((await service.setStatus(auth, "a", "unread")).status, "unread"); });
test("notification persistence is idempotent and deep links are internal allowlisted destinations", async () => { const { service } = setup(); const input = { notificationId: "terminal-action", workspaceId: "averon", category: "ACTION_RESULT" as const, severity: "success" as const, title: "Action completed", message: "Verification passed.", source: "emmy.action", authoritativeStatus: "completed" as const, destination: { kind: "internal" as const, path: "/chat", label: "Open chat" } }; assert.equal((await service.record(input)).created, true); assert.equal((await service.record(input)).created, false); assert.equal(safeNotificationDestination("/diagnostics"), "/diagnostics"); assert.equal(safeNotificationDestination("https://evil.example"), null); await assert.rejects(() => service.record({ ...input, notificationId: "unsafe", destination: { kind: "internal", path: "//evil.example", label: "Open" } })); });
test("health review executes Analytics, grounds OBSERVED, persists SUGGESTED, and remains idempotent", async () => { let calls = 0; const provider: AiProvider = { async generate(request) { calls += 1; assert.equal(request.observability?.agentId, "analytics"); assert.match(request.messages[0]?.content ?? "", /authoritativeHealthEvidence/); return { text: analyticsResult() }; } }; const { service } = setup(provider); const result = await service.healthReview(auth, "averon", "health-request"); assert.equal(calls, 1); assert.equal(result.providerCalls, 1); assert.equal(result.report.specialistId, "analytics"); assert.equal(result.report.overall, "critical"); assert.deepEqual(result.report.observed, ["API health check failed."]); assert.deepEqual(result.report.suggested, ["Investigate API runtime stability."]); assert.equal(result.notification.source, "workspace.health_review.analytics"); assert.equal(result.notification.category, "WEBSITE_HEALTH"); assert.equal((await service.healthReview(auth, "averon", "health-request")).created, false); assert.deepEqual(workspaceHealthSchedules.map((item) => [item.workspaceId, item.weekday]), [["movento", 1], ["lumora", 2], ["averon", 4]]); assert.equal(evaluateWorkspaceHealth("averon", {}).overall, "healthy"); });
test("ungrounded or failed Analytics output creates no health notification", async () => { const ungrounded: AiProvider = { async generate() { return { text: analyticsResult(["Traffic increased by 50%."]) }; } }; const first = setup(ungrounded); await assert.rejects(() => first.service.healthReview(auth, "averon", "health-request"), (error: { code?: string }) => error.code === "HEALTH_REVIEW_UNGROUNDED_OBSERVATION"); assert.equal(first.repository.items.size, 0); const failed: AiProvider = { async generate() { throw new Error("provider unavailable"); } }; const second = setup(failed); await assert.rejects(() => second.service.healthReview(auth, "averon", "health-request")); assert.equal(second.repository.items.size, 0); });
