import test from "node:test";
import assert from "node:assert/strict";
import type { AiDiagnostic, WorkspaceTask } from "@averon/shared-types";
import type { AiProvider, AiProviderRequest } from "../src/ai/providers/ai-provider.ts";
import { AiDiagnosticsStore } from "../src/ai/diagnostics/diagnostics.store.ts";
import type { PrivateEmmyService } from "../src/ai/emmy/private-emmy.ts";
import { MemoryWorkspaceTaskRepository } from "../src/domains/workspace-tasks/workspace-task.repository.ts";
import { WorkspaceTaskService } from "../src/domains/workspace-tasks/workspace-task.service.ts";
import { MemoryWorkspaceRepository, request } from "./http-harness.ts";
import { WorkspaceAuthorizationService } from "../src/domains/workspaces/workspace.service.ts";
import type { AuthContext } from "../src/services/auth/authentication.ts";

const auth: AuthContext = { user: { userId: "user-1", emailVerified: true, role: "owner", isAdmin: false, permissions: [] } };
const workspaces = () => new WorkspaceAuthorizationService(new MemoryWorkspaceRepository({ businesses: [{ id: "averon", name: "Averon", slug: "averon", status: "active" }, { id: "lumora", name: "Lumora", slug: "lumora", status: "active" }], workspaces: [{ id: "averon", businessId: "averon", name: "Averon", slug: "averon", status: "active" }, { id: "lumora", businessId: "lumora", name: "Lumora", slug: "lumora", status: "active" }], memberships: [{ id: "member", userId: "user-1", workspaceId: "averon", businessId: "averon", role: "owner", status: "active" }] }));
const task = (extra: Partial<WorkspaceTask> = {}): Omit<WorkspaceTask, "version" | "createdAt" | "updatedAt"> => ({ id: "task-1", workspaceId: "averon", title: "Review website SEO", description: "Provide validated recommendations only.", status: "TODO", priority: "NORMAL", assignedAgentIds: ["seo"], linkedRunIds: [], linkedActionIds: [], createdBy: "user-1", updatedBy: "user-1", ...extra });
const diagnostic = (requestId: string): AiDiagnostic => ({ requestId, workspaceId: "averon", businessId: "averon", startedAt: new Date().toISOString(), durationMs: 1, finalStatus: "completed", plan: { taskCount: 1, agentIds: ["seo"] }, tasks: [], citations: [], errorCodes: [], providerCalls: 1, tokenUsage: { inputTokens: 1, outputTokens: 1, totalTokens: 2 } });
function emmy(result: Record<string, unknown>, diagnostics?: AiDiagnosticsStore, gate?: Promise<void>) { return { async send(_auth: AuthContext, _workspaceId: string, _input: unknown, requestId: string) { if (gate) await gate; await diagnostics?.add(diagnostic(requestId)); return result; } } as unknown as PrivateEmmyService; }

test("explicit controlled execution creates one distinct linked Run and completes only validated advisory success", async () => { const repository = new MemoryWorkspaceTaskRepository(); await repository.create(task()); const diagnostics = new AiDiagnosticsStore(); const service = new WorkspaceTaskService(repository, workspaces(), emmy({ finalStatus: "completed", reply: "Validated recommendation" }, diagnostics), diagnostics); const result = await service.execute(auth, "averon", "task-1", { idempotencyKey: "attempt-one" }); assert.equal(result.status, "COMPLETED"); assert.notEqual(result.runId, "task-1"); const stored = (await repository.get("averon", "task-1"))!; assert.deepEqual(stored.linkedRunIds, [result.runId]); assert.equal(stored.status, "COMPLETED"); assert.equal((await diagnostics.get(result.runId))?.taskId, "task-1"); });

test("production execute endpoint authorizes then reuses Private Emmy and durable Diagnostics", async () => { const repository = new MemoryWorkspaceTaskRepository(); await repository.create(task()); let calls = 0; const provider: AiProvider = { async generate(input: AiProviderRequest) { calls += 1; const agentId = input.observability?.agentId; if (agentId === "seo") { const taskId = (JSON.parse(input.messages[0]!.content) as { task: { taskId: string } }).task.taskId; return { text: JSON.stringify({ schemaVersion: "seo.v1", agentId: "seo", taskId, status: "completed", summary: "SEO review completed.", missingInformation: [], output: { targetIntent: "informational", suggestedKeywords: ["efficiency"], titleSuggestions: ["Efficiency"], metaDescriptionSuggestions: ["Efficiency recommendations."], contentOutline: ["Review"], limitations: ["External metrics were not supplied."] } }) }; } return { text: JSON.stringify({ reply: "Validated advisory recommendations are ready.", claims: [] }) }; } }; const allowed = await request("/api/v1/workspaces/averon/tasks/task-1/execute", { method: "POST", authorization: "Bearer valid", workspaceRepository: new MemoryWorkspaceRepository({ businesses: [{ id: "averon", name: "Averon", slug: "averon", status: "active" }], workspaces: [{ id: "averon", businessId: "averon", name: "Averon", slug: "averon", status: "active" }], memberships: [{ id: "member", userId: "user-1", workspaceId: "averon", businessId: "averon", role: "owner", status: "active" }] }), workspaceTaskRepository: repository, aiProvider: provider, body: { idempotencyKey: "production-path" } }); assert.equal(allowed.status, 202); assert.equal(allowed.payload.data.status, "COMPLETED"); assert.notEqual(allowed.payload.data.runId, "task-1"); assert.equal(calls, 2); const deniedCalls = calls; const denied = await request("/api/v1/workspaces/averon/tasks/task-1/execute", { method: "POST", authorization: "Bearer valid", workspaceRepository: new MemoryWorkspaceRepository({ businesses: [{ id: "averon", name: "Averon", slug: "averon", status: "active" }], workspaces: [{ id: "averon", businessId: "averon", name: "Averon", slug: "averon", status: "active" }], memberships: [{ id: "member", userId: "user-1", workspaceId: "averon", businessId: "averon", role: "member", status: "active" }] }), workspaceTaskRepository: repository, aiProvider: provider, body: { idempotencyKey: "unauthorized-path" } }); assert.equal(denied.status, 403); assert.equal(calls, deniedCalls); });

test("idempotent replay returns the same Run and a concurrent distinct attempt fails closed", async () => { const repository = new MemoryWorkspaceTaskRepository(); await repository.create(task()); let release!: () => void; const gate = new Promise<void>((resolve) => { release = resolve; }); const service = new WorkspaceTaskService(repository, workspaces(), emmy({ finalStatus: "completed", reply: "Done" }, undefined, gate)); const first = service.execute(auth, "averon", "task-1", { idempotencyKey: "same-request" }); await new Promise((resolve) => setImmediate(resolve)); const replay = await service.execute(auth, "averon", "task-1", { idempotencyKey: "same-request" }); assert.equal(replay.idempotentReplay, true); await assert.rejects(() => service.execute(auth, "averon", "task-1", { idempotencyKey: "different-request" }), (error: { code?: string }) => error.code === "TASK_EXECUTION_ALREADY_ACTIVE"); release(); const completed = await first; assert.equal(completed.runId, replay.runId); assert.equal((await repository.get("averon", "task-1"))!.linkedRunIds.length, 1); });

test("approval-required action stays authoritative and failure blocks without fabricated completion", async () => { const approvalRepository = new MemoryWorkspaceTaskRepository(); await approvalRepository.create(task()); const action = { actionId: "proposal-1", actionType: "frontend.source.propose", status: "approval_required", approvalStatus: "pending", verificationStatus: "pending", targetFiles: ["src/example.css"], changedLines: 1, insertions: 1, deletions: 1, warnings: [] }; const approval = await new WorkspaceTaskService(approvalRepository, workspaces(), emmy({ finalStatus: "completed", reply: "Proposal ready", action })).execute(auth, "averon", "task-1", { idempotencyKey: "approval-attempt" }); assert.equal(approval.status, "AWAITING_APPROVAL"); assert.equal((await approvalRepository.get("averon", "task-1"))!.linkedActionIds[0], "proposal-1"); const failedRepository = new MemoryWorkspaceTaskRepository(); await failedRepository.create(task()); const failed = await new WorkspaceTaskService(failedRepository, workspaces(), emmy({ finalStatus: "failed", reply: "Failed" })).execute(auth, "averon", "task-1", { idempotencyKey: "failed-attempt" }); assert.equal(failed.status, "BLOCKED"); assert.equal((await failedRepository.get("averon", "task-1"))!.completedAt, undefined); });

test("an action cannot complete its Task until its authoritative verification passed", async () => { const repository = new MemoryWorkspaceTaskRepository(); await repository.create(task()); const action = { actionId: "action-1", actionType: "blog.draft.update", status: "completed", approvalStatus: "not_required", verificationStatus: "failed", warnings: [] }; const result = await new WorkspaceTaskService(repository, workspaces(), emmy({ finalStatus: "completed", reply: "Unverified", action })).execute(auth, "averon", "task-1", { idempotencyKey: "unverified-action" }); assert.equal(result.status, "BLOCKED"); const stored = (await repository.get("averon", "task-1"))!; assert.equal(stored.status, "BLOCKED"); assert.equal(stored.lastExecutionSummary, "The controlled execution was blocked; inspect the linked Run."); assert.equal(stored.completedAt, undefined); });

test("approval remains action-authoritative and Task reconciliation completes only after verified action evidence", async () => { const repository = new MemoryWorkspaceTaskRepository(); await repository.create(task()); const diagnostics = new AiDiagnosticsStore(); const pending = { actionId: "proposal-2", actionType: "frontend.source.propose", status: "approval_required", approvalStatus: "pending", verificationStatus: "pending", targetFiles: ["src/example.css"], changedLines: 1, insertions: 1, deletions: 1, warnings: [] } as const; const service = new WorkspaceTaskService(repository, workspaces(), emmy({ finalStatus: "completed", reply: "Proposal ready", action: pending }, diagnostics), diagnostics); const execution = await service.execute(auth, "averon", "task-1", { idempotencyKey: "approval-follow-through" }); await diagnostics.recordOperation(execution.runId, pending, { workspaceId: "averon", businessId: "averon" }); assert.equal((await service.detail(auth, "averon", "task-1")).status, "AWAITING_APPROVAL"); await diagnostics.recordOperation("apply-request", { ...pending, status: "completed", approvalStatus: "approved", verificationStatus: "passed" }, { workspaceId: "averon", businessId: "averon" }); const completed = await service.detail(auth, "averon", "task-1"); assert.equal(completed.status, "COMPLETED"); assert.equal(completed.lastExecutionStatus, "COMPLETED"); assert.equal(completed.linkedRunIds.length, 1); assert.equal(completed.linkedActionIds[0], "proposal-2"); });

test("retry creates a new Run while cancelled completed and cross-workspace Tasks fail closed", async () => { const repository = new MemoryWorkspaceTaskRepository(); await repository.create(task({ status: "BLOCKED", lastExecutionStatus: "BLOCKED", linkedRunIds: ["old-run"] })); const service = new WorkspaceTaskService(repository, workspaces(), emmy({ finalStatus: "completed", reply: "Recovered" })); const retry = await service.execute(auth, "averon", "task-1", { idempotencyKey: "retry-attempt" }); assert.equal(retry.status, "COMPLETED"); assert.deepEqual((await repository.get("averon", "task-1"))!.linkedRunIds, ["old-run", retry.runId]); await repository.create(task({ id: "cancelled", status: "CANCELLED" })); await assert.rejects(() => service.execute(auth, "averon", "cancelled", { idempotencyKey: "cancelled-attempt" }), (error: { code?: string }) => error.code === "TASK_EXECUTION_NOT_ALLOWED"); await assert.rejects(() => service.execute(auth, "lumora", "task-1", { idempotencyKey: "cross-workspace" }), (error: { status?: number }) => error.status === 403); });

const homepageReview = { title: "Review Averon homepage design", description: "Review the Averon Technologies homepage and identify the most important improvements needed to make it look like a premium, established technology company.\n\nFocus on typography, spacing, visual hierarchy, layout composition, trust presentation, brand quality, and overall premium appearance.\n\nDo not modify any files or content.\nReturn recommendations only.", assignedAgentIds: ["critic", "marketing", "frontend"] };
function frontendReviewProvider(synthesis: string[]) { const calls: string[] = []; return { calls, provider: { async generate(input: AiProviderRequest) { const agentId = input.observability?.agentId; calls.push(agentId ?? String(input.observability?.operation)); if (agentId === "frontend") { const taskId = (JSON.parse(input.messages[0]!.content) as { task: { taskId: string } }).task.taskId; return { text: JSON.stringify({ schemaVersion: "frontend.v1", agentId: "frontend", taskId, status: "completed", summary: "Homepage review completed.", warnings: [], missingInformation: [], output: { findings: ["The hierarchy can be strengthened."], recommendations: ["Refine type scale and spacing."], risks: [], assumptions: [], missingInformation: [] } }) }; } return { text: synthesis.shift() ?? "invalid" }; } } as AiProvider }; }

test("production-shaped advisory homepage review completes its Run and Task without creating an action", async () => {
  const repository = new MemoryWorkspaceTaskRepository(); await repository.create(task(homepageReview)); const diagnostics = new AiDiagnosticsStore(); const fixture = frontendReviewProvider([JSON.stringify({ reply: "The validated homepage review is ready.", claims: [] })]);
  const result = await request("/api/v1/workspaces/averon/tasks/task-1/execute", { method: "POST", authorization: "Bearer valid", workspaceRepository: new MemoryWorkspaceRepository({ businesses: [{ id: "averon", name: "Averon", slug: "averon", status: "active" }], workspaces: [{ id: "averon", businessId: "averon", name: "Averon", slug: "averon", status: "active" }], memberships: [{ id: "member", userId: "user-1", workspaceId: "averon", businessId: "averon", role: "owner", status: "active" }] }), workspaceTaskRepository: repository, aiProvider: fixture.provider, aiDiagnostics: diagnostics, body: { idempotencyKey: "homepage-advisory-success" } });
  assert.equal(result.payload.data.status, "COMPLETED"); assert.deepEqual(fixture.calls, ["frontend", "synthesis"]); const stored = (await repository.get("averon", "task-1"))!; assert.equal(stored.status, "COMPLETED"); assert.equal(stored.linkedActionIds.length, 0); assert.equal(stored.lastExecutionSummary, "The validated advisory execution completed."); const run = await diagnostics.get(String(result.payload.data.runId)); assert.equal(run?.finalStatus, "completed"); assert.deepEqual(run?.plan.agentIds, ["frontend"]); assert.equal(run?.errorCodes.length, 0);
});

test("genuine advisory finalization failure keeps the Run failed and Task blocked with safe evidence", async () => {
  const repository = new MemoryWorkspaceTaskRepository(); await repository.create(task(homepageReview)); const diagnostics = new AiDiagnosticsStore(); const fixture = frontendReviewProvider(["not json", "still not json"]);
  const result = await request("/api/v1/workspaces/averon/tasks/task-1/execute", { method: "POST", authorization: "Bearer valid", workspaceRepository: new MemoryWorkspaceRepository({ businesses: [{ id: "averon", name: "Averon", slug: "averon", status: "active" }], workspaces: [{ id: "averon", businessId: "averon", name: "Averon", slug: "averon", status: "active" }], memberships: [{ id: "member", userId: "user-1", workspaceId: "averon", businessId: "averon", role: "owner", status: "active" }] }), workspaceTaskRepository: repository, aiProvider: fixture.provider, aiDiagnostics: diagnostics, body: { idempotencyKey: "homepage-advisory-failure" } });
  assert.equal(result.payload.data.status, "BLOCKED"); assert.deepEqual(fixture.calls, ["frontend", "synthesis", "synthesis"]); const stored = (await repository.get("averon", "task-1"))!; assert.equal(stored.status, "BLOCKED"); assert.equal(stored.linkedActionIds.length, 0); const run = await diagnostics.get(String(result.payload.data.runId)); assert.equal(run?.finalStatus, "failed"); assert.ok(run?.errorCodes.includes("SYNTHESIS_OBJECT_REQUIRED"));
});
