import assert from "node:assert/strict";
import test from "node:test";
import type { WorkspaceRole } from "@averon/shared-types";
import { MemoryWorkspaceRepository, request, StubVerifier, userToken } from "./http-harness.ts";

const businesses = [{ id: "movento", name: "Movento", slug: "movento", status: "active" as const }, { id: "lumora", name: "Lumora", slug: "lumora", status: "active" as const }];
const workspaces = [{ id: "movento", businessId: "movento", name: "Movento", slug: "movento", status: "active" as const }, { id: "lumora", businessId: "lumora", name: "Lumora", slug: "lumora", status: "active" as const }];
function repo(role: WorkspaceRole = "member", status: "active" | "disabled" = "active") { return new MemoryWorkspaceRepository({ businesses, workspaces, memberships: [{ id: "movento__user-1", userId: "user-1", workspaceId: "movento", businessId: "movento", role, status }] }); }

test("workspace listing requires authentication", async () => { const result = await request("/api/v1/workspaces"); assert.equal(result.status, 401); });
test("workspace listing returns only active authorized membership", async () => { const result = await request("/api/v1/workspaces", { authorization: "Bearer valid", workspaceRepository: repo() }); assert.equal(result.status, 200); assert.equal((result.payload.data.items as unknown[]).length, 1); assert.equal(JSON.stringify(result.payload).includes("userId"), false); });
test("workspace detail resolves current user's safe context", async () => { const result = await request("/api/v1/workspaces/movento", { authorization: "Bearer valid", workspaceRepository: repo() }); assert.equal(result.status, 200); assert.equal((result.payload.data.workspace as { id: string }).id, "movento"); assert.equal(result.payload.data.role, "member"); });
test("browser-selected workspace does not bypass membership", async () => { const result = await request("/api/v1/workspaces/lumora", { authorization: "Bearer valid", workspaceRepository: repo() }); assert.equal(result.status, 403); assert.equal(result.payload.error.code, "WORKSPACE_ACCESS_DENIED"); });
test("inactive membership loses listing and detail access", async () => { const repository = repo("member", "disabled"); assert.equal(((await request("/api/v1/workspaces", { authorization: "Bearer valid", workspaceRepository: repository })).payload.data.items as unknown[]).length, 0); assert.equal((await request("/api/v1/workspaces/movento", { authorization: "Bearer valid", workspaceRepository: repository })).status, 403); });
test("disabled workspace cannot authorize access", async () => { const repository = repo(); repository.workspaces.set("movento", { ...workspaces[0], status: "disabled" }); assert.equal((await request("/api/v1/workspaces/movento", { authorization: "Bearer valid", workspaceRepository: repository })).status, 403); });
test("workspace roles map to bounded permission sets", async () => { for (const role of ["owner", "admin", "member", "viewer"] as const) { const result = await request("/api/v1/workspaces/movento", { authorization: "Bearer valid", workspaceRepository: repo(role) }); const permissions = result.payload.data.permissions as string[]; assert.equal(permissions.includes("workspace:read"), true); assert.equal(permissions.includes("workspace:manage"), role === "owner" || role === "admin"); assert.equal(permissions.includes("emmy:use"), role !== "viewer"); } });
test("workspace owner can add a valid membership", async () => { const repository = repo("owner"); const result = await request("/api/v1/admin/workspaces/movento/members", { method: "POST", authorization: "Bearer valid", body: { userId: "user-2", role: "viewer" }, workspaceRepository: repository }); assert.equal(result.status, 201); assert.equal(result.payload.data.userId, "user-2"); });
test("ordinary member cannot grant access", async () => { const result = await request("/api/v1/admin/workspaces/movento/members", { method: "POST", authorization: "Bearer valid", body: { userId: "user-2", role: "viewer" }, workspaceRepository: repo("member") }); assert.equal(result.status, 403); assert.equal(result.payload.error.code, "WORKSPACE_PERMISSION_DENIED"); });
test("workspace admin cannot escalate another user to owner", async () => { const result = await request("/api/v1/admin/workspaces/movento/members", { method: "POST", authorization: "Bearer valid", body: { userId: "user-2", role: "owner" }, workspaceRepository: repo("admin") }); assert.equal(result.status, 403); assert.equal(result.payload.error.code, "PRIVILEGE_ESCALATION_DENIED"); });
test("only platform owner may invoke canonical bootstrap", async () => { const result = await request("/api/v1/admin/workspaces/bootstrap", { method: "POST", authorization: "Bearer valid", verifier: new StubVerifier({ ...userToken, role: "admin" }), workspaceRepository: repo("owner") }); assert.equal(result.status, 403); assert.equal(result.payload.error.code, "PLATFORM_OWNER_REQUIRED"); });
test("invalid membership role is rejected", async () => { const result = await request("/api/v1/admin/workspaces/movento/members", { method: "POST", authorization: "Bearer valid", body: { userId: "user-2", role: "superadmin" }, workspaceRepository: repo("owner") }); assert.equal(result.status, 400); assert.equal(result.payload.error.code, "INVALID_MEMBERSHIP"); });
test("unknown workspace is denied before membership mutation", async () => { const result = await request("/api/v1/admin/workspaces/unknown/members", { method: "POST", authorization: "Bearer valid", body: { userId: "user-2", role: "viewer" }, workspaceRepository: repo("owner") }); assert.equal(result.status, 403); });
test("duplicate membership is rejected safely", async () => { const result = await request("/api/v1/admin/workspaces/movento/members", { method: "POST", authorization: "Bearer valid", body: { userId: "user-1", role: "viewer" }, workspaceRepository: repo("owner") }); assert.equal(result.status, 409); assert.equal(result.payload.error.code, "MEMBERSHIP_EXISTS"); });
test("membership deactivation immediately removes access", async () => { const repository = repo("owner"); repository.memberships.set("movento__user-2", { id: "movento__user-2", userId: "user-2", workspaceId: "movento", businessId: "movento", role: "viewer", status: "active" }); const patch = await request("/api/v1/admin/workspaces/movento/members/movento__user-2", { method: "PATCH", authorization: "Bearer valid", body: { status: "disabled" }, workspaceRepository: repository }); assert.equal(patch.status, 200); const user2 = new StubVerifier({ ...userToken, uid: "user-2", sub: "user-2" }); assert.equal((await request("/api/v1/workspaces/movento", { authorization: "Bearer valid", verifier: user2, workspaceRepository: repository })).status, 403); });
