import type { CapabilityPlan, PlannedTask, TaskPlan, TeamSelectionResult } from "@averon/agent-contracts";
import type { BusinessOsSectionType } from "@averon/shared-types";

export const MAX_SPECIALIST_TASKS = 4;
const specialistTaskTypes: Record<string, string> = { research: "research", seo: "seo", blog: "writing", analytics: "analytics", documentation: "documentation", frontend: "frontend-analysis", backend: "backend-analysis", database: "database-analysis", testing: "test-strategy", security: "security-review", "business-operations": "operations-analysis", marketing: "marketing-strategy", sales: "sales-strategy", "customer-operations": "customer-operations", critic: "verification" };
specialistTaskTypes.guardian = "website-health";
type Rule = { skillId: string; pattern: RegExp; sections: BusinessOsSectionType[]; expected: string };
const rules: Rule[] = [
  { skillId: "website.health_check", pattern: /\b(?:guardian\b[\s\S]{0,80}\b(?:check|inspect|review)|health (?:check|review)|check\s+(?:averon|movento|lumora)\b[\s\S]{0,40}\b(?:website|site|broken pages?)|broken (?:pages?|links?|images?|assets?))\b/i, sections: ["profile", "operations", "instructions"], expected: "An evidence-bounded website health report separating passed, failed, and not-checked checks with no changes performed." },
  { skillId: "research.internal_synthesis", pattern: /\b(research|competitors?|find today|market analysis|investigate|compare companies)\b/i, sections: ["profile", "services", "marketing"], expected: "Structured internal synthesis, gaps, and whether external research is required." },
  { skillId: "seo.content_strategy", pattern: /\b(seo|keyword|search intent|meta description|search strategy|ranking)\b/i, sections: ["brand", "services", "seo", "marketing"], expected: "SEO recommendations without unsupported live metrics." },
  { skillId: "content.blog_drafting", pattern: /\b(blog|article|landing page|social post|copywriting|rewrite)\b/i, sections: ["brand", "instructions", "services", "marketing"], expected: "A clearly labeled unpublished content draft." },
  { skillId: "analytics.interpretation", pattern: /\b(analytics|metrics?|performance|conversions?|traffic|revenue|trends?|business data)\b/i, sections: ["sales", "marketing", "operations"], expected: "Source-bounded metric interpretation or an explicit data request." },
  { skillId: "documentation.sop_drafting", pattern: /\b(documentation|document|sop|runbook|report|technical spec|internal guide|procedure)\b/i, sections: ["operations", "sop", "instructions", "policies"], expected: "A structured documentation draft with no file or system changes." },
  { skillId: "development.frontend_analysis", pattern: /\b(frontend|react|typescript ui|component|user interface|accessibility|client-side|dashboard ui)\b/i, sections: ["instructions", "roadmap"], expected: "Frontend architecture and implementation recommendations without repository changes." },
  { skillId: "development.backend_architecture", pattern: /\b(backend|api design|server-side|authentication|authorization|server architecture|dashboard architecture)\b/i, sections: ["instructions", "operations", "policies", "roadmap"], expected: "Backend architecture recommendations without code execution." },
  { skillId: "development.backend_analysis", pattern: /\b(backend source|api endpoint|server route|health endpoint)\b/i, sections: ["instructions", "operations", "policies", "roadmap"], expected: "A bounded backend source-change analysis without direct repository mutation." },
  { skillId: "database.schema_design", pattern: /\b(database|data model|schema design|firestore|query|indexes?|migration)\b/i, sections: ["operations", "policies", "roadmap"], expected: "Data-model and migration recommendations without database operations." },
  { skillId: "quality.test_strategy", pattern: /\b(test strategy|test cases?|testing|qa|regression|e2e|(?:test|qa|quality|verification) acceptance criteria|acceptance criteria for (?:testing|qa|verification)|propose tests?)\b/i, sections: ["instructions", "operations", "policies"], expected: "A bounded test strategy and acceptance criteria." },
  { skillId: "security.architecture_review", pattern: /\b(security|secure|threat|tenant isolation|secrets?|data exposure|authorization review|payment security)\b/i, sections: ["policies", "operations", "instructions"], expected: "A defensive security review with evidence and no offensive execution." },
  { skillId: "operations.workflow_analysis", pattern: /\b(business operations|operational workflow|process optimization|internal coordination|operations plan)\b/i, sections: ["operations", "sop", "policies", "instructions"], expected: "Operational workflow recommendations grounded in authorized context." },
  { skillId: "marketing.strategy", pattern: /\b(marketing strategy|campaign|positioning|acquisition|conversion strategy|messaging strategy)\b/i, sections: ["marketing", "brand", "services"], expected: "Marketing strategy recommendations distinct from SEO implementation." },
  { skillId: "sales.strategy", pattern: /\b(sales strategy|lead handling|quotation strategy|proposal structure|sales workflow|customer journey)\b/i, sections: ["sales", "pricing", "services", "policies"], expected: "Sales recommendations without contacting customers or changing commercial records." },
  { skillId: "customer.operations", pattern: /\b(customer operations|support workflow|customer request|communication draft|escalation recommendation|service process)\b/i, sections: ["operations", "policies", "services", "instructions"], expected: "Customer operations recommendations or drafts without sending messages or changing records." },
  { skillId: "verification.independent_review", pattern: /\b(security|secure|authentication|authorization|payment|database migration|high-impact business decision|independent verification|verify the recommendation)\b/i, sections: ["policies", "instructions", "decisions"], expected: "An independent structured verification verdict based on supplied evidence and upstream results." },
];
const discourseReference = /\b(?:this|that|it|those|these|previous|earlier|above|what\s+(?:happened|you\s+mean)|continue|resume|go\s+on|try|retry|elaborate|clarify|explain|again)\b/i;
const continuationShape = /^(?:[\p{L}\p{N}'’,?]+\s*){1,12}$/u;
export function isConversationalFollowUp(message: string, history: readonly { role: "user" | "assistant"; content: string }[]) {
  const normalized = message.trim();
  if (!history.length || !normalized || !continuationShape.test(normalized)) return false;
  if (rules.some((rule) => rule.pattern.test(normalized))) return false;
  return discourseReference.test(normalized);
}
export class TaskPlanner {
  capabilities(message: string, history: readonly { role: "user" | "assistant"; content: string }[] = [], mandatorySkills: readonly string[] = []): CapabilityPlan { if (!mandatorySkills.length && isConversationalFollowUp(message, history)) return { directAnswerPossible: true, requiredSkills: [], optionalSkills: [], requestedContextSections: [] }; const all = rules.filter((rule) => rule.pattern.test(message)); const mandatoryRules = mandatorySkills.map((skill) => rules.find((rule) => rule.skillId === skill)).filter((rule): rule is Rule => Boolean(rule)); const candidates = [...mandatoryRules, ...all.filter((rule) => !mandatorySkills.includes(rule.skillId))]; const verifier = candidates.find((rule) => rule.skillId === "verification.independent_review"); const matched = verifier && candidates.length > MAX_SPECIALIST_TASKS ? [...candidates.filter((rule) => rule !== verifier).slice(0, MAX_SPECIALIST_TASKS - 1), verifier] : candidates.slice(0, MAX_SPECIALIST_TASKS); const ids = new Set(matched.map((rule) => rule.skillId)); const boundedGtm = ids.has("marketing.strategy") && ids.has("research.internal_synthesis"); const optionalSkills = boundedGtm && ids.has("seo.content_strategy") && !mandatorySkills.includes("seo.content_strategy") ? ["seo.content_strategy"] : []; const requiredSkills = [...new Set(matched.map((rule) => rule.skillId).filter((skill) => !optionalSkills.includes(skill)))]; return { directAnswerPossible: requiredSkills.length === 0, requiredSkills, optionalSkills, requestedContextSections: [...new Set(matched.flatMap((rule) => rule.sections))] }; }
  materialize(message: string, capabilityPlan: CapabilityPlan, team: TeamSelectionResult): TaskPlan {
    const tasks: PlannedTask[] = team.selectedAgents.map((agentId, index) => { const skills = capabilityPlan.requiredSkills.filter((skill) => team.skillCoverage[skill] === agentId); const rule = rules.find((item) => skills.includes(item.skillId)); return { taskId: `task-${index + 1}-${agentId}`, agentId, taskType: specialistTaskTypes[agentId] ?? "unsupported", objective: message, dependencies: [], dependencyPolicy: "required", requiredContextSections: [...new Set(skills.flatMap((skill) => rules.find((item) => item.skillId === skill)?.sections ?? []))], expectedOutput: rule?.expected ?? "A validated read-only recommendation." }; });
    const seo = tasks.find((task) => task.agentId === "seo"); const blog = tasks.find((task) => task.agentId === "blog"); if (seo && blog) { blog.dependencies = [seo.taskId]; tasks.splice(tasks.indexOf(seo), 1); tasks.unshift(seo); } const critic = tasks.find((task) => task.agentId === "critic"); if (critic) { critic.dependencies = tasks.filter((task) => task !== critic).map((task) => task.taskId); tasks.splice(tasks.indexOf(critic), 1); tasks.push(critic); }
    return { directAnswerPossible: capabilityPlan.directAnswerPossible, tasks, teamSelection: team };
  }
  /** Backwards-compatible deterministic view for callers that have not yet supplied readiness context. */
  plan(message: string, availableSections: BusinessOsSectionType[] = [], identity?: { workspaceId: string; businessId: string }): TaskPlan { const capabilityPlan = this.capabilities(message); const legacy: Record<string, string> = { "website.health_check": "guardian", "research.internal_synthesis": "research", "seo.content_strategy": "seo", "content.blog_drafting": "blog", "analytics.interpretation": "analytics", "documentation.sop_drafting": "documentation", "development.frontend_analysis": "frontend", "development.backend_architecture": "backend", "database.schema_design": "database", "quality.test_strategy": "testing", "security.architecture_review": "security", "operations.workflow_analysis": "business-operations", "marketing.strategy": "marketing", "sales.strategy": "sales", "customer.operations": "customer-operations", "verification.independent_review": "critic" }; const selectedAgents = [...new Set(capabilityPlan.requiredSkills.map((skill) => legacy[skill]))]; const skillCoverage = Object.fromEntries(capabilityPlan.requiredSkills.map((skill) => [skill, legacy[skill]])); void availableSections; void identity; const materialized = this.materialize(message, capabilityPlan, { requiredSkills: capabilityPlan.requiredSkills, selectedAgents, skillCoverage, unresolvedSkills: [], readinessWarnings: [], expectedRisk: "moderate", expectedProviderCalls: selectedAgents.length * 2, candidateCount: selectedAgents.length }); return { directAnswerPossible: materialized.directAnswerPossible, tasks: materialized.tasks }; }
}
