import type { AgentId, AgentSpec } from "@averon/agent-contracts";
import { workerSchemaVersions } from "./schemas.ts";
const record = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === "object" && !Array.isArray(value); const strings = (value: unknown): value is string[] => Array.isArray(value) && value.every((item) => typeof item === "string");
export function isValidAgentSpec(value: unknown): value is AgentSpec { if (!record(value)) return false; const requiredText = [value.id, value.name, value.domain, value.description, value.version, value.inputSchema, value.outputSchema]; return requiredText.every((item) => typeof item === "string" && item.length > 0) && [value.skills, value.capabilities, value.allowedTaskTypes, value.providerRequirements, value.modelRequirements, value.toolRequirements, value.requiredPermissions, value.executionRights, value.verificationRequirements, value.readinessRequirements].every(strings) && ["low", "moderate", "high", "critical"].includes(String(value.riskLevel)) && ["low", "medium", "high"].includes(String(value.costClass)) && typeof value.maxProviderCalls === "number" && value.maxProviderCalls >= 0 && typeof value.maxRuntimeMs === "number" && value.maxRuntimeMs > 0 && typeof value.enabled === "boolean" && typeof value.experimental === "boolean" && record(value.certification); }

const common: Pick<AgentSpec, "version" | "capabilities" | "providerRequirements" | "modelRequirements" | "toolRequirements" | "requiredPermissions" | "businessOsAccess" | "executionMode" | "executionRights" | "costClass" | "maxProviderCalls" | "maxRuntimeMs" | "inputSchema" | "verificationRequirements" | "enabled" | "experimental" | "readinessRequirements"> = { version: "1.0.0", capabilities: ["structured_recommendation"], providerRequirements: ["ai.text_generation"], modelRequirements: ["structured_output"], toolRequirements: [], requiredPermissions: ["emmy:use"], businessOsAccess: "internal", executionMode: "provider", executionRights: ["read", "analyze", "draft", "recommend"], costClass: "low", maxProviderCalls: 2, maxRuntimeMs: 20_000, inputSchema: "agent-task.v1", verificationRequirements: ["validator_only"], enabled: true, experimental: false, readinessRequirements: ["provider", "schema", "skills", "permissions", "certification"] };
export const productionAgentSpecs: readonly AgentSpec[] = [
  { ...common, id: "research", name: "Research AI", domain: "research", description: "Synthesizes authorized internal information and identifies research gaps.", skills: ["research.internal_synthesis"], allowedTaskTypes: ["research"], riskLevel: "low", outputSchema: workerSchemaVersions.research, certification: { lastEvalStatus: "passed", certificationStatus: "passed", certifiedSchemaVersion: workerSchemaVersions.research } },
  { ...common, id: "seo", name: "SEO AI", domain: "seo", description: "Produces source-bounded SEO recommendations without live metrics.", skills: ["seo.content_strategy", "seo.metadata"], allowedTaskTypes: ["seo"], riskLevel: "low", outputSchema: workerSchemaVersions.seo, certification: { lastEvalStatus: "passed", certificationStatus: "passed", certifiedSchemaVersion: workerSchemaVersions.seo } },
  { ...common, id: "blog", name: "Blog/Writing AI", domain: "content", description: "Creates drafts without publishing.", skills: ["content.blog_drafting"], allowedTaskTypes: ["writing"], riskLevel: "moderate", outputSchema: workerSchemaVersions.blog, certification: { lastEvalStatus: "passed", certificationStatus: "passed", certifiedSchemaVersion: workerSchemaVersions.blog } },
  { ...common, id: "analytics", name: "Analytics AI", domain: "analytics", description: "Interprets supplied or authorized internal data.", skills: ["analytics.interpretation"], allowedTaskTypes: ["analytics"], riskLevel: "moderate", outputSchema: workerSchemaVersions.analytics, certification: { lastEvalStatus: "passed", certificationStatus: "passed", certifiedSchemaVersion: workerSchemaVersions.analytics } },
  { ...common, id: "documentation", name: "Documentation AI", domain: "documentation", description: "Drafts internal documentation and reports.", skills: ["documentation.sop_drafting"], allowedTaskTypes: ["documentation"], riskLevel: "moderate", outputSchema: workerSchemaVersions.documentation, certification: { lastEvalStatus: "passed", certificationStatus: "passed", certifiedSchemaVersion: workerSchemaVersions.documentation } },
  { ...common, id: "frontend", name: "Frontend Development AI", domain: "development", description: "Analyzes frontend architecture, React/TypeScript, UI, accessibility, performance, and debugging.", skills: ["development.frontend_analysis"], allowedTaskTypes: ["frontend-analysis"], riskLevel: "moderate", maxProviderCalls: 1, outputSchema: workerSchemaVersions.frontend, certification: { lastEvalStatus: "passed", certificationStatus: "passed", certifiedSchemaVersion: workerSchemaVersions.frontend } },
  { ...common, id: "backend", name: "Backend Development AI", domain: "development", description: "Analyzes API, server, authorization, integration, and backend designs.", skills: ["development.backend_architecture", "development.backend_analysis"], allowedTaskTypes: ["backend-analysis"], riskLevel: "moderate", maxProviderCalls: 1, outputSchema: workerSchemaVersions.backend, certification: { lastEvalStatus: "passed", certificationStatus: "passed", certifiedSchemaVersion: workerSchemaVersions.backend } },
  { ...common, id: "database", name: "Database AI", domain: "database", description: "Analyzes data models, schemas, indexes, migrations, and integrity without database operations.", skills: ["database.schema_design"], allowedTaskTypes: ["database-analysis"], riskLevel: "moderate", maxProviderCalls: 1, outputSchema: workerSchemaVersions.database, certification: { lastEvalStatus: "passed", certificationStatus: "passed", certifiedSchemaVersion: workerSchemaVersions.database } },
  { ...common, id: "testing", name: "Testing/QA AI", domain: "quality", description: "Drafts test strategies, cases, regression plans, edge cases, and acceptance criteria.", skills: ["quality.test_strategy"], allowedTaskTypes: ["test-strategy"], riskLevel: "moderate", maxProviderCalls: 1, outputSchema: workerSchemaVersions.testing, certification: { lastEvalStatus: "passed", certificationStatus: "passed", certifiedSchemaVersion: workerSchemaVersions.testing } },
  { ...common, id: "security", name: "Security AI", domain: "security", description: "Reviews authorization, tenancy, APIs, secrets, threats, and data exposure without offensive execution.", skills: ["security.architecture_review"], allowedTaskTypes: ["security-review"], riskLevel: "high", maxProviderCalls: 1, verificationRequirements: ["validator_only", "independent_critic"], outputSchema: workerSchemaVersions.security, certification: { lastEvalStatus: "passed", certificationStatus: "passed", certifiedSchemaVersion: workerSchemaVersions.security } },
  { ...common, id: "business-operations", name: "Business Operations AI", domain: "operations", description: "Analyzes workflows, SOPs, coordination, and operational optimization.", skills: ["operations.workflow_analysis"], allowedTaskTypes: ["operations-analysis"], riskLevel: "moderate", maxProviderCalls: 1, outputSchema: workerSchemaVersions["business-operations"], certification: { lastEvalStatus: "passed", certificationStatus: "passed", certifiedSchemaVersion: workerSchemaVersions["business-operations"] } },
  { ...common, id: "marketing", name: "Marketing AI", domain: "marketing", description: "Develops positioning, campaign, acquisition, messaging, and conversion recommendations.", skills: ["marketing.strategy"], allowedTaskTypes: ["marketing-strategy"], riskLevel: "moderate", maxProviderCalls: 1, outputSchema: workerSchemaVersions.marketing, certification: { lastEvalStatus: "passed", certificationStatus: "passed", certifiedSchemaVersion: workerSchemaVersions.marketing } },
  { ...common, id: "sales", name: "Sales AI", domain: "sales", description: "Analyzes sales, lead, proposal, quotation, conversion, and customer journey strategy without customer actions.", skills: ["sales.strategy"], allowedTaskTypes: ["sales-strategy"], riskLevel: "moderate", maxProviderCalls: 1, outputSchema: workerSchemaVersions.sales, certification: { lastEvalStatus: "passed", certificationStatus: "passed", certifiedSchemaVersion: workerSchemaVersions.sales } },
  { ...common, id: "customer-operations", name: "Customer Operations AI", domain: "customer", description: "Analyzes customer requests, support workflows, communication drafts, and escalation recommendations.", skills: ["customer.operations"], allowedTaskTypes: ["customer-operations"], riskLevel: "moderate", maxProviderCalls: 1, outputSchema: workerSchemaVersions["customer-operations"], certification: { lastEvalStatus: "passed", certificationStatus: "passed", certifiedSchemaVersion: workerSchemaVersions["customer-operations"] } },
  { ...common, id: "critic", name: "Critic/Verifier AI", domain: "verification", description: "Independently verifies structured upstream outputs for evidence, contradictions, requirements, and risk.", skills: ["verification.independent_review"], allowedTaskTypes: ["verification"], riskLevel: "high", maxProviderCalls: 1, outputSchema: workerSchemaVersions.critic, certification: { lastEvalStatus: "passed", certificationStatus: "passed", certifiedSchemaVersion: workerSchemaVersions.critic } },
  { ...common, id: "guardian", name: "Guardian", domain: "website-reliability", description: "Inspects registered website health evidence, classifies incidents, and recommends maintenance without repairs or mutation.", skills: ["website.health_check", "website.health_report"], allowedTaskTypes: ["website-health"], riskLevel: "moderate", maxProviderCalls: 1, outputSchema: workerSchemaVersions.guardian, certification: { lastEvalStatus: "passed", certificationStatus: "passed", certifiedSchemaVersion: workerSchemaVersions.guardian } },
];

export class DefaultAgentRegistry {
  private readonly byId = new Map<AgentId, AgentSpec>(); private readonly bySkill = new Map<string, AgentSpec[]>(); private readonly byDomain = new Map<string, AgentSpec[]>();
  constructor(definitions: readonly AgentSpec[] = productionAgentSpecs) { for (const definition of definitions) { if (!isValidAgentSpec(definition)) throw new Error("INVALID_AGENT_SPEC"); if (this.byId.has(definition.id)) throw new Error(`DUPLICATE_AGENT:${definition.id}`); this.byId.set(definition.id, definition); this.byDomain.set(definition.domain, [...(this.byDomain.get(definition.domain) ?? []), definition]); for (const skill of definition.skills) this.bySkill.set(skill, [...(this.bySkill.get(skill) ?? []), definition]); } }
  get(id: AgentId) { return this.byId.get(id); }
  list() { return [...this.byId.values()]; }
  listBySkill(skillId: string) { return [...(this.bySkill.get(skillId) ?? [])]; }
  listByDomain(domain: string) { return [...(this.byDomain.get(domain) ?? [])]; }
  listEnabled() { return this.list().filter((agent) => agent.enabled); }
}
