import { useEffect, useState, type FormEvent } from "react";
import type { WorkspaceAutomation, WorkspaceAutomationDetail, WorkspaceAutomationTrigger, WorkspaceSummary, WorkspaceTaskPriority } from "@averon/shared-types";
import { averonApi } from "./api";
type Draft = { title: string; description: string; enabled: boolean; triggerType: "ONCE" | "DAILY" | "WEEKLY"; runAt: string; time: string; weekday: number; timezone: string; taskTitle: string; taskDescription: string; priority: WorkspaceTaskPriority; assignedAgentIds: string[] };
const empty: Draft = { title: "", description: "", enabled: false, triggerType: "WEEKLY", runAt: "", time: "09:00", weekday: 1, timezone: "Europe/Rome", taskTitle: "", taskDescription: "", priority: "NORMAL", assignedAgentIds: [] };
const priorities: WorkspaceTaskPriority[] = ["LOW", "NORMAL", "HIGH", "URGENT"];
const weekdays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];
const when = (value: unknown) => typeof value === "string" && !Number.isNaN(Date.parse(value)) ? new Date(value).toLocaleString() : "—";
function triggerText(trigger: WorkspaceAutomationTrigger) { if (trigger.type === "ONCE") return `Once · ${when(trigger.runAt)}`; if (trigger.type === "DAILY") return `Daily · ${trigger.time}`; return `Every ${weekdays[trigger.weekday - 1]} · ${trigger.time}`; }
function toDraft(item: WorkspaceAutomation): Draft { return { title: item.title, description: item.description, enabled: item.enabled, triggerType: item.trigger.type, runAt: item.trigger.type === "ONCE" ? item.trigger.runAt.slice(0, 16) : "", time: item.trigger.type === "ONCE" ? "09:00" : item.trigger.time, weekday: item.trigger.type === "WEEKLY" ? item.trigger.weekday : 1, timezone: item.trigger.timezone, taskTitle: item.operation.taskTemplate.title, taskDescription: item.operation.taskTemplate.description, priority: item.operation.taskTemplate.priority, assignedAgentIds: item.operation.taskTemplate.assignedAgentIds } }
function trigger(draft: Draft): WorkspaceAutomationTrigger { return draft.triggerType === "ONCE" ? { type: "ONCE", runAt: new Date(draft.runAt).toISOString(), timezone: draft.timezone } : draft.triggerType === "DAILY" ? { type: "DAILY", time: draft.time, timezone: draft.timezone } : { type: "WEEKLY", weekday: draft.weekday as 1, time: draft.time, timezone: draft.timezone }; }
export function AutomationsControlCenter({ workspace }: { workspace?: WorkspaceSummary }) { return <AutomationWorkspace key={workspace?.workspace.id ?? "none"} workspace={workspace}/>; }
function AutomationWorkspace({ workspace }: { workspace?: WorkspaceSummary }) {
  const workspaceId = workspace?.workspace.id ?? ""; const [data, setData] = useState<Awaited<ReturnType<typeof averonApi.automations.list>>["data"] | null>(null); const [selected, setSelected] = useState<WorkspaceAutomationDetail | null>(null); const [draft, setDraft] = useState<Draft | null>(null); const [editing, setEditing] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { let active = true; if (workspaceId) averonApi.automations.list(workspaceId).then((response) => { if (active) setData(response.data); }).catch(() => { if (active) setError("Automations could not be loaded."); }); return () => { active = false; }; }, [workspaceId]);
  if (!workspace) return <section><h1>Automations</h1><p>Select an authorized workspace.</p></section>; if (!data) return error ? <p role="alert">{error}</p> : <div className="loading-list" aria-label="Loading Automations"><i/><i/><i/></div>;
  const identities = data.agentIdentities;
  const picker = (value: Draft, update: (next: Draft) => void) => <fieldset><legend>Assigned specialists</legend>{Object.entries(identities).map(([id, identity]) => <label key={id}><input type="checkbox" checked={value.assignedAgentIds.includes(id)} onChange={(event) => update({ ...value, assignedAgentIds: event.target.checked ? [...value.assignedAgentIds, id] : value.assignedAgentIds.filter((item) => item !== id) })}/>{identity.displayName} · {identity.displayRole}</label>)}</fieldset>;
  async function open(item: WorkspaceAutomation) { try { setSelected((await averonApi.automations.get(workspaceId, item.id)).data); setDraft(null); setEditing(false); } catch { setError("The Automation could not be loaded."); } }
  async function save(event: FormEvent) { event.preventDefault(); if (!draft || !data!.canManage) return; setSaving(true); const input = { title: draft.title, description: draft.description, enabled: draft.enabled, trigger: trigger(draft), operation: { type: "CREATE_TASK" as const, taskTemplate: { title: draft.taskTitle, description: draft.taskDescription, priority: draft.priority, assignedAgentIds: draft.assignedAgentIds } } }; try { if (selected && editing) await averonApi.automations.update(workspaceId, selected.id, { expectedVersion: selected.version, ...input }); else await averonApi.automations.create(workspaceId, input); setData((await averonApi.automations.list(workspaceId)).data); if (selected) setSelected((await averonApi.automations.get(workspaceId, selected.id)).data); else setDraft(null); setEditing(false); } catch { setError("The Automation change was rejected."); } finally { setSaving(false); } }
  async function toggle(item: WorkspaceAutomationDetail) { if (!data!.canManage) return; setSaving(true); try { await averonApi.automations.update(workspaceId, item.id, { expectedVersion: item.version, enabled: !item.enabled }); const detail = (await averonApi.automations.get(workspaceId, item.id)).data; setSelected(detail); setData((current) => current && ({ ...current, items: current.items.map((candidate) => candidate.id === detail.id ? detail : candidate) })); } catch { setError("The Automation status could not be changed."); } finally { setSaving(false); } }
  const form = draft && <form className="task-form automation-form" onSubmit={save}><label>Title<input aria-label="Automation title" value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} required/></label><label>Description<textarea aria-label="Automation description" value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} required/></label><label>Schedule<select aria-label="Schedule type" value={draft.triggerType} onChange={(event) => setDraft({ ...draft, triggerType: event.target.value as Draft["triggerType"] })}><option>ONCE</option><option>DAILY</option><option>WEEKLY</option></select></label>{draft.triggerType === "ONCE" ? <label>Run at<input aria-label="Run at" type="datetime-local" value={draft.runAt} onChange={(event) => setDraft({ ...draft, runAt: event.target.value })} required/></label> : <label>Time<input aria-label="Schedule time" type="time" value={draft.time} onChange={(event) => setDraft({ ...draft, time: event.target.value })} required/></label>}{draft.triggerType === "WEEKLY" && <label>Weekday<select aria-label="Weekday" value={draft.weekday} onChange={(event) => setDraft({ ...draft, weekday: Number(event.target.value) })}>{weekdays.map((day, index) => <option value={index + 1} key={day}>{day}</option>)}</select></label>}<label>Timezone<input aria-label="Timezone" value={draft.timezone} onChange={(event) => setDraft({ ...draft, timezone: event.target.value })} required/></label><label><input type="checkbox" checked={draft.enabled} onChange={(event) => setDraft({ ...draft, enabled: event.target.checked })}/>Enabled immediately</label><h3>Create Task</h3><label>Task title<input aria-label="Task title" value={draft.taskTitle} onChange={(event) => setDraft({ ...draft, taskTitle: event.target.value })} required/></label><label>Task description<textarea aria-label="Task description" value={draft.taskDescription} onChange={(event) => setDraft({ ...draft, taskDescription: event.target.value })} required/></label><label>Task priority<select aria-label="Task priority" value={draft.priority} onChange={(event) => setDraft({ ...draft, priority: event.target.value as WorkspaceTaskPriority })}>{priorities.map((item) => <option key={item}>{item}</option>)}</select></label>{picker(draft, setDraft)}<div><button type="submit" disabled={saving}>{saving ? "Saving…" : editing ? "Save Automation" : "Create Automation"}</button><button type="button" onClick={() => { setDraft(null); setEditing(false); }}>Cancel</button></div></form>;
  if (selected) return <section className="tasks-page"><button className="text-link" type="button" onClick={() => { setSelected(null); setDraft(null); }}>← All Automations</button><header className="task-detail-head"><div><small>Automation · v{selected.version}</small><h1>{selected.title}</h1><p>{selected.description}</p></div><span>{selected.enabled ? "Enabled" : "Paused"}</span></header>{form}<div className="task-detail-grid"><article><h2>Schedule</h2><p>{triggerText(selected.trigger)}</p><p>{selected.trigger.timezone}</p><p>Operation: Create Task</p><strong>{selected.operation.taskTemplate.title}</strong><p>Created: {when(selected.createdAt)}</p><p>Updated: {when(selected.updatedAt)}</p><p>Last trigger: {when(selected.lastTriggeredAt)}</p><p>Next trigger: {when(selected.nextRunAt)}</p>{data.canManage && <div><button type="button" onClick={() => { setDraft(toDraft(selected)); setEditing(true); }}>Edit</button><button type="button" disabled={saving} onClick={() => void toggle(selected)}>{selected.enabled ? "Pause" : "Enable"}</button></div>}</article><article><h2>History</h2>{selected.history.map((item) => <div className="task-history" key={item.id}><strong>{item.eventType.replaceAll("automation.", "").replaceAll("_", " ")}</strong><span>{item.createdTaskId ?? item.safeErrorCode ?? "Recorded"}</span><time>{when(item.occurredAt)}</time></div>)}</article></div>{error && <p role="alert">{error}</p>}</section>;
  return <section className="tasks-page"><header className="tasks-heading"><div><p className="eyebrow">Automations — {data.workspace.name}</p><h1>Workspace Automations</h1><p>Deterministic schedules create Tasks; they never execute specialists directly.</p></div>{data.canManage && <button type="button" onClick={() => setDraft({ ...empty })}>New Automation</button>}</header>{form}<div className="task-list automation-list">{data.items.map((item) => <button key={item.id} type="button" onClick={() => void open(item)}><span><strong>{item.title}</strong><small>{triggerText(item.trigger)} · {item.trigger.timezone}</small><small>Creates Task: {item.operation.taskTemplate.title}</small></span><em>{item.enabled ? "Enabled" : "Paused"}</em><time>Next: {when(item.nextRunAt)}</time></button>)}</div>{error && <p role="alert">{error}</p>}</section>;
}
