import { useEffect, useMemo, useState, type FormEvent } from "react";
import { useParams } from "react-router";
import type { BusinessDecision, BusinessDecisionStatus, BusinessOs, BusinessOsHistoryItem, BusinessOsSection, BusinessOsVisibility } from "@averon/shared-types";
import { averonApi } from "./api";
type View = "overview" | "knowledge" | "decisions" | "history";
type Loaded = { workspaceId: string; root: BusinessOs | null; workspaceName: string; canManage: boolean; sections: BusinessOsSection[]; decisions: BusinessDecision[]; history: BusinessOsHistoryItem[] };
type DecisionDraft = { mode: "create" | "edit"; id: string; title: string; summary: string; rationale: string; status: BusinessDecisionStatus; effectiveDate: string };
const date = (value: unknown) => { if (typeof value === "string" || typeof value === "number") { const parsed = new Date(value); return Number.isNaN(parsed.valueOf()) ? "Not recorded" : parsed.toLocaleString(); } if (value && typeof value === "object" && "_seconds" in value) return new Date(Number((value as { _seconds: unknown })._seconds) * 1000).toLocaleString(); return "Not recorded"; };
const epoch = (value: unknown) => { if (typeof value === "string" || typeof value === "number") { const parsed = new Date(value).valueOf(); return Number.isNaN(parsed) ? 0 : parsed; } if (value && typeof value === "object" && "_seconds" in value) return Number((value as { _seconds: unknown })._seconds) * 1000; return 0; };
const searchable = (value: unknown) => JSON.stringify(value).toLowerCase();
export function BusinessOsControlCenter() {
  const { workspaceId = "" } = useParams(); const [data, setData] = useState<Loaded | null>(null); const [view, setView] = useState<View>("overview"); const [query, setQuery] = useState(""); const [selected, setSelected] = useState<BusinessOsSection | null>(null); const [editing, setEditing] = useState(false); const [title, setTitle] = useState(""); const [visibility, setVisibility] = useState<BusinessOsVisibility>("internal"); const [content, setContent] = useState(""); const [decisionDraft, setDecisionDraft] = useState<DecisionDraft | null>(null); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { let active = true; Promise.all([averonApi.businessOs.get(workspaceId), averonApi.businessOs.listSections(workspaceId), averonApi.businessOs.listDecisions(workspaceId), averonApi.businessOs.history(workspaceId)]).then(([root, sections, decisions, history]) => { if (active) { setData({ workspaceId, root: root.data.businessOs, workspaceName: root.data.workspace.name, canManage: root.data.access.canManage, sections: sections.data.items, decisions: decisions.data.items, history: history.data.items }); setSelected(null); setDecisionDraft(null); setEditing(false); setView("overview"); setQuery(""); setError(""); } }).catch(() => { if (active) { setData(null); setDecisionDraft(null); setError("Business OS could not be loaded for this workspace."); } }); return () => { active = false; }; }, [workspaceId]);
  const term = query.trim().toLowerCase(); const sections = useMemo(() => data?.sections.filter((item) => !term || searchable({ title: item.title, type: item.type, content: item.content }).includes(term)) ?? [], [data, term]); const decisions = useMemo(() => data?.decisions.filter((item) => !term || searchable({ title: item.title, summary: item.summary, rationale: item.rationale, status: item.status }).includes(term)) ?? [], [data, term]);
  const dirty = selected ? title !== selected.title || visibility !== selected.visibility || content !== JSON.stringify(selected.content, null, 2) : false;
  function open(item: BusinessOsSection) { setSelected(item); setEditing(false); setTitle(item.title); setVisibility(item.visibility); setContent(JSON.stringify(item.content, null, 2)); setError(""); }
  async function save(event: FormEvent) { event.preventDefault(); if (!selected || !data?.canManage) return; setSaving(true); setError(""); try { const response = await averonApi.businessOs.updateSection(workspaceId, selected.id, { title, visibility, content: JSON.parse(content) as BusinessOsSection["content"] }); setData((current) => current ? { ...current, sections: current.sections.map((item) => item.id === response.data.id ? response.data : item) } : current); open(response.data); } catch { setError("The section could not be saved. Check its structured content and your permission."); } finally { setSaving(false); } }
  function editDecision(item?: BusinessDecision) { setDecisionDraft(item ? { mode: "edit", id: item.id, title: item.title, summary: item.summary, rationale: item.rationale ?? "", status: item.status, effectiveDate: item.effectiveDate ?? "" } : { mode: "create", id: "", title: "", summary: "", rationale: "", status: "proposed", effectiveDate: "" }); setError(""); }
  async function saveDecision(event: FormEvent) { event.preventDefault(); if (!decisionDraft || !data?.canManage) return; setSaving(true); setError(""); const input = { title: decisionDraft.title, summary: decisionDraft.summary, rationale: decisionDraft.rationale || undefined, status: decisionDraft.status, effectiveDate: decisionDraft.effectiveDate || undefined }; try { const response = decisionDraft.mode === "create" ? await averonApi.businessOs.createDecision(workspaceId, { id: decisionDraft.id, ...input }) : await averonApi.businessOs.updateDecision(workspaceId, decisionDraft.id, input); setData((current) => current ? { ...current, decisions: decisionDraft.mode === "create" ? [...current.decisions, response.data] : current.decisions.map((item) => item.id === response.data.id ? response.data : item) } : current); setDecisionDraft(null); } catch { setError("The decision could not be saved. Check its fields and your permission."); } finally { setSaving(false); } }
  if (error && !data) return <section className="business-control"><h1>Business OS</h1><p role="alert">{error}</p></section>; if (!data || data.workspaceId !== workspaceId) return <div className="loading-list" aria-label="Loading Business OS"><i/><i/><i/></div>; if (!data.root) return <section className="business-control"><h1>Business OS</h1><p>Business OS is not initialized for {data.workspaceName}.</p></section>;
  const restricted = data.sections.filter((item) => item.visibility === "restricted").length; const latestUpdate = [...data.sections.map((item) => item.updatedAt), ...data.decisions.map((item) => item.updatedAt)].sort((left, right) => epoch(right) - epoch(left))[0]; const updated = date(latestUpdate);
  return <section className="business-control"><header className="business-control-heading"><div><p className="eyebrow">Business OS — {data.workspaceName}</p><h1>Operational knowledge</h1><p>Authoritative, versioned workspace knowledge used by Emmy through bounded retrieval.</p></div><span className="status-badge">Schema v{data.root.schemaVersion}</span></header><nav className="business-tabs" aria-label="Business OS views">{(["overview", "knowledge", "decisions", "history"] as View[]).map((item) => <button type="button" className={view === item ? "active" : ""} key={item} onClick={() => { setView(item); setSelected(null); }}>{item}</button>)}</nav>{view !== "overview" && <label className="business-search">Search accessible records<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search Business OS"/></label>}
  {view === "overview" && <><div className="business-metrics"><article><strong>{data.sections.length}</strong><small>Knowledge sections</small></article><article><strong>{data.decisions.length}</strong><small>Decisions</small></article><article><strong>{restricted}</strong><small>Restricted sections visible</small></article><article><strong>{updated}</strong><small>Last updated</small></article></div><div className="business-summary"><h2>Knowledge structure</h2>{[...new Set(data.sections.map((item) => item.type))].map((type) => <span key={type}>{type}</span>)}</div></>}
  {view === "knowledge" && (selected ? <article className="business-detail"><button type="button" className="text-link" onClick={() => setSelected(null)}>← All knowledge</button><header><div><small>{selected.type}</small><h2>{selected.title}</h2></div><span>{selected.visibility} · v{selected.version}</span></header>{editing ? <form onSubmit={save}><label>Title<input value={title} onChange={(event) => setTitle(event.target.value)} required/></label><label>Visibility<select value={visibility} onChange={(event) => setVisibility(event.target.value as BusinessOsVisibility)}><option value="public">Public</option><option value="internal">Internal</option><option value="restricted">Restricted</option></select></label><label>Structured content<textarea rows={14} value={content} onChange={(event) => setContent(event.target.value)}/></label><div>{dirty && <span role="status">Unsaved changes</span>}<button type="submit" disabled={saving || !dirty}>{saving ? "Saving…" : "Save"}</button><button type="button" onClick={() => open(selected)}>Cancel</button></div></form> : <><p>{selected.content.summary}</p><dl>{Object.entries(selected.content.fields).map(([key, value]) => <div key={key}><dt>{key.replaceAll("_", " ")}</dt><dd>{typeof value === "object" ? JSON.stringify(value) : String(value)}</dd></div>)}</dl><footer><span>Version {selected.version}</span><span>Updated {date(selected.updatedAt)}</span><span>Source: Business OS section {selected.id}</span>{data.canManage && <button type="button" onClick={() => setEditing(true)}>Edit</button>}</footer></>}</article> : <div className="knowledge-grid">{sections.map((item) => <button type="button" key={item.id} onClick={() => open(item)}><small>{item.type}</small><strong>{item.title}</strong><span>{item.visibility} · v{item.version}</span><p>{item.content.summary}</p><time>{date(item.updatedAt)}</time></button>)}</div>)}
  {view === "decisions" && <div className="decision-list">{data.canManage && !decisionDraft && <button type="button" className="text-link" onClick={() => editDecision()}>New decision</button>}{decisionDraft && <form className="business-decision-form" onSubmit={saveDecision}>{decisionDraft.mode === "create" && <label>Decision ID<input value={decisionDraft.id} onChange={(event) => setDecisionDraft({ ...decisionDraft, id: event.target.value })} required/></label>}<label>Title<input value={decisionDraft.title} onChange={(event) => setDecisionDraft({ ...decisionDraft, title: event.target.value })} required/></label><label>Summary<textarea value={decisionDraft.summary} onChange={(event) => setDecisionDraft({ ...decisionDraft, summary: event.target.value })} required/></label><label>Rationale<textarea value={decisionDraft.rationale} onChange={(event) => setDecisionDraft({ ...decisionDraft, rationale: event.target.value })}/></label><label>Status<select value={decisionDraft.status} onChange={(event) => setDecisionDraft({ ...decisionDraft, status: event.target.value as BusinessDecisionStatus })}><option value="proposed">Proposed</option><option value="active">Active</option><option value="superseded">Superseded</option><option value="archived">Archived</option></select></label><label>Effective date<input type="date" value={decisionDraft.effectiveDate} onChange={(event) => setDecisionDraft({ ...decisionDraft, effectiveDate: event.target.value })}/></label><div><span role="status">Unsaved changes</span><button type="submit" disabled={saving}>{saving ? "Saving…" : "Save decision"}</button><button type="button" onClick={() => setDecisionDraft(null)}>Cancel</button></div></form>}{decisions.map((item) => <article key={item.id}><header><div><small>Decision</small><h2>{item.title}</h2></div><span>{item.status}</span></header><p>{item.summary}</p>{item.rationale && <details><summary>Rationale</summary><p>{item.rationale}</p></details>}<footer>v{item.version} · Updated {date(item.updatedAt)}{item.effectiveDate ? ` · Effective ${item.effectiveDate}` : ""}{data.canManage && <button type="button" onClick={() => editDecision(item)}>Edit decision</button>}</footer></article>)}</div>}
  {view === "history" && <div className="history-list">{data.history.filter((item) => !term || searchable(item).includes(term)).map((item) => <article key={item.id}><strong>{item.eventType.replaceAll("_", " ")}</strong><span>{item.targetType} · {item.targetId}{item.version ? ` · v${item.version}` : ""}</span><time>{date(item.occurredAt)}</time></article>)}</div>}{error && <p role="alert">{error}</p>}</section>;
}
