import type { BlogDraft } from "@averon/shared-types";
import { ApiError } from "../../errors/api-error.ts";
import { getFirebaseAdminServices } from "../../services/firebase/admin.ts";
import type { BlogDraftCreatePayload, BlogDraftRepository, BlogDraftUpdatePatch } from "./blog-draft.types.ts";

export class FirebaseBlogDraftRepository implements BlogDraftRepository {
  private readonly db = getFirebaseAdminServices().firestore;
  async get(workspaceId: string, draftId: string) { const found = await this.db.collection("blogDrafts").doc(draftId).get(); const item = found.exists ? found.data() as BlogDraft : null; return item?.workspaceId === workspaceId ? { ...item, id: found.id } : null; }
  async create(actionId: string, input: BlogDraftCreatePayload & { workspaceId: string; businessId: string; actorId: string }) {
    const actionRef = this.db.collection("actionExecutions").doc(actionId); const draftRef = this.db.collection("blogDrafts").doc(); const now = new Date().toISOString();
    return this.db.runTransaction(async (tx) => { const action = await tx.get(actionRef); if (action.exists) { const data = action.data() as { workspaceId?: string; actionType?: string; draftId?: string }; if (data.workspaceId !== input.workspaceId || data.actionType !== "blog.draft.create" || !data.draftId) throw new ApiError(409, "ACTION_IDEMPOTENCY_CONFLICT", "The action ID is already used by another operation."); const existing = await tx.get(this.db.collection("blogDrafts").doc(data.draftId)); if (!existing.exists) throw new ApiError(500, "ACTION_VERIFICATION_FAILED", "The prior draft action cannot be verified."); return { draft: { ...(existing.data() as BlogDraft), id: existing.id }, duplicate: true }; }
      const draft: BlogDraft = { id: draftRef.id, workspaceId: input.workspaceId, businessId: input.businessId, title: input.title, slug: input.slug, excerpt: input.excerpt, body: input.body, ...(input.seoTitle ? { seoTitle: input.seoTitle } : {}), ...(input.metaDescription ? { metaDescription: input.metaDescription } : {}), ...(input.tags ? { tags: input.tags } : {}), status: "draft", published: false, createdBy: input.actorId, updatedBy: input.actorId, createdAt: now, updatedAt: now };
      tx.create(draftRef, draft); tx.create(actionRef, { actionId, workspaceId: input.workspaceId, actionType: "blog.draft.create", draftId: draft.id, status: "completed", createdAt: now }); tx.create(this.db.collection("auditLogs").doc(), { actorId: input.actorId, action: "BLOG_DRAFT_CREATED", targetCollection: "blogDrafts", targetId: draft.id, workspaceId: input.workspaceId, businessId: input.businessId, actionId, createdAt: now }); return { draft, duplicate: false };
    });
  }
  async update(actionId: string, workspaceId: string, draftId: string, patch: BlogDraftUpdatePatch, actorId: string) {
    const actionRef = this.db.collection("actionExecutions").doc(actionId); const draftRef = this.db.collection("blogDrafts").doc(draftId); const now = new Date().toISOString();
    return this.db.runTransaction(async (tx) => { const action = await tx.get(actionRef); if (action.exists) { const data = action.data() as { workspaceId?: string; actionType?: string; draftId?: string }; if (data.workspaceId !== workspaceId || data.actionType !== "blog.draft.update" || data.draftId !== draftId) throw new ApiError(409, "ACTION_IDEMPOTENCY_CONFLICT", "The action ID is already used by another operation."); const existing = await tx.get(draftRef); if (!existing.exists) throw new ApiError(500, "ACTION_VERIFICATION_FAILED", "The prior draft action cannot be verified."); return { draft: { ...(existing.data() as BlogDraft), id: existing.id }, duplicate: true }; }
      const found = await tx.get(draftRef); if (!found.exists) throw new ApiError(404, "BLOG_DRAFT_NOT_FOUND", "The blog draft was not found."); const current = { ...(found.data() as BlogDraft), id: found.id }; if (current.workspaceId !== workspaceId) throw new ApiError(403, "ACTION_FORBIDDEN", "The blog draft belongs to another workspace."); if (current.published || current.status !== "draft") throw new ApiError(400, "ACTION_UNSUPPORTED", "Only unpublished drafts may be updated."); const draft = { ...current, ...patch, published: false as const, status: "draft" as const, updatedBy: actorId, updatedAt: now };
      tx.update(draftRef, { ...patch, published: false, status: "draft", updatedBy: actorId, updatedAt: now }); tx.create(actionRef, { actionId, workspaceId, actionType: "blog.draft.update", draftId, status: "completed", createdAt: now }); tx.create(this.db.collection("auditLogs").doc(), { actorId, action: "BLOG_DRAFT_UPDATED", targetCollection: "blogDrafts", targetId: draftId, workspaceId, businessId: current.businessId, actionId, createdAt: now }); return { draft, duplicate: false };
    });
  }
}
