import type { PageContent, PageContentActionMetadata, PageContentField, StaticPageId } from "@averon/shared-types";
import type { AuthContext } from "../../services/auth/authentication.ts";
import { ApiError } from "../../errors/api-error.ts";
import { log } from "../../logger.ts";
import type { WorkspaceAuthorizationService } from "../workspaces/workspace.service.ts";
import type { PageContentRepository } from "./page-content.types.ts";

const allowed: Record<string, readonly PageContentField[]> = { hero: ["heading", "subheading"], primaryCta: ["label", "supportingCopy"], intro: ["heading", "intro"], aiSolutions: ["title", "description"] };
const unsafe = /<[^>]+>|javascript:|\bon\w+\s*=|<script/i;
export function parsePageContentPatch(sectionId: string, value: unknown) { if (!value || typeof value !== "object" || Array.isArray(value)) throw new ApiError(400, "ACTION_PAYLOAD_INVALID", "A partial content patch is required."); const entries = Object.entries(value as Record<string, unknown>); if (!entries.length || entries.some(([key, item]) => !allowed[sectionId]?.includes(key as PageContentField) || typeof item !== "string" || !item.trim() || item.length > 500 || unsafe.test(item))) throw new ApiError(400, "ACTION_PAYLOAD_INVALID", "Only safe allowlisted content fields may be changed."); return Object.fromEntries(entries.map(([key, item]) => [key, String(item).trim()])) as Partial<Record<PageContentField, string>>; }
const page = (text: string): StaticPageId | undefined => /\bhome(?:page)?\b/i.test(text) ? "home" : /\bservices?\s+page\b|\/services\b/i.test(text) ? "services" : undefined;
const section = (text: string) => /\bhero\b/i.test(text) ? "hero" : /\b(?:primary\s+)?cta\b|call\s+to\s+action/i.test(text) ? "primaryCta" : /\b(?:introduction|intro)\b/i.test(text) ? "intro" : /\bai\s+solutions?\b/i.test(text) ? "aiSolutions" : undefined;
const mutation = /\b(?:change|update|replace|rewrite|edit|revise|set)\b/i;
export function pageContentIntent(message: string, history: Array<{ role: "user" | "assistant"; content: string }> = []) {
  const explicit = mutation.test(message); if (!explicit) return { action: "read" as const, explicit: false, pageId: page(message), sectionId: section(message) };
  const context = history.slice().reverse().map((item) => item.content).join(" "); return { action: "update" as const, explicit: true, pageId: page(message) ?? page(context), sectionId: section(message) ?? section(context) };
}
const fields = (text: string, sectionId: string): PageContentField[] => { const found: PageContentField[] = []; if (/\bheading|headline\b/i.test(text)) found.push("heading"); if (/\bsubheading\b/i.test(text)) found.push("subheading"); if (/\b(?:cta|button)\s+(?:label|text)\b/i.test(text)) found.push("label"); if (/\bsupporting\s+copy\b/i.test(text)) found.push("supportingCopy"); if (/\bservice\s+title\b/i.test(text)) found.push("title"); if (/\bdescription\b/i.test(text)) found.push("description"); if (/\b(?:introduction|intro)\b/i.test(text)) found.push("intro"); if (!found.length && sectionId === "primaryCta") found.push("label"); return [...new Set(found)].filter((item) => allowed[sectionId]?.includes(item)); };
export function buildPageContentPatch(message: string, sectionId: string, specialist: Record<string, unknown>) { const requested = fields(message, sectionId); if (!requested.length) throw new ApiError(400, "ACTION_FIELD_REQUIRED", "A content field is required."); const quoted = [...message.matchAll(/[“"]([^”"]+)[”"]/g)].map((item) => item[1]); const suggestions = Array.isArray(specialist.recommendations) ? specialist.recommendations.filter((item): item is string => typeof item === "string") : []; const values = quoted.length ? quoted : suggestions; if (values.length < requested.length) throw new ApiError(400, "ACTION_PAYLOAD_INVALID", "The requested content values could not be resolved."); return parsePageContentPatch(sectionId, Object.fromEntries(requested.map((item, index) => [item, values[index]]))); }
export class PageContentActionService {
  private readonly repository: PageContentRepository; private readonly workspaces: WorkspaceAuthorizationService;
  constructor(repository: PageContentRepository, workspaces: WorkspaceAuthorizationService) { this.repository = repository; this.workspaces = workspaces; }
  async read(auth: AuthContext, workspaceId: string, pageId: StaticPageId) { await this.workspaces.requirePermission(auth, workspaceId, "content:read"); const item = await this.repository.get(workspaceId, pageId); if (!item) throw new ApiError(404, "PAGE_CONTENT_NOT_FOUND", "Page content was not found."); return item; }
  async update(auth: AuthContext, actionId: string, workspaceId: string, pageId: StaticPageId, sectionId: string, value: unknown): Promise<{ result: PageContent; metadata: PageContentActionMetadata }> { const patch = parsePageContentPatch(sectionId, value); const changedFields = Object.keys(patch) as PageContentField[]; const diagnostic = (event: string, verificationStatus: string, errorCode?: string) => log(event === "action.completed" ? "info" : "warn", "page_content_action", { event, actionId, workspaceId, pageId, sectionId, changedFields, verificationStatus, ...(errorCode ? { errorCode } : {}) }); diagnostic("action.requested", "pending"); try { await this.workspaces.requirePermission(auth, workspaceId, "content:manage"); diagnostic("action.authorized", "pending"); const before = await this.repository.get(workspaceId, pageId); const beforeSection = before?.sections.find((item) => item.sectionId === sectionId); if (!before || !beforeSection) throw new ApiError(404, "PAGE_CONTENT_TARGET_NOT_FOUND", "Page content target was not found."); diagnostic("action.started", "pending"); const written = await this.repository.update(actionId, workspaceId, pageId, sectionId, patch, auth.user.userId); const readBack = await this.repository.get(workspaceId, pageId); const after = readBack?.sections.find((item) => item.sectionId === sectionId); const unchangedSections = before.sections.filter((item) => item.sectionId !== sectionId); const unrelatedFields = Object.keys(beforeSection.fields).filter((key) => !changedFields.includes(key as PageContentField)).every((key) => beforeSection.fields[key as PageContentField] === after?.fields[key as PageContentField]); const verified = Boolean(readBack && after && readBack.workspaceId === workspaceId && readBack.pageId === pageId && changedFields.every((key) => after.fields[key] === patch[key]) && unrelatedFields && JSON.stringify(unchangedSections) === JSON.stringify(readBack.sections.filter((item) => item.sectionId !== sectionId))); if (!verified || !readBack) throw new ApiError(500, "ACTION_VERIFICATION_FAILED", "The content update could not be verified."); diagnostic("action.completed", "passed"); return { result: readBack, metadata: { actionId, actionType: "page.content.update", status: "completed", verificationStatus: "passed", pageId, sectionId, changedFields, specialists: [], warnings: written.duplicate ? ["Idempotent replay returned existing content."] : [] } }; } catch (caught) { const error = caught instanceof ApiError ? caught : new ApiError(500, "ACTION_EXECUTION_FAILED", "The content update failed."); diagnostic("action.failed", "failed", error.code); throw error; } }
}
