import type { PageContent, PageContentField, StaticPageId } from "@averon/shared-types";
import { ApiError } from "../../errors/api-error.ts";
import { getFirebaseAdminServices } from "../../services/firebase/admin.ts";
import type { PageContentRepository } from "./page-content.types.ts";
const id = (workspaceId: string, pageId: string) => `${workspaceId}__${pageId}`;
export class FirebasePageContentRepository implements PageContentRepository {
  private readonly db; constructor(db = getFirebaseAdminServices().firestore) { this.db = db; }
  private collection() { return this.db.collection("pageContent"); }
  async get(workspaceId: string, pageId: StaticPageId) { const snap = await this.collection().doc(id(workspaceId, pageId)).get(); if (!snap.exists) return null; const item = snap.data() as PageContent; return item.workspaceId === workspaceId && item.pageId === pageId ? { ...item, sections: structuredClone(item.sections) } : null; }
  async seed(records: readonly PageContent[]) { let count = 0; for (const item of records) { const ref = this.collection().doc(id(item.workspaceId, item.pageId)); if ((await ref.get()).exists) continue; await ref.create({ ...item, updatedAt: getFirebaseAdminServices().serverTimestamp() }); count += 1; } return count; }
  async update(actionId: string, workspaceId: string, pageId: StaticPageId, sectionId: string, patch: Partial<Record<PageContentField, string>>, actorId: string) {
    const actionRef = this.db.collection("actionExecutions").doc(actionId); const contentRef = this.collection().doc(id(workspaceId, pageId));
    return this.db.runTransaction(async (tx) => { const prior = await tx.get(actionRef); if (prior.exists) { const data = prior.data(); if (data?.workspaceId !== workspaceId || data?.pageId !== pageId || data?.sectionId !== sectionId || data?.actionType !== "page.content.update") throw new ApiError(409, "ACTION_IDEMPOTENCY_CONFLICT", "The action ID belongs to another operation."); const existing = await tx.get(contentRef); if (!existing.exists) throw new ApiError(500, "ACTION_VERIFICATION_FAILED", "The prior action cannot be verified."); return { content: existing.data() as PageContent, duplicate: true }; } const found = await tx.get(contentRef); if (!found.exists) throw new ApiError(404, "PAGE_CONTENT_NOT_FOUND", "Page content was not found."); const current = found.data() as PageContent; if (current.workspaceId !== workspaceId || current.pageId !== pageId) throw new ApiError(403, "ACTION_FORBIDDEN", "The content target is outside this workspace."); const section = current.sections.find((item) => item.sectionId === sectionId); if (!section) throw new ApiError(404, "PAGE_CONTENT_SECTION_NOT_FOUND", "Page content section was not found."); const sections = current.sections.map((item) => item.sectionId === sectionId ? { ...item, fields: { ...item.fields, ...patch } } : item); const now = new Date().toISOString(); const content = { ...current, sections, version: current.version + 1, updatedAt: now }; tx.update(contentRef, { sections, version: content.version, updatedAt: now, updatedBy: actorId }); tx.create(actionRef, { actionId, workspaceId, actionType: "page.content.update", pageId, sectionId, changedFields: Object.keys(patch), status: "completed", createdAt: now }); tx.create(this.db.collection("auditLogs").doc(), { actorId, action: "PAGE_CONTENT_UPDATED", targetCollection: "pageContent", targetId: pageId, workspaceId, actionId, sectionId, changedFields: Object.keys(patch), createdAt: now }); return { content, duplicate: false }; });
  }
}
