import { type FormEvent, useEffect, useState } from "react";
import { averonApi } from "../../lib/averonApi";

type AdminProject = Awaited<ReturnType<typeof averonApi.adminProjects.list>>["data"]["items"][number];
const encodeFile=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(reader.error);reader.onload=()=>resolve(String(reader.result).split(",",2)[1]??"");reader.readAsDataURL(file);});

export default function AdminProjects() {
  const [projects,setProjects]=useState<AdminProject[]>([]);const [projectId,setProjectId]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");
  useEffect(()=>{void averonApi.adminProjects.list().then(({data})=>{setProjects(data.items);setProjectId(data.items[0]?.id??"");}).catch((caught:Error)=>setError(caught.message));},[]);
  const upload=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget;const values=new FormData(form);const file=values.get("file");if(!(file instanceof File)||!projectId)return;setBusy(true);setError("");setNotice("");try{const result=await averonApi.adminProjects.uploadFile(projectId,{name:String(values.get("name")||file.name),description:String(values.get("description")??""),category:String(values.get("category")) as "deliverable"|"document"|"design"|"report"|"other",deliveryStatus:String(values.get("deliveryStatus")) as "working"|"deliverable"|"final",customerVisible:values.get("customerVisible")==="on",mimeType:file.type||"application/octet-stream",contentBase64:await encodeFile(file),idempotencyKey:crypto.randomUUID()});setNotice(result.data.created?`Uploaded ${result.data.file.name}.`:`That upload was already recorded.`);form.reset();}catch(caught){setError(caught instanceof Error?caught.message:"Upload failed.");}finally{setBusy(false);}};
  return <div className="admin-page-stack"><section className="admin-page-header"><div><p className="admin-eyebrow">Projects</p><h2>Project files and deliverables.</h2><p>Upload immutable, customer-visible files to an authoritative customer project.</p></div></section><section className="admin-panel"><form className="settings-form project-file-upload" onSubmit={(event)=>void upload(event)}><label>Project<select value={projectId} onChange={(event)=>setProjectId(event.target.value)} required><option value="">Select a project</option>{projects.map((project)=><option key={project.id} value={project.id}>{project.projectReference} — {project.title} ({project.customerEmail})</option>)}</select></label><label>File<input name="file" type="file" required accept=".pdf,.png,.jpg,.jpeg,.webp,.txt,.csv,.zip,.docx,.xlsx"/></label><label>Customer-facing filename<input name="name" maxLength={180} placeholder="Defaults to the selected filename"/></label><label>Description<textarea name="description" maxLength={1000}/></label><div className="admin-two-column"><label>Category<select name="category" defaultValue="deliverable"><option value="deliverable">Deliverable</option><option value="document">Document</option><option value="design">Design</option><option value="report">Report</option><option value="other">Other</option></select></label><label>Delivery state<select name="deliveryStatus" defaultValue="deliverable"><option value="working">Working document</option><option value="deliverable">Deliverable</option><option value="final">Final delivery</option></select></label></div><label className="admin-checkbox"><input name="customerVisible" type="checkbox" defaultChecked/>Visible to customer</label><button className="btn-primary" disabled={busy||!projectId}>{busy?"Uploading...":"Upload project file"}</button>{error&&<p role="alert" className="portal-error">{error}</p>}{notice&&<p role="status">{notice}</p>}</form></section></div>;
}
